// Migration guidance is deliberately separate from general product vocabulary.
// English is explicitly marked on the UI when a translation is unavailable.
const en = {
  fallbackNotice: 'This migration guide is currently available in English and French. You are viewing the English version.',
  title: 'Move safely to qetoret.com',
  nudge: 'Qetoret has a new address. You can keep praying here and move when you are ready.',
  open: 'Prepare my move',
  later: 'Remind me in a week',
  close: 'Close',
  intro: 'Your prayers stay in the same account. This browser keeps a private encryption key, so signing in at the new address also needs your recovery passphrase.',
  first: '1. Prepare recovery on this browser',
  setup: 'Set up recovery',
  setupBody: 'Choose a recovery passphrase and save the recovery code. This keeps your existing encryption key.',
  check: '2. Check before opening the new address',
  checkBody: 'Finish saving prayers and notes first. Enter your recovery passphrase to check that it opens the same key used here and that its encrypted recovery record is saved online. Your passphrase stays in this browser.',
  passphrase: 'Recovery passphrase',
  verify: 'Check my recovery and saved changes',
  checking: 'Checking…',
  ready: 'Your recovery record is saved online and no pending changes or active local drafts were found. Keep this tab open while you check the new address.',
  recovery: 'Set up recovery first, and keep your recovery code somewhere safe.',
  wrongPassphrase: 'That passphrase could not verify this browser’s encryption key. Check your recovery passphrase or stay here and review recovery in Settings.',
  pending: 'Some changes are still waiting to save. Stay here until the sync indicator confirms they are saved, then check again.',
  drafts: 'An unfinished prayer or prayer-session note is still stored only in this browser. Finish and save it here before moving. Local drafts do not follow you to the new address.',
  offline: 'Reconnect to the internet, then check again. Nothing has been moved or deleted.',
  popupBlocked: 'Your browser blocked the new tab. Allow pop-ups for this app, then check again. Your prayers are still available here.',
  failed: 'We could not confirm that recovery is saved online. Keep using this address and check again later.',
  changed: 'Something changed after the check. Check again before opening the new address.',
  next: '3. Sign in and check your prayers',
  nextBody: 'Open qetoret.com in a new tab, sign in to the same account, and unlock with your recovery passphrase. Check your prayers, history, attachments and groups before leaving this tab. Keep the old browser data until everything is readable.',
  continue: 'Open qetoret.com in a new tab',
  reminder: 'Notifications need permission again at the new address. Enable them there when you are ready.',
  return: 'Return to praystead.com on this browser',
  returnWww: 'Used www.praystead.com? Open that address instead.',
  returnBody: 'If you used Praystead, your encryption key may still be at the old address. Open it on the browser where your prayers worked, set up recovery, then return here and sign in again.',
};

const fr = {
  fallbackNotice: 'Ce guide de changement d’adresse est actuellement disponible en anglais et en français. Tu consultes la version française.',
  title: 'Passer à qetoret.com en toute sécurité',
  nudge: 'Qetoret a une nouvelle adresse. Tu peux continuer à prier ici et changer d’adresse quand tu seras prêt.',
  open: 'Préparer mon changement d’adresse',
  later: 'Me le rappeler dans une semaine',
  close: 'Fermer',
  intro: 'Tes prières restent dans le même compte. Ce navigateur conserve une clé de chiffrement privée : à la nouvelle adresse, il te faudra aussi ta phrase secrète de récupération.',
  first: '1. Préparer la récupération dans ce navigateur',
  setup: 'Configurer la récupération',
  setupBody: 'Choisis une phrase secrète de récupération et conserve le code de récupération. Ta clé de chiffrement actuelle est préservée.',
  check: '2. Vérifier avant d’ouvrir la nouvelle adresse',
  checkBody: 'Termine d’abord l’enregistrement de tes prières et de tes notes. Saisis ta phrase secrète pour vérifier qu’elle ouvre la clé utilisée ici et que la sauvegarde chiffrée de récupération est bien enregistrée en ligne. Ta phrase secrète reste dans ce navigateur.',
  passphrase: 'Phrase secrète de récupération',
  verify: 'Vérifier la récupération et l’enregistrement',
  checking: 'Vérification…',
  ready: 'La sauvegarde de récupération est enregistrée en ligne. Aucune modification en attente ni aucun brouillon local actif n’a été trouvé. Garde cet onglet ouvert pendant la vérification à la nouvelle adresse.',
  recovery: 'Configure d’abord la récupération et conserve ton code de récupération en lieu sûr.',
  wrongPassphrase: 'Cette phrase secrète n’a pas permis de vérifier la clé de chiffrement de ce navigateur. Vérifie-la ou reste ici pour consulter la récupération dans les paramètres.',
  pending: 'Des modifications attendent encore d’être enregistrées. Reste ici jusqu’à la confirmation de l’indicateur de synchronisation, puis relance la vérification.',
  drafts: 'Une prière ou une note de séance inachevée est encore conservée uniquement dans ce navigateur. Termine-la et enregistre-la ici avant de changer d’adresse. Les brouillons locaux ne suivent pas à la nouvelle adresse.',
  offline: 'Reconnecte-toi à Internet, puis relance la vérification. Rien n’a été déplacé ni supprimé.',
  popupBlocked: 'Ton navigateur a bloqué le nouvel onglet. Autorise les fenêtres contextuelles pour cette application, puis relance la vérification. Tes prières restent accessibles ici.',
  failed: 'Impossible de confirmer l’enregistrement de la récupération en ligne. Continue à utiliser cette adresse et réessaie plus tard.',
  changed: 'Un élément a changé depuis la vérification. Relance-la avant d’ouvrir la nouvelle adresse.',
  next: '3. Se connecter et vérifier ses prières',
  nextBody: 'Ouvre qetoret.com dans un nouvel onglet, connecte-toi au même compte et déverrouille avec ta phrase secrète de récupération. Vérifie tes prières, leur historique, les pièces jointes et les groupes avant de quitter cet onglet. Conserve les données de l’ancien navigateur jusqu’à ce que tout soit lisible.',
  continue: 'Ouvrir qetoret.com dans un nouvel onglet',
  reminder: 'Les notifications demandent une nouvelle autorisation à la nouvelle adresse. Active-les quand tu seras prêt.',
  return: 'Revenir à praystead.com dans ce navigateur',
  returnWww: 'Tu utilisais www.praystead.com ? Ouvre plutôt cette adresse.',
  returnBody: 'Si tu utilisais Praystead, ta clé de chiffrement peut encore se trouver à l’ancienne adresse. Ouvre-la dans le navigateur où tes prières étaient accessibles, configure la récupération, puis reviens ici et reconnecte-toi.',
};

export function originMigrationCopy(lang) {
  return { copy: lang === 'fr' ? fr : en, lang: lang === 'fr' ? 'fr' : 'en' };
}
