// Candidates for children21, researched 2026-09-28. NONE is approved: every entry is
// needs_review with no sign-off, so the resolver never shows it. See
// docs/resources/candidates/children21.md for the verification worksheet.
export const CHILDREN21_CANDIDATES = [
  {
    id: 'crouch-tech-wise-family',
    type: 'book',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['parenting', 'family-discipleship', 'wisdom'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A practical book, drawing on Barna research, on shaping family habits so that screens serve wisdom and character rather than rule the home — beginning with the adults’ own habits.',
      fr: 'Un livre pratique, appuyé sur des enquêtes de Barna, pour façonner les habitudes familiales afin que les écrans servent la sagesse et le caractère au lieu de gouverner la maison — en commençant par les habitudes des adultes.',
    },
    editions: {
      en: { title: 'The Tech-Wise Family: Everyday Steps for Putting Technology in Its Proper Place', author: 'Andy Crouch', publisher: 'Baker Books (Baker Publishing Group)', url: 'https://bakerpublishinggroup.com/products/9780801018664_the-tech-wise-family', available: true, lastVerifiedAt: '2026-09-28' },
      es: { title: 'Familias tecnológicamente sabias: Pautas para situar la tecnología en el lugar que le corresponde', author: 'Andy Crouch', publisher: 'Andamio Editorial', url: 'https://andamioeditorial.com/producto/familias-tecnologicamente-sabias/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'ortiz-consejos-culto-familiar',
    type: 'article',
    originalLanguage: 'es',
    domains: ['relationships'],
    topics: ['family-discipleship', 'parenting'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A short article by a Mexico City pastor on simple family worship at home — Scripture, prayer and song — as a companion to the local church, not a replacement for it. In Spanish.',
      fr: 'Un court article d’un pasteur de Mexico sur un culte familial simple à la maison — Écriture, prière et chant — en complément de l’Église locale, non en remplacement. En espagnol.',
    },
    editions: {
      es: { title: '3 consejos para el culto familiar en casa', author: 'Josué Ortiz', publisher: 'Coalición por el Evangelio', url: 'https://www.coalicionporelevangelio.org/articulo/3-consejos-culto-familiar/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'berndt-praying-scriptures-children',
    type: 'prayerGuide',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['children', 'intercession', 'parenting'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A guide to turning Bible passages into prayers for a child’s faith, character, friendships, technology use and future — the same ground this plan walks, one theme at a time.',
      fr: 'Un guide pour transformer des passages bibliques en prières pour la foi d’un enfant, son caractère, ses amitiés, son usage de la technologie et son avenir — le même chemin que ce parcours, thème après thème. En anglais.',
    },
    editions: {
      en: { title: 'Praying the Scriptures for Your Children (20th Anniversary Edition): Discover How to Pray God’s Purpose for Their Lives', author: 'Jodie Berndt', publisher: 'Zondervan (HarperCollins Christian Publishing, FaithGateway store)', url: 'https://store.faithgateway.com/products/praying-the-scriptures-for-your-children-20th-anniversary-edition-discover-how-to-pray-gods-purpose-for-their-lives', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'bloom-seven-things-pray-children',
    type: 'article',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['children', 'intercession'],
    perspective: ['reformed'],
    status: 'needs_review',
    description: {
      en: 'Seven short, Scripture-anchored requests to pray for a child, prefaced by a plain reminder that prayers are not magic spells and that God answers for purposes we may not see.',
      fr: 'Sept courtes demandes ancrées dans l’Écriture pour prier pour un enfant, précédées d’un rappel clair : la prière n’est pas une formule magique, et Dieu répond selon des desseins que nous ne voyons pas toujours. En anglais.',
    },
    editions: {
      en: { title: 'Seven Things to Pray for Your Children', author: 'Jon Bloom', publisher: 'Desiring God', url: 'https://www.desiringgod.org/articles/seven-things-to-pray-for-your-children', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'powell-sticky-faith',
    type: 'book',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['family-discipleship', 'parenting'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'Research from the Fuller Youth Institute on the relationships and practices that help young people carry faith into adulthood — mentors and a whole church, not parents alone; findings, not guarantees.',
      fr: 'Des recherches du Fuller Youth Institute sur les relations et les pratiques qui aident les jeunes à porter leur foi jusqu’à l’âge adulte — des mentors et toute une Église, pas seulement les parents ; des constats, non des garanties. En anglais.',
    },
    editions: {
      en: { title: 'Sticky Faith: Everyday Ideas to Build Lasting Faith in Your Kids', author: 'Kara E. Powell and Chap Clark', publisher: 'Zondervan; sold by the Fuller Youth Institute (Fuller Theological Seminary)', url: 'https://shop.fulleryouthinstitute.org/products/sticky-faith', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'nielson-parents-we-get-to-pray',
    type: 'article',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['children', 'intercession', 'parenting'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A mother and grandmother on praying for children over a lifetime — with thanksgiving, with the church, for grown children too — and finally releasing them into God’s hands because they are not ours.',
      fr: 'Une mère et grand-mère sur la prière pour les enfants tout au long d’une vie — avec reconnaissance, avec l’Église, pour les enfants adultes aussi — pour finalement les remettre entre les mains de Dieu, car ils ne nous appartiennent pas.',
    },
    editions: {
      en: { title: 'Parents, We Get to Pray', author: 'Kathleen Nielson', publisher: 'The Gospel Coalition', url: 'https://www.thegospelcoalition.org/article/parents-pray/', available: true, lastVerifiedAt: '2026-09-28' },
      fr: { title: 'Prions avec joie pour nos enfants', author: 'Kathleen Nielson', publisher: 'Évangile 21 (The Gospel Coalition)', url: 'https://evangile21.thegospelcoalition.org/article/prions-avec-joie-pour-nos-enfants/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'guthrie-praying-through-bible-kids',
    type: 'prayerGuide',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['children', 'intercession', 'parenting'],
    perspective: ['reformed'],
    status: 'needs_review',
    description: {
      en: 'A year of short daily readings that each turn a Bible passage into a prayer for one’s children, so that hopes for them are shaped by Scripture rather than by the culture.',
      fr: 'Une année de courtes lectures quotidiennes qui transforment chacune un passage biblique en prière pour ses enfants, afin que les espoirs pour eux soient façonnés par l’Écriture plutôt que par la culture ambiante.',
    },
    editions: {
      en: { title: 'The One Year Praying through the Bible for Your Kids', author: 'Nancy Guthrie', publisher: 'Tyndale House Publishers (Tyndale Momentum)', url: 'https://www.tyndale.com/p/the-one-year-praying-through-the-bible-for-your-kids/9781496413369', available: true, lastVerifiedAt: '2026-09-28' },
      de: { title: 'Mit der Bibel für deine Kinder beten: 365 Andachten & Gebete für Eltern', author: 'Nancy Guthrie', publisher: 'Verbum Medien', url: 'https://verbum-medien.de/products/mit-der-bibel-fur-deine-kinder-beten', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'beeke-ore-pela-salvacao-filhos',
    type: 'article',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['children', 'gospel', 'intercession'],
    perspective: ['reformed'],
    status: 'needs_review',
    description: {
      en: 'A pastor’s call to pray for children’s new birth — with Nicodemus as the reminder that a godly upbringing is not the same as faith of one’s own. In Portuguese.',
      fr: 'Un appel pastoral à prier pour la nouvelle naissance des enfants — Nicodème rappelant qu’une éducation pieuse n’est pas encore une foi personnelle. En portugais.',
    },
    editions: {
      pt: { title: 'Ore Pela Salvação de Seus Filhos', author: 'Joel R. Beeke (tradução: Victor San)', publisher: 'Coalizão pelo Evangelho (TGC Brasil)', url: 'https://coalizaopeloevangelho.org/article/ore-pela-salvacaeo-de-seus-filhos/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'shin-hyungseob-faith-planting-parent-coaching',
    type: 'book',
    originalLanguage: 'ko',
    domains: ['relationships'],
    topics: ['family-discipleship', 'parenting'],
    perspective: ['reformed'],
    status: 'needs_review',
    description: {
      en: 'Thirty short chapters by a Korean professor of Christian education on passing faith to the next generation — the parent’s posture, family worship and children’s questions — for couples or small groups. In Korean.',
      fr: 'Trente courts chapitres d’un professeur coréen d’éducation chrétienne sur la transmission de la foi à la génération suivante — l’attitude des parents, le culte familial, les questions des enfants — pour les couples ou les petits groupes. En coréen.',
    },
    editions: {
      ko: { title: '신앙을 심는 부모 코칭 30일', author: '신형섭 (Shin Hyung-seob)', publisher: '두란노 (Duranno)', url: 'https://www.duranno.com/books/view/bookdetail.asp?bcod=9397', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'cheng-depeng-raising-godly-next-generation-grace',
    type: 'article',
    originalLanguage: 'zh',
    domains: ['relationships'],
    topics: ['parenting', 'family-discipleship'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A Chinese-American pastor and father of six on leading children with grace rather than control, apologising to them, and entrusting them to God in prayer — raising children is not “do A, B, C and get the result”. In Chinese.',
      fr: 'Un pasteur sino-américain, père de six enfants, sur l’art de conduire les enfants par la grâce plutôt que par le contrôle, de savoir leur demander pardon et de les confier à Dieu dans la prière — élever un enfant n’est pas « faire A, B, C et obtenir le résultat ». En chinois.',
    },
    editions: {
      zh: { title: '如何培养敬虔的下一代——以恩典来带领子女', author: '程德鹏', publisher: '使者协会 (Ambassadors for Christ, AFC)', url: 'https://afcministry.org/%E5%A6%82%E4%BD%95%E5%9F%B9%E5%85%BB%E6%95%AC%E8%99%94%E7%9A%84%E4%B8%8B%E4%B8%80%E4%BB%A3-%E4%BB%A5%E6%81%A9%E5%85%B8%E6%9D%A5%E5%B8%A6%E9%A2%86%E5%AD%90%E5%A5%B3/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'reju-on-guard',
    type: 'book',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['children', 'abuse-safety'],
    perspective: ['evangelical'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A pastor and biblical counsellor on why abusers target churches and how a congregation can protect children and care for those who have been harmed — prayer joined to concrete safeguarding.',
      fr: 'Un pasteur et conseiller biblique explique pourquoi les agresseurs ciblent les Églises et comment une communauté peut protéger les enfants et prendre soin de ceux qui ont été blessés — la prière unie à une protection concrète. En anglais.',
    },
    editions: {
      en: { title: 'On Guard: Preventing and Responding to Child Abuse at Church', author: 'Deepak Reju', publisher: 'New Growth Press', url: 'https://newgrowthpress.com/christian-books/children-youth-ministry/on-guard-preventing-and-responding-to-child-about-at-church/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'jones-how-and-when-tell-kids-about-sex',
    type: 'book',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['parenting', 'sexuality'],
    perspective: ['evangelical'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A guide for parents to age-appropriate conversations about the body, sexuality and online risks over the whole of childhood, so that children hear about God’s good design from the people who love them.',
      fr: 'Un guide pour que les parents abordent, à chaque âge et de façon adaptée, le corps, la sexualité et les risques en ligne, afin que les enfants entendent parler du bon dessein de Dieu par ceux qui les aiment. En anglais.',
    },
    editions: {
      en: { title: 'How and When to Tell Your Kids about Sex: A Lifelong Approach to Shaping Your Child’s Sexual Character (God’s Design for Sex)', author: 'Stan Jones and Brenna Jones', publisher: 'NavPress (Tyndale House Publishers)', url: 'https://www.tyndale.com/p/how-and-when-to-tell-your-kids-about-sex/9781631469442', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'obuchi-jozu-ni-okoru-hito-ni-naru',
    type: 'book',
    originalLanguage: 'ja',
    domains: ['relationships'],
    topics: ['parenting'],
    status: 'needs_review',
    description: {
      en: 'A short, illustrated book by a Japanese Christian-school counsellor on noticing and handling one’s own anger as a parent — a practical companion to the “do not provoke your children” day. In Japanese.',
      fr: 'Un court livre illustré d’une conseillère d’école chrétienne japonaise pour repérer et gérer sa propre colère de parent — un compagnon pratique pour la journée « n’irritez pas vos enfants ». En japonais.',
    },
    editions: {
      ja: { title: '上手に怒る人になる 子育てが楽になるアンガーマネジメント', author: '小渕朝子 (Asako Obuchi)', publisher: 'いのちのことば社・フォレストブックス (Word of Life Press, Forest Books)', url: 'https://www.gospelshop.jp/shopdetail/000000014919/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'macarthur-kak-blagovestvovat-detyam',
    type: 'article',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['children', 'gospel', 'family-discipleship'],
    perspective: ['reformed'],
    status: 'needs_review',
    description: {
      en: 'On telling children the whole gospel patiently, without pressing them into a prayer or a decision — new birth is the Spirit’s work, not the reward of parental effort. In Russian.',
      fr: 'Annoncer tout l’Évangile aux enfants avec patience, sans les pousser à une prière ou à une décision — la nouvelle naissance est l’œuvre de l’Esprit, non la récompense des efforts des parents. En russe.',
    },
    editions: {
      ru: { title: 'Как благовествовать детям', author: 'Джон Макартур (John MacArthur)', publisher: 'Слово Благодати (slovo.org)', url: 'https://slovo.org/resursy/stati/kak-blagovestvovat-detyam/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'pardoe-pray-big-things-little-ones',
    type: 'article',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['children', 'intercession'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'For days when prayers for a child feel dry: eight requests drawn from Paul’s prayer in Colossians 1:9-12 — knowledge of God’s will, a worthy life, fruit, strength, patience and joy.',
      fr: 'Pour les jours où la prière pour un enfant semble sèche : huit demandes tirées de la prière de Paul en Colossiens 1.9-12 — connaître la volonté de Dieu, une vie digne, du fruit, de la force, de la patience et de la joie.',
    },
    editions: {
      en: { title: 'Pray Big Things for Your Little Ones', author: 'Stacey Pardoe', publisher: 'Desiring God', url: 'https://www.desiringgod.org/articles/pray-big-things-for-your-little-ones', available: true, lastVerifiedAt: '2026-09-28' },
      id: { title: 'Doakanlah Hal-Hal Besar untuk Anak-Anak Anda', author: 'Stacey Pardoe (penerjemah: Santi T.)', publisher: 'Situs Doa Kristen (Yayasan Lembaga SABDA)', url: 'https://doa.sabda.org/doakanlah_halhal_besar_untuk_anakanak_anda', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'shenouda-family-religious-education',
    type: 'article',
    originalLanguage: 'ar',
    domains: ['relationships'],
    topics: ['family-discipleship', 'parenting'],
    perspective: ['orthodox'],
    status: 'needs_review',
    description: {
      en: 'A chapter by the late Coptic Orthodox Pope Shenouda III on faith taught at home, from Deuteronomy 6 to Timothy’s grandmother Lois and mother Eunice — and the grandmothers who kept faith alive under persecution. In Arabic.',
      fr: 'Un chapitre du défunt pape copte orthodoxe Chenouda III sur la foi transmise à la maison, de Deutéronome 6 à Loïs et Eunice, grand-mère et mère de Timothée — et aux grand-mères qui ont gardé la foi vivante sous la persécution. En arabe.',
    },
    editions: {
      ar: { title: 'الأسرة والتربية الدينية (من كتاب الأسرة الروحية السعيدة)', author: 'البابا شنوده الثالث (Pope Shenouda III)', publisher: 'St-Takla.org (موقع الأنبا تكلا هيمانوت، الكنيسة القبطية الأرثوذكسية)', url: 'https://st-takla.org/books/pope-sheounda-iii/spiritual-happy-family/religious-education.html', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'steer-doaye-madar-baraye-farzand',
    type: 'article',
    originalLanguage: 'fa',
    domains: ['relationships'],
    topics: ['children', 'intercession'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'An article for Persian-speaking believers on praying for one’s children before and after birth, drawing on Jochebed, Hannah, Mary, Elizabeth, Eunice and Lois, and on parents as praying examples. In Persian.',
      fr: 'Un article pour les croyants persanophones sur la prière pour ses enfants avant et après la naissance, à partir de Jokébed, Anne, Marie, Élisabeth, Eunice et Loïs, et sur les parents comme exemples de prière. En persan.',
    },
    editions: {
      fa: { title: 'دعای مادر برای فرزند', author: 'آن استیر (Ann Steer)', publisher: 'کلمه (Kalameh, خدمات ایلام / Elam Ministries)', url: 'https://www.kalameh.com/article/%D8%AF%D8%B9%D8%A7%DB%8C-%D9%85%D8%A7%D8%AF%D8%B1-%D8%A8%D8%B1%D8%A7%DB%8C-%D9%81%D8%B1%D8%B2%D9%86%D8%AF', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'parfan-usapang-pamilya-mga-anak',
    type: 'teaching',
    originalLanguage: 'tl',
    domains: ['relationships'],
    topics: ['children', 'family-discipleship'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A Filipino pastor’s sermon on Jesus welcoming the children (Matthew 19:13-15), addressed to every disciple “with or without children”: bring them to Jesus, pray for them with the church — the outcome does not rest on our effort. In Tagalog/Taglish.',
      fr: 'Une prédication d’un pasteur philippin sur Jésus qui accueille les enfants (Matthieu 19.13-15), adressée à tout disciple « avec ou sans enfants » : les amener à Jésus, prier pour eux avec l’Église — le résultat ne repose pas sur nos efforts. En tagalog.',
    },
    editions: {
      tl: { title: 'Usapang Pamilya: Mga Anak (Mateo 19:13-15)', author: 'Pastor Derick Parfan', publisher: 'Treasuring Christ PH', url: 'https://treasuringchristph.org/sermon/mate-1913-15-usapang-pamilya-mga-anak/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'varak-transmettre-la-foi-enfants',
    type: 'article',
    originalLanguage: 'fr',
    domains: ['relationships'],
    topics: ['family-discipleship', 'children', 'gospel'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A French pastor on passing faith to children by loving God and his word in front of them and teaching it day by day — while remembering that only God converts. In French.',
      fr: 'Un pasteur français sur la transmission de la foi aux enfants : aimer Dieu et sa Parole devant eux et l’enseigner au quotidien — en se souvenant que Dieu seul convertit.',
    },
    editions: {
      fr: { title: 'Comment transmettre la foi à nos enfants', author: 'Florent Varak', publisher: 'Évangile 21 (The Gospel Coalition)', url: 'https://evangile21.thegospelcoalition.org/article/comment-transmettre-la-foi-a-nos-enfants/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'erf-voss-wie-kinder-glauben-lernen',
    type: 'podcast',
    originalLanguage: 'de',
    domains: ['relationships'],
    topics: ['children', 'family-discipleship'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A radio conversation with a German children’s author from the Bible-reading fellowship on how young children come to faith — rituals, age-appropriate steps, a secular environment — for parents and church volunteers alike. In German.',
      fr: 'Un entretien radio avec un auteur allemand pour enfants, de la ligue pour la lecture de la Bible, sur la manière dont les jeunes enfants entrent dans la foi — rituels, étapes adaptées à l’âge, environnement sécularisé — pour les parents comme pour les bénévoles d’Église. En allemand.',
    },
    editions: {
      de: { title: 'Wie Kinder glauben (lernen) — Das Gespräch', author: 'Harry Voß (Bibellesebund) im Gespräch', publisher: 'ERF Medien (ERF Plus)', url: 'https://www.erf.de/hoeren-sehen/erf-plus/audiothek/das-gespraech/wie-kinder-glauben-lernen/38142-45', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'gotquestions-let-go-adult-children',
    type: 'article',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['parenting', 'children', 'intercession'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A short answer for parents of grown children: give up control, respect their independence and keep praying for them — because they belong to God, not to us.',
      fr: 'Une courte réponse pour les parents d’enfants adultes : renoncer au contrôle, respecter leur indépendance et continuer à prier pour eux — car ils appartiennent à Dieu, non à nous. En anglais et en hindi.',
    },
    editions: {
      en: { title: 'I am a parent; how can I let go of my adult children?', author: 'Got Questions Ministries (unsigned staff article)', publisher: 'Got Questions Ministries (GotQuestions.org)', url: 'https://www.gotquestions.org/letting-go.html', available: true, lastVerifiedAt: '2026-09-28' },
      hi: { title: 'मैं एक अभिभावक हूँ; मैं अपने वयस्क बच्चों को कैसे छोड़ सकता हूँ?', author: 'Got Questions Ministries (unsigned staff article)', publisher: 'Got Questions Ministries (GotQuestions.org हिन्दी)', url: 'https://www.gotquestions.org/Hindi/Hindi-letting-go.html', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'mahibere-kidusan-technology-child-rearing',
    type: 'article',
    originalLanguage: 'am',
    domains: ['relationships'],
    topics: ['parenting', 'children', 'wisdom'],
    perspective: ['orthodox'],
    status: 'needs_review',
    description: {
      en: 'An Ethiopian Orthodox article on screens, the internet and cultural pressure in raising children — naming real online risks while urging closeness, conversation and measured use rather than blanket bans. In Amharic.',
      fr: 'Un article orthodoxe éthiopien sur les écrans, Internet et la pression culturelle dans l’éducation des enfants — il nomme les vrais risques en ligne tout en appelant à la proximité, au dialogue et à un usage mesuré plutôt qu’à l’interdiction pure et simple. En amharique.',
    },
    editions: {
      am: { title: 'የቴክኖሎጂ ውጤቶች ና የሉላዊነት ጫና በልጆች አስተዳደግ', author: 'ዶ/ር በላቸው ጨከነ ተስፋ (Dr. Belachew Chekene Tesfa)', publisher: 'ማኅበረ ቅዱሳን አውሮፓ ማዕከል (Mahibere Kidusan Europe Center, Ethiopian Orthodox Tewahedo Church Sunday School Department)', url: 'https://eu.eotcmk.org/site/%E1%8B%A8%E1%89%B4%E1%8A%AD%E1%8A%96%E1%88%8E%E1%8C%82-%E1%8B%8D%E1%8C%A4%E1%89%B6%E1%89%BD-%E1%8A%93-%E1%8B%A8%E1%88%89%E1%88%8B%E1%8B%8A%E1%8A%90%E1%89%B5-%E1%8C%AB%E1%8A%93-%E1%89%A0%E1%88%8D/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'gotquestions-parents-leaving-inheritance',
    type: 'article',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['family-discipleship', 'parenting'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A short answer on what parents truly leave their children: property may be passed on wisely, but the lasting inheritance is teaching them God’s ways, as in Deuteronomy 6 and Ephesians 6:4. In Swahili.',
      fr: 'Une courte réponse sur ce que les parents laissent vraiment à leurs enfants : des biens peuvent être transmis avec sagesse, mais l’héritage durable est de leur enseigner les voies de Dieu, comme en Deutéronome 6 et Éphésiens 6.4. En swahili.',
    },
    editions: {
      sw: { title: 'Biblia inasema nini kuhusu wazazi wanaoacha urithi kwa watoto wao?', author: 'Got Questions Ministries (unsigned staff article, Swahili translation)', publisher: 'Got Questions Ministries (GotQuestions.org Kiswahili)', url: 'https://www.gotquestions.org/Kiswahili/urithi-wa-Biblia.html', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
];
