// Candidates for holySpirit21, researched 2026-09-28. NONE is approved: every entry is
// needs_review with no sign-off, so the resolver never shows it. See
// docs/resources/candidates/holySpirit21.md for the verification worksheet.
//
// Tagging rule for this plan: the christian-living shelf is shared by seven
// "Growing in Christ" plans, so entries carry Spirit-specific topics
// (holy-spirit, spirit-baptism, spiritual-gifts, prophecy, discernment,
// fruit-of-the-spirit) and avoid generic ones (identity, character, calling,
// work, leadership) unless the work is centrally about them.
export const HOLY_SPIRIT21_CANDIDATES = [
  {
    id: 'packer-keep-in-step-with-the-spirit',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['holy-spirit', 'holiness', 'spirit-baptism'],
    perspective: ['evangelical', 'anglican'],
    status: 'needs_review',
    description: {
      en: 'A classic on the Spirit’s Christ-centred ministry and the call to holiness, with an even-handed assessment of the charismatic movement from a non-Pentecostal evangelical.',
      fr: 'Un classique sur le ministère du Saint-Esprit centré sur Christ et l’appel à la sainteté, avec une évaluation mesurée du mouvement charismatique par un évangélique non pentecôtiste.',
    },
    editions: {
      en: {
        title: 'Keep in Step with the Spirit',
        author: 'J. I. Packer',
        publisher: 'Baker Books',
        url: 'https://bakerpublishinggroup.com/products/9780801065583_keep-in-step-with-the-spirit',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      fr: {
        title: 'Marcher au rythme de l’Esprit : vivre la plénitude dans notre relation avec Dieu',
        author: 'James I. Packer',
        publisher: 'Grâce et Vérité (diffusion Excelsis)',
        url: 'https://www.xl6.com/articles/9782853310758-marcher-au-rythme-de-l-esprit',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      ko: {
        title: '성령을 아는 지식 (개정판)',
        author: '제임스 패커 (J. I. Packer), 홍종락 역',
        publisher: '홍성사 (Hongsungsa)',
        url: 'https://shop.hongsungsa.com/product/%ec%84%b1%eb%a0%b9%ec%9d%84-%ec%95%84%eb%8a%94-%ec%a7%80%ec%8b%9d-2/',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'ferguson-the-holy-spirit',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['holy-spirit', 'holiness'],
    perspective: ['reformed', 'evangelical'],
    status: 'needs_review',
    description: {
      en: 'A careful Reformed theology of who the Spirit is and how he unites us to Christ and makes us holy — a serious study for readers who want depth behind days 1–6.',
      fr: 'Une théologie réformée approfondie de la personne du Saint-Esprit, qui nous unit à Christ et nous sanctifie — une étude exigeante pour qui veut creuser les jours 1 à 6.',
    },
    editions: {
      en: {
        title: 'The Holy Spirit (Contours of Christian Theology)',
        author: 'Sinclair B. Ferguson',
        publisher: 'IVP Academic',
        url: 'https://www.ivpress.com/the-holy-spirit',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      fr: {
        title: 'L’Esprit Saint (deuxième édition révisée)',
        author: 'Sinclair Ferguson',
        publisher: 'Excelsis',
        url: 'https://www.xl6.com/articles/9782755003680-l-esprit-saint-deuxieme-edition-revisee',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'chan-forgotten-god',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['holy-spirit'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A short, searching book on how easily Christians neglect the Holy Spirit, and on depending on him as a Person rather than an idea.',
      fr: 'Un livre court et percutant sur la facilité avec laquelle les chrétiens négligent le Saint-Esprit, et sur la dépendance envers lui comme Personne et non comme idée.',
      es: 'Un libro breve y desafiante sobre lo fácil que es descuidar al Espíritu Santo, y sobre depender de él como Persona y no como idea.',
      pt: 'Um livro curto e desafiador sobre como os cristãos negligenciam facilmente o Espírito Santo, e sobre depender dele como Pessoa, não como ideia.',
    },
    editions: {
      en: {
        title: 'Forgotten God',
        author: 'Francis Chan',
        publisher: 'David C Cook',
        url: 'https://shop.davidccook.org/products/forgotten-god-francis-chan-small-groups',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      pt: {
        title: 'O Deus esquecido',
        author: 'Francis Chan',
        publisher: 'Editora Mundo Cristão',
        url: 'https://www.mundocristao.com.br/produto/o-deus-esquecido/',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      es: {
        title: 'El Dios olvidado',
        author: 'Francis Chan',
        publisher: 'Casa Creación',
        url: 'https://casacreacion.com/site/producto/el-dios-olvidado/',
        available: false,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'fee-paul-the-spirit-and-the-people-of-god',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['holy-spirit', 'fruit-of-the-spirit', 'spiritual-gifts'],
    perspective: ['pentecostal', 'evangelical'],
    status: 'needs_review',
    description: {
      en: 'A Pentecostal New Testament scholar’s accessible study of the Spirit in Paul — Romans 8, Galatians 5 and 1 Corinthians 12–14 — as God’s personal, empowering presence among his people.',
      fr: 'L’étude accessible d’un bibliste pentecôtiste sur l’Esprit chez Paul — Romains 8, Galates 5, 1 Corinthiens 12 à 14 — comme présence personnelle et agissante de Dieu parmi son peuple.',
    },
    editions: {
      en: {
        title: 'Paul, the Spirit, and the People of God',
        author: 'Gordon D. Fee',
        publisher: 'Baker Academic',
        url: 'https://bakerpublishinggroup.com/products/9781540966025_paul-the-spirit-and-the-people-of-god',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'keener-gift-and-giver',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['holy-spirit', 'spiritual-gifts', 'spirit-baptism', 'discernment'],
    perspective: ['charismatic', 'evangelical'],
    status: 'needs_review',
    description: {
      en: 'A leading New Testament scholar on hearing God, spiritual gifts, the fruit of the Spirit and power for witness, in fair conversation with Pentecostal, moderate and cessationist readings.',
      fr: 'Un bibliste de premier plan sur l’écoute de Dieu, les dons spirituels, le fruit de l’Esprit et la puissance pour témoigner, en dialogue honnête avec les lectures pentecôtiste, modérée et cessationniste.',
    },
    editions: {
      en: {
        title: 'Gift and Giver',
        author: 'Craig S. Keener',
        publisher: 'Baker Academic',
        url: 'https://bakerpublishinggroup.com/products/9781540963611_gift-and-giver',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'stronstad-charismatic-theology-of-st-luke',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['spirit-baptism', 'holy-spirit'],
    perspective: ['pentecostal'],
    status: 'needs_review',
    description: {
      en: 'The classic Pentecostal study of Luke–Acts, reading the gift of the Spirit as empowerment for prophetic witness — scholarly background for day 18.',
      fr: 'L’étude pentecôtiste classique de Luc et des Actes, qui lit le don de l’Esprit comme une puissance pour le témoignage prophétique — un arrière-plan savant pour le jour 18.',
    },
    editions: {
      en: {
        title: 'The Charismatic Theology of St. Luke',
        author: 'Roger Stronstad',
        publisher: 'Baker Academic',
        url: 'https://bakerpublishinggroup.com/products/9780801048586_the-charismatic-theology-of-st-luke',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      pt: {
        title: 'A Teologia Carismática de Lucas',
        author: 'Roger Stronstad',
        publisher: 'CPAD (Casa Publicadora das Assembleias de Deus)',
        url: 'https://www.cpad.com.br/a-teologia-carismatica-de-lucas-329267/p',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'ag-modern-day-prophecy',
    type: 'article',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['prophecy', 'discernment', 'spiritual-gifts'],
    perspective: ['pentecostal'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'The Assemblies of God’s own position paper on prophecy today: every prophecy is weighed by Scripture and the church, none carries Scripture’s authority, and prophets stay accountable — the testing the plan asks for on days 9 and 16.',
      fr: 'La prise de position officielle des Assemblées de Dieu (États-Unis) sur la prophétie aujourd’hui : toute prophétie est examinée à la lumière de l’Écriture et par l’Église, aucune n’a l’autorité de l’Écriture, et ceux qui prophétisent rendent des comptes — le discernement que le parcours demande aux jours 9 et 16.',
    },
    editions: {
      en: {
        title: 'Modern-Day Prophecy (official position paper)',
        author: 'General Presbytery of the Assemblies of God',
        publisher: 'Assemblies of God (USA)',
        url: 'https://ag.org/Beliefs/Position-Papers/Modern-Day-Prophecy',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'willard-hearing-god',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['listening', 'discernment', 'holy-spirit'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A wise, unhurried classic on hearing God within a friendship with him — weighed by Scripture, character and circumstance, never as a shortcut around thinking or around others.',
      fr: 'Un classique sage et posé sur l’écoute de Dieu dans une relation d’amitié avec lui — une écoute éprouvée par l’Écriture, le caractère et les circonstances, jamais un raccourci qui dispense de réfléchir ou de consulter les autres.',
    },
    editions: {
      en: {
        title: 'Hearing God: Developing a Conversational Relationship with God',
        author: 'Dallas Willard',
        publisher: 'IVP Formatio (InterVarsity Press)',
        url: 'https://www.ivpress.com/hearing-god',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'gotquestions-who-is-the-holy-spirit',
    type: 'article',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['holy-spirit'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A short, free answer showing from Scripture that the Holy Spirit is God and a Person who thinks, loves, can be grieved and prays for us — days 1 and 2 in a few minutes.',
      fr: 'Une réponse courte et gratuite qui montre par l’Écriture que le Saint-Esprit est Dieu et une Personne qui pense, aime, peut être attristée et prie pour nous — les jours 1 et 2 en quelques minutes.',
      es: 'Una respuesta breve y gratuita que muestra con la Escritura que el Espíritu Santo es Dios y una Persona que piensa, ama, puede ser contristada e intercede por nosotros.',
      pt: 'Uma resposta curta e gratuita que mostra pela Escritura que o Espírito Santo é Deus e uma Pessoa que pensa, ama, pode ser entristecida e intercede por nós.',
      de: 'Eine kurze, kostenlose Antwort, die aus der Schrift zeigt, dass der Heilige Geist Gott ist und eine Person, die denkt, liebt, betrübt werden kann und für uns eintritt.',
    },
    editions: {
      en: {
        title: 'Who is the Holy Spirit?',
        author: 'GotQuestions.org',
        publisher: 'Got Questions Ministries',
        url: 'https://www.gotquestions.org/who-Holy-Spirit.html',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      fr: {
        title: 'Qui est le Saint-Esprit ?',
        author: 'GotQuestions.org',
        publisher: 'Got Questions Ministries',
        url: 'https://www.gotquestions.org/Francais/Esprit-Saint.html',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      de: {
        title: 'Wer ist der Heilige Geist?',
        author: 'GotQuestions.org',
        publisher: 'Got Questions Ministries',
        url: 'https://www.gotquestions.org/Deutsch/Heilige-Geist.html',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      es: {
        title: '¿Quién es el Espíritu Santo?',
        author: 'GotQuestions.org',
        publisher: 'Got Questions Ministries',
        url: 'https://www.gotquestions.org/Espanol/Espiritu-Santo.html',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      pt: {
        title: 'Quem é o Espírito Santo?',
        author: 'GotQuestions.org',
        publisher: 'Got Questions Ministries',
        url: 'https://www.gotquestions.org/Portugues/Espirito-Santo.html',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      ru: {
        title: 'Кто такой Святой Дух?',
        author: 'GotQuestions.org',
        publisher: 'Got Questions Ministries',
        url: 'https://www.gotquestions.org/Russian/Russian-Holy-Spirit.html',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      zh: {
        title: '圣灵是谁？',
        author: 'GotQuestions.org',
        publisher: 'Got Questions Ministries',
        url: 'https://www.gotquestions.org/Chinese/Chinese-Holy-Spirit.html',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      ja: {
        title: '聖霊とは誰ですか？',
        author: 'GotQuestions.org',
        publisher: 'Got Questions Ministries',
        url: 'https://www.gotquestions.org/Japanese/Japanese-Holy-Spirit.html',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      ko: {
        title: '성령님은 누구신가?',
        author: 'GotQuestions.org',
        publisher: 'Got Questions Ministries',
        url: 'https://www.gotquestions.org/Korean/Korean-Holy-Spirit.html',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      ar: {
        title: 'من هو الروح القدس؟',
        author: 'GotQuestions.org',
        publisher: 'Got Questions Ministries',
        url: 'https://www.gotquestions.org/Arabic/Arabic-Holy-Spirit.html',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      fa: {
        title: 'روح القدس کیست؟',
        author: 'GotQuestions.org',
        publisher: 'Got Questions Ministries',
        url: 'https://www.gotquestions.org/Farsi/Farsi-Holy-Spirit.html',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      hi: {
        title: 'पवित्र आत्मा कौन है?',
        author: 'GotQuestions.org',
        publisher: 'Got Questions Ministries',
        url: 'https://www.gotquestions.org/Hindi/Hindi-Holy-Spirit.html',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      id: {
        title: 'Siapakah Roh Kudus?',
        author: 'GotQuestions.org',
        publisher: 'Got Questions Ministries',
        url: 'https://www.gotquestions.org/Indonesia/siapakah-Roh-Kudus.html',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      sw: {
        title: 'Roho mtakatifu ni nani?',
        author: 'GotQuestions.org',
        publisher: 'Got Questions Ministries',
        url: 'https://www.gotquestions.org/Kiswahili/Roho-Mtakatifu.html',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      tl: {
        title: 'Sino ba ang Banal na Espiritu?',
        author: 'GotQuestions.org',
        publisher: 'Got Questions Ministries',
        url: 'https://www.gotquestions.org/Tagalog/Banal-Espiritu.html',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      am: {
        title: 'መንፈስ ቃዱስ ማነው?',
        author: 'GotQuestions.org',
        publisher: 'Got Questions Ministries',
        url: 'https://www.gotquestions.org/Amharic/Amharic-Holy-Spirit.html',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'storms-beginners-guide-to-spiritual-gifts',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['spiritual-gifts', 'prophecy', 'holy-spirit'],
    perspective: ['charismatic', 'reformed'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A pastor-theologian’s clear introduction to the gifts of 1 Corinthians 12–14 — prophecy, tongues, healing and the rest — given for the good of others and always exercised in love and under testing.',
      fr: 'Une introduction claire, par un pasteur-théologien, aux dons de 1 Corinthiens 12 à 14 — prophétie, langues, guérison et les autres — donnés pour le bien des autres et toujours exercés dans l’amour et soumis à l’examen.',
    },
    editions: {
      en: {
        title: 'The Beginner’s Guide to Spiritual Gifts',
        author: 'Sam Storms',
        publisher: 'Bethany House Publishers',
        url: 'https://bakerpublishinggroup.com/products/9780764215926_the-beginners-guide-to-spiritual-gifts',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'stott-message-of-acts',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['holy-spirit', 'spirit-baptism', 'church'],
    perspective: ['evangelical', 'anglican'],
    status: 'needs_review',
    description: {
      en: 'A readable expository commentary on Acts — Pentecost, the Spirit-filled church and power for witness — from an Anglican evangelical who reads Spirit baptism differently from Pentecostals, the “other view” day 18 names.',
      fr: 'Un commentaire accessible des Actes — la Pentecôte, l’Église remplie de l’Esprit, la puissance pour témoigner — par un évangélique anglican qui lit le baptême dans l’Esprit autrement que les pentecôtistes : l’« autre lecture » nommée au jour 18.',
    },
    editions: {
      en: {
        title: 'The Message of Acts (The Bible Speaks Today)',
        author: 'John Stott',
        publisher: 'IVP Academic (InterVarsity Press)',
        url: 'https://www.ivpress.com/the-message-of-acts',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'fee-first-epistle-to-the-corinthians',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['spiritual-gifts'],
    perspective: ['pentecostal', 'evangelical'],
    status: 'needs_review',
    description: {
      en: 'The standard commentary on 1 Corinthians by a Pentecostal scholar — gifts, love, tongues and weighing prophecy in chapters 12–14 — for readers who want to study days 16 and 17 in depth.',
      fr: 'Le commentaire de référence sur 1 Corinthiens, par un bibliste pentecôtiste — dons, amour, langues et discernement des prophéties aux chapitres 12 à 14 — pour qui veut approfondir les jours 16 et 17.',
    },
    editions: {
      en: {
        title: 'The First Epistle to the Corinthians, Revised Edition (NICNT)',
        author: 'Gordon D. Fee',
        publisher: 'Eerdmans',
        url: 'https://www.eerdmans.com/9780802871367/the-first-epistle-to-the-corinthians-revised-edition/',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'fee-saint-esprit-presence-renouvelee-de-dieu',
    type: 'article',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['holy-spirit'],
    perspective: ['pentecostal', 'evangelical'],
    status: 'needs_review',
    description: {
      en: 'A free French translation of Gordon Fee’s lecture on the Spirit as God’s own renewed presence — personal, not an impersonal force — among his people and in each believer.',
      fr: 'Une conférence de Gordon Fee, traduite en français et gratuite, sur l’Esprit comme présence renouvelée de Dieu lui-même — une Personne, non une force impersonnelle — au milieu de son peuple et en chaque croyant.',
    },
    editions: {
      fr: {
        title: 'Le Saint-Esprit, présence renouvelée de Dieu',
        author: 'Gordon Fee',
        publisher: 'Évangile 21 (The Gospel Coalition)',
        url: 'https://evangile21.thegospelcoalition.org/article/le-saint-esprit-presence-renouvelee-de-dieu/',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'blocher-plenitude-du-saint-esprit',
    type: 'article',
    originalLanguage: 'fr',
    domains: ['christian-living'],
    topics: ['spirit-baptism', 'holy-spirit'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A French theologian distinguishes two biblical senses of being “full of the Spirit” — sudden empowering for speaking God’s word, and a lasting saturation of character — and urges believers to seek both.',
      fr: 'Un théologien français distingue deux sens bibliques d’« être rempli de l’Esprit » — un élan soudain de puissance pour annoncer la Parole, et une imprégnation durable du caractère — et invite à rechercher l’une et l’autre.',
    },
    editions: {
      fr: {
        title: 'La plénitude du Saint-Esprit',
        author: 'Henri Blocher',
        publisher: 'Évangile 21 (The Gospel Coalition), d’après la revue Ichthus',
        url: 'https://evangile21.thegospelcoalition.org/article/la-plenitude-du-saint-esprit/',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'bfp-grundlegende-wirkungen-des-heiligen-geistes',
    type: 'article',
    originalLanguage: 'de',
    domains: ['christian-living'],
    topics: ['spirit-baptism', 'holy-spirit', 'spiritual-gifts'],
    perspective: ['pentecostal'],
    status: 'needs_review',
    description: {
      en: 'The German Pentecostal federation’s statement on the Spirit in new birth and in Spirit baptism as empowerment for service, calling tongues a clear but not mandatory sign — close to the plan’s own balance on day 18.',
      fr: 'La prise de position de la fédération pentecôtiste allemande sur l’Esprit dans la nouvelle naissance et dans le baptême de l’Esprit comme puissance pour servir ; elle présente les langues comme un signe clair mais non obligatoire — proche de l’équilibre du jour 18.',
      de: 'Die Stellungnahme des BFP zum Wirken des Geistes in der Wiedergeburt und in der Geistestaufe als Bevollmächtigung zum Dienst; das Zungenreden gilt darin als deutliches, aber nicht zwingendes Zeichen.',
    },
    editions: {
      de: {
        title: 'Die grundlegenden Wirkungen des Heiligen Geistes auf das Leben des Menschen: Die Rolle des Heiligen Geistes in der christlichen Initiation',
        author: 'Bund Freikirchlicher Pfingstgemeinden (BFP)',
        publisher: 'Bund Freikirchlicher Pfingstgemeinden KdöR',
        url: 'https://www.bfp.de/de/bfp-ordnungen?file=files%2Fdocs%2Fbfp-statements%2FBFP-Stellungnahme-Grundlegende-Wirkungen-Heiliger-Geist-2019.pdf&cid=12110',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'rust-geist-gottes-quelle-des-lebens',
    type: 'book',
    originalLanguage: 'de',
    domains: ['christian-living'],
    topics: ['holy-spirit', 'spiritual-gifts'],
    perspective: ['charismatic', 'evangelical'],
    status: 'needs_review',
    description: {
      en: 'A German Baptist pastor-theologian of the charismatic renewal grounds experience of the Spirit in sound theology — the Spirit’s work in the world, the church and each person.',
      fr: 'Un pasteur-théologien baptiste allemand, acteur du renouveau charismatique, enracine l’expérience de l’Esprit dans une théologie solide — l’œuvre de l’Esprit dans le monde, l’Église et chaque personne.',
      de: 'Ein Pastor und Theologe der charismatischen Erneuerung verankert die Erfahrung des Geistes in einer tragfähigen Theologie — Gottes Geist in der Welt, in der Gemeinde und im einzelnen Menschen.',
    },
    editions: {
      de: {
        title: 'Geist Gottes – Quelle des Lebens: Grundlagen einer missionalen Pneumatologie',
        author: 'Heinrich Christian Rust',
        publisher: 'Neufeld Verlag (Edition TSC-IGW)',
        url: 'https://www.neufeld-verlag.de/shop/geist-gottes-quelle-des-lebens/',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'salcedo-como-andar-por-el-espiritu',
    type: 'teaching',
    originalLanguage: 'es',
    domains: ['christian-living'],
    topics: ['holy-spirit', 'fruit-of-the-spirit'],
    perspective: ['evangelical', 'reformed'],
    status: 'needs_review',
    description: {
      en: 'A six-session Spanish video course by a Dominican pastor on who the Spirit is, what walking by the Spirit means, its obstacles, and cultivating his fruit (Galatians 5).',
      fr: 'Un cours vidéo en espagnol, en six séances, par un pasteur dominicain : qui est l’Esprit, ce que signifie marcher par l’Esprit, les obstacles, et la culture de son fruit (Galates 5).',
      es: 'Un curso en video de seis sesiones sobre quién es el Espíritu, qué significa andar por el Espíritu, sus obstáculos y cómo cultivar su fruto (Gálatas 5).',
    },
    editions: {
      es: {
        title: 'Cómo andar por el Espíritu',
        author: 'Héctor Salcedo',
        publisher: 'Coalición por el Evangelio',
        url: 'https://www.coalicionporelevangelio.org/curso/como-andar-por-el-espiritu/',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'he-chunxun-ruhe-jiechu-shengling-de-guozi',
    type: 'article',
    originalLanguage: 'zh',
    domains: ['christian-living'],
    topics: ['fruit-of-the-spirit', 'holy-spirit'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A Chinese pastor’s article on the nine-fold fruit of Galatians 5 as the Spirit’s work rather than natural temperament, and on why Corinth, rich in gifts, still lacked fruit.',
      fr: 'Un article d’un pasteur chinois sur le fruit de l’Esprit (Galates 5), œuvre de l’Esprit et non tempérament naturel, et sur la raison pour laquelle Corinthe, riche en dons, manquait encore de fruit.',
      zh: '一篇华人牧者的文章：加拉太书五章的九样果子是圣灵的工作，而不是天生的性情；哥林多教会恩赐丰富，却仍缺少果子。',
    },
    editions: {
      zh: {
        title: '我如何结出“圣灵的果子”？',
        author: '何春勋',
        publisher: '生命季刊 (Christian Life Quarterly)',
        url: 'https://www.cclife.org/View/Article/6249',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'sgc-holy-life-fullness-of-the-spirit',
    type: 'study',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['holiness', 'holy-spirit', 'fruit-of-the-spirit'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A free lesson from a Bible-college course, in many languages, on Pentecost, Peter’s change and the fruit of the Spirit as the mark of a Spirit-filled, holy life.',
      fr: 'Une leçon gratuite d’un cours de niveau institut biblique, disponible en de nombreuses langues, sur la Pentecôte, la transformation de Pierre et le fruit de l’Esprit comme marque d’une vie sainte remplie de l’Esprit.',
      es: 'Una lección gratuita de un curso de nivel instituto bíblico, en muchos idiomas, sobre Pentecostés, el cambio de Pedro y el fruto del Espíritu como señal de una vida santa llena del Espíritu.',
      pt: 'Uma lição gratuita de um curso de nível bíblico, em muitas línguas, sobre o Pentecostes, a mudança de Pedro e o fruto do Espírito como marca de uma vida santa cheia do Espírito.',
      sw: 'Somo la bure kutoka kozi ya kiwango cha chuo cha Biblia, kuhusu Pentekoste, mabadiliko ya Petro, na tunda la Roho kama alama ya maisha matakatifu yaliyojaa Roho.',
    },
    editions: {
      en: {
        title: 'Doctrine and Practice of the Holy Life — Lesson 9: A Holy Life Is Lived in the Fullness of the Spirit',
        author: 'Randall McElwain',
        publisher: 'Shepherds Global Classroom',
        url: 'https://courses.shepherdsglobal.org/english/doctrine-and-practice-of-the-holy-life/lesson/9-a-holy-life-is-lived-in-the-fullness-of-the-spirit',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      fr: {
        title: 'La doctrine et la pratique de la sanctification — Leçon 9 : La sainteté est la plénitude du Saint-Esprit',
        author: 'Randall McElwain',
        publisher: 'Shepherds Global Classroom',
        url: 'https://courses.shepherdsglobal.org/french/doctrine-and-practice-of-the-holy-life/lesson/9-la-saintet%C3%A9-est-la-pl%C3%A9nitude-du-saint-esprit',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      es: {
        title: 'Doctrina y práctica de la vida santa — Lección 9: Una vida santa se vive en la plenitud del Espíritu',
        author: 'Randall McElwain',
        publisher: 'Shepherds Global Classroom',
        url: 'https://courses.shepherdsglobal.org/spanish/doctrine-and-practice-of-the-holy-life/lesson/9-una-vida-santa-se-vive-en-la-plenitud-del-esp%C3%ADritu',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      pt: {
        title: 'Doutrina e Prática da Vida Santa — Lição 9: Uma Vida Santa é Vivida na Plenitude do Espírito',
        author: 'Randall McElwain',
        publisher: 'Shepherds Global Classroom',
        url: 'https://courses.shepherdsglobal.org/portuguese/doctrine-and-practice-of-the-holy-life/lesson/9-uma-vida-santa-%C3%A9-vivida-na-plenitude-do-esp%C3%ADrito',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      ru: {
        title: 'Доктрина и практика святой жизни — Урок 9: Святая жизнь в полноте Духа',
        author: 'Randall McElwain',
        publisher: 'Shepherds Global Classroom',
        url: 'https://courses.shepherdsglobal.org/russian/doctrine-and-practice-of-the-holy-life/lesson/9-%D1%81%D0%B2%D1%8F%D1%82%D0%B0%D1%8F-%D0%B6%D0%B8%D0%B7%D0%BD%D1%8C-%D0%B2-%D0%BF%D0%BE%D0%BB%D0%BD%D0%BE%D1%82%D0%B5-%D0%B4%D1%83%D1%85%D0%B0',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      ar: {
        title: 'عقيدة وممارسة حياة القدَّاسة — الدرس 9: حياة القداسة تُعاش في ملء الروح',
        author: 'Randall McElwain',
        publisher: 'Shepherds Global Classroom',
        url: 'https://courses.shepherdsglobal.org/arabic/doctrine-and-practice-of-the-holy-life/lesson/9-%D8%AD%D9%8A%D8%A7%D8%A9-%D8%A7%D9%84%D9%82%D8%AF%D8%A7%D8%B3%D8%A9-%D8%AA%D8%B9%D8%A7%D8%B4-%D9%81%D9%8A-%D9%85%D9%84%D8%A1-%D8%A7%D9%84%D8%B1%D9%88%D8%AD',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      zh: {
        title: '圣洁生活的教义与实践 — 第9课 圣洁生活就是被圣灵充满的生活',
        author: 'Randall McElwain',
        publisher: 'Shepherds Global Classroom',
        url: 'https://courses.shepherdsglobal.org/simplified-chinese/doctrine-and-practice-of-the-holy-life/lesson/9-%E7%AC%AC9%E8%AF%BE-%E5%9C%A3%E6%B4%81%E7%94%9F%E6%B4%BB%E5%B0%B1%E6%98%AF%E8%A2%AB%E5%9C%A3%E7%81%B5%E5%85%85%E6%BB%A1%E7%9A%84%E7%94%9F%E6%B4%BB',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      tl: {
        title: 'Doktrina at Pagsasabuhay ng Isang Buhay na Banal — Aralin 9: Ang Banal na Buhay ay Ipinapamuhay sa Kapuspusan ng Espiritu',
        author: 'Randall McElwain',
        publisher: 'Shepherds Global Classroom',
        url: 'https://courses.shepherdsglobal.org/tagalog/doctrine-and-practice-of-the-holy-life/lesson/9-ang-banal-na-buhay-ay-ipinapamuhay-sa-kapuspusan-ng-espiritu',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      sw: {
        title: 'Mafundisho na mazoezi ya maisha Matakatifu — Somo 9: Maisha Matakatifu ni katika Ukamilifu wa Roho',
        author: 'Randall McElwain',
        publisher: 'Shepherds Global Classroom',
        url: 'https://courses.shepherdsglobal.org/kiswahili/doctrine-and-practice-of-the-holy-life/lesson/9-maisha-matakatifu-ni-katika-ukamilifu-wa-roho',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'bibleproject-spirit-of-god-podcast',
    type: 'podcast',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['holy-spirit', 'spiritual-gifts'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'An 11-episode conversation tracing God’s Spirit as his personal, life-giving presence from Genesis to Pentecost and the gifted church — Scripture-first background for the whole plan.',
      fr: 'Une série de 11 épisodes (en anglais) qui suit l’Esprit de Dieu, sa présence personnelle et vivifiante, de la Genèse à la Pentecôte et à l’Église dotée de dons — un arrière-plan biblique pour tout le parcours.',
    },
    editions: {
      en: {
        title: 'Spirit of God (podcast series)',
        author: 'Tim Mackie and Jon Collins',
        publisher: 'BibleProject',
        url: 'https://bibleproject.com/podcasts/series/spirit-of-god/',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'hayford-sorting-out-spiritual-language',
    type: 'article',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['spirit-baptism', 'spiritual-gifts'],
    perspective: ['pentecostal'],
    status: 'needs_review',
    description: {
      en: 'A gentle Pentecostal pastor on praying in tongues as a gift and a resource for prayer, “not as a proof” — irenic toward Christians who read it differently, as day 12 asks.',
      fr: 'Un pasteur pentecôtiste bienveillant sur la prière en langues comme don et ressource pour la prière, et non comme une « preuve » — paisible envers les chrétiens qui lisent autrement, comme le demande le jour 12.',
    },
    editions: {
      en: {
        title: 'Sorting Out Spiritual Language',
        author: 'Jack W. Hayford',
        publisher: 'Jack Hayford Ministries',
        url: 'https://www.jackhayford.org/teaching/articles/sorting-out-spiritual-language/',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
];
