// Candidates for identity21, researched 2026-09-29. NONE is approved: every entry is
// needs_review with no sign-off, so the resolver never shows it. See
// docs/resources/candidates/identity21.md for the verification worksheet.
//
// Tagging rule for this plan: the christian-living shelf is shared by seven
// "Growing in Christ" plans, so entries carry the identity plan's gospel topics
// (identity, gospel, holiness, repentance, forgiveness, church…) only where the
// work is centrally about them, and never manhood/womanhood. Generic
// self-esteem or positive-affirmation material is rejected in the worksheet.

const VERIFIED = '2026-09-29';
const BP = 'BibleProject';
// A BibleProject video edition. Languages without a dedicated video page link to
// BibleProject's own language hub, where the video is listed (title as listed)
// with in-page play, YouTube and download — the same pattern as psalms42.
const bp = (title, url, publisher = BP) => ({
  title, author: BP, publisher, url, available: true, lastVerifiedAt: VERIFIED,
});

export const IDENTITY21_CANDIDATES = [
  {
    id: 'wilbourne-union-with-christ',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['identity', 'gospel', 'spiritual-formation'],
    perspective: ['reformed', 'evangelical'],
    status: 'needs_review',
    description: {
      en: 'A pastor’s accessible book on union with Christ — being “in Christ” and Christ in us — as the answer to “who am I?”, the thread that runs through the whole plan.',
      fr: 'Un livre accessible d’un pasteur sur l’union avec Christ — être « en Christ » et Christ en nous — comme réponse à la question « qui suis-je ? », fil conducteur de tout le parcours.',
    },
    editions: {
      en: {
        title: 'Union with Christ: The Way to Know and Enjoy God',
        author: 'Rankin Wilbourne',
        publisher: 'David C Cook',
        url: 'https://shop.davidccook.org/products/union-with-christ',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
      de: {
        title: 'Einheit mit Christus: Gott erkennen und sich an ihm erfreuen',
        author: 'Rankin Wilbourne',
        publisher: '3L Verlag',
        url: 'https://www.3lverlag.de/kategorien/1771--einheit-mit-christus.html',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
    },
  },
  {
    id: 'ferguson-children-of-the-living-god',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['identity', 'gospel', 'prayer'],
    perspective: ['reformed', 'evangelical'],
    status: 'needs_review',
    description: {
      en: 'A short classic on new birth and adoption into God’s family — calling God Father, the Spirit of adoption, freedom and prayer — for the “born of God” and “Abba” days.',
      fr: 'Un court classique sur la nouvelle naissance et l’adoption dans la famille de Dieu — appeler Dieu Père, l’Esprit d’adoption, la liberté et la prière — pour les jours « né de Dieu » et « Abba ».',
    },
    editions: {
      en: {
        title: 'Children of the Living God',
        author: 'Sinclair B. Ferguson',
        publisher: 'Banner of Truth',
        url: 'https://banneroftruth.org/uk/store/theology/children-of-the-living-god/',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
    },
  },
  {
    id: 'keller-freedom-of-self-forgetfulness',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['identity', 'gospel', 'contentment'],
    perspective: ['reformed', 'evangelical'],
    status: 'needs_review',
    description: {
      en: 'A very short book on 1 Corinthians 3–4: the verdict of justification frees us from needing others’ approval or our own — the opposite of self-esteem teaching.',
      fr: 'Un tout petit livre sur 1 Corinthiens 3–4 : le verdict de la justification libère du besoin de l’approbation des autres comme de la sienne — l’inverse d’un discours sur l’estime de soi.',
    },
    editions: {
      en: {
        title: 'The Freedom of Self-Forgetfulness: The Path to True Christian Joy',
        author: 'Timothy Keller',
        publisher: '10Publishing (10ofThose)',
        url: 'https://us.10ofthose.com/product/9781906173418/the-freedom-of-self-forgetfulness-paperback',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
      es: {
        title: 'La libertad de olvidarse de uno mismo: El camino al verdadero gozo cristiano',
        author: 'Timothy Keller',
        publisher: 'B&H Español',
        url: 'https://www.bhpublishinggroup.com/product/la-libertad-de-olvidarse-de-uno-mismo-2/',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
      pt: {
        title: 'Ego transformado: a humildade que brota do evangelho e traz a verdadeira alegria',
        author: 'Timothy Keller',
        publisher: 'Edições Vida Nova',
        url: 'https://www.vidanova.com.br/livros/ego-transformado-a-humildade-que-brota-do-evangelho-e-traz-a-verdadeira-alegria',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
    },
  },
  {
    id: 'bibleproject-ephesians-overview',
    type: 'video',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['gospel', 'identity', 'church', 'community'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A free nine-minute animated overview of Ephesians: grace, being chosen “in Christ”, and one new multi-ethnic family — the backbone of the plan’s belonging days.',
      fr: 'Un panorama animé gratuit de neuf minutes sur Éphésiens : la grâce, être choisi « en Christ » et une seule famille nouvelle issue de tous les peuples — l’ossature des jours sur l’appartenance.',
    },
    editions: {
      en: bp('Ephesians', 'https://bibleproject.com/videos/ephesians/'),
      fr: bp('Éphésiens', 'https://bibleproject.com/fr/videos/ephesiens/'),
      es: bp('Efesios', 'https://bibleproject.com/es/videos/efesios/'),
      pt: bp('Efésios', 'https://bibleproject.com/pt-br/videos/efesios/'),
      de: bp('Epheser', 'https://bibleproject.visiomedia.org/video/epheser/', 'BibleProject – Deutsch (Visiomedia)'),
      ru: bp('Обзор: Ефесянам', 'https://bibleproject.com/ru/'),
      zh: bp('以弗所书 - Ephesians', 'https://bibleproject.com/zh-hans/'),
      ja: bp('エペソ人への手紙 Ephesians', 'https://bibleproject.com/ja/'),
      ko: bp('에베소서 개요 Ephesians', 'https://bibleproject.com/ko/'),
      ar: bp('نظرة عامّة: الرسالة إلى أفسس', 'https://bibleproject.com/ar/'),
      fa: bp('مروری بر افسسیان', 'https://bibleproject.com/fa/'),
      hi: bp('अवलोकन: इफिसियों Ephesians', 'https://bibleproject.com/hi/'),
      id: bp('Ringkasan: Efesus', 'https://bibleproject.com/id/'),
      sw: bp('Muhtasari: Waefeso', 'https://bibleproject.com/sw/'),
      tl: bp('Buong-ideya: Efeso', 'https://bibleproject.com/tl/'),
      am: bp('ዳሰሳ፦ ኤፌሶን Ephesians', 'https://bibleproject.com/am/'),
    },
  },
  {
    id: 'bibleproject-romans-5-16-overview',
    type: 'video',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['gospel', 'holiness', 'identity'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A free nine-minute animated overview of Romans 5–16: new life in Christ, freedom from sin’s rule, no condemnation and the Spirit of adoption — the ground of days 5, 10 and 16.',
      fr: 'Un panorama animé gratuit de neuf minutes sur Romains 5–16 : la vie nouvelle en Christ, la liberté face à l’emprise du péché, l’absence de condamnation et l’Esprit d’adoption — le socle des jours 5, 10 et 16.',
    },
    editions: {
      en: bp('Romans 5-16', 'https://bibleproject.com/videos/romans-5-16/'),
      fr: bp('Romains 5-16', 'https://bibleproject.com/fr/videos/romains-5-16/'),
      es: bp('Romanos 5-16', 'https://bibleproject.com/es/videos/romanos-5-16/'),
      pt: bp('Romanos 5-16', 'https://bibleproject.com/pt-br/videos/romanos-5-16/'),
      de: bp('Römer • Teil 2', 'https://bibleproject.visiomedia.org/video/roemer-2/', 'BibleProject – Deutsch (Visiomedia)'),
      ru: bp('Обзор: Римлянам 5-16', 'https://bibleproject.com/ru/'),
      zh: bp('罗马书 下集 - Romans 5-16', 'https://bibleproject.com/zh-hans/'),
      ja: bp('ローマ人への手紙 5-16章 Romans 5-16', 'https://bibleproject.com/ja/'),
      ko: bp('로마서 5~16장 개요 Romans 5-16', 'https://bibleproject.com/ko/'),
      ar: bp('نظرة عامّة: الرسالة إلى روما 5 - 16', 'https://bibleproject.com/ar/'),
      fa: bp('مروری بر رومیان ۱۶-۵', 'https://bibleproject.com/fa/'),
      hi: bp('१२_रोमियों५-१६ Romans 5-16', 'https://bibleproject.com/hi/'),
      id: bp('Ringkasan: Roma 5-16', 'https://bibleproject.com/id/'),
      sw: bp('Muhtasari: Warumi 5-16', 'https://bibleproject.com/sw/'),
      tl: bp('Buong-ideya: Roma 5-16', 'https://bibleproject.com/tl/'),
      am: bp('ዳሰሳ፦ ሮሜ 5-16 Romans', 'https://bibleproject.com/am/'),
    },
  },
  {
    // No fa edition: the Persian hub lists a Colossians slot but titles it
    // "مروری بر غلاطیان" (Galatians), so the Persian video could not be confirmed.
    id: 'bibleproject-colossians-overview',
    type: 'video',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['gospel', 'identity', 'spiritual-formation'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A free nine-minute animated overview of Colossians: Christ over all, our life raised and “hidden with Christ”, and every part of life remade — for the plan’s final day.',
      fr: 'Un panorama animé gratuit de neuf minutes sur Colossiens : Christ au-dessus de tout, notre vie ressuscitée et « cachée avec Christ », chaque domaine de la vie renouvelé — pour le dernier jour du parcours.',
    },
    editions: {
      en: bp('Colossians', 'https://bibleproject.com/videos/colossians/'),
      fr: bp('Colossiens', 'https://bibleproject.com/fr/videos/colossiens/'),
      es: bp('Colosenses', 'https://bibleproject.com/es/videos/colosenses/'),
      pt: bp('Colossenses', 'https://bibleproject.com/pt-br/videos/colossenses/'),
      de: bp('Kolosser', 'https://bibleproject.visiomedia.org/video/kolosser/', 'BibleProject – Deutsch (Visiomedia)'),
      ru: bp('Обзор: Колоссянам', 'https://bibleproject.com/ru/'),
      zh: bp('歌罗西书 - Colossians', 'https://bibleproject.com/zh-hans/'),
      ja: bp('コロサイ人への手紙 Colossians', 'https://bibleproject.com/ja/'),
      ko: bp('골로새서 개요 Colossians', 'https://bibleproject.com/ko/'),
      ar: bp('نظرة عامّة: الرسالة إلى كولوسّي', 'https://bibleproject.com/ar/'),
      hi: bp('अवलोकन: कुलुस्सियों Colossians', 'https://bibleproject.com/hi/'),
      id: bp('Ringkasan: Kolose', 'https://bibleproject.com/id/'),
      sw: bp('Muhtasari: Wakolosai', 'https://bibleproject.com/sw/'),
      tl: bp('Buong-ideya: Colosas', 'https://bibleproject.com/tl/'),
      am: bp('ዳሰሳ፦ ቆላስይስ Colossians', 'https://bibleproject.com/am/'),
    },
  },
  {
    id: 'bridges-who-am-i',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['identity', 'gospel', 'holiness'],
    perspective: ['reformed', 'evangelical'],
    status: 'needs_review',
    description: {
      en: 'A short book giving eight biblical answers to “who am I?” — creature, in Christ, justified, adopted, new creation, saint, servant, and “not yet perfect” — very close to this plan’s arc.',
      fr: 'Un petit livre qui donne huit réponses bibliques à « qui suis-je ? » — créature, en Christ, justifié, adopté, nouvelle création, saint, serviteur et « pas encore parfait » — très proche du fil de ce parcours.',
    },
    editions: {
      en: {
        title: 'Who Am I? Identity in Christ',
        author: 'Jerry Bridges',
        publisher: 'Cruciform Press',
        url: 'https://www.cruciformpress.com/product/who-am-i/',
        available: true,
        lastVerifiedAt: VERIFIED,
      },
    },
  },
  {
    id: 'billings-union-with-christ',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['identity', 'gospel', 'church'],
    perspective: ['reformed'],
    status: 'needs_review',
    description: {
      en: 'A theologian’s study of union with Christ and adoption and what they mean for worship, the church and mission — for readers who want the doctrine behind the plan in more depth.',
      fr: 'L’étude d’un théologien sur l’union avec Christ et l’adoption, et leurs conséquences pour le culte, l’Église et la mission — pour qui veut approfondir la doctrine qui porte le parcours.',
    },
    editions: {
      en: {
        title: 'Union with Christ: Reframing Theology and Ministry for the Church',
        author: 'J. Todd Billings',
        publisher: 'Baker Academic',
        url: 'https://bakerpublishinggroup.com/products/9780801039348_union-with-christ',
        available: true,
        lastVerifiedAt: VERIFIED,
      },
    },
  },
  {
    id: 'keener-mind-of-the-spirit',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['holy-spirit', 'spiritual-formation', 'holiness'],
    perspective: ['charismatic', 'evangelical'],
    status: 'needs_review',
    description: {
      en: 'A New Testament scholar from a charismatic background on how Paul describes the renewed mind — “count yourselves dead to sin” (Romans 6), the mind of the Spirit (Romans 8), setting the mind above (Colossians 3).',
      fr: 'Un bibliste du Nouveau Testament, issu du monde charismatique, sur l’intelligence renouvelée selon Paul — « considérez-vous comme morts au péché » (Romains 6), la pensée de l’Esprit (Romains 8), penser aux choses d’en haut (Colossiens 3).',
    },
    editions: {
      en: {
        title: 'The Mind of the Spirit: Paul’s Approach to Transformed Thinking',
        author: 'Craig S. Keener',
        publisher: 'Baker Academic',
        url: 'https://bakerpublishinggroup.com/products/9781540961136_the-mind-of-the-spirit',
        available: true,
        lastVerifiedAt: VERIFIED,
      },
    },
  },
  {
    id: 'gotquestions-identity-in-christ',
    type: 'article',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['identity', 'gospel', 'church', 'kingdom-of-god'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A short free article on living from identity in Christ: a new creation, adopted and able to call God Father, part of his family, a citizen of his kingdom.',
      fr: 'Un court article gratuit sur la vie à partir de l’identité en Christ : nouvelle création, adopté et pouvant appeler Dieu Père, membre de sa famille, citoyen de son royaume.',
    },
    editions: {
      en: { title: 'How should we live our lives in light of our identity in Christ?', author: 'Got Questions Ministries', publisher: 'GotQuestions.org', url: 'https://www.gotquestions.org/identity-in-Christ.html', available: true, lastVerifiedAt: VERIFIED },
      fr: { title: 'Comment devons-nous vivre notre vie à la lumière de notre identité en Christ ?', author: 'Got Questions Ministries', publisher: 'GotQuestions.org', url: 'https://www.gotquestions.org/Francais/notre-identite-en-Christ.html', available: true, lastVerifiedAt: VERIFIED },
      es: { title: '¿Cómo debemos vivir nuestra vida a la luz de nuestra identidad en Cristo?', author: 'Got Questions Ministries', publisher: 'GotQuestions.org', url: 'https://www.gotquestions.org/Espanol/identidad-en-Cristo.html', available: true, lastVerifiedAt: VERIFIED },
      pt: { title: 'Como devemos viver nossas vidas à luz da nossa identidade em Cristo?', author: 'Got Questions Ministries', publisher: 'GotQuestions.org', url: 'https://www.gotquestions.org/Portugues/identidade-em-Cristo.html', available: true, lastVerifiedAt: VERIFIED },
      ru: { title: 'Как мы должны жить в свете нашей идентичности во Христе?', author: 'Got Questions Ministries', publisher: 'GotQuestions.org', url: 'https://www.gotquestions.org/Russian/Russian-identity-in-Christ.html', available: true, lastVerifiedAt: VERIFIED },
      ar: { title: 'كيف يجب أن نعيش حياتنا في ضوء هويتنا في المسيح؟', author: 'Got Questions Ministries', publisher: 'GotQuestions.org', url: 'https://www.gotquestions.org/Arabic/Arabic-identity-in-Christ.html', available: true, lastVerifiedAt: VERIFIED },
      id: { title: 'Bagaimana seharusnya kita menjalani kehidupan kita berdasarkan identitas kita di dalam Kristus?', author: 'Got Questions Ministries', publisher: 'GotQuestions.org', url: 'https://www.gotquestions.org/Indonesia/identitas-di-dalam-Kristus.html', available: true, lastVerifiedAt: VERIFIED },
      sw: { title: 'Je, ni namna gani tunapaswa kuishi maisha yetu kulingana na utambulisho wetu katika Kristo?', author: 'Got Questions Ministries', publisher: 'GotQuestions.org', url: 'https://www.gotquestions.org/Kiswahili/Utambulisho-katika-Kristo.html', available: true, lastVerifiedAt: VERIFIED },
      tl: { title: 'Paano ba tayo dapat mamuhay ayon sa liwanag ng ating pagkakakilanlan kay Cristo?', author: 'Got Questions Ministries', publisher: 'GotQuestions.org', url: 'https://www.gotquestions.org/Tagalog/pagkakakilanlan-kay-Cristo.html', available: true, lastVerifiedAt: VERIFIED },
    },
  },
  {
    id: 'morey-introduccion-union-con-cristo',
    type: 'article',
    originalLanguage: 'es',
    domains: ['christian-living'],
    topics: ['identity', 'gospel', 'holiness'],
    perspective: ['reformed', 'evangelical'],
    status: 'needs_review',
    description: {
      en: 'A Spanish-language pastor’s short introduction to union with Christ — grafted into him, sharing in his death and resurrection — and the assurance, joy and desire for holiness it brings.',
      fr: 'Une courte introduction, par un pasteur hispanophone, à l’union avec Christ — greffé en lui, participant à sa mort et à sa résurrection — et à l’assurance, la joie et le désir de sainteté qui en découlent.',
    },
    editions: {
      es: {
        title: 'Una introducción a nuestra Unión con Cristo',
        author: 'Gerson Morey',
        publisher: 'Coalición por el Evangelio',
        url: 'https://www.coalicionporelevangelio.org/entradas/gerson-morey/una-introduccion-a-nuestra-union-con-cristo/',
        available: true,
        lastVerifiedAt: VERIFIED,
      },
    },
  },
  {
    id: 'lotz-identitaet-wiederhergestellt-in-christus',
    type: 'teaching',
    originalLanguage: 'de',
    domains: ['christian-living'],
    topics: ['identity', 'gospel', 'church'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A German-language talk that receives identity from God’s Word rather than constructing it: a sinner saved by grace, a child of God, a member of Christ’s body, a co-heir with Christ.',
      fr: 'Une conférence en allemand qui reçoit l’identité de la Parole de Dieu au lieu de la construire : pécheur sauvé par grâce, enfant de Dieu, membre du corps de Christ, cohéritier avec Christ.',
    },
    editions: {
      de: {
        title: 'Identität wiederhergestellt in Christus',
        author: 'Kim Lotz',
        publisher: 'Evangelium21',
        url: 'https://www.evangelium21.net/media/2035/identitaet-wiederhergestellt-in-christus',
        available: true,
        lastVerifiedAt: VERIFIED,
      },
    },
  },
  {
    // Written by ten women and marketed to women; the content is general
    // identity in Christ, so it is NOT tagged womanhood — see the worksheet.
    id: 'kruger-identity-theft',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['identity', 'gospel', 'church', 'kingdom-of-god'],
    perspective: ['evangelical', 'reformed'],
    status: 'needs_review',
    description: {
      en: 'Ten short chapters, each with group questions: saved by grace, made in God’s image, loved by the Father, member of the church, citizen longing for home — almost the plan’s own outline.',
      fr: 'Dix courts chapitres, chacun avec des questions pour un groupe : sauvé par grâce, créé à l’image de Dieu, aimé du Père, membre de l’Église, citoyen en attente de sa patrie — presque le plan du parcours.',
    },
    editions: {
      en: {
        title: 'Identity Theft: Reclaiming the Truth of Who We Are in Christ',
        author: 'Melissa B. Kruger (ed.), with Jen Wilkin, Trillia Newbell, Hannah Anderson and others',
        publisher: 'The Gospel Coalition',
        url: 'https://store.thegospelcoalition.org/product/9780692134665/identity-theft-paperback',
        available: true,
        lastVerifiedAt: VERIFIED,
      },
      fr: {
        title: 'Identité en crise ? Revêtir notre véritable identité en Christ',
        author: 'Melissa Kruger (dir.), collectif',
        publisher: 'Éditions Clé',
        url: 'https://editionscle.com/vie-chretienne/344-identit%C3%A9-en-crise-9782358431620.html',
        available: true,
        lastVerifiedAt: VERIFIED,
      },
    },
  },
  {
    id: 'lawrence-biblical-theology-and-identity',
    type: 'article',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['identity', 'gospel', 'discipleship'],
    perspective: ['evangelical', 'reformed'],
    status: 'needs_review',
    description: {
      en: 'A pastor traces sonship from Adam to Christ: we are loved as God’s adopted children because we are in the beloved Son — and that security is the ground of obedience, not its reward.',
      fr: 'Un pasteur suit le fil de la filiation d’Adam à Christ : nous sommes aimés comme enfants adoptés parce que nous sommes dans le Fils bien-aimé — une sécurité qui fonde l’obéissance au lieu d’en être la récompense.',
    },
    editions: {
      en: {
        title: 'Biblical Theology and Identity',
        author: 'Michael Lawrence',
        publisher: '9Marks',
        url: 'https://www.9marks.org/article/biblical-theology-and-identity/',
        available: true,
        lastVerifiedAt: VERIFIED,
      },
      pt: {
        title: 'Teologia bíblica e identidade: filhos de Deus',
        author: 'Michael Lawrence (trad. Vinícius Silva Pimentel)',
        publisher: 'Fé para Hoje (Ministério Fiel)',
        url: 'https://feparahoje.com.br/teologia-biblica-e-identidade-filhos-de-deus/',
        available: true,
        lastVerifiedAt: VERIFIED,
      },
    },
  },
  {
    id: 'tennison-what-we-believe-about-sanctification',
    type: 'article',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['holiness', 'holy-spirit', 'discipleship'],
    perspective: ['pentecostal'],
    status: 'needs_review',
    description: {
      en: 'A Pentecostal (Assemblies of God) explanation of sanctification as both a position received in Christ and a lifelong growth by the Spirit — explicitly not a teaching of sinless perfection.',
      fr: 'Une présentation pentecôtiste (Assemblées de Dieu) de la sanctification, à la fois position reçue en Christ et croissance de toute une vie par l’Esprit — en refusant explicitement l’idée d’une perfection sans péché.',
    },
    editions: {
      en: {
        title: 'What We Believe About Sanctification',
        author: 'Allen Tennison',
        publisher: 'Influence Magazine (Assemblies of God USA)',
        url: 'https://influencemagazine.com/Practice/What-We-Believe-About-Sanctification',
        available: true,
        lastVerifiedAt: VERIFIED,
      },
    },
  },
  {
    id: 'mbewe-unity',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['church', 'community', 'gospel'],
    perspective: ['reformed', 'evangelical'],
    status: 'needs_review',
    description: {
      en: 'A Zambian pastor on the unity Christ has already won and the Spirit applies — why belonging to one body means striving side by side, not splitting over lesser things.',
      fr: 'Un pasteur zambien sur l’unité que Christ a déjà acquise et que l’Esprit applique — pourquoi appartenir à un seul corps veut dire combattre côte à côte, sans se diviser sur l’accessoire.',
    },
    editions: {
      en: {
        title: 'Unity: Striving Side by Side for the Gospel',
        author: 'Conrad Mbewe',
        publisher: 'Crossway',
        url: 'https://www.crossway.org/books/unity-tpb/',
        available: true,
        lastVerifiedAt: VERIFIED,
      },
    },
  },
  {
    id: 'gaffin-union-with-christ',
    type: 'article',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['identity', 'gospel'],
    perspective: ['reformed'],
    status: 'needs_review',
    description: {
      en: 'A concise theological essay on union with Christ — by the Spirit, through faith — and how it holds together justification, new life and the believer’s hope; for readers who want the doctrine stated carefully.',
      fr: 'Un essai théologique concis sur l’union avec le Christ — par l’Esprit, au moyen de la foi — et sur la manière dont elle relie justification, vie nouvelle et espérance ; pour qui veut la doctrine exposée avec précision.',
    },
    editions: {
      en: {
        title: 'Union with Christ',
        author: 'Richard B. Gaffin Jr.',
        publisher: 'The Gospel Coalition (Concise Theology essays)',
        url: 'https://www.thegospelcoalition.org/essay/union-with-christ/',
        available: true,
        lastVerifiedAt: VERIFIED,
      },
      fr: {
        title: 'L’union avec le Christ',
        author: 'Richard B. Gaffin Jr.',
        publisher: 'Évangile21 (The Gospel Coalition)',
        url: 'https://evangile21.thegospelcoalition.org/essais/lunion-avec-le-christ/',
        available: true,
        lastVerifiedAt: VERIFIED,
      },
      zh: {
        title: '与基督联合',
        author: '小理查德·加芬 (Richard B. Gaffin Jr.)',
        publisher: '福音联盟 (TGC Chinese)',
        url: 'https://www.tgcchinese.org/essay/union-with-christ',
        available: true,
        lastVerifiedAt: VERIFIED,
      },
    },
  },
];
