// Candidates for kingdomCome14, researched 2026-09-29. NONE is approved: every entry is
// needs_review with no sign-off, so the resolver never shows it. See
// docs/resources/candidates/kingdomCome14.md for the verification worksheet.
//
// Tagging rule for this plan: the `christian-living` shelf is shared by seven
// "Growing in Christ" plans, so Lord's Prayer and kingdom material carries the
// precise topics its days use (`lords-prayer`, `kingdom-of-god`, `justice`,
// `end-times`, `forgiveness`, `mission`) and avoids the generic `identity` /
// `character` / `calling` / `work` tags, so it does not flood the other plans.

const VERIFIED = '2026-09-29';
const BP = 'BibleProject';
// A BibleProject video edition. Languages without a dedicated video page link to
// BibleProject's own language hub, where the video was seen listed (title as listed).
const bp = (title, url, publisher = BP) => ({
  title, author: BP, publisher, url, available: true, lastVerifiedAt: VERIFIED,
});

export const KINGDOM_COME14_CANDIDATES = [
  {
    id: 'wright-lord-and-his-prayer',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['lords-prayer', 'kingdom-of-god'],
    perspective: ['anglican'],
    status: 'needs_review',
    description: {
      en: 'Short pastoral reflections that read each clause of the Lord’s Prayer against Jesus’ own announcement of God’s kingdom, then let it shape prayer today.',
      fr: 'De courtes méditations pastorales qui lisent chaque demande du Notre Père à la lumière de l’annonce du Royaume par Jésus, puis la laissent façonner la prière d’aujourd’hui.',
    },
    editions: {
      en: {
        title: 'The Lord and His Prayer',
        author: 'N. T. Wright',
        publisher: 'Eerdmans',
        url: 'https://www.eerdmans.com/9780802871770/the-lord-and-his-prayer/',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
    },
  },
  {
    id: 'keller-prayer',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['prayer', 'lords-prayer'],
    perspective: ['reformed'],
    status: 'needs_review',
    description: {
      en: 'A pastor’s book on prayer as both conversation and encounter with God, drawing on Augustine, Luther and Calvin, with a chapter that works through the Lord’s Prayer petition by petition.',
      fr: 'Un livre de pasteur sur la prière, à la fois conversation et rencontre avec Dieu, nourri d’Augustin, de Luther et de Calvin, avec un chapitre qui parcourt le Notre Père demande après demande.',
    },
    editions: {
      en: {
        title: 'Prayer: Experiencing Awe and Intimacy with God',
        author: 'Timothy Keller',
        publisher: 'Penguin Books',
        url: 'https://www.penguinrandomhouse.com/books/313534/prayer-by-timothy-keller/',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
      fr: {
        title: 'La prière : S’émerveiller dans l’intimité de Dieu',
        author: 'Timothy Keller',
        publisher: 'Éditions Clé',
        url: 'https://editionscle.com/vie-chretienne/237-la-priere-9782358430425.html',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
      de: {
        title: 'Beten: Dem heiligen Gott nahekommen',
        author: 'Timothy Keller',
        publisher: 'Brunnen Verlag',
        url: 'https://brunnen-verlag.de/190943/beten.html',
        available: false,
        lastVerifiedAt: '2026-09-29',
      },
      es: {
        title: 'La oración: Experimentando asombro e intimidad con Dios',
        author: 'Timothy Keller',
        publisher: 'B&H Español',
        url: 'https://www.bhpublishinggroup.com/product/la-oracion-3/la-oracion/',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
      pt: {
        title: 'Oração: experimentando intimidade com Deus',
        author: 'Timothy Keller',
        publisher: 'Vida Nova',
        url: 'https://www.vidanova.com.br/livros/oracao-experimentando-intimidade-com-deus',
        available: false,
        lastVerifiedAt: '2026-09-29',
      },
      ko: {
        title: '팀 켈러의 기도',
        author: '팀 켈러 (Timothy Keller)',
        publisher: '두란노 (Duranno)',
        url: 'https://www.duranno.com/books/view/bookdetail.asp?bcod=5674',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
    },
  },
  {
    id: 'packer-praying-the-lords-prayer',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['lords-prayer', 'prayer'],
    perspective: ['anglican', 'reformed'],
    status: 'needs_review',
    description: {
      en: 'A brief, clear walk through the Lord’s Prayer by a trusted theologian, treating it as a pattern for how children speak with their Father.',
      fr: 'Un bref parcours du Notre Père par un théologien reconnu, qui le présente comme un modèle pour la manière dont des enfants parlent à leur Père.',
    },
    editions: {
      en: {
        title: 'Praying the Lord’s Prayer',
        author: 'J. I. Packer',
        publisher: 'Crossway',
        url: 'https://www.crossway.org/books/praying-the-lords-prayer-tpb/',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
    },
  },
  {
    id: 'greig-how-to-pray',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['prayer', 'lords-prayer'],
    perspective: ['charismatic', 'evangelical'],
    status: 'needs_review',
    description: {
      en: 'An accessible, honest guide to prayer by a founder of 24-7 Prayer, organised around the Lord’s Prayer and written for beginners and weary pray-ers alike.',
      fr: 'Un guide de la prière accessible et honnête, par un fondateur de 24-7 Prayer, construit autour du Notre Père et écrit autant pour les débutants que pour ceux qui se sont lassés de prier.',
    },
    editions: {
      en: {
        title: 'How to Pray: A Simple Guide for Normal People',
        author: 'Pete Greig',
        publisher: 'NavPress',
        url: 'https://www.navigators.org/resource/how-to-pray-pete-greig/',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
    },
  },
  {
    id: '24-7-prayer-the-prayer-course',
    type: 'video',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['lords-prayer', 'prayer', 'intercession'],
    perspective: ['charismatic', 'evangelical'],
    status: 'needs_review',
    description: {
      en: 'A free eight-session video course that journeys through the Lord’s Prayer, with a short film, discussion guide and practical prayer ideas for each session — made for small groups.',
      fr: 'Un parcours vidéo gratuit en huit séances qui traverse le Notre Père, avec pour chaque séance un court film, un guide de discussion et des idées concrètes pour prier — pensé pour les petits groupes.',
    },
    editions: {
      en: {
        title: 'The Prayer Course: An eight week journey through the Lord’s Prayer',
        author: 'Pete Greig',
        publisher: '24-7 Prayer International',
        url: 'https://prayercourse.org/home/',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
      fr: {
        title: 'Le cours sur la prière',
        author: 'Pete Greig',
        publisher: '24-7 Prayer (Suisse romande)',
        url: 'https://courspriere.org/',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
      de: {
        title: 'Gebetskurs: Eine achtwöchige Reise durch das Vaterunser',
        author: 'Pete Greig',
        publisher: '24-7 Prayer',
        url: 'https://gebetskurs.org/',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
      es: {
        title: 'El Curso de Oración',
        author: 'Pete Greig',
        publisher: '24-7 Prayer',
        url: 'https://elcursodeoracion.com/',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
    },
  },
  {
    id: 'bibleproject-lords-prayer',
    type: 'video',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['lords-prayer', 'kingdom-of-god'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A nine-minute animated study of the Lord’s Prayer (Sermon on the Mount, part 7) showing how each line realigns our desires with God’s kingdom. Outside English, French, Spanish and Portuguese, the link opens BibleProject’s language page, where the episode is listed. Free.',
      fr: 'Une étude animée de neuf minutes sur le Notre Père (Sermon sur la montagne, épisode 7) qui montre comment chaque demande réaligne nos désirs sur le Royaume de Dieu. Hors anglais, français, espagnol et portugais, le lien ouvre la page de langue de BibleProject, où figure l’épisode. Gratuit.',
    },
    editions: {
      en: bp('The Lord’s Prayer (Sermon on the Mount, E7)', 'https://bibleproject.com/videos/lords-prayer/'),
      fr: bp('Le Notre Père', 'https://bibleproject.com/fr/videos/le-notre-pere/'),
      es: bp('La oración de Jesús', 'https://bibleproject.com/es/videos/la-oracion-de-jesus/'),
      pt: bp('A oração do Pai Nosso', 'https://bibleproject.com/pt-br/videos/a-oracao-do-pai-nosso/'),
      ko: bp('주기도문 (산상수훈)', 'https://bibleproject.com/ko/'),
      zh: bp('耶稣如何祷告？他如何教导他的跟随者祷告 (登山宝训 7)', 'https://bibleproject.com/zh-hans/'),
      ja: bp('主の祈り　山上の説教　パート⑦', 'https://bibleproject.com/ja/'),
      hi: bp('पहाड़ी उपदेश Sermon on the Mount Ep 7', 'https://bibleproject.com/hi/'),
    },
  },
  {
    id: 'bibleproject-gospel-of-the-kingdom',
    type: 'video',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['kingdom-of-god', 'gospel'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A five-minute animated video on “gospel” as a royal announcement: in Jesus, God’s kingdom has arrived on earth, in ways no one expected. Outside English, Spanish and Portuguese, the link opens BibleProject’s language page, where the video is listed. Free.',
      fr: 'Une vidéo animée de cinq minutes sur l’« Évangile » comme annonce royale : en Jésus, le règne de Dieu est arrivé sur la terre, d’une manière que personne n’attendait. Hors anglais, espagnol et portugais, le lien ouvre la page de langue de BibleProject, où figure la vidéo. Pas de version française vérifiée. Gratuit.',
    },
    editions: {
      en: bp('Gospel of the Kingdom', 'https://bibleproject.com/videos/gospel-kingdom/'),
      es: bp('Evangelio del Reino', 'https://bibleproject.com/es/videos/evangelio-del-reino/'),
      pt: bp('Evangelho do reino', 'https://bibleproject.com/pt-br/videos/evangelho-do-reino/'),
      ru: bp('Евангелие Царства', 'https://bibleproject.com/ru/'),
      zh: bp('天国的福音 - Gospel of the Kingdom', 'https://bibleproject.com/zh-hans/'),
      ja: bp('神の国の福音 Gospel of the Kingdom', 'https://bibleproject.com/ja/'),
      ko: bp('하나님 나라의 복음', 'https://bibleproject.com/ko/'),
      ar: bp('إنجيل الملكوت', 'https://bibleproject.com/arz/', 'BibleProject (Egyptian Arabic)'),
      fa: bp('انجیل پادشاهی', 'https://bibleproject.com/fa/'),
      hi: bp('परमेश्वर के राज्य का सुसमाचार Gospel of the Kingdom', 'https://bibleproject.com/hi/'),
      id: bp('Injil Kerajaan Allah', 'https://bibleproject.com/id/'),
      sw: bp('Injili ya Ufalme', 'https://bibleproject.com/sw/'),
      tl: bp('Magandang Balita ng Kaharian', 'https://bibleproject.com/tl/'),
      am: bp('የመንግሥቱ ወንጌል Gospel of the Kingdom', 'https://bibleproject.com/am/'),
    },
  },
  {
    id: 'bibleproject-heaven-and-earth',
    type: 'video',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['kingdom-of-god', 'end-times'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A seven-minute animated theme video on why the Bible sees heaven and earth as meant to overlap, and how Jesus reunites them — background for “on earth as in heaven” and the new creation. Outside English, Spanish and Portuguese, the link opens BibleProject’s language page. Free.',
      fr: 'Une vidéo thématique animée de sept minutes : pourquoi la Bible voit le ciel et la terre destinés à se rejoindre, et comment Jésus les réunit — un arrière-plan pour « sur la terre comme au ciel » et la nouvelle création. Hors anglais, espagnol et portugais, le lien ouvre la page de langue de BibleProject. Pas de version française vérifiée. Gratuit.',
    },
    editions: {
      en: bp('Heaven & Earth', 'https://bibleproject.com/videos/heaven-and-earth/'),
      es: bp('Cielo y Tierra', 'https://bibleproject.com/es/videos/cielo-y-tierra/'),
      pt: bp('Céu e terra', 'https://bibleproject.com/pt-br/videos/ceu-e-terra/'),
      ru: bp('Небеса & Земля', 'https://bibleproject.com/ru/'),
      zh: bp('天与地 - Heaven & Earth', 'https://bibleproject.com/zh-hans/'),
      ja: bp('天と地 Heaven & Earth', 'https://bibleproject.com/ja/'),
      ko: bp('하늘과 땅', 'https://bibleproject.com/ko/'),
      ar: bp('السموات والأرض', 'https://bibleproject.com/arz/', 'BibleProject (Egyptian Arabic)'),
      fa: bp('Heaven and Earth بهشت و زمین', 'https://bibleproject.com/fa/'),
      hi: bp('स्वर्ग और पृथ्वी Heaven and Earth', 'https://bibleproject.com/hi/'),
      id: bp('Surga dan Bumi', 'https://bibleproject.com/id/'),
      sw: bp('Mbingu na Dunia', 'https://bibleproject.com/sw/'),
      tl: bp('Langit at Lupa', 'https://bibleproject.com/tl/'),
      am: bp('ሰማይ እና ምድር Heaven & Earth', 'https://bibleproject.com/am/'),
    },
  },
  {
    id: 'bibleproject-justice',
    type: 'video',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['justice'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A six-minute animated theme video tracing biblical justice — God’s call to defend the vulnerable — through the story that leads to Jesus. Outside English, French, Spanish and Portuguese, the link opens BibleProject’s language page. Free.',
      fr: 'Une vidéo thématique animée de six minutes qui suit la justice biblique — l’appel de Dieu à défendre les plus vulnérables — à travers le récit qui mène à Jésus. Hors anglais, français, espagnol et portugais, le lien ouvre la page de langue de BibleProject. Gratuit.',
    },
    editions: {
      en: bp('Justice', 'https://bibleproject.com/videos/justice/'),
      fr: bp('Justice', 'https://bibleproject.com/fr/videos/justice/'),
      es: bp('Justicia', 'https://bibleproject.com/es/videos/justicia/'),
      pt: bp('Justiça', 'https://bibleproject.com/pt-br/videos/justica/'),
      ru: bp('Справедливость', 'https://bibleproject.com/ru/'),
      zh: bp('公义 - Justice', 'https://bibleproject.com/zh-hans/'),
      ja: bp('正義と公正　Justice', 'https://bibleproject.com/ja/'),
      ko: bp('정의', 'https://bibleproject.com/ko/'),
      hi: bp('न्याय Justice', 'https://bibleproject.com/hi/'),
      id: bp('Keadilan', 'https://bibleproject.com/id/'),
      sw: bp('Haki', 'https://bibleproject.com/sw/'),
      am: bp('ፍትሕ Justice', 'https://bibleproject.com/am/'),
    },
  },
  {
    id: 'bibleproject-sermon-on-the-mount-podcast',
    type: 'podcast',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['lords-prayer', 'kingdom-of-god', 'forgiveness'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A long podcast series on the Sermon on the Mount, with a five-part run on the Lord’s Prayer (the Father’s name, daily bread, what forgiveness is and isn’t, temptation) and episodes on money, anxiety and seeking the kingdom. For readers who want depth. Free.',
      fr: 'Une longue série de podcasts sur le Sermon sur la montagne, dont cinq épisodes sur le Notre Père (le nom du Père, le pain quotidien, ce qu’est — et n’est pas — le pardon, la tentation) et d’autres sur l’argent, l’inquiétude et la recherche du Royaume. Pour qui veut approfondir. En anglais. Gratuit.',
    },
    editions: {
      en: {
        title: 'Sermon on the Mount (podcast series)',
        author: 'Tim Mackie and Jon Collins',
        publisher: BP,
        url: 'https://bibleproject.com/podcasts/series/sermon-on-the-mount/',
        available: true,
        lastVerifiedAt: VERIFIED,
      },
    },
  },
  {
    id: 'coalicion-padre-nuestro-curso',
    type: 'study',
    originalLanguage: 'es',
    domains: ['christian-living'],
    topics: ['lords-prayer', 'kingdom-of-god', 'forgiveness'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A free seven-session Spanish course that walks through the Lord’s Prayer petition by petition — the Father’s name, “on earth as in heaven”, daily bread, forgiving as we are forgiven, deliverance from evil — with Scripture, short videos and reflection questions. Spanish only.',
      fr: 'Un cours gratuit en espagnol, en sept séances, qui parcourt le Notre Père demande après demande — le nom du Père, « sur la terre comme au ciel », le pain quotidien, le pardon reçu et donné, la délivrance du mal — avec des textes bibliques, de courtes vidéos et des questions de réflexion. En espagnol uniquement.',
      es: 'Un curso gratuito de siete sesiones que recorre el Padre nuestro petición por petición, con lecturas bíblicas, videos breves y preguntas de reflexión.',
    },
    editions: {
      es: {
        title: '¿Cómo podemos orar el “Padre nuestro”? (El “Padre nuestro”: orando con Jesús)',
        author: 'Coalición por el Evangelio (videos de Proyecto Biblia / BibleProject)',
        publisher: 'Coalición por el Evangelio',
        url: 'https://www.coalicionporelevangelio.org/curso/padre-nuestro-oracion-jesus/',
        available: true,
        lastVerifiedAt: VERIFIED,
      },
    },
  },
  {
    id: 'ladd-gospel-of-the-kingdom',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['kingdom-of-god', 'end-times'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A classic, readable study of the kingdom of God in Jesus’ parables and the Sermon on the Mount, and the best-known account of the kingdom as “already” present and “not yet” complete.',
      fr: 'Une étude classique et accessible du Royaume de Dieu dans les paraboles de Jésus et le Sermon sur la montagne, et la présentation la plus connue du Royaume « déjà » présent et « pas encore » accompli.',
    },
    editions: {
      en: {
        title: 'The Gospel of the Kingdom: Scriptural Studies in the Kingdom of God',
        author: 'George Eldon Ladd',
        publisher: 'Eerdmans',
        url: 'https://www.eerdmans.com/9780802812803/the-gospel-of-the-kingdom/',
        available: true,
        lastVerifiedAt: VERIFIED,
      },
    },
  },
  {
    id: 'mcknight-kingdom-conspiracy',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['kingdom-of-god', 'mission'],
    perspective: ['anglican', 'evangelical'],
    status: 'needs_review',
    description: {
      en: 'A New Testament scholar argues that “kingdom” is often misused — for social activism on the left or cultural power on the right — and roots it again in King Jesus and the life of the local church.',
      fr: 'Un bibliste montre que le mot « Royaume » est souvent détourné — vers l’activisme social ou vers le pouvoir culturel — et le réenracine dans le Roi Jésus et la vie de l’Église locale.',
    },
    editions: {
      en: {
        title: 'Kingdom Conspiracy: Returning to the Radical Mission of the Local Church',
        author: 'Scot McKnight',
        publisher: 'Brazos Press (Baker Publishing Group)',
        url: 'https://bakerpublishinggroup.com/books/kingdom-conspiracy/351124',
        available: false,
        lastVerifiedAt: VERIFIED,
      },
    },
  },
  {
    id: 'stott-message-of-the-sermon-on-the-mount',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['kingdom-of-god', 'lords-prayer', 'discipleship'],
    perspective: ['anglican', 'evangelical'],
    status: 'needs_review',
    description: {
      en: 'A classic, verse-by-verse exposition of Matthew 5–7 that reads the Sermon — the Lord’s Prayer at its centre — as the “counter-culture” of kingdom people, with a study guide for groups.',
      fr: 'Un commentaire classique, verset par verset, de Matthieu 5–7 qui lit le Sermon — avec le Notre Père en son centre — comme la « contre-culture » du peuple du Royaume, avec un guide d’étude pour les groupes.',
    },
    editions: {
      en: {
        title: 'The Message of the Sermon on the Mount (The Bible Speaks Today)',
        author: 'John Stott',
        publisher: 'Inter-Varsity Press (IVP UK)',
        url: 'https://ivpbooks.com/the-message-of-the-sermon-on-the-mount',
        available: true,
        lastVerifiedAt: VERIFIED,
      },
    },
  },
  {
    id: 'evangile21-seigneur-apprends-nous-a-prier',
    type: 'article',
    originalLanguage: 'fr',
    domains: ['christian-living'],
    topics: ['lords-prayer', 'prayer'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A French pastor’s fifteen-minute reading on the Lord’s Prayer as a way to pray Scripture rather than repeat a formula — God’s name, kingdom and will before our own needs. French only.',
      fr: 'Un texte d’un quart d’heure, par un pasteur français, sur le Notre Père comme manière de prier l’Écriture plutôt que de répéter une formule — le nom, le règne et la volonté de Dieu avant nos propres besoins.',
    },
    editions: {
      fr: {
        title: 'Seigneur, apprends-nous à prier !',
        author: 'Jean-Jacques Riou',
        publisher: 'Évangile 21 (The Gospel Coalition)',
        url: 'https://evangile21.thegospelcoalition.org/article/seigneur-apprend-nous-a-prier/',
        available: true,
        lastVerifiedAt: VERIFIED,
      },
    },
  },
  {
    id: 'leparcours-le-notre-pere',
    type: 'study',
    originalLanguage: 'fr',
    domains: ['christian-living'],
    topics: ['lords-prayer', 'kingdom-of-god', 'forgiveness'],
    perspective: ['pentecostal'],
    status: 'needs_review',
    description: {
      en: 'A free ten-lesson French study that takes the Lord’s Prayer one line at a time — Father, name, kingdom, will, daily bread, forgiveness, temptation, evil — from an Assemblies of God online ministry. French only.',
      fr: 'Une étude gratuite en dix leçons qui prend le Notre Père ligne après ligne — le Père, le nom, le règne, la volonté, le pain quotidien, le pardon, la tentation, le mal — proposée par un ministère en ligne des Assemblées de Dieu.',
    },
    editions: {
      fr: {
        title: 'Le Notre Père (série de 10 leçons)',
        author: 'LeParcours.net',
        publisher: 'LeParcours.net (Assemblées de Dieu)',
        url: 'https://leparcours.net/series/le-notre-pere/',
        available: true,
        lastVerifiedAt: VERIFIED,
      },
    },
  },
  {
    id: 'erf-dein-reich-komme',
    type: 'teaching',
    originalLanguage: 'de',
    domains: ['christian-living'],
    topics: ['kingdom-of-god', 'lords-prayer'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A short German audio devotional (with transcript) on “Your kingdom come”: God’s reign is present now and still to come, and it advances through prayer, not force. German only.',
      fr: 'Une courte méditation audio en allemand (avec transcription) sur « Que ton règne vienne » : le règne de Dieu est déjà là et encore à venir, et il avance par la prière, non par la force. En allemand uniquement.',
      de: 'Eine kurze Audio-Andacht (mit Text) zu „Dein Reich komme“: Gottes Herrschaft ist schon da und kommt noch — und sie wächst durch Gebet, nicht durch Gewalt.',
    },
    editions: {
      de: {
        title: 'Dein Reich komme (Wort zum Tag)',
        author: 'Matthias Dreßler',
        publisher: 'ERF Medien',
        url: 'https://www.erf.de/erf-plus/audiothek/wort-zum-tag/dein-reich-komme/73-4728',
        available: true,
        lastVerifiedAt: VERIFIED,
      },
    },
  },
  {
    id: 'evangelium21-vergebung-im-vaterunser',
    type: 'article',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['forgiveness', 'lords-prayer'],
    perspective: ['reformed', 'evangelical'],
    status: 'needs_review',
    description: {
      en: 'A German article on the forgiveness petition: we need God’s forgiveness as daily as bread, and those who receive it learn to extend it. German translation of an English original.',
      fr: 'Un article en allemand sur la demande de pardon : nous avons besoin du pardon de Dieu aussi quotidiennement que du pain, et ceux qui le reçoivent apprennent à le donner. Traduction allemande d’un original anglais.',
      de: 'Ein Artikel zur Vergebungsbitte: Wir brauchen Gottes Vergebung so täglich wie Brot — und wer sie empfängt, lernt, sie weiterzugeben.',
    },
    editions: {
      de: {
        title: 'Vergebung im Vaterunser',
        author: 'Marshall Segal',
        publisher: 'Evangelium21',
        url: 'https://www.evangelium21.net/media/4909/vergebung-im-vaterunser',
        available: true,
        lastVerifiedAt: VERIFIED,
      },
    },
  },
  {
    id: 'sproul-prayer-of-the-lord',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['lords-prayer', 'prayer'],
    perspective: ['reformed'],
    status: 'needs_review',
    description: {
      en: 'A short book that gives one chapter to each line of the Lord’s Prayer, keeping two facts in view — who God is and who we are — with an emphasis on His holiness and our daily dependence.',
      fr: 'Un petit livre qui consacre un chapitre à chaque ligne du Notre Père, en gardant deux réalités sous les yeux — qui est Dieu et qui nous sommes — avec un accent sur sa sainteté et notre dépendance quotidienne.',
    },
    editions: {
      en: {
        title: 'The Prayer of the Lord',
        author: 'R.C. Sproul',
        publisher: 'Ligonier Ministries',
        url: 'https://store.ligonier.org/the-prayer-of-the-lord-paperback',
        available: true,
        lastVerifiedAt: VERIFIED,
      },
      es: {
        title: 'The Prayer of the Lord (Spanish edition)',
        author: 'R.C. Sproul',
        publisher: 'Baptist Spanish Publishing House (Casa Bautista), via Ligonier Ministries',
        url: 'https://store.ligonier.org/the-prayer-of-the-lord-paperback-spanish',
        available: true,
        lastVerifiedAt: VERIFIED,
      },
      ar: {
        title: 'The Prayer of the Lord (Arabic edition)',
        author: 'R.C. Sproul',
        publisher: 'Al Haq Yoharerakom (TSF Egypt), via Ligonier Ministries',
        url: 'https://store.ligonier.org/the-prayer-of-the-lord-paperback-arabic',
        available: true,
        lastVerifiedAt: VERIFIED,
      },
    },
  },
  {
    id: 'oshima-asayu-ni-inoru-shu-no-inori',
    type: 'prayerGuide',
    originalLanguage: 'ja',
    domains: ['christian-living'],
    topics: ['lords-prayer', 'prayer'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A Japanese 30-day retreat through the Lord’s Prayer, one phrase at a time, to be read morning and evening — by a pastor and former student-ministry leader. Japanese only.',
      fr: 'Une retraite de trente jours en japonais à travers le Notre Père, une phrase après l’autre, à lire matin et soir — par un pasteur, ancien responsable d’un mouvement d’étudiants chrétiens. En japonais uniquement.',
      ja: 'イエスが教えられた「主の祈り」を一節ずつ、朝と夕に30日間かけて読み味わう小さな本。',
    },
    editions: {
      ja: {
        title: '朝夕に祈る 主の祈り　30日間のリトリート',
        author: '大嶋重徳',
        publisher: 'いのちのことば社',
        url: 'https://www.gospelshop.jp/shopdetail/000000000560/',
        available: true,
        lastVerifiedAt: VERIFIED,
      },
    },
  },
];
