// Candidates for manOfGod21, researched 2026-09-28. NONE is approved: every entry is
// needs_review with no sign-off, so the resolver never shows it. See
// docs/resources/candidates/manOfGod21.md for the verification worksheet.
//
// Tagging rule for this plan: the `christian-living` shelf is shared by seven
// "Growing in Christ" plans (including womanOfGod21 and identityInChrist), so
// men's material carries `manhood` plus precise topics and avoids the generic
// `identity` / `character` / `calling` tags unless they are central.
export const MAN_OF_GOD21_CANDIDATES = [
  {
    id: 'hughes-disciplines-of-a-godly-man',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['manhood'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A pastor’s practical book for men on the everyday disciplines of godliness — purity, friendship, prayer, integrity, work, perseverance and leadership.',
      fr: 'Un livre pratique d’un pasteur pour les hommes sur les disciplines quotidiennes de la piété : pureté, amitié, prière, intégrité, travail, persévérance et leadership.',
    },
    editions: {
      en: {
        title: 'Disciplines of a Godly Man (Updated Edition)',
        author: 'R. Kent Hughes',
        publisher: 'Crossway',
        url: 'https://www.crossway.org/books/disciplines-of-a-godly-man-tpb-2/',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'scazzero-emotionally-healthy-spirituality',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['lament', 'spiritual-rhythms'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A pastor’s account of why spiritual maturity needs emotional honesty — naming anger, sadness and fear before God, and grieving losses instead of hiding them.',
      fr: 'Le témoignage d’un pasteur sur la nécessité de l’honnêteté émotionnelle pour grandir dans la foi : nommer la colère, la tristesse et la peur devant Dieu, et porter ses pertes au lieu de les cacher.',
    },
    editions: {
      en: {
        title: 'Emotionally Healthy Spirituality (Updated Edition)',
        author: 'Peter Scazzero',
        publisher: 'Emotionally Healthy Discipleship (Zondervan)',
        url: 'https://www.emotionallyhealthy.org/product/emotionally-healthy-spirituality-update-revised-edition/',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      es: {
        title: 'Espiritualidad emocionalmente sana (edición actualizada, libro electrónico)',
        author: 'Peter Scazzero',
        publisher: 'Emotionally Healthy Discipleship',
        url: 'https://www.emotionallyhealthy.org/product/espiritualidad-es-electronico-edicion-actualizada/',
        available: false,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'chester-closing-the-window',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['pornography', 'purity'],
    perspective: ['evangelical'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A grace-centred, practical book for Christians who want to stop using pornography: God offers more than porn does, and change happens in community, not by willpower alone.',
      fr: 'Un livre pratique, centré sur la grâce, pour les chrétiens qui veulent arrêter la pornographie : Dieu offre plus qu’elle, et le changement se vit en communauté, pas par la seule volonté.',
    },
    editions: {
      en: {
        title: 'Closing the Window: Steps to Living Porn Free',
        author: 'Tim Chester',
        publisher: 'IVP (InterVarsity Press)',
        url: 'https://www.ivpress.com/closing-the-window',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'covenant-eyes-life-change-workbook',
    type: 'study',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['pornography'],
    perspective: ['evangelical'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A twelve-week Bible study for quitting pornography, alone or in a group, that deals with shame, lies, confession and forgiveness and points back to Christ.',
      fr: 'Une étude biblique de douze semaines pour sortir de la pornographie, seul ou en groupe, qui aborde la honte, les mensonges, la confession et le pardon en ramenant au Christ.',
    },
    editions: {
      en: {
        title: 'Life Change: A Biblical Journey to Freedom (workbook)',
        author: 'James Reeves',
        publisher: 'Covenant Eyes',
        url: 'https://www.covenanteyes.com/resources/life-change-workbook/',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'piper-husbands-who-love-like-christ',
    type: 'teaching',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['marriage-roles', 'marriage'],
    lifeStages: ['married'],
    perspective: ['reformed'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A complementarian sermon on Ephesians 5:21-33 that reads “head” as a husband’s Christlike servant leadership, insists it is never a right to command or control, and answers the mutual-submission reading.',
      fr: 'Une prédication complémentarienne sur Éphésiens 5.21-33 qui comprend « chef » comme le leadership serviteur du mari à l’image du Christ, affirme que ce n’est jamais un droit de commander ou de contrôler, et répond à la lecture de la soumission mutuelle.',
    },
    editions: {
      en: {
        title: 'Husbands Who Love Like Christ and the Wives Who Submit to Them',
        author: 'John Piper',
        publisher: 'Desiring God',
        url: 'https://www.desiringgod.org/messages/husbands-who-love-like-christ-and-the-wives-who-submit-to-them',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'cbe-pershey-ephesians-5',
    type: 'article',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['marriage-roles', 'marriage'],
    lifeStages: ['married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'An egalitarian reading of Ephesians 5:21-33 that frames the passage by verse 21’s mutual submission and reads a husband’s calling as self-giving, Christlike care rather than rule.',
      fr: 'Une lecture égalitarienne d’Éphésiens 5.21-33 qui éclaire le passage par la soumission mutuelle du verset 21 et comprend l’appel du mari comme un soin donné, à l’image du Christ, plutôt qu’une autorité.',
    },
    editions: {
      en: {
        title: 'Ephesians 5',
        author: 'Katherine Willis Pershey',
        publisher: 'CBE International',
        url: 'https://www.cbeinternational.org/resource/ephesians-5/',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'hunter-why-is-friendship-hard-for-men',
    type: 'article',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['manhood'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A short article on why close friendship is hard for many men, with five simple ways to build it — including letting go of the cultural fear of showing affection, as David and Jonathan did.',
      fr: 'Un court article sur les raisons pour lesquelles l’amitié profonde est difficile pour beaucoup d’hommes, avec cinq pistes simples pour la construire, dont celle de dépasser la gêne culturelle à montrer de l’affection, comme David et Jonathan.',
    },
    editions: {
      en: {
        title: 'Why Is Friendship Hard for Men? Five Ways to Build Stronger Relationships',
        author: 'Drew Hunter',
        publisher: 'Desiring God',
        url: 'https://www.desiringgod.org/articles/why-is-friendship-hard-for-men',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'hunter-made-for-friendship',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['friendship', 'community'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A warm, biblical book on why we all need true friends, what friendship in Christ looks like and how to cultivate it — written for anyone, married or single.',
      fr: 'Un livre chaleureux et biblique sur notre besoin d’amis véritables, sur ce qu’est l’amitié en Christ et sur la manière de la cultiver — pour tous, mariés ou célibataires.',
    },
    editions: {
      en: {
        title: 'Made for Friendship: The Relationship That Halves Our Sorrows and Doubles Our Joys',
        author: 'Drew Hunter',
        publisher: 'Crossway',
        url: 'https://www.crossway.org/books/made-for-friendship-tpb/',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'pyle-man-enough',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['manhood'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A pastor’s book for men who feel they never measure up to a macho ideal: it roots manhood in the gospel and in Jesus, and shows that Scripture’s men were not all one type.',
      fr: 'Le livre d’un pasteur pour les hommes qui ont l’impression de ne jamais être à la hauteur d’un idéal viril : il enracine la masculinité dans l’Évangile et en Jésus, et montre que les hommes de la Bible n’étaient pas tous du même moule.',
    },
    editions: {
      en: {
        title: 'Man Enough: How Jesus Redefines Manhood',
        author: 'Nate Pyle',
        publisher: 'Zondervan (HarperCollins Christian Publishing, FaithGateway store)',
        url: 'https://faithgateway.com/products/man-enough-how-jesus-redefines-manhood',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'bloom-strong-legacy-of-a-weak-father',
    type: 'article',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['manhood', 'parenting'],
    perspective: ['evangelical'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A son’s tribute to a father whose mental illness took away much of what he had been, and whose perseverance, honesty and faithfulness in weakness became his strongest legacy (2 Corinthians 12:9).',
      fr: 'L’hommage d’un fils à un père que la maladie psychique a privé de beaucoup de ce qu’il était, et dont la persévérance, l’honnêteté et la fidélité dans la faiblesse sont devenues le plus bel héritage (2 Corinthiens 12.9).',
    },
    editions: {
      en: {
        title: 'The Strong Legacy of a Weak Father',
        author: 'Jon Bloom',
        publisher: 'Desiring God',
        url: 'https://www.desiringgod.org/articles/the-strong-legacy-of-a-weak-father',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'packer-finishing-our-course-with-joy',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['discipleship', 'suffering'],
    perspective: ['anglican', 'reformed'],
    status: 'needs_review',
    description: {
      en: 'A short book, written by an elderly theologian, on growing old as a Christian: keep running the race to the end, with zeal and hope rather than retreat.',
      fr: 'Un court livre d’un théologien âgé sur la manière de vieillir en chrétien : courir la course jusqu’au bout, avec zèle et espérance plutôt qu’en se retirant.',
    },
    editions: {
      en: {
        title: 'Finishing Our Course with Joy: Guidance from God for Engaging with Our Aging',
        author: 'J. I. Packer',
        publisher: 'Crossway',
        url: 'https://www.crossway.org/books/finishing-our-course-with-joy-tpb/',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'erf-raus-aus-der-porno-falle',
    type: 'study',
    originalLanguage: 'de',
    domains: ['christian-living'],
    topics: ['pornography'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A free German online workshop in fifteen units for adults who want to get free of pornography, combining psychology with a Christian view and offering optional support from trained course companions.',
      fr: 'Un atelier en ligne gratuit, en allemand, en quinze étapes, pour les adultes qui veulent se libérer de la pornographie ; il associe psychologie et regard chrétien et propose, si on le souhaite, l’accompagnement de personnes formées.',
      de: 'Ein kostenloser Online-Workshop in 15 Einheiten für Erwachsene, die von Pornografie frei werden wollen – mit psychologischem Wissen, christlicher Sicht und auf Wunsch begleitet von geschulten Kursbegleitern.',
    },
    editions: {
      de: {
        title: 'Raus aus der Porno-Falle (kostenloser Online-Workshop)',
        author: 'ERF und Weißes Kreuz',
        publisher: 'ERF – Der Sinnsender / Weißes Kreuz e.V.',
        url: 'https://www.erf.de/entdecken/erf-workshops/raus-aus-der-porno-falle/18000-59',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'burgarth-echte-maenner-singen-nicht',
    type: 'article',
    originalLanguage: 'de',
    domains: ['christian-living'],
    topics: ['manhood'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A short German article on the cliché that “real men don’t sing”: David wrote and sang his faith openly, and worship is about pleasing God, not how manly we look.',
      fr: 'Un court article allemand sur le cliché selon lequel « les vrais hommes ne chantent pas » : David chantait et écrivait sa foi ouvertement, et l’adoration cherche à plaire à Dieu, non à paraître viril.',
      de: 'Ein kurzer Artikel über das Klischee „Echte Männer singen nicht“: David hat seinen Glauben offen besungen, und Anbetung will Gott gefallen – nicht männlich wirken.',
    },
    editions: {
      de: {
        title: 'Verzerrtes Männerbild – Echte Männer singen nicht … Wirklich?',
        author: 'Hauke Burgarth',
        publisher: 'Jesus.ch (Livenet)',
        url: 'https://www.jesus.ch/articles/thema/echte-maenner-singen-nicht-wirklich',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'lambert-finally-free',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['pornography'],
    perspective: ['reformed'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A biblical counsellor’s eight grace-based strategies for fighting pornography — sorrow, accountability, confession and humility rooted in what Christ has done, not in shame.',
      fr: 'Huit stratégies fondées sur la grâce, par un conseiller biblique, pour combattre la pornographie : tristesse selon Dieu, redevabilité, confession et humilité enracinées dans l’œuvre du Christ, non dans la honte.',
    },
    editions: {
      en: {
        title: 'Finally Free: Fighting for Purity with the Power of Grace',
        author: 'Heath Lambert',
        publisher: 'Zondervan (HarperCollins Christian Publishing, FaithGateway store)',
        url: 'https://faithgateway.com/products/finally-free-fighting-for-purity-with-the-power-of-grace',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      fr: {
        title: 'Être libre : c’est possible ! (nouvelle édition)',
        author: 'Heath Lambert',
        publisher: 'BLF Éditions',
        url: 'https://blfstore.com/products/etre-libre-c-est-possible-nouvelle-edition',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'orange-etre-un-homme-selon-dieu',
    type: 'article',
    originalLanguage: 'fr',
    domains: ['christian-living'],
    topics: ['manhood'],
    perspective: ['evangelical'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A French article from a Brussels Bible institute: the model for a man is not domination or wealth but the crucified Christ who came to serve, lived out through prayer, godliness and Scripture — written from a complementarian view of roles.',
      fr: 'Un article de l’Institut biblique de Bruxelles : le modèle de l’homme n’est ni la domination ni l’argent, mais le Christ crucifié venu pour servir, vécu dans la prière, la piété et la Parole — dans une perspective complémentarienne des rôles.',
    },
    editions: {
      fr: {
        title: 'Être un homme selon Dieu',
        author: 'Stephen Orange',
        publisher: 'Institut Biblique de Bruxelles',
        url: 'https://www.institutbiblique.be/articles/etre-un-homme-selon-dieu',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'servir-ensemble-masculinite-de-jesus',
    type: 'article',
    originalLanguage: 'fr',
    domains: ['christian-living'],
    topics: ['manhood'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A French egalitarian article questioning the idea that Jesus models a “pure masculinity” that qualifies men alone to lead: courage and leadership in Scripture belong to women and men, and Jesus saves as the true human.',
      fr: 'Un article égalitarien qui interroge l’idée d’une « masculinité pure » de Jésus réservant le leadership aux hommes : dans l’Écriture, le courage et la conduite appartiennent aux femmes comme aux hommes, et Jésus sauve en tant que vrai homme, pleinement humain.',
    },
    editions: {
      fr: {
        title: 'La masculinité de Jésus #bingodesclichés',
        author: 'Servir Ensemble',
        publisher: 'Servir Ensemble',
        url: 'https://servirensemble.com/2022/06/03/la-masculinite-de-jesus-bingodescliches/',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'atkinson-amistad-masculina',
    type: 'article',
    originalLanguage: 'es',
    domains: ['christian-living'],
    topics: ['manhood'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A Spanish article urging men not to let “macho” stereotypes keep them from deep friendship, drawing on David and Jonathan and David and Hushai.',
      fr: 'Un article espagnol qui invite les hommes à ne pas laisser les clichés « machos » les priver d’amitiés profondes, à partir de David et Jonathan, et de David et Houshaï.',
      es: 'Un artículo que anima a los hombres a no dejar que los estereotipos de «machos» les impidan vivir amistades profundas, a partir de David y Jonatán, y de David y Husai.',
    },
    editions: {
      es: {
        title: 'La amistad masculina en un mundo de machos',
        author: 'Ian Atkinson',
        publisher: 'Coalición por el Evangelio',
        url: 'https://www.coalicionporelevangelio.org/articulo/amistad-masculina/',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'mccormick-se-un-hombre-como-jesus',
    type: 'article',
    originalLanguage: 'es',
    domains: ['christian-living'],
    topics: ['manhood'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A Spanish article on being a man like Jesus in the local church: caring for and protecting the vulnerable, with gentleness and emotions that are handled, not suppressed.',
      fr: 'Un article espagnol sur le fait d’être un homme à l’image de Jésus dans l’Église locale : prendre soin des plus vulnérables et les protéger, avec douceur et des émotions assumées plutôt que réprimées.',
      es: 'Un artículo sobre ser un hombre como Jesús en la iglesia local: cuidar y proteger a los vulnerables, con mansedumbre y con emociones bien encauzadas, no reprimidas.',
    },
    editions: {
      es: {
        title: 'Sé un hombre como Jesús: Cuida a los demás en tu iglesia',
        author: 'David McCormick',
        publisher: 'Coalición por el Evangelio',
        url: 'https://www.coalicionporelevangelio.org/articulo/masculinidad-biblica-iglesia/',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'segal-more-than-sexual-purity',
    type: 'article',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['manhood'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'An article arguing that Christian manhood is far more than avoiding lust: five ambitions for men — words that bless, a life not wasted, strength spent serving others, a living faith, and holy self-control.',
      fr: 'Un article qui montre que la vie d’un homme chrétien est bien plus que fuir la convoitise : cinq ambitions — des paroles qui bénissent, une vie qui ne se gaspille pas, une force mise au service des autres, une foi vivante et une maîtrise de soi sainte.',
      pt: 'Um artigo que mostra que ser homem cristão é muito mais do que evitar a impureza: cinco ambições — palavras que abençoam, uma vida bem investida, força gasta servindo aos outros, uma fé viva e domínio próprio em santidade.',
    },
    editions: {
      en: {
        title: 'More Than Sexual Purity: Five Ambitions for Christian Men',
        author: 'Marshall Segal',
        publisher: 'Desiring God',
        url: 'https://www.desiringgod.org/articles/more-than-sexual-purity',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
      pt: {
        title: 'Mais do que pureza sexual: cinco ambições para o homem cristão',
        author: 'Marshall Segal (trad. Hugo J. Ribeiro)',
        publisher: 'Ministério Fiel (Fé para Hoje)',
        url: 'https://feparahoje.com.br/mais-do-que-pureza-sexual-cinco-ambicoes-para-o-homem-cristao/',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
  {
    id: 'fiel-machismo-vs-masculinidade-biblica',
    type: 'teaching',
    originalLanguage: 'pt',
    domains: ['christian-living'],
    topics: ['manhood'],
    perspective: ['reformed'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A Brazilian video course in eight lessons contrasting machismo with biblical manhood — created, corrupted by the Fall, passive, fragile and redeemed — and applying it at home, in church and in society, from a Reformed view of roles.',
      fr: 'Un cours vidéo brésilien en huit leçons qui oppose le machisme à la masculinité biblique — créée, corrompue par la chute, démissionnaire, fragile, rachetée — et l’applique au foyer, à l’Église et dans la société, dans une perspective réformée des rôles.',
      pt: 'Um curso em vídeo, em oito aulas, que contrasta o machismo com a masculinidade bíblica — criada, corrompida, omissa, frágil e resgatada — e a aplica no lar, na igreja e na sociedade, a partir de uma visão reformada dos papéis.',
    },
    editions: {
      pt: {
        title: 'Machismo vs. Masculinidade Bíblica (curso)',
        author: 'Gilson Santos, Rubner Durais e Maurício Fonseca',
        publisher: 'Ministério Fiel (Fiel Digital)',
        url: 'https://ministeriofiel.com.br/cursos/machismo-vs-masculinidade-biblica-gilson-santos-rubner-durais-e-mauricio-fonseca',
        available: true,
        lastVerifiedAt: '2026-09-28',
      },
    },
  },
];
