// Candidates for prodigal30, researched 2026-09-28. NONE is approved: every entry is
// needs_review with no sign-off, so the resolver never shows it. See
// docs/resources/candidates/prodigal30.md for the verification worksheet.
export const PRODIGAL30_CANDIDATES = [
  {
    id: 'graham-prodigals-and-those-who-love-them',
    type: 'book',
    originalLanguage: 'en',
    domains: ['intercession'],
    topics: ['prodigals', 'grief', 'trust', 'prayer'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'Readings, poems and prayers gathered by a mother who waited for two wandering children; comfort for the one praying rather than a method for winning someone back.',
      fr: 'Lectures, poèmes et prières réunis par une mère qui a attendu deux enfants éloignés de la foi ; un réconfort pour celui qui prie plutôt qu’une méthode pour faire revenir quelqu’un.',
    },
    editions: {
      en: { title: 'Prodigals and Those Who Love Them', author: 'Ruth Bell Graham', publisher: 'Baker Books (Baker Publishing Group)', url: 'https://bakerpublishinggroup.com/products/9780801071553_prodigals-and-those-who-love-them', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'keller-prodigal-god',
    type: 'book',
    originalLanguage: 'en',
    domains: ['intercession'],
    topics: ['prodigals', 'repentance', 'forgiveness'],
    perspective: ['reformed'],
    status: 'needs_review',
    description: {
      en: 'A short reading of Luke 15 as the story of two lost sons and a lavish father; it helps the intercessor see the elder-brother heart as well as the younger son.',
      fr: 'Une courte lecture de Luc 15 comme l’histoire de deux fils perdus et d’un père généreux ; elle aide celui qui intercède à reconnaître le cœur du fils aîné autant que celui du cadet.',
    },
    editions: {
      en: { title: 'The Prodigal God: Recovering the Heart of the Christian Faith', author: 'Timothy Keller', publisher: 'Penguin Books (Penguin Random House)', url: 'https://www.penguinrandomhouse.com/books/301319/the-prodigal-god-by-timothy-keller/9781594484025/', available: true, lastVerifiedAt: '2026-09-28' },
      fr: { title: 'Le Dieu prodigue : Revenir au cœur de la foi chrétienne', author: 'Timothy Keller', publisher: 'La Maison de la Bible', url: 'https://maisonbible.ch/2882-dieu-prodigue-le-revenir-au-coeur-de-la-foi-chretienne-9782826035527.html', available: true, lastVerifiedAt: '2026-09-28' },
      es: { title: 'El Dios pródigo', author: 'Timothy Keller', publisher: 'Poiema Publicaciones', url: 'https://poiema.co/products/el-dios-prodigo', available: true, lastVerifiedAt: '2026-09-28' },
      pt: { title: 'O Deus pródigo: recuperando a essência da fé cristã', author: 'Timothy Keller', publisher: 'Edições Vida Nova', url: 'https://www.vidanova.com.br/livros/deus-prodigo-o-recuperando-a-essencia-da-fe-crista', available: true, lastVerifiedAt: '2026-09-28' },
      ja: { title: '「放蕩」する神：キリスト教信仰の回復をめざして', author: 'ティモシー・ケラー 著、廣橋麻子 訳', publisher: 'いのちのことば社 (Word of Life Press)', url: 'https://www.gospelshop.jp/shopdetail/000000003718/', available: true, lastVerifiedAt: '2026-09-28' },
      ko: { title: '팀 켈러의 탕부 하나님', author: '팀 켈러 (Timothy Keller), 윤종석 옮김', publisher: '두란노 (Duranno)', url: 'https://www.duranno.com/books/view/bookdetail.asp?bcod=5915', available: true, lastVerifiedAt: '2026-09-28' },
      ru: { title: 'Расточительный Бог. Возрождение основ христианской веры', author: 'Тимоти Келлер', publisher: 'Христианский центр «Мирт»', url: 'https://mirt.ru/rastochitelnyy-bog-tkeller/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'piper-seven-encouragements-parents-prodigals',
    type: 'podcast',
    originalLanguage: 'en',
    domains: ['intercession'],
    topics: ['prodigals', 'intercession', 'prayer'],
    perspective: ['reformed'],
    status: 'needs_review',
    description: {
      en: 'A short Ask Pastor John episode (with transcript) drawing seven encouragements from Luke 15 for parents who wait, ending with the call to pray and not lose heart.',
      fr: 'Un court épisode d’Ask Pastor John (avec transcription) qui tire de Luc 15 sept encouragements pour les parents qui attendent, et se termine par l’appel à prier sans se décourager. En anglais.',
    },
    editions: {
      en: { title: 'Seven Encouragements for Parents of Prodigals (Ask Pastor John, episode 2070)', author: 'John Piper', publisher: 'Desiring God', url: 'https://www.desiringgod.org/interviews/seven-encouragements-for-parents-of-prodigals', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'kohlmeyer-six-ways-love-wayward-child',
    type: 'article',
    originalLanguage: 'en',
    domains: ['intercession'],
    topics: ['prodigals', 'family', 'trust', 'forgiveness'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A mother of a wandering daughter walks through Luke 15: releasing, accepting, praying, waiting and being ready to receive, without claiming to know how the story ends.',
      fr: 'Une mère dont la fille s’est éloignée relit Luc 15 : laisser aller, accepter, prier, attendre et se tenir prête à accueillir, sans prétendre connaître la fin de l’histoire. En anglais.',
    },
    editions: {
      en: { title: 'Six Ways to Love a Wayward Child', author: 'Denise Kohlmeyer', publisher: 'Desiring God', url: 'https://www.desiringgod.org/articles/six-ways-to-love-a-wayward-child', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'childers-barnett-loved-one-deconstructing',
    type: 'article',
    originalLanguage: 'en',
    domains: ['intercession'],
    topics: ['prodigals', 'apologetics', 'communication', 'intercession'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'For a family whose loved one is deconstructing: seek the relationship first, try to understand before answering, and keep praying.',
      fr: 'Pour une famille dont un proche « déconstruit » sa foi : chercher d’abord la relation, essayer de comprendre avant de répondre, et continuer à prier. En anglais.',
    },
    editions: {
      en: { title: 'Help! My Loved One Is Deconstructing.', author: 'Alisa Childers and Tim Barnett', publisher: 'The Gospel Coalition', url: 'https://www.thegospelcoalition.org/article/help-loved-one-deconstructing/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'vandewerken-praying-for-prodigal-children',
    type: 'article',
    originalLanguage: 'en',
    domains: ['intercession'],
    topics: ['prodigals', 'prayer', 'intercession', 'family', 'trust'],
    perspective: ['reformed'],
    status: 'needs_review',
    description: {
      en: 'A pastor’s five prayers for parents of grown children who left the faith: honest about the limits of a parent’s influence, about speaking and staying silent, and about there being no guarantees.',
      fr: 'Cinq prières d’un pasteur pour les parents d’enfants adultes qui ont quitté la foi : lucides sur les limites de l’influence parentale, sur le moment de parler ou de se taire, et sur l’absence de garanties. En anglais.',
    },
    editions: {
      en: { title: 'Praying for Prodigal Children', author: 'Rev. Joel Vande Werken', publisher: 'Family Fire (ReFrame Ministries)', url: 'https://familyfire.com/articles/praying-for-prodigal-children', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'harvey-lift-heavy-burden-of-shame',
    type: 'article',
    originalLanguage: 'en',
    domains: ['intercession'],
    topics: ['prodigals', 'family', 'grief'],
    perspective: ['reformed'],
    status: 'needs_review',
    description: {
      en: 'Names the shame parents of wanderers often carry, rejects the idea that faithful parenting guarantees faithful children, and asks the church to grieve with them rather than judge.',
      fr: 'Nomme la honte que portent souvent les parents d’un enfant éloigné de la foi, rejette l’idée qu’une éducation fidèle garantit des enfants croyants, et invite l’Église à pleurer avec eux plutôt qu’à juger. En anglais.',
    },
    editions: {
      en: { title: 'Lift the Heavy Burden of Shame', author: 'Dave Harvey', publisher: 'Desiring God', url: 'https://www.desiringgod.org/articles/lift-the-heavy-burden-of-shame', available: true, lastVerifiedAt: '2026-09-28' },
      id: { title: 'Anak Terhilang, Salah Siapa?', author: 'Dave Harvey', publisher: 'Hikmat Alkitab untuk Keluarga (Our Daily Bread Ministries Indonesia), translated with permission from Desiring God', url: 'https://hikmat-keluarga.org/articles/anak-terhilang-salah-siapa/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'banks-prayers-for-prodigals',
    type: 'prayerGuide',
    originalLanguage: 'en',
    domains: ['intercession'],
    topics: ['prodigals', 'intercession', 'prayer'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'Ninety short Scripture-based prayers from a pastor whose own children wandered; a companion for days when words run out, not a promise of how or when prayer is answered.',
      fr: 'Quatre-vingt-dix courtes prières tirées de l’Écriture, écrites par un pasteur dont les enfants se sont éloignés ; un appui quand les mots manquent, non une promesse sur la manière ou le moment de l’exaucement. En anglais.',
    },
    editions: {
      en: { title: 'Prayers for Prodigals: 90 Days of Prayer for Your Child (Updated and Expanded)', author: 'James Banks', publisher: 'Our Daily Bread Publishing', url: 'https://store.odbm.org/prayers-for-prodigals-updated-and-expanded.html', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'banks-hope-lies-ahead',
    type: 'book',
    originalLanguage: 'en',
    domains: ['intercession'],
    topics: ['prodigals', 'intercession', 'family', 'trust'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A pastor who prayed and the son who wandered tell the same story from both sides; honest about the pain on each side, though it is one family’s story and not a pattern every family will see.',
      fr: 'Un pasteur qui a prié et le fils qui s’est éloigné racontent la même histoire chacun de son côté ; un récit honnête sur la douleur des deux, même s’il s’agit de l’histoire d’une famille et non d’un schéma que toutes connaîtront. En anglais.',
    },
    editions: {
      en: { title: 'Hope Lies Ahead: Encouragement for Parents of Prodigals from a Family That’s Been There', author: 'James Banks and Geoffrey Banks', publisher: 'Our Daily Bread Publishing', url: 'https://store.odbm.org/products/hope-lies-ahead-encouragement-for-parents-of-prodigals-from-a-family-thats-been-there', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'herrera-hijo-indiferente-al-evangelio',
    type: 'article',
    originalLanguage: 'es',
    domains: ['intercession'],
    topics: ['prodigals', 'prayer', 'family', 'communication'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A Spanish pastor’s wife and mother of a child who does not believe shares lessons learned: parents cannot save, keep praying, stop reproaching, and leave judgment to God. In Spanish.',
      fr: 'Épouse de pasteur en Espagne et mère d’un enfant qui ne croit pas, l’autrice partage ce qu’elle a appris : les parents ne sauvent pas, il faut continuer à prier, cesser les reproches et laisser le jugement à Dieu. En espagnol.',
      es: 'Una madre, esposa de pastor en España, comparte lo que ha aprendido: los padres no pueden salvar, hay que seguir orando, dejar de reprochar y dejar el juicio a Dios.',
    },
    editions: {
      es: { title: '¿Qué hago si mi hijo es indiferente al evangelio?', author: 'Pilar Herrera', publisher: 'Coalición por el Evangelio', url: 'https://www.coalicionporelevangelio.org/articulo/que-hago-si-mi-hijo-es-indiferente-al-evangelio/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'richards-los-hijos-prodigos',
    type: 'article',
    originalLanguage: 'es',
    domains: ['intercession'],
    topics: ['prodigals', 'repentance', 'forgiveness'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A Mexican pastor reads Luke 15 as the story of two lost sons and warns those who stayed home against the elder brother’s heart. In Spanish.',
      fr: 'Un pasteur mexicain lit Luc 15 comme l’histoire de deux fils perdus et met en garde ceux qui sont restés à la maison contre le cœur du fils aîné. En espagnol.',
      es: 'Un pastor mexicano lee Lucas 15 como la historia de dos hijos perdidos y advierte a quienes se quedaron en casa contra el corazón del hermano mayor.',
    },
    editions: {
      es: { title: 'Los hijos pródigos', author: 'Steven Richards', publisher: 'Coalición por el Evangelio', url: 'https://www.coalicionporelevangelio.org/articulo/los-hijos-prodigos/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'moore-ama-a-tu-hijo-prodigo',
    type: 'article',
    originalLanguage: 'en',
    domains: ['intercession'],
    topics: ['prodigals', 'family', 'forgiveness', 'addiction'],
    perspective: ['evangelical'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'An excerpt from The Storm-Tossed Family: keep every connection open, grieve without family pride, and expect a long, patient road even after a return. Spanish translation.',
      fr: 'Extrait de The Storm-Tossed Family : garder ouverts tous les liens, pleurer sans orgueil familial, et s’attendre à un long chemin de patience, même après un retour. Traduction espagnole.',
      es: 'Fragmento de The Storm-Tossed Family: mantener abiertas todas las conexiones, sufrir sin orgullo familiar y esperar un camino largo y paciente, incluso después de un regreso.',
    },
    editions: {
      es: { title: 'Ama a tu hijo pródigo como a ti mismo', author: 'Russell Moore', publisher: 'Coalición por el Evangelio', url: 'https://www.coalicionporelevangelio.org/articulo/ama-hijo-prodigo-ti/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'ortis-when-prodigal-children-dont-return',
    type: 'article',
    originalLanguage: 'en',
    domains: ['intercession'],
    topics: ['prodigals', 'grief', 'forgiveness', 'family', 'trust'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A family therapist and former pastor writes for parents whose children have not come back: false guilt and Proverbs 22:6, letting go, choosing relationship over being right, and waiting without despair.',
      fr: 'Un thérapeute familial, ancien pasteur, écrit pour les parents dont les enfants ne sont pas revenus : la fausse culpabilité et Proverbes 22.6, laisser aller, choisir la relation plutôt que d’avoir raison, attendre sans désespérer. En anglais.',
    },
    editions: {
      en: { title: 'When prodigal children don’t return', author: 'David Ortis', publisher: 'Christian Leader (U.S. Mennonite Brethren); first published in the Mennonite Brethren Herald', url: 'https://christianleadermag.com/when-prodigal-children-dont-return/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'gandolfo-a-mae-do-filho-prodigo',
    type: 'article',
    originalLanguage: 'pt',
    domains: ['intercession'],
    topics: ['prodigals', 'grief', 'prayer', 'spiritual-formation'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A short Brazilian narrative meditation: a mother prays through her son’s leaving and is herself comforted and healed by Scripture while she waits. In Portuguese.',
      fr: 'Une courte méditation narrative brésilienne : une mère prie pendant l’éloignement de son fils et trouve elle-même consolation et guérison dans l’Écriture pendant l’attente. En portugais.',
      pt: 'Uma breve meditação narrativa: uma mãe ora durante a partida do filho e é, ela mesma, consolada e curada pela Palavra enquanto espera.',
    },
    editions: {
      pt: { title: 'A mãe do filho pródigo', author: 'Renata Gandolfo', publisher: 'Voltemos ao Evangelho', url: 'https://voltemosaoevangelho.com/blog/2018/05/a-mae-do-filho-prodigo/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'nouwen-return-of-the-prodigal-son',
    type: 'book',
    originalLanguage: 'en',
    domains: ['intercession'],
    topics: ['prodigals', 'forgiveness', 'spiritual-formation', 'repentance'],
    perspective: ['catholic'],
    status: 'needs_review',
    description: {
      en: 'A meditation on Rembrandt’s painting of Luke 15 by a Catholic priest: the reader finds themselves in the younger son, the elder son, and finally in the father who waits and welcomes. Catholic author, widely read across traditions.',
      fr: 'Une méditation d’un prêtre catholique sur le tableau de Rembrandt inspiré de Luc 15 : le lecteur se reconnaît dans le cadet, dans l’aîné, puis dans le père qui attend et accueille. Auteur catholique, lu dans toutes les traditions.',
    },
    editions: {
      en: { title: 'The Return of the Prodigal Son: A Story of Homecoming', author: 'Henri J. M. Nouwen', publisher: 'Image (PRH Christian Publishing)', url: 'https://www.penguinrandomhouse.com/books/122877/the-return-of-the-prodigal-son-by-henri-jm-nouwen/', available: true, lastVerifiedAt: '2026-09-28' },
      es: { title: 'El regreso del hijo pródigo: Meditaciones ante un cuadro de Rembrandt', author: 'Henri J. M. Nouwen', publisher: 'PPC Editorial', url: 'https://www.ppc-editorial.com/libro/el-regreso-del-hijo-prodigo', available: true, lastVerifiedAt: '2026-09-28' },
      de: { title: 'Nimm sein Bild in dein Herz: Geistliche Deutung eines Gemäldes von Rembrandt', author: 'Henri J. M. Nouwen (übersetzt von Ulrich Schütz)', publisher: 'Verlag Herder', url: 'https://www.herder.de/religion-spiritualitaet/shop/p3/50266-nimm-sein-bild-in-dein-herz-gebundene-ausgabe/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'foma-deti-uhodyat-iz-tserkvi',
    type: 'article',
    originalLanguage: 'ru',
    domains: ['intercession'],
    topics: ['prodigals', 'family', 'prayer', 'communication'],
    perspective: ['orthodox'],
    status: 'needs_review',
    description: {
      en: 'Russian Orthodox parents and priests on children who leave the church: no recipe, no spiritual pressure, stay close and keep praying; one mother says plainly that her son has not come back. Orthodox voices, in Russian.',
      fr: 'Des parents et des prêtres orthodoxes russes parlent des enfants qui quittent l’Église : pas de recette, pas de pression spirituelle, rester proche et continuer à prier ; une mère dit simplement que son fils n’est pas revenu. Voix orthodoxes, en russe.',
      ru: 'Православные родители и священники о детях, ушедших из Церкви: рецепта нет, давить в духовной жизни нельзя, важно оставаться рядом и молиться; одна мама честно говорит, что сын не вернулся.',
    },
    editions: {
      ru: { title: 'Что делать родителям, если дети уходят из Церкви?', author: 'Мария Свешникова, прот. Константин Островский, Ирина Копчинская, прот. Александр Ильяшенко, прот. Димитрий Струев и др.', publisher: 'Православный журнал «Фома» (№5 (145), май 2015)', url: 'https://foma.ru/chto-delat-roditelyam-esli-deti-uhodyat-iz-tserkvi.html', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'mofei-wei-langzixing-ernu-daogao',
    type: 'article',
    originalLanguage: 'zh',
    domains: ['intercession'],
    topics: ['prodigals', 'prayer', 'family', 'trust'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A Chinese mother writes for parents of adult children who have drifted: stop blaming yourself or others, stop trying to repair what only God can, and entrust the child to Him in patient prayer. In Simplified Chinese.',
      fr: 'Une mère chinoise écrit pour les parents d’enfants adultes qui se sont éloignés : cesser de s’accuser ou d’accuser les autres, renoncer à réparer ce que seul Dieu peut réparer, et confier l’enfant à Dieu dans une prière patiente. En chinois simplifié.',
      zh: '一位母亲写给成年子女远离神的父母：停止自责或怪罪他人，承认只有神能修补孩子生命的破口，在恒切的祷告中将孩子交托给神。',
    },
    editions: {
      zh: { title: '为浪子型的儿女祷告', author: '莫非', publisher: '基督教北京守望教会（《@守望》第116期；原载创世纪文字培训书苑）', url: 'https://t5.shwchurch.org/2018/07/28/%E4%B8%BA%E6%B5%AA%E5%AD%90%E5%9E%8B%E7%9A%84%E5%84%BF%E5%A5%B3%E7%A5%B7%E5%91%8A/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'hawksley-masal-gomshodeha',
    type: 'study',
    originalLanguage: 'fa',
    domains: ['intercession'],
    topics: ['prodigals', 'repentance'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A study of the lost sheep and the lost coin (Luke 15:1-10) in their cultural setting: God is the seeker who takes the first step, and heaven rejoices when the lost are found. In Persian.',
      fr: 'Une étude de la brebis et de la pièce perdues (Luc 15.1-10) dans leur contexte culturel : Dieu est celui qui cherche et fait le premier pas, et le ciel se réjouit quand ce qui était perdu est retrouvé. En persan.',
      fa: 'بررسی مثل گوسفند و سکهٔ گمشده (لوقا ۱۵:‏۱-۱۰) در بستر تاریخی و فرهنگی‌شان: خدا جستجوگری است که قدم اول را برمی‌دارد و از یافت‌شدن گمشده شادی می‌کند.',
    },
    editions: {
      fa: { title: 'مثل گمشــده‌ها', author: 'Tom Hawksley', publisher: 'کلمه (Kalameh, Elam Ministries)', url: 'https://kalameh.com/en/node/4371', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'bing-grace-lessons-prodigal-son',
    type: 'article',
    originalLanguage: 'en',
    domains: ['intercession'],
    topics: ['prodigals', 'repentance', 'forgiveness'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A short study of Luke 15:11-32: the father’s love takes the risk of freedom, the bond is not cancelled by wandering, and both brothers misread grace.',
      fr: 'Une courte étude de Luc 15.11-32 : l’amour du père prend le risque de la liberté, l’éloignement ne rompt pas le lien, et les deux frères se méprennent sur la grâce. En anglais et en tagalog.',
    },
    editions: {
      en: { title: 'GraceNote #85: Grace Lessons from the Parable of the Prodigal Son', author: 'Charlie Bing', publisher: 'GraceLife Ministries', url: 'https://www.gracelife.org/resources/gracenotes/?id=85&lang=en', available: true, lastVerifiedAt: '2026-09-28' },
      tl: { title: 'Mga Aral ng Biyaya Mula sa Parabula ng Alibughang Anak, Lukas 15:11-32', author: 'Charlie Bing', publisher: 'GraceLife Ministries', url: 'https://www.gracelife.org/resources/gracenotes/?id=85&lang=tgl', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'guzik-luke-15-commentary',
    type: 'study',
    originalLanguage: 'en',
    domains: ['intercession'],
    topics: ['prodigals', 'repentance', 'forgiveness'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A free verse-by-verse commentary on Luke 15: the setting among grumbling religious leaders, the father who lets his son go and then runs to meet him, and the elder brother who stays home without knowing his father’s heart.',
      fr: 'Un commentaire gratuit, verset par verset, de Luc 15 : le contexte des chefs religieux qui murmurent, le père qui laisse partir son fils puis court à sa rencontre, et le fils aîné resté à la maison sans connaître le cœur de son père. En anglais, arabe, russe et chinois.',
    },
    editions: {
      en: { title: 'Luke 15 – The Joy of Finding the Lost', author: 'David Guzik', publisher: 'Enduring Word', url: 'https://enduringword.com/bible-commentary/luke-15/', available: true, lastVerifiedAt: '2026-09-28' },
      ar: { title: 'إنجيل لوقا – الإصحاح ١٥', author: 'ديفيد غوزيك (David Guzik)', publisher: 'Enduring Word (Arabic)', url: 'https://arabic.enduringword.com/luke-15-ar/', available: true, lastVerifiedAt: '2026-09-28' },
      ru: { title: 'Евангелие от Луки, Глава 15 — Радость обретения потерянного', author: 'Дэвид Гузик (David Guzik)', publisher: 'Enduring Word (Russian)', url: 'https://russian.enduringword.com/%D0%B5%D0%B2%D0%B0%D0%BD%D0%B3%D0%B5%D0%BB%D0%B8%D0%B5-%D0%BE%D1%82-%D0%BB%D1%83%D0%BA%D0%B8-%D0%B3%D0%BB%D0%B0%D0%B2%D0%B0-15/', available: true, lastVerifiedAt: '2026-09-28' },
      zh: { title: '路加福音第15章——找到迷失者的喜乐', author: '古大卫 (David Guzik)', publisher: 'Enduring Word (Chinese Version)', url: 'https://chinese.enduringword.com/%E8%B7%AF%E5%8A%A0%E7%A6%8F%E9%9F%B3%E7%AC%AC15%E7%AB%A0/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
];
