// Candidates for psalms42, researched 2026-09-28. NONE is approved: every entry is
// needs_review with no sign-off, so the resolver never shows it. See
// docs/resources/candidates/psalms42.md for the verification worksheet.
const ed = (title, author, publisher, url, available = true) => ({
  title, author, publisher, url, available, lastVerifiedAt: '2026-09-28',
});
const BP = 'BibleProject';

export const PSALMS42_CANDIDATES = [
  {
    id: 'bibleproject-psalms-overview',
    type: 'video',
    originalLanguage: 'en',
    domains: ['bible-study'],
    topics: ['psalms', 'lament', 'worship', 'prayer'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A nine-minute animated overview of the whole Psalter — its five books, laments and praises, and messianic hope — to watch before or during the first week. Outside English, French, Spanish, Portuguese and German, the link opens BibleProject’s language page, where the Psalms overview is listed. Free.',
      fr: 'Un panorama animé de neuf minutes sur l’ensemble du Psautier — ses cinq livres, ses lamentations et ses louanges, son espérance messianique — à regarder avant ou pendant la première semaine. Hors anglais, français, espagnol, portugais et allemand, le lien ouvre la page de langue de BibleProject, où figure le panorama des Psaumes. Gratuit.',
    },
    editions: {
      en: ed('Psalms', BP, BP, 'https://bibleproject.com/videos/psalms/'),
      fr: ed('Psaumes', BP, BP, 'https://bibleproject.com/fr/videos/psaumes/'),
      es: ed('Salmos', BP, BP, 'https://bibleproject.com/es/videos/salmos/'),
      pt: ed('Salmos', BP, BP, 'https://bibleproject.com/pt-br/videos/salmos/'),
      de: ed('Psalmen', BP, 'BibleProject – Deutsch (visiomedia)', 'https://bibleproject.visiomedia.org/video/psalmen/'),
      ru: ed('Обзор: Псалтирь', BP, BP, 'https://bibleproject.com/ru/'),
      zh: ed('诗篇 - Psalms', BP, BP, 'https://bibleproject.com/zh-hans/'),
      ja: ed('詩篇 Psalms【概観】', BP, BP, 'https://bibleproject.com/ja/'),
      ko: ed('시편 개요 Psalms', BP, BP, 'https://bibleproject.com/ko/'),
      ar: ed('نظرة عامّة: المزامير', BP, 'BibleProject (Egyptian Arabic)', 'https://bibleproject.com/arz/'),
      fa: ed('Psalms مروری بر مزامیر', BP, BP, 'https://bibleproject.com/fa/'),
      hi: ed('अवलोकन: भजन संहिता Psalms', BP, BP, 'https://bibleproject.com/hi/'),
      id: ed('Ringkasan: Mazmur', BP, BP, 'https://bibleproject.com/id/'),
      sw: ed('Muhtasari: Zaburi', BP, BP, 'https://bibleproject.com/sw/'),
      tl: ed('Buong-ideya: Mga Awit', BP, BP, 'https://bibleproject.com/tl/'),
      am: ed('ዳሰሳ፦ መጽሐፈ መዝሙር Psalms', BP, BP, 'https://bibleproject.com/am/'),
    },
  },
  {
    id: 'bibleproject-how-to-read-psalms',
    type: 'video',
    originalLanguage: 'en',
    domains: ['bible-study'],
    topics: ['psalms', 'kingdom-of-god', 'scripture-prayer'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A short animated study of how the Psalter is arranged — Psalms 1–2 as its gateway, five books, royal and messianic threads — which supports day 1’s method and the week on Psalms 1, 2 and 72. Free.',
      fr: 'Une courte étude animée sur l’organisation du Psautier — les Psaumes 1 et 2 comme porte d’entrée, cinq livres, les fils royal et messianique — en appui à la méthode du jour 1 et à la semaine des Psaumes 1, 2 et 72. Gratuit.',
    },
    editions: {
      en: ed('The Book of Psalms (How to Read the Bible)', BP, BP, 'https://bibleproject.com/videos/book-of-psalms/'),
      fr: ed('Le livre des Psaumes (Comment lire la Bible ?)', BP, BP, 'https://bibleproject.com/fr/videos/le-livre-des-psaumes/'),
      es: ed('El libro de los Salmos', BP, BP, 'https://bibleproject.com/es/videos/el-libro-de-salmos/'),
      pt: ed('O livro dos Salmos', BP, BP, 'https://bibleproject.com/pt-br/videos/o-livro-dos-salmos/'),
      ru: ed('Книга Псалмов', BP, BP, 'https://bibleproject.com/ru/'),
      zh: ed('诗篇 - The Book of Psalms', BP, BP, 'https://bibleproject.com/zh-hans/'),
      ja: ed('聖書の読み方：詩篇 The Book of Psalms', BP, BP, 'https://bibleproject.com/ja/'),
      ko: ed('시편 The Book of Psalms', BP, BP, 'https://bibleproject.com/ko/'),
      hi: ed('भजन संहिता की पुस्तक The Book of Psalms', BP, BP, 'https://bibleproject.com/hi/'),
      id: ed('Kitab Mazmur', BP, BP, 'https://bibleproject.com/id/'),
    },
  },
  {
    id: 'bibleproject-psalms-study-podcast',
    type: 'podcast',
    originalLanguage: 'en',
    domains: ['bible-study'],
    topics: ['psalms', 'lament', 'fear', 'repentance', 'prayer'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'Four free English podcast talks — fear, pain, confession and doubt — on letting the Psalms teach us to pray; they fit the lament and repentance weeks (Psalm 22 in “Pain”, Psalm 32 in “Confession”).',
      fr: 'Quatre enseignements gratuits en anglais, en podcast — la peur, la douleur, la confession et le doute — pour laisser les Psaumes nous apprendre à prier ; ils accompagnent les semaines de la lamentation et de la repentance (Psaume 22 dans « Pain », Psaume 32 dans « Confession »).',
    },
    editions: {
      en: ed('Exploring My Strange Bible: Psalms Study', 'Tim Mackie', BP, 'https://bibleproject.com/podcasts/series/psalms-study/'),
    },
  },
  {
    id: 'bibleproject-psalms-1-2-podcast',
    type: 'podcast',
    originalLanguage: 'en',
    domains: ['bible-study'],
    topics: ['psalms', 'kingdom-of-god', 'scripture-prayer'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'Four free English conversations on Psalms 1 and 2 as the Psalter’s double gateway — delight in God’s word and the Lord’s anointed King — for the days on those two psalms.',
      fr: 'Quatre conversations gratuites en anglais sur les Psaumes 1 et 2, double porte d’entrée du Psautier — l’amour de la parole de Dieu et le Roi oint du Seigneur — pour les jours consacrés à ces deux psaumes.',
    },
    editions: {
      en: ed('Psalms 1 & 2', 'Tim Mackie and Jon Collins', BP, 'https://bibleproject.com/podcasts/series/psalms-1-2/'),
    },
  },
  {
    id: 'keller-songs-of-jesus',
    type: 'book',
    originalLanguage: 'en',
    domains: ['bible-study'],
    topics: ['psalms', 'prayer', 'scripture-prayer', 'worship'],
    perspective: ['reformed'],
    status: 'needs_review',
    description: {
      en: 'A year of one-page readings that walk through every psalm and then turn each one into prayer — a gentle way to keep praying the Psalter after the six weeks.',
      fr: 'Une année de lectures d’une page qui parcourent chaque psaume puis le transforment en prière — une manière douce de continuer à prier le Psautier après les six semaines.',
    },
    editions: {
      en: ed('The Songs of Jesus: A Year of Daily Devotions in the Psalms', 'Timothy Keller with Kathy Keller', 'Viking (Penguin Random House)', 'https://www.penguinrandomhouse.com/books/318419/the-songs-of-jesus-by-timothy-keller-with-kathy-keller/'),
      es: ed('Los Cantos de Jesús: Un año de devocionales diarios en Los Salmos', 'Timothy Keller y Kathy Keller', 'Poiema Publicaciones', 'https://poiema.co/products/los-cantos-de-jesus'),
      pt: ed('Os cânticos de Jesus: Um ano de devocionais diários nos Salmos', 'Timothy Keller e Kathy Keller', 'Edições Vida Nova', 'https://www.vidanova.com.br/livros/canticos-de-jesus-os-um-ano-de-devocionais-diarios-nos-salmos'),
      de: ed('Ein Jahr mit den Psalmen: 365 Andachten', 'Timothy Keller und Kathy Keller', 'Fontis', 'https://www.fontis-shop.ch/products/ein-jahr-mit-den-psalmen'),
    },
  },
  {
    id: 'bonhoeffer-psalms-prayer-book',
    type: 'book',
    originalLanguage: 'de',
    domains: ['bible-study'],
    topics: ['psalms', 'scripture-prayer', 'prayer', 'lament'],
    status: 'needs_review',
    description: {
      en: 'Bonhoeffer’s short 1940 introduction to praying the Psalms as the Bible’s own prayer book, with brief chapters on creation, law, suffering, guilt, enemies and the end — a classic companion to the whole plan, including the hard psalms of week 3.',
      fr: 'La courte introduction de Bonhoeffer (1940) à la prière des Psaumes, livre de prière de la Bible elle-même, avec de brefs chapitres sur la création, la loi, la souffrance, la culpabilité, les ennemis et la fin — un classique pour tout le parcours, y compris les psaumes difficiles de la semaine 3.',
    },
    editions: {
      de: ed('Die Psalmen: Das Gebetbuch der Bibel (mit einer Einführung von Peter Zimmerling)', 'Dietrich Bonhoeffer', 'Brunnen Verlag', 'https://brunnen-verlag.de/193405/die-psalmen.html'),
      en: ed('Psalms: The Prayer Book of the Bible (introduction by Walter Brueggemann)', 'Dietrich Bonhoeffer', 'Broadleaf Books', 'https://www.broadleafbooks.com/store/product/9781506480190/Psalms'),
    },
  },
  {
    id: 'vroegop-dark-clouds-deep-mercy',
    type: 'book',
    originalLanguage: 'en',
    domains: ['bible-study'],
    topics: ['psalms', 'lament', 'suffering', 'grief'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A pastor’s study of the lament psalms (77, 10, 22, 13) and Lamentations that names four movements — turn, complain, ask, trust — without hurrying grief; a companion for the lament week.',
      fr: 'L’étude, par un pasteur, des psaumes de lamentation (77, 10, 22, 13) et des Lamentations, qui distingue quatre mouvements — se tourner, se plaindre, demander, faire confiance — sans presser le deuil ; pour accompagner la semaine de la lamentation.',
    },
    editions: {
      en: ed('Dark Clouds, Deep Mercy: Discovering the Grace of Lament', 'Mark Vroegop', 'Crossway', 'https://www.crossway.org/books/dark-clouds-deep-mercy-tpb/'),
      es: ed('Nubes oscuras, misericordia profunda', 'Mark Vroegop', 'Editorial Portavoz', 'https://www.portavoz.com/nubes-oscuras-misericordia-profunda'),
    },
  },
  {
    id: 'peterson-answering-god',
    type: 'book',
    originalLanguage: 'en',
    domains: ['bible-study'],
    topics: ['psalms', 'prayer', 'scripture-prayer', 'spiritual-formation'],
    status: 'needs_review',
    description: {
      en: 'A short classic on the Psalms as God’s “tools for prayer”: why honest, earthy psalm language — including hostility and memory — trains us to answer God as we really are.',
      fr: 'Un court classique sur les Psaumes comme « outils de prière » : pourquoi leur langage franc et concret — y compris l’hostilité et la mémoire — nous apprend à répondre à Dieu tels que nous sommes.',
    },
    editions: {
      en: ed('Answering God: The Psalms as Tools for Prayer', 'Eugene H. Peterson', 'HarperOne', 'https://www.harpercollins.com/products/answering-god-eugene-h-peterson'),
      ko: ed('하나님께 응답하는 기도', '유진 피터슨', 'IVP (한국기독학생회출판부)', 'https://ivp.co.kr/books/book_detail.html?book=s01&idx=1529'),
    },
  },
  {
    id: 'wright-case-for-the-psalms',
    type: 'book',
    originalLanguage: 'en',
    domains: ['bible-study'],
    topics: ['psalms', 'worship', 'kingdom-of-god', 'prayer'],
    perspective: ['anglican'],
    status: 'needs_review',
    description: {
      en: 'A New Testament scholar’s short, personal case for praying and singing the Psalms every day, showing how they reshape our sense of time, place and God’s coming kingdom.',
      fr: 'Un plaidoyer bref et personnel d’un spécialiste du Nouveau Testament pour prier et chanter les Psaumes chaque jour, montrant comment ils transforment notre perception du temps, du lieu et du règne de Dieu qui vient.',
    },
    editions: {
      en: ed('The Case for the Psalms: Why They Are Essential', 'N. T. Wright', 'HarperOne', 'https://www.harpercollins.com/products/the-case-for-the-psalms-n-t-wright'),
    },
  },
  {
    id: 'longman-how-to-read-the-psalms',
    type: 'book',
    originalLanguage: 'en',
    domains: ['bible-study'],
    topics: ['psalms', 'lament', 'worship', 'scripture-prayer'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'An accessible introduction to reading the Psalms well — their genres, Hebrew poetry and parallelism, imagery, and a Christian reading — with worked examples including Psalm 69; it backs up day 1’s six questions.',
      fr: 'Une introduction accessible pour bien lire les Psaumes — leurs genres, la poésie hébraïque et le parallélisme, les images, une lecture chrétienne — avec des exemples travaillés dont le Psaume 69 ; elle prolonge les six questions du jour 1.',
    },
    editions: {
      en: ed('How to Read the Psalms (2nd ed.)', 'Tremper Longman III', 'IVP Academic', 'https://www.ivpress.com/how-to-read-the-psalms'),
    },
  },
  {
    id: 'longman-psalms-totc',
    type: 'book',
    originalLanguage: 'en',
    domains: ['bible-study'],
    topics: ['psalms', 'lament', 'worship', 'kingdom-of-god'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A compact evangelical commentary on all 150 psalms that reads each one in its Old Testament setting and then asks how it points to Christ — a reliable reference for the “context” notes on each day.',
      fr: 'Un commentaire évangélique compact sur les 150 psaumes, qui lit chacun dans son contexte de l’Ancien Testament avant de se demander comment il conduit au Christ — une référence fiable pour les notes de « contexte » de chaque jour.',
    },
    editions: {
      en: ed('Psalms: An Introduction and Commentary (Tyndale Old Testament Commentaries 15)', 'Tremper Longman III', 'IVP Academic', 'https://www.ivpress.com/psalms-totc'),
    },
  },
  {
    id: 'kidner-psalms',
    type: 'book',
    originalLanguage: 'en',
    domains: ['bible-study'],
    topics: ['psalms', 'worship', 'prayer'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'Derek Kidner’s much-loved two-volume commentary (Psalms 1–72 and 73–150), concise and warm, that explains each psalm and its interpretative questions for ordinary readers.',
      fr: 'Le commentaire très apprécié de Derek Kidner en deux volumes (Psaumes 1–72 et 73–150), concis et chaleureux, qui explique chaque psaume et ses questions d’interprétation pour tout lecteur.',
    },
    editions: {
      en: ed('Psalms 1–72 (Kidner Classic Commentaries; companion volume Psalms 73–150)', 'Derek Kidner', 'IVP Academic', 'https://www.ivpress.com/psalms-1-72-kcc'),
    },
  },
  {
    id: 'wax-cs-lewis-cursing-psalms',
    type: 'article',
    originalLanguage: 'en',
    domains: ['bible-study'],
    topics: ['psalms', 'justice', 'lament'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A short article on the “cursing” psalms: why they are cries for God’s justice rather than licence for revenge, and how Christians pray them in Christ instead of taking vengeance into their own hands — for the day on Psalm 69.',
      fr: 'Un court article sur les psaumes « de malédiction » : pourquoi ils sont un cri vers la justice de Dieu et non une permission de se venger, et comment les chrétiens les prient en Christ au lieu de se faire justice eux-mêmes — pour le jour du Psaume 69.',
    },
    editions: {
      en: ed('What C. S. Lewis Got Wrong About the Cursing Psalms', 'Trevin Wax', 'The Gospel Coalition', 'https://www.thegospelcoalition.org/blogs/trevin-wax/cs-lewis-cursing-psalms/'),
      es: ed('Lo que C. S. Lewis entendió mal sobre los salmos imprecatorios', 'Trevin Wax', 'Coalición por el Evangelio', 'https://www.coalicionporelevangelio.org/articulo/lewis-salmos-imprecatorios/'),
    },
  },
  {
    id: 'coalicion-oracion-imprecatoria',
    type: 'article',
    originalLanguage: 'es',
    domains: ['bible-study'],
    topics: ['psalms', 'justice', 'forgiveness', 'lament'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A Spanish-language article explaining the imprecatory prayers of the Psalms (69, 109, 137 and others) as cries of distress for God’s justice, read in the light of Jesus’ call to love and pray for enemies. Spanish only.',
      fr: 'Un article en espagnol qui explique les prières imprécatoires des Psaumes (69, 109, 137 et d’autres) comme des cris de détresse vers la justice de Dieu, lus à la lumière de l’appel de Jésus à aimer ses ennemis et à prier pour eux. En espagnol uniquement.',
    },
    editions: {
      es: ed('¿Qué es la oración imprecatoria?', 'Nimrod López Noj', 'Coalición por el Evangelio', 'https://www.coalicionporelevangelio.org/articulo/oracion-imprecatoria/'),
    },
  },
  {
    id: 'wax-psalms-in-30-days',
    type: 'prayerGuide',
    originalLanguage: 'en',
    domains: ['bible-study'],
    topics: ['psalms', 'prayer', 'scripture-prayer', 'worship'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A prayer book that sets all 150 psalms in a morning, midday and evening pattern over thirty days, with other biblical songs and historic prayers — a way to keep praying the whole Psalter once the study ends.',
      fr: 'Un livre de prière qui répartit les 150 psaumes en offices du matin, de midi et du soir sur trente jours, avec d’autres cantiques bibliques et des prières historiques — pour continuer à prier tout le Psautier après la fin de l’étude.',
    },
    editions: {
      en: ed('Psalms in 30 Days: CSB Edition', 'Trevin Wax (ed.)', 'B&H Publishing Group', 'https://www.lifeway.com/en/product/psalms-in-30-days-csb-edition-P005833698'),
    },
  },
  {
    id: 'cavin-prier-jugement-ennemis',
    type: 'article',
    originalLanguage: 'fr',
    domains: ['bible-study'],
    topics: ['psalms', 'justice', 'forgiveness'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A French article on the psalms of imprecation (starting from Psalm 52): God hates evil and will judge it, vengeance is his and not ours, and the call to love our enemies still stands. French only.',
      fr: 'Un article sur les psaumes d’imprécation (à partir du Psaume 52) : Dieu hait le mal et le jugera, la vengeance lui appartient et non à nous, et l’appel à aimer nos ennemis demeure.',
    },
    editions: {
      fr: ed('Peut-on prier pour le jugement de nos ennemis ?', 'Jérémie Cavin', 'Évangile 21 (The Gospel Coalition)', 'https://evangile21.thegospelcoalition.org/article/peut-on-prier-pour-le-jugement-de-nos-ennemis/'),
    },
  },
  {
    id: 'excelsis-redecouvrir-les-psaumes',
    type: 'book',
    originalLanguage: 'fr',
    domains: ['bible-study'],
    topics: ['psalms', 'prayer', 'worship', 'lament'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A French collection by evangelical Bible scholars that joins careful exegesis with daily prayer, including the imprecatory psalms and the New Testament’s messianic reading of the Psalter. French only.',
      fr: 'Un ouvrage collectif de biblistes évangéliques francophones qui unit une exégèse rigoureuse et la prière quotidienne, y compris sur les psaumes d’imprécation et la lecture messianique du Psautier dans le Nouveau Testament.',
    },
    editions: {
      fr: ed('Redécouvrir les Psaumes', 'Collectif (Émile Nicole, Matthieu Richelle, Jacques Buchhold, Christophe Paya et al.)', 'Édifac / Excelsis', 'https://www.xl6.com/articles/9782755002331-redecouvrir-les-psaumes'),
    },
  },
  {
    id: 'nicole-livre-des-psaumes',
    type: 'study',
    originalLanguage: 'fr',
    domains: ['bible-study'],
    topics: ['psalms', 'worship', 'justice'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A short French study of all 150 psalms and the shape of the whole book, from twenty years of teaching the Psalter — including the psalms’ many enemies and calls for God’s vengeance. French only.',
      fr: 'Une courte étude des 150 psaumes et de la structure du livre entier, fruit de vingt ans d’enseignement du Psautier — y compris les nombreux ennemis et les appels à la vengeance de Dieu.',
    },
    editions: {
      fr: ed('Le livre des Psaumes (coll. À l’étude de la Bible)', 'Émile Nicole', 'Institut Biblique de Nogent (distribution Excelsis)', 'https://www.xl6.com/articles/9782903100599-le-livre-des-psaumes'),
    },
  },
  {
    id: 'brueggemann-message-of-the-psalms',
    type: 'book',
    originalLanguage: 'en',
    domains: ['bible-study'],
    topics: ['psalms', 'lament', 'worship', 'suffering'],
    status: 'needs_review',
    description: {
      en: 'An influential scholarly reading that groups the psalms as songs of orientation, disorientation and new orientation — a lens for why the plan moves from praise through lament to thanksgiving. For readers who want the academic background.',
      fr: 'Une lecture savante influente qui classe les psaumes en chants d’orientation, de désorientation et de réorientation — une clé pour comprendre pourquoi le parcours passe de la louange à la lamentation puis à l’action de grâce. Pour qui veut l’arrière-plan universitaire.',
    },
    editions: {
      en: ed('The Message of the Psalms: A Theological Commentary', 'Walter Brueggemann', 'Fortress Press', 'https://www.augsburgfortress.org/store/product/9780806621203/The-Message-of-the-Psalms'),
    },
  },
  {
    id: 'ellison-christ-shape-psalms',
    type: 'article',
    originalLanguage: 'en',
    domains: ['bible-study'],
    topics: ['psalms', 'kingdom-of-god', 'gospel'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A short article tracing the Psalter’s five books — from the gateway of Psalms 1–2 to the closing hallelujahs — and how their arrangement stirs hope for God’s promised King; for day 1 and the week on Psalms 1, 2 and 72.',
      fr: 'Un court article qui suit les cinq livres du Psautier — de la porte d’entrée des Psaumes 1 et 2 aux alléluias de la fin — et montre comment leur agencement nourrit l’espérance du Roi promis par Dieu ; pour le jour 1 et la semaine des Psaumes 1, 2 et 72.',
    },
    editions: {
      en: ed('Seeing Christ in the Shape of the Psalms', 'Davy Ellison', 'The Gospel Coalition', 'https://www.thegospelcoalition.org/article/seeing-christ-shape-psalms/'),
      pt: ed('Vendo a Cristo na Estrutura do Livro dos Salmos', 'Davy Ellison', 'Coalizão pelo Evangelho (TGC Brasil)', 'https://coalizaopeloevangelho.org/article/vendo-a-cristo-na-estrutura-do-livro-dos-salmos/'),
      zh: ed('从《诗篇》中看到基督', 'Davy Ellison', '福音联盟 (TGC Chinese)', 'https://www.tgcchinese.org/article/seeing-christ-shape-psalms'),
    },
  },
  {
    id: 'fox-hope-darkest-psalm',
    type: 'article',
    originalLanguage: 'en',
    domains: ['bible-study'],
    topics: ['psalms', 'lament', 'grief', 'mental-health'],
    perspective: ['evangelical'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A short personal reflection on Psalm 88, which ends in darkness: it lets that ending stand and finds hope only in the God who still hears — for the day on Psalm 88.',
      fr: 'Une courte méditation personnelle sur le Psaume 88, qui se termine dans les ténèbres : elle laisse cette fin telle quelle et ne trouve l’espérance qu’en Dieu qui écoute encore — pour le jour du Psaume 88.',
    },
    editions: {
      en: ed('How I Gleaned Hope from the Darkest Psalm', 'Christina Fox', 'The Gospel Coalition', 'https://www.thegospelcoalition.org/article/how-i-gleaned-hope-from-the-darkest-psalm/'),
      pt: ed('Como Extraí Esperança do Salmo mais Escuro', 'Christina Fox', 'Coalizão pelo Evangelho (TGC Brasil)', 'https://coalizaopeloevangelho.org/article/como-extrai-esperanca-do-salmo-mais-escuro/'),
    },
  },
  {
    id: 'everingham-learning-to-lament',
    type: 'article',
    originalLanguage: 'en',
    domains: ['bible-study'],
    topics: ['psalms', 'lament', 'grief', 'prayer'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A pastor who lost his sister walks through Psalms 13, 22 and 88 to show lament’s four movements — turn to God, complain, ask, trust — and admits that Psalm 88 does not end in praise.',
      fr: 'Un pasteur qui a perdu sa sœur parcourt les Psaumes 13, 22 et 88 pour montrer les quatre mouvements de la lamentation — se tourner vers Dieu, se plaindre, demander, faire confiance — et reconnaît que le Psaume 88 ne se termine pas par la louange.',
    },
    editions: {
      en: ed('Learning to Lament: A Guide to Praying in Our Hardest Moments', 'Mitch Everingham', 'The Gospel Coalition Australia', 'https://au.thegospelcoalition.org/article/learning-to-lament-a-guide-to-praying-in-our-hardest-moments/'),
      de: ed('Klagen lernen: Wie wir in schweren Zeiten beten können', 'Mitch Everingham', 'Evangelium21', 'https://www.evangelium21.net/media/4783/klagen-lernen-wie-wir-in-schweren-zeiten-beten-koennen'),
    },
  },
  {
    id: 'godfrey-learning-to-love-the-psalms',
    type: 'book',
    originalLanguage: 'en',
    domains: ['bible-study'],
    topics: ['psalms', 'worship', 'prayer'],
    perspective: ['reformed'],
    status: 'needs_review',
    description: {
      en: 'An accessible introduction to reading and loving the Psalms — their shape, poetry and difficulties — through selected psalms such as 77 (questions in grief) and 145; the Chinese translation is free to read online.',
      fr: 'Une introduction accessible pour lire et aimer les Psaumes — leur structure, leur poésie et leurs difficultés — à travers des psaumes choisis comme le 77 (les questions du deuil) et le 145 ; la traduction chinoise se lit gratuitement en ligne.',
    },
    editions: {
      en: ed('Learning to Love the Psalms', 'W. Robert Godfrey', 'Ligonier Ministries (Reformation Trust)', 'https://store.ligonier.org/learning-to-love-the-psalms-hardcover'),
      zh: ed('爱上诗篇', 'W. Robert Godfrey（葛福雷）', 'Reformation Translation Fellowship (改革宗翻译社)', 'https://rtf-usa.com/books/learning-to-love-the-psalms/'),
    },
  },
  {
    id: 'thornton-tears-in-heaven-psalm-56',
    type: 'article',
    originalLanguage: 'en',
    domains: ['bible-study'],
    topics: ['psalms', 'lament', 'fear', 'grief'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A short study of Psalm 56 — its setting as the superscription gives it, the fear it names, and the image of God keeping our tears in his bottle — for the day on Psalm 56.',
      fr: 'Une courte étude du Psaume 56 — son cadre tel que le donne la suscription, la peur qu’il nomme, et l’image de Dieu qui recueille nos larmes dans son outre — pour le jour du Psaume 56.',
    },
    editions: {
      en: ed('Tears in Heaven (Psalm 56)', 'Angie Velasquez Thornton', 'The Gospel Coalition Canada', 'https://ca.thegospelcoalition.org/columns/femmes-scriptura/tears-in-heaven-psalm-56/'),
      zh: ed('天堂的泪水（《诗篇》56 篇）', 'Angie Velasquez Thornton', '福音联盟 (TGC Chinese)', 'https://www.tgcchinese.org/article/tears-in-heaven-psalm-56'),
    },
  },
];
