// Candidates for unbelievers30, researched 2026-09-28. NONE is approved: every entry is
// needs_review with no sign-off, so the resolver never shows it. See
// docs/resources/candidates/unbelievers30.md for the verification worksheet.
export const UNBELIEVERS30_CANDIDATES = [
  {
    id: 'operation-world-pray-today',
    type: 'prayerGuide',
    originalLanguage: 'en',
    domains: ["mission"],
    topics: ['mission', 'intercession', 'prayer'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A daily country-by-country prayer guide with facts and prayer points, for the one who wants to pray beyond their own circle for every nation.',
      fr: 'Un guide de prière quotidien, pays par pays, avec repères et sujets de prière, pour qui veut prier au-delà de son entourage pour toutes les nations.',
    },
    editions: {
      en: { title: 'Operation World — Pray Today', author: 'Operation World (founded by Patrick Johnstone)', publisher: 'Operation World, with WEC International and InterVarsity Press', url: 'https://operationworld.org/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'joshua-project-unreached-of-the-day',
    type: 'prayerGuide',
    originalLanguage: 'en',
    domains: ["mission"],
    topics: ['mission', 'intercession'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'One people group a day with a short profile, a Scripture and prayer points, so intercession for the unreached becomes concrete and regular.',
      fr: 'Un peuple par jour, avec un court portrait, un texte biblique et des sujets de prière, pour que l’intercession pour les peuples non atteints devienne concrète et régulière.',
    },
    editions: {
      en: { title: 'Unreached of the Day', author: 'Joshua Project', publisher: 'Joshua Project', url: 'https://joshuaproject.net/pray/unreachedoftheday/today', available: true, lastVerifiedAt: '2026-09-28' },
      es: { title: 'Unreached of the Day', author: 'Joshua Project', publisher: 'Joshua Project', url: 'https://unreachedoftheday.org/prayer/es/', available: true, lastVerifiedAt: '2026-09-28' },
      fr: { title: 'Unreached of the Day', author: 'Joshua Project', publisher: 'Joshua Project', url: 'https://unreachedoftheday.org/prayer/fr/', available: true, lastVerifiedAt: '2026-09-28' },
      de: { title: 'Unreached of the Day', author: 'Joshua Project', publisher: 'Joshua Project', url: 'https://unreachedoftheday.org/prayer/de/', available: true, lastVerifiedAt: '2026-09-28' },
      pt: { title: 'Unreached of the Day', author: 'Joshua Project', publisher: 'Joshua Project', url: 'https://unreachedoftheday.org/prayer/pt/', available: true, lastVerifiedAt: '2026-09-28' },
      ko: { title: 'Unreached of the Day', author: 'Joshua Project', publisher: 'Joshua Project', url: 'https://unreachedoftheday.org/prayer/ko/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'open-doors-world-watch-list',
    type: 'prayerGuide',
    originalLanguage: 'en',
    domains: ["mission"],
    topics: ['persecution', 'intercession'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'The yearly list of the fifty countries where following Jesus costs most, with country profiles and prayer requests for the persecuted church.',
      fr: 'La liste annuelle des cinquante pays où suivre Jésus coûte le plus, avec des fiches par pays et des sujets de prière pour l’Église persécutée.',
    },
    editions: {
      en: { title: 'The 2026 World Watch List', author: 'Open Doors', publisher: 'Open Doors US', url: 'https://www.opendoorsus.org/persecution/countries', available: true, lastVerifiedAt: '2026-09-28' },
      fr: { title: 'Index Mondial de Persécution des Chrétiens 2026', author: 'Portes Ouvertes', publisher: 'Portes Ouvertes (France)', url: 'https://www.portesouvertes.fr/persecution-des-chretiens/', available: true, lastVerifiedAt: '2026-09-28' },
      de: { title: 'Weltverfolgungsindex 2026', author: 'Open Doors', publisher: 'Open Doors Deutschland e.V.', url: 'https://www.opendoors.de/christenverfolgung/weltverfolgungsindex', available: true, lastVerifiedAt: '2026-09-28' },
      es: { title: 'La Lista Mundial de la Persecución 2026', author: 'Puertas Abiertas', publisher: 'Puertas Abiertas España', url: 'https://www.puertasabiertas.org/persecucion/lmp', available: true, lastVerifiedAt: '2026-09-28' },
      pt: { title: 'Países da Lista Mundial da Perseguição 2026', author: 'Portas Abertas', publisher: 'Portas Abertas (Brasil)', url: 'https://portasabertas.org.br/lista-mundial/paises-da-lista/', available: true, lastVerifiedAt: '2026-09-28' },
      ko: { title: '[2026년] 세계 기독교 박해 지수(World Watch List) 관련 자료', author: '한국오픈도어선교회', publisher: '한국오픈도어선교회 (Open Doors Korea)', url: 'https://www.opendoors.or.kr/board/view.do?iboardgroupseq=8&iboardmanagerseq=56&iboardseq=1583&irefamily=1583&ireseq=0', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'thy-kingdom-come-pray-for-five',
    type: 'prayerGuide',
    originalLanguage: 'en',
    domains: ["mission"],
    topics: ['intercession', 'friendship', 'prayer', 'evangelism'],
    perspective: ['anglican'],
    status: 'needs_review',
    description: {
      en: 'A simple habit from an ecumenical prayer movement: choose five people, write their names down and pray for them regularly, asking to be a better witness yourself.',
      fr: 'Une habitude simple venue d’un mouvement de prière œcuménique : choisir cinq personnes, noter leurs noms et prier régulièrement pour elles, en demandant soi-même à mieux témoigner.',
    },
    editions: {
      en: { title: 'Pray for Five', author: 'Thy Kingdom Come', publisher: 'Thy Kingdom Come', url: 'https://www.thykingdomcome.global/resources/pray-five-friends', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'lawrence-how-can-i-pray-for-non-christians',
    type: 'article',
    originalLanguage: 'en',
    domains: ["mission"],
    topics: ['intercession', 'prayer', 'friendship'],
    perspective: ['reformed'],
    status: 'needs_review',
    description: {
      en: 'A pastor answers whether to pray for a non-Christian friend’s job, health and relationships as well as their salvation, and leaves the answer to God’s wisdom.',
      fr: 'Un pasteur se demande s’il faut prier pour le travail, la santé et les relations d’un ami non chrétien autant que pour son salut, et remet la réponse à la sagesse de Dieu.',
    },
    editions: {
      en: { title: 'How Can I Pray for Non-Christians?', author: 'Michael Lawrence', publisher: 'Tabletalk Magazine (Ligonier Ministries)', url: 'https://tabletalkmagazine.com/article/2019/03/can-pray-non-christians/', available: true, lastVerifiedAt: '2026-09-28' },
      es: { title: '¿Cómo orar por los inconversos?', author: 'Michael Lawrence', publisher: 'Ministerios Ligonier', url: 'https://es.ligonier.org/articulos/como-orar-por-los-inconversos/', available: true, lastVerifiedAt: '2026-09-28' },
      de: { title: 'Wie kann ich für Nicht-Christen beten?', author: 'Michael Lawrence', publisher: 'Herold-Mission (translation of the Tabletalk article)', url: 'https://herold-mission.com/wie-kann-ich-fuer-nicht-christen-beten/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'pippert-out-of-the-saltshaker',
    type: 'book',
    originalLanguage: 'en',
    domains: ["mission"],
    topics: ['evangelism', 'friendship', 'gospel'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A classic on witness as a way of life, taking Jesus as the model: ordinary friendship, honest questions and sharing the good news without fear or pressure.',
      fr: 'Un classique sur le témoignage comme manière de vivre, avec Jésus pour modèle : amitié ordinaire, questions honnêtes et partage de la bonne nouvelle sans peur ni pression.',
    },
    editions: {
      en: { title: 'Out of the Saltshaker and Into the World: Evangelism as a Way of Life', author: 'Rebecca Manley Pippert', publisher: 'InterVarsity Press (IVP Signature Collection)', url: 'https://www.ivpress.com/out-of-the-saltshaker-and-into-the-world', available: true, lastVerifiedAt: '2026-09-28' },
      es: { title: 'Fuera del salero', author: 'Rebecca Manley Pippert', publisher: 'Ediciones Certeza Unida / Ediciones Puma', url: 'https://edicionespuma.org/product/fuera-del-salero-co/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'chan-evangelism-skeptical-world-course',
    type: 'teaching',
    originalLanguage: 'en',
    domains: ["mission"],
    topics: ['evangelism', 'apologetics', 'friendship'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'Free video talks by an Australian evangelist on sharing Jesus with sceptical friends through relationships, stories and honest answers.',
      fr: 'Des exposés vidéo gratuits d’un évangéliste australien sur la manière de parler de Jésus à des amis sceptiques, par la relation, les récits et des réponses honnêtes.',
    },
    editions: {
      en: { title: 'Evangelism in a Skeptical World (TGC course)', author: 'Sam Chan', publisher: 'The Gospel Coalition', url: 'https://www.thegospelcoalition.org/course/evangelism-skeptical-world/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'koukl-tactics',
    type: 'book',
    originalLanguage: 'en',
    domains: ["mission"],
    topics: ['apologetics', 'evangelism', 'listening'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'How to talk about faith by asking good questions and answering graciously, for the one who fears being drawn into arguments.',
      fr: 'Comment parler de la foi en posant de bonnes questions et en répondant avec grâce, pour qui redoute de se laisser entraîner dans des disputes.',
    },
    editions: {
      en: { title: 'Tactics, 10th Anniversary Edition: A Game Plan for Discussing Your Christian Convictions', author: 'Gregory Koukl', publisher: 'Zondervan Academic', url: 'https://zondervanacademic.com/products/tactics-10th-anniversary-edition', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'lausanne-cape-town-commitment',
    type: 'article',
    originalLanguage: 'en',
    domains: ["mission"],
    topics: ['mission', 'evangelism', 'persecution'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'The global evangelical statement on mission; its section on living the love of Christ among people of other faiths asks for ethical witness, respect and religious freedom for all.',
      fr: 'La déclaration évangélique mondiale sur la mission ; sa section sur l’amour du Christ auprès de ceux qui professent d’autres religions demande un témoignage éthique, le respect et la liberté religieuse pour tous.',
    },
    editions: {
      en: { title: 'The Cape Town Commitment', author: 'Lausanne Movement', publisher: 'Lausanne Movement', url: 'https://lausanne.org/statement/ctcommitment', available: true, lastVerifiedAt: '2026-09-28' },
      fr: { title: 'L’Engagement du Cap', author: 'Lausanne Movement', publisher: 'Lausanne Movement', url: 'https://lausanne.org/fr/statement/engagement-du-cap', available: true, lastVerifiedAt: '2026-09-28' },
      de: { title: 'Die Kapstadt-Verpflichtung', author: 'Lausanne Movement', publisher: 'Lausanne Movement', url: 'https://lausanne.org/de/statement/die-kapstadt-verpflichtung', available: true, lastVerifiedAt: '2026-09-28' },
      es: { title: 'El Compromiso de Ciudad del Cabo', author: 'Lausanne Movement', publisher: 'Lausanne Movement', url: 'https://lausanne.org/es/statement/compromiso', available: true, lastVerifiedAt: '2026-09-28' },
      pt: { title: 'Compromisso da Cidade do Cabo', author: 'Lausanne Movement', publisher: 'Lausanne Movement', url: 'https://lausanne.org/pt-br/statement/compromisso', available: true, lastVerifiedAt: '2026-09-28' },
      ru: { title: 'Посвящение из Кейптауна', author: 'Lausanne Movement', publisher: 'Lausanne Movement', url: 'https://lausanne.org/ru/statement/posvjasenie-iz-kejptauna', available: true, lastVerifiedAt: '2026-09-28' },
      zh: { title: '开普敦承诺', author: 'Lausanne Movement', publisher: 'Lausanne Movement', url: 'https://lausanne.org/zh-hans/statement/ctcommitment-zh', available: true, lastVerifiedAt: '2026-09-28' },
      ja: { title: 'ケープタウン決意表明', author: 'Lausanne Movement', publisher: 'Lausanne Movement', url: 'https://lausanne.org/ja/statement/%e3%82%b1%e3%83%bc%e3%83%97%e3%82%bf%e3%82%a6%e3%83%b3%e6%b1%ba%e6%84%8f%e8%a1%a8%e6%98%8e', available: true, lastVerifiedAt: '2026-09-28' },
      ko: { title: '케이프타운 서약 신앙고백과 행동', author: 'Lausanne Movement', publisher: 'Lausanne Movement', url: 'https://lausanne.org/ko/statement/ctcommitment-ko', available: true, lastVerifiedAt: '2026-09-28' },
      ar: { title: 'عهد كيب تاون', author: 'Lausanne Movement', publisher: 'Lausanne Movement', url: 'https://lausanne.org/ar/statement/commitment-ar', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'sgc-biblical-evangelism-and-discipleship',
    type: 'study',
    originalLanguage: 'en',
    domains: ["mission"],
    topics: ['evangelism', 'gospel', 'holy-spirit'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A free training course for church leaders on sharing the gospel, the Holy Spirit’s work in conversion, prayer and fasting, and caring for new believers.',
      fr: 'Un cours de formation gratuit pour responsables d’Église : annoncer l’Évangile, l’œuvre du Saint-Esprit dans la conversion, la prière et le jeûne, l’accompagnement des nouveaux croyants.',
    },
    editions: {
      en: { title: 'Biblical Evangelism and Discipleship', author: 'Shepherds Global Classroom', publisher: 'Shepherds Global Classroom', url: 'https://courses.shepherdsglobal.org/english/biblical-evangelism-and-discipleship', available: true, lastVerifiedAt: '2026-09-28' },
      fr: { title: 'Évangélisation Biblique et formation de disciples', author: 'Shepherds Global Classroom', publisher: 'Shepherds Global Classroom', url: 'https://courses.shepherdsglobal.org/french/biblical-evangelism-and-discipleship', available: true, lastVerifiedAt: '2026-09-28' },
      es: { title: 'Evangelismo Bíblico y discipulado', author: 'Shepherds Global Classroom', publisher: 'Shepherds Global Classroom', url: 'https://courses.shepherdsglobal.org/spanish/biblical-evangelism-and-discipleship', available: true, lastVerifiedAt: '2026-09-28' },
      pt: { title: 'Evangelismo e Discipulado Bíblico', author: 'Shepherds Global Classroom', publisher: 'Shepherds Global Classroom', url: 'https://courses.shepherdsglobal.org/portuguese/biblical-evangelism-and-discipleship', available: true, lastVerifiedAt: '2026-09-28' },
      ru: { title: 'Библейский евангелизм и ученичество', author: 'Shepherds Global Classroom', publisher: 'Shepherds Global Classroom', url: 'https://courses.shepherdsglobal.org/russian/biblical-evangelism-and-discipleship', available: true, lastVerifiedAt: '2026-09-28' },
      zh: { title: '圣经中的传福音和门徒训练', author: 'Shepherds Global Classroom', publisher: 'Shepherds Global Classroom', url: 'https://courses.shepherdsglobal.org/simplified-chinese/biblical-evangelism-and-discipleship', available: true, lastVerifiedAt: '2026-09-28' },
      ar: { title: 'الكرازة الكتابية والتلمذة', author: 'Shepherds Global Classroom', publisher: 'Shepherds Global Classroom', url: 'https://courses.shepherdsglobal.org/arabic/biblical-evangelism-and-discipleship', available: true, lastVerifiedAt: '2026-09-28' },
      hi: { title: 'बाइबल आधारित सुसमाचार का प्रचार और शिष्‍यत्‍व', author: 'Shepherds Global Classroom', publisher: 'Shepherds Global Classroom', url: 'https://courses.shepherdsglobal.org/hindi/biblical-evangelism-and-discipleship', available: true, lastVerifiedAt: '2026-09-28' },
      sw: { title: 'Uinjilisti Wa Kibiblia Na Uanafunzi', author: 'Shepherds Global Classroom', publisher: 'Shepherds Global Classroom', url: 'https://courses.shepherdsglobal.org/kiswahili/biblical-evangelism-and-discipleship', available: true, lastVerifiedAt: '2026-09-28' },
      tl: { title: 'Biblikal na Pag-eebanghelyo at Pagdidisipulo', author: 'Shepherds Global Classroom', publisher: 'Shepherds Global Classroom', url: 'https://courses.shepherdsglobal.org/tagalog/biblical-evangelism-and-discipleship', available: true, lastVerifiedAt: '2026-09-28' },
      am: { title: 'መጽሐፍ ቅዱሳዊ የወንጌል አገልግሎት እና ደቀ መዝሙርነት', author: 'Shepherds Global Classroom', publisher: 'Shepherds Global Classroom', url: 'https://courses.shepherdsglobal.org/amharic/biblical-evangelism-and-discipleship', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'kapitaniuk-prier-pour-le-salut-de-non-chretiens',
    type: 'article',
    originalLanguage: 'fr',
    domains: ["mission"],
    topics: ['intercession', 'prayer', 'gospel'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A short French article showing from Romans 10 and 1 Timothy 2 that praying for others’ salvation is biblical, while leaving the outcome to God.',
      fr: 'Un court article qui montre, à partir de Romains 10 et de 1 Timothée 2, qu’il est biblique de prier pour le salut des autres, tout en laissant l’issue à Dieu.',
    },
    editions: {
      fr: { title: 'Est-ce biblique de prier pour le salut de non-chrétiens ?', author: 'Stéphane Kapitaniuk', publisher: 'Toutpoursagloire.com', url: 'https://toutpoursagloire.com/article/prier-pour-le-salut-de-non-chretiens/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'thirty-days-prayer-muslim-world',
    type: 'prayerGuide',
    originalLanguage: 'en',
    domains: ["mission"],
    topics: ['mission', 'intercession', 'evangelism'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A yearly guide with a short story and prayer points for each day of Ramadan, to pray with love for Muslim neighbours and peoples around the world.',
      fr: 'Un livret annuel avec un court récit et des sujets de prière pour chaque jour du Ramadan, pour prier avec amour pour nos voisins et les peuples musulmans du monde.',
    },
    editions: {
      en: { title: '30 Days of Prayer for the Muslim World', author: '30 Days of Prayer', publisher: '30 Days of Prayer (pray30days.org)', url: 'https://www.pray30days.org/', available: true, lastVerifiedAt: '2026-09-28' },
      fr: { title: '30 jours de prière pour le monde musulman', author: '30 jours', publisher: '30 jours (30jours.org)', url: 'https://www.30jours.org/', available: true, lastVerifiedAt: '2026-09-28' },
      de: { title: '30 Tage Gebet für die Islamische Welt', author: '30 Tage Gebet', publisher: 'Evangelische Allianz in Deutschland e.V.', url: 'https://www.30tagegebet.de/', available: true, lastVerifiedAt: '2026-09-28' },
      es: { title: '30 Días de Oración por el Mundo Musulmán', author: '30 Days of Prayer', publisher: '30 Days of Prayer (pray30days.org)', url: 'https://www.pray30days.org/spanish', available: true, lastVerifiedAt: '2026-09-28' },
      ko: { title: '무슬림을 위한 30일 기도운동', author: '무슬림을 위한 30일 기도운동', publisher: '무슬림을 위한 30일 기도운동 (pray30days.kr)', url: 'https://www.pray30days.kr/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'kalameh-basharat-ya-feshar',
    type: 'article',
    originalLanguage: 'fa',
    domains: ["mission"],
    topics: ['evangelism', 'friendship', 'listening'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A Persian article on sharing the good news without pressure: compassion, a consistent life, friendship and respectful conversation instead of attacking other beliefs.',
      fr: 'Un article en persan sur l’annonce de la bonne nouvelle sans pression : compassion, vie cohérente, amitié et dialogue respectueux plutôt que l’attaque des autres croyances.',
    },
    editions: {
      fa: { title: 'بشارت یا فشارت/بخش اول', author: 'Kalameh (کلمه)', publisher: 'Kalameh — Elam Ministries (خدمات ایلام)', url: 'https://www.kalameh.com/article/%D8%A8%D8%B4%D8%A7%D8%B1%D8%AA-%DB%8C%D8%A7-%D9%81%D8%B4%D8%A7%D8%B1%D8%AA%D8%A8%D8%AE%D8%B4-%D8%A7%D9%88%D9%84', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'gotquestions-evangelize-friends-family',
    type: 'article',
    originalLanguage: 'en',
    domains: ["mission"],
    topics: ['evangelism', 'family', 'friendship'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A short answer on speaking of Jesus to friends and relatives: pray first, live consistently, share with gentleness and respect, and leave the outcome to God.',
      fr: 'Une courte réponse sur la manière de parler de Jésus à ses amis et à ses proches : prier d’abord, vivre de façon cohérente, partager avec douceur et respect, et laisser l’issue à Dieu.',
    },
    editions: {
      en: { title: 'How can I evangelize my friends and family without pushing them away?', author: 'Got Questions Ministries', publisher: 'GotQuestions.org', url: 'https://www.gotquestions.org/evangelize-friends-family.html', available: true, lastVerifiedAt: '2026-09-28' },
      es: { title: '¿Cómo puedo evangelizar a mis amigos y familiares sin ofenderlos o alejarlos?', author: 'Got Questions Ministries', publisher: 'GotQuestions.org/Espanol', url: 'https://www.gotquestions.org/Espanol/evangelizar-amigos-familia.html', available: true, lastVerifiedAt: '2026-09-28' },
      pt: { title: 'Como posso evangelizar meus amigos e membros da família sem ofendê-los ou afastá-los?', author: 'Got Questions Ministries', publisher: 'GotQuestions.org/Portugues', url: 'https://www.gotquestions.org/Portugues/evangelizar-amigos-familia.html', available: true, lastVerifiedAt: '2026-09-28' },
      id: { title: 'Bagaimana saya dapat menginjili teman-teman dan keluarga saya tanpa menyinggung atau membuat mereka menjauh?', author: 'Got Questions Ministries', publisher: 'GotQuestions.org/Indonesia', url: 'https://www.gotquestions.org/Indonesia/menginjili-teman-keluarga.html', available: true, lastVerifiedAt: '2026-09-28' },
      fa: { title: 'چطور می توانیم به دوستان و خانواده خود بشارت بدهیم بدون اینکه آنها از خود دور کنیم؟', author: 'Got Questions Ministries', publisher: 'GotQuestions.org/Farsi', url: 'https://www.gotquestions.org/Farsi/Farsi-evangelize.html', available: true, lastVerifiedAt: '2026-09-28' },
      // Editions below added by the completion run (2026-09-28): each page opened,
      // localized title and body, each links back to the English original.
      ru: { title: 'Как я могу евангелизировать своих друзей и семью, чтобы не оскорбить и не оттолкнуть их?', author: 'Got Questions Ministries', publisher: 'GotQuestions.org/Russian', url: 'https://www.gotquestions.org/Russian/Russian-evangelize-family.html', available: true, lastVerifiedAt: '2026-09-28' },
      zh: { title: '我如何在不冒犯朋友和家人的情况下向他们宣讲福音？', author: 'Got Questions Ministries', publisher: 'GotQuestions.org/Chinese', url: 'https://www.gotquestions.org/Chinese/Chinese-evangelism.html', available: true, lastVerifiedAt: '2026-09-28' },
      ja: { title: '友達や家族の気を害したり、遠ざけたりすることなく、福音伝道するにはどうしたらいいでしょうか？', author: 'Got Questions Ministries', publisher: 'GotQuestions.org/Japanese', url: 'https://www.gotquestions.org/Japanese/Japanese-evangelize.html', available: true, lastVerifiedAt: '2026-09-28' },
      ar: { title: 'كيف أبشِّر أصدقائي وعائلتي دون أن أضايقهم أو أخسرهم؟', author: 'Got Questions Ministries', publisher: 'GotQuestions.org/Arabic', url: 'https://www.gotquestions.org/Arabic/Arabic-evangelize.html', available: true, lastVerifiedAt: '2026-09-28' },
      hi: { title: 'मैं कैसे बिना ठेस पहुँचाए और अपमानजनक तरीके से अपने मित्रों और परिवार के सदस्यों को सुसमाचार प्रचार कर सकता हूँ?', author: 'Got Questions Ministries', publisher: 'GotQuestions.org/Hindi', url: 'https://www.gotquestions.org/Hindi/Hindi-evangelize.html', available: true, lastVerifiedAt: '2026-09-28' },
      sw: { title: 'Nitawezaje kuwahubiria marafiki na jamii yangu bila kuwakashirisha au kuwafukuza mbali?', author: 'Got Questions Ministries', publisher: 'GotQuestions.org/Kiswahili', url: 'https://www.gotquestions.org/Kiswahili/kuhubiria-marafiki-jamii.html', available: true, lastVerifiedAt: '2026-09-28' },
      tl: { title: 'Papaano ko maituturo ang Ebanghelyo sa aking mga kapatid at kasambahay na hindi sila magagalit, masasaktan, o maitutulak na papalayo?', author: 'Got Questions Ministries', publisher: 'GotQuestions.org/Tagalog', url: 'https://www.gotquestions.org/Tagalog/Ituro-ang-Ebanghelyo.html', available: true, lastVerifiedAt: '2026-09-28' },
      am: { title: 'ባልንጀሮቼንና የቤተሰቤን አባላት በወንጌል እንዴት ልደርስ እችላለሁ፣ ሳላስቀይማቸውና ሳልገፋቸው?', author: 'Got Questions Ministries', publisher: 'GotQuestions.org/Amharic', url: 'https://www.gotquestions.org/Amharic/Amharic-evangelize.html', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'challies-18-prayers-for-unbelievers',
    type: 'prayerGuide',
    originalLanguage: 'en',
    domains: ["mission"],
    topics: ['intercession', 'prayer', 'evangelism'],
    perspective: ['reformed'],
    status: 'needs_review',
    description: {
      en: 'Eighteen short prayers drawn from Scripture: for the person who does not yet believe, for the one who prays and witnesses, and for patience in praying.',
      fr: 'Dix-huit courtes prières tirées de l’Écriture : pour la personne qui ne croit pas encore, pour celui qui prie et témoigne, et pour la persévérance dans la prière.',
    },
    editions: {
      en: { title: '18 Prayers to Pray for Unbelievers', author: 'Tim Challies', publisher: 'challies.com', url: 'https://www.challies.com/articles/how-to-pray-for-unbelievers/', available: true, lastVerifiedAt: '2026-09-28' },
      pt: { title: '18 orações para orar por incrédulos', author: 'Tim Challies', publisher: 'Voltemos ao Evangelho (translation via Ministério Fiel)', url: 'https://voltemosaoevangelho.com/blog/2016/12/18-oracoes-para-orar-por-incredulos/', available: true, lastVerifiedAt: '2026-09-28' },
      zh: { title: '十八种为未信主的朋友祷告的方式', author: 'Tim Challies（提姆·查理斯）', publisher: '福音联盟 (The Gospel Coalition Chinese), tr. 杨忠道', url: 'https://www.tgcchinese.org/article/how-to-pray-for-unbelievers', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'perez-relacionarme-con-un-no-creyente',
    type: 'article',
    originalLanguage: 'es',
    domains: ["mission"],
    topics: ['friendship', 'evangelism', 'hospitality'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A Spanish-language pastor confesses seeing a colleague only as someone to evangelise, and calls for real interest in the whole person.',
      fr: 'Un pasteur hispanophone reconnaît n’avoir vu un collègue que comme quelqu’un à évangéliser, et appelle à s’intéresser vraiment à toute la personne.',
    },
    editions: {
      es: { title: '¿Cómo debo relacionarme con un no creyente?', author: 'Ramny Pérez', publisher: 'Coalición por el Evangelio', url: 'https://www.coalicionporelevangelio.org/articulo/como-debo-relacionarme-con-un-no-creyente/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'ando-inorarete-shu-no-waza-wo-miru',
    type: 'article',
    originalLanguage: 'ja',
    domains: ['mission'],
    topics: ['intercession', 'prayer-together', 'family', 'trust'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A Japanese Christian educator admits she had quietly given up praying for her family, asked her church to pray with her, and learned to trust God’s love for them.',
      fr: 'Une éducatrice chrétienne japonaise avoue avoir cessé de prier pour sa famille, demande à son Église de prier avec elle et réapprend à se fier à l’amour de Dieu pour les siens.',
    },
    editions: {
      ja: { title: '祈られて、主の業を見る', author: '安藤理恵子（玉川聖学院 学院長）', publisher: '種まき（いのちのことば社）', url: 'https://www.wlpm.or.jp/tanemaki/2022/12/lead/top-202301/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
];
