// Candidates for unborn21, researched 2026-09-28. NONE is approved: every entry is
// needs_review with no sign-off, so the resolver never shows it. See
// docs/resources/candidates/unborn21.md for the verification worksheet.
export const UNBORN21_CANDIDATES = [
  {
    id: 'hutto-inheritance-of-tears',
    type: 'book',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['miscarriage', 'lament', 'grief'],
    perspective: ['evangelical'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A short book by a mother who lost two babies in the womb, bringing the grief of miscarriage to Scripture and to Christ without pat answers.',
      fr: 'Un court livre d’une mère qui a perdu deux bébés pendant la grossesse : il porte le deuil d’une fausse couche devant l’Écriture et devant le Christ, sans réponses toutes faites. En anglais.',
    },
    editions: {
      en: { title: 'Inheritance of Tears: Trusting the Lord of Life When Death Visits the Womb', author: 'Jessalyn Hutto', publisher: 'Cruciform Press', url: 'https://www.cruciformpress.com/product/inheritance-of-tears/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'booker-grace-like-scarlett',
    type: 'book',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['miscarriage', 'lament', 'grief'],
    perspective: ['evangelical'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A memoir of three consecutive miscarriages that makes room for honest questions about faith and suffering, with practical help for fathers, siblings and pregnancy after loss.',
      fr: 'Le récit de trois fausses couches successives, qui laisse place aux questions honnêtes sur la foi et la souffrance, avec des conseils pratiques pour les pères, les frères et sœurs et une grossesse après une perte. En anglais.',
    },
    editions: {
      en: { title: 'Grace Like Scarlett', author: 'Adriel Booker', publisher: 'Baker Books (Baker Publishing Group)', url: 'https://bakerpublishinggroup.com/products/9780801075810_grace-like-scarlett', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'furman-labor-with-hope',
    type: 'book',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['pregnancy', 'fear'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'Twenty-five short gospel meditations on pregnancy, childbirth and early motherhood that speak honestly about fear and discouragement, and also touch on infertility and miscarriage.',
      fr: 'Vingt-cinq courtes méditations sur la grossesse, l’accouchement et les débuts de la maternité à la lumière de l’Évangile, qui parlent franchement de la peur et du découragement, et abordent aussi l’infertilité et la fausse couche. En anglais.',
    },
    editions: {
      en: { title: 'Labor with Hope: Gospel Meditations on Pregnancy, Childbirth, and Motherhood', author: 'Gloria Furman (with Jesse Scheumann)', publisher: 'Crossway', url: 'https://www.crossway.org/books/labor-with-hope-tpb/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'swanson-pregnancy-can-be-scary',
    type: 'article',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['pregnancy', 'fear', 'psalms'],
    perspective: ['reformed'],
    status: 'needs_review',
    description: {
      en: 'A short article on praying Psalm 139 through the worries of pregnancy — turning anxious late-night searching into honest prayer to the God who sees the child we cannot.',
      fr: 'Un court article pour prier le Psaume 139 au milieu des inquiétudes de la grossesse : transformer les recherches anxieuses de la nuit en prière sincère au Dieu qui voit l’enfant que nous ne voyons pas. En anglais.',
    },
    editions: {
      en: { title: 'Pregnancy Can Be Scary: Finding Peace While Expecting', author: 'Tanner Kay Swanson', publisher: 'Desiring God', url: 'https://www.desiringgod.org/articles/pregnancy-can-be-scary', available: true, lastVerifiedAt: '2026-09-28' },
      pt: { title: 'Encontrando paz durante a gravidez', author: 'Tanner Swanson', publisher: 'Voltemos ao Evangelho (tradução de Desiring God)', url: 'https://voltemosaoevangelho.com/blog/2024/05/encontrando-paz-durante-a-gravidez/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'polimino-praying-through-your-pregnancy',
    type: 'prayerGuide',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['pregnancy', 'fear'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A week-by-week prayer companion for pregnancy that pairs each stage of the baby’s development with Scripture, prayers for the child and space to bring worries to God.',
      fr: 'Un compagnon de prière semaine après semaine pendant la grossesse, qui associe chaque étape du développement du bébé à l’Écriture, à des prières pour l’enfant et à un espace pour confier ses inquiétudes à Dieu. En anglais.',
    },
    editions: {
      en: { title: 'Praying Through Your Pregnancy', author: 'Jennifer Polimino and Carolyn Warren', publisher: 'Revell (Baker Publishing Group)', url: 'https://bakerpublishinggroup.com/products/9780800746018_praying-through-your-pregnancy', available: true, lastVerifiedAt: '2026-09-28' },
      de: { title: 'Beten für mein Baby: Geistliche und praktische Impulse für werdende Mütter', author: 'Jennifer Polimino, Carolyn Warren', publisher: 'cap-books', url: 'https://www.cap-music.de/buecher/frauen/1157/beten-fuer-mein-baby-buch-jennifer-polimino-carolyn-warren/0/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'butler-postpartum-depression-christian',
    type: 'article',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['mental-health', 'suffering'],
    perspective: ['evangelical'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A Christian physician explains the signs of postpartum depression, says plainly that it is not a mother’s fault or a failure of faith, and urges seeing a doctor and letting the church help.',
      fr: 'Une médecin chrétienne décrit les signes de la dépression post-partum, affirme clairement qu’elle n’est ni la faute de la mère ni un échec de la foi, et encourage à consulter un médecin et à accepter l’aide de l’Église. En anglais, portugais et chinois.',
    },
    editions: {
      en: { title: 'Postpartum Depression and the Christian', author: 'Kathryn Butler', publisher: 'The Gospel Coalition', url: 'https://www.thegospelcoalition.org/article/postpartum-depression-christian/', available: true, lastVerifiedAt: '2026-09-28' },
      pt: { title: 'Depressão Pós-Parto e o Cristão', author: 'Kathryn Butler (trad. Giovanna Braz dos S. Garotti)', publisher: 'Coalizão pelo Evangelho (TGC Brasil)', url: 'https://coalizaopeloevangelho.org/article/depressao-pos-parto-e-o-cristao/', available: true, lastVerifiedAt: '2026-09-28' },
      zh: { title: '产后抑郁和基督徒', author: '凯瑟琳·巴特勒 (Kathryn Butler)', publisher: '福音联盟中文版 (The Gospel Coalition Chinese)', url: 'https://www.tgcchinese.org/article/postpartum-depression-christian', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'brisley-medication-postpartum-depression',
    type: 'article',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['mental-health', 'suffering'],
    perspective: ['evangelical'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A mother’s account of postpartum depression — prayer, church support and her doctor together — and why Christians are free to accept medical treatment without shame.',
      fr: 'Le témoignage d’une mère sur sa dépression post-partum — la prière, le soutien de l’Église et son médecin ensemble — et sur la liberté des chrétiens d’accepter un traitement médical sans honte. En anglais.',
    },
    editions: {
      en: { title: 'Medication for Postpartum Depression Is God’s Good Gift', author: 'Winfree Brisley', publisher: 'The Gospel Coalition', url: 'https://www.thegospelcoalition.org/article/medication-postpartum-depression/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'brisley-verses-dont-enjoy-motherhood',
    type: 'article',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['scripture-prayer'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'Four short passages — among them Psalm 121 and James 1:5 — turned into prayers for the tired, unglamorous early days of caring for a baby.',
      fr: 'Quatre courts passages — dont le Psaume 121 et Jacques 1.5 — transformés en prières pour les premiers temps, fatigants et sans éclat, où l’on prend soin d’un bébé.',
    },
    editions: {
      en: { title: '4 Verses to Pray When You Don’t Enjoy Motherhood', author: 'Winfree Brisley', publisher: 'The Gospel Coalition', url: 'https://www.thegospelcoalition.org/article/verses-dont-enjoy-motherhood/', available: true, lastVerifiedAt: '2026-09-28' },
      fr: { title: '4 versets pouvant inspirer vos prières quand votre maternité devient pesante', author: 'Winfree Brisley', publisher: 'Évangile 21 (The Gospel Coalition, édition française)', url: 'https://evangile21.thegospelcoalition.org/article/4-versets-pouvant-inspirer-vos-prieres-quand-votre-maternite-devient-pesante/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'wunnenberg-grieving-child-never-knew',
    type: 'book',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['miscarriage', 'lament', 'grief'],
    perspective: ['evangelical'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A devotional companion for parents after miscarriage, stillbirth or the death of a newborn, with Scripture, prayers and gentle questions for grieving honestly before God.',
      fr: 'Un compagnon de méditation pour les parents après une fausse couche, une mort in utero ou le décès d’un nouveau-né, avec des passages bibliques, des prières et des questions douces pour porter son deuil devant Dieu en vérité. En anglais.',
    },
    editions: {
      en: { title: 'Grieving the Child I Never Knew', author: 'Kathe Wunnenberg', publisher: 'Zondervan (sold by Focus on the Family)', url: 'https://store.focusonthefamily.com/grieving-the-child-i-never-knew/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'mcclure-consuelo-perdida-embarazo',
    type: 'article',
    originalLanguage: 'es',
    domains: ['relationships'],
    topics: ['miscarriage', 'grief', 'lament'],
    perspective: ['evangelical'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A pastoral article on the grief of pregnancy loss: grief is love, not sin; a mother is not to blame; and God’s comfort meets parents in their sorrow. In Spanish.',
      fr: 'Un article pastoral sur le deuil d’une grossesse perdue : le chagrin est de l’amour, non un péché ; la mère n’est pas coupable ; et la consolation de Dieu rejoint les parents dans leur peine. En espagnol.',
    },
    editions: {
      es: { title: 'El consuelo de Dios en la pérdida de un embarazo', author: 'Craig McClure', publisher: 'Coalición por el Evangelio', url: 'https://www.coalicionporelevangelio.org/articulo/el-consuelo-de-dios-en-la-perdida-de-un-embarazo/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'sabatier-consolar-casal-aborto-espontaneo',
    type: 'article',
    originalLanguage: 'pt',
    domains: ['relationships'],
    topics: ['miscarriage', 'grief', 'lament'],
    perspective: ['reformed'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A Brazilian father who lost a baby in early pregnancy shares three simple ways friends and church can stand with a grieving couple — starting with the freedom to weep before God. In Portuguese.',
      fr: 'Un père brésilien qui a perdu un bébé en début de grossesse partage trois façons simples, pour les amis et l’Église, d’entourer un couple en deuil — à commencer par la liberté de pleurer devant Dieu. En portugais.',
    },
    editions: {
      pt: { title: 'Como consolar um casal após um aborto espontâneo', author: 'Lucas Sabatier', publisher: 'Voltemos ao Evangelho', url: 'https://voltemosaoevangelho.com/blog/2025/06/como-consolar-um-casal-apos-um-aborto-espontaneo/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'lessa-consolo-gestante',
    type: 'article',
    originalLanguage: 'pt',
    domains: ['relationships'],
    topics: ['pregnancy'],
    perspective: ['reformed'],
    status: 'needs_review',
    description: {
      en: 'An Angolan writer, expecting her first child, reflects on the tiredness of pregnancy and the feeling of being useless, and finds rest in God’s quiet work in a limited body. In Portuguese.',
      fr: 'Une auteure angolaise, enceinte de son premier enfant, médite sur la fatigue de la grossesse et le sentiment d’inutilité, et trouve le repos dans l’œuvre discrète de Dieu au sein d’un corps limité. En portugais.',
    },
    editions: {
      pt: { title: 'Consolo a uma gestante', author: 'Prisca Lessa', publisher: 'Voltemos ao Evangelho', url: 'https://voltemosaoevangelho.com/blog/2021/05/consolo-a-uma-gestante/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'knodel-bin-kaum-da-muss-schon-fort',
    type: 'article',
    originalLanguage: 'de',
    domains: ['relationships'],
    topics: ['miscarriage', 'grief', 'lament'],
    perspective: ['evangelical'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A mother after a stillbirth and a father after a miscarriage tell honestly how they grieved — anger and bewilderment included — and how naming, farewell and faith helped. In German.',
      fr: 'Une mère après une mort in utero et un père après une fausse couche racontent sincèrement leur deuil — colère et désarroi compris — et comment nommer l’enfant, lui dire adieu et la foi les ont aidés. En allemand.',
    },
    editions: {
      de: { title: 'Bin kaum da, muss schon fort', author: 'Patricia Knodel, Erich Koslowski', publisher: 'ERF (Evangeliums-Rundfunk)', url: 'https://www.erf.de/lesen/themen/glaube/bin-kaum-da-muss-schon-fort/2803-542-3787', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'gibson-gods-comfort-loss-of-child',
    type: 'article',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['miscarriage', 'grief', 'lament'],
    perspective: ['reformed'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A mother whose daughter was stillborn a week before her due date finds comfort in Jesus who cares, weeps at death and has overcome it — without promising another child or a tidy answer.',
      fr: 'Une mère dont la fille est morte in utero une semaine avant le terme trouve du réconfort en Jésus, qui prend soin, pleure devant la mort et l’a vaincue — sans promettre un autre enfant ni une réponse toute faite.',
    },
    editions: {
      en: { title: 'God’s Comfort in the Loss of a Child', author: 'Jackie Gibson', publisher: 'Ligonier Ministries', url: 'https://learn.ligonier.org/articles/gods-comfort-in-the-loss-of-a-child', available: true, lastVerifiedAt: '2026-09-28' },
      ko: { title: '자녀를 잃은 슬픔에 임하는 하나님의 위로', author: '재키 깁슨 (Jackie Gibson)', publisher: '리고니어 미니스트리 (Ligonier Ministries)', url: 'https://ko.ligonier.org/blog/articles/gods-comfort-in-the-loss-of-a-child/', available: true, lastVerifiedAt: '2026-09-28' },
      zh: { title: '上帝在失去孩子时的安慰', author: 'Jackie Gibson', publisher: '林格尼尔福音事工 (Ligonier Ministries)', url: 'https://zh.ligonier.org/articles/gods-comfort-in-the-loss-of-a-child/', available: true, lastVerifiedAt: '2026-09-28' },
      ja: { title: 'わが子を失ったときの神の慰め', author: 'ジャッキー・ギブソン (Jackie Gibson)', publisher: 'リゴニア・ミニストリーズ (Ligonier Ministries)', url: 'https://ja.ligonier.org/blog/tabletalk/gods-comfort-in-the-loss-of-a-child/', available: true, lastVerifiedAt: '2026-09-28' },
      id: { title: 'Penghiburan Allah ketika Kehilangan Seorang Anak', author: 'Jackie Gibson', publisher: 'Pelayanan Ligonier (Ligonier Ministries)', url: 'https://id.ligonier.org/articles/gods-comfort-in-the-loss-of-a-child/', available: true, lastVerifiedAt: '2026-09-28' },
      hi: { title: 'बच्चे के खोने में परमेश्वर की सान्त्वना', author: 'जैकी गिबसन (Jackie Gibson)', publisher: 'लिग्निएर मिनिस्ट्रीज़ (Ligonier Ministries)', url: 'https://hi.ligonier.org/articles/gods-comfort-in-the-loss-of-a-child/', available: true, lastVerifiedAt: '2026-09-28' },
      sw: { title: 'Faraja ya Mungu Katika Kumpoteza Mtoto', author: 'Jackie Gibson', publisher: 'Huduma za Ligonier (Ligonier Ministries)', url: 'https://sw.ligonier.org/articles/gods-comfort-in-the-loss-of-a-child/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'singh-miscarriage-pregnancy-loss-love-of-god',
    type: 'article',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['miscarriage', 'grief', 'lament'],
    perspective: ['evangelical'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'An Indian couple in Delhi tell honestly of repeated pregnancy losses — grief that has not fully passed, shame replaced by the care of their church, and a hope in God that grew stronger than the pain.',
      fr: 'Un couple indien de Delhi raconte sincèrement plusieurs grossesses perdues — un chagrin qui n’a pas entièrement disparu, une honte remplacée par le soin de leur Église, et une espérance en Dieu devenue plus forte que la douleur. En anglais et en chinois.',
    },
    editions: {
      en: { title: 'Miscarriage, Pregnancy Loss, and the Love of God', author: 'Joy and Janice Singh', publisher: 'The Gospel Coalition India', url: 'https://in.thegospelcoalition.org/article/miscarriage-pregnancy-loss-and-the-love-of-god/', available: true, lastVerifiedAt: '2026-09-28' },
      zh: { title: '在失去中得着', author: '乔伊·辛格、珍妮丝·辛格 (Joy and Janice Singh)', publisher: '福音联盟中文版 (The Gospel Coalition Chinese)', url: 'https://www.tgcchinese.org/article/miscarriage-pregnancy-loss-and-the-love-of-god', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'carlson-sharing-painful-loss-miscarriage',
    type: 'article',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['miscarriage', 'grief'],
    perspective: ['evangelical'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A mother explains why speaking about a miscarriage, instead of grieving alone, lets the church see the loss, carry the burden and learn to care for other bereaved parents.',
      fr: 'Une mère explique pourquoi parler d’une fausse couche, plutôt que de porter son deuil seule, permet à l’Église de voir la perte, de porter le fardeau et d’apprendre à prendre soin d’autres parents endeuillés. En anglais et en chinois.',
    },
    editions: {
      en: { title: 'Sharing the Painful Loss of Miscarriage', author: 'Jamie Carlson', publisher: 'The Gospel Coalition', url: 'https://www.thegospelcoalition.org/article/sharing-the-painful-loss-of-miscarriage/', available: true, lastVerifiedAt: '2026-09-28' },
      zh: { title: '分享流产给你带来的痛苦', author: '杰米·卡尔森 (Jamie Carlson)', publisher: '福音联盟中文版 (The Gospel Coalition Chinese)', url: 'https://www.tgcchinese.org/article/sharing-the-painful-loss-of-miscarriage', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'allen-psalms-lamenting-miscarriage',
    type: 'article',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['miscarriage', 'lament'],
    perspective: ['evangelical'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'Six short psalm passages that give words to the tears, silence and loneliness of miscarriage, so grief can be brought to God as honest lament.',
      fr: 'Six courts passages des Psaumes qui donnent des mots aux larmes, au silence et à la solitude d’une fausse couche, pour porter le deuil devant Dieu comme une lamentation sincère. En anglais.',
    },
    editions: {
      en: { title: '6 Psalms for Lamenting Miscarriage', author: 'Brittany Allen', publisher: 'The Gospel Coalition', url: 'https://www.thegospelcoalition.org/article/6-psalms-lamenting-miscarriage/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'gotquestions-miscarriage-bible',
    type: 'article',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['miscarriage', 'grief'],
    perspective: ['evangelical'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A short Bible Q&A for parents asking “why?” after a miscarriage: God does not take a child as punishment, most losses have medical causes, and he grieves with those who grieve.',
      fr: 'Une courte réponse biblique pour les parents qui demandent « pourquoi ? » après une fausse couche : Dieu ne reprend pas un enfant pour punir, la plupart des pertes ont des causes médicales, et il pleure avec ceux qui pleurent.',
    },
    editions: {
      en: { title: 'What does the Bible say about miscarriage?', author: 'Got Questions Ministries', publisher: 'Got Questions Ministries', url: 'https://www.gotquestions.org/miscarriage-Bible.html', available: true, lastVerifiedAt: '2026-09-28' },
      fr: { title: 'Que dit la Bible des fausses couches ?', author: 'Got Questions Ministries', publisher: 'Got Questions Ministries', url: 'https://www.gotquestions.org/Francais/fausse-couche-Bible.html', available: true, lastVerifiedAt: '2026-09-28' },
      de: { title: 'Was sagt die Bibel über Fehlgeburten?', author: 'Got Questions Ministries', publisher: 'Got Questions Ministries', url: 'https://www.gotquestions.org/Deutsch/Fehlgeburt-Bibel.html', available: true, lastVerifiedAt: '2026-09-28' },
      es: { title: '¿Qué dice la Biblia sobre el aborto espontáneo?', author: 'Got Questions Ministries', publisher: 'Got Questions Ministries', url: 'https://www.gotquestions.org/Espanol/aborto-espontaneo-Biblia.html', available: true, lastVerifiedAt: '2026-09-28' },
      id: { title: 'Apa yang Alkitab nyatakan mengenai keguguran?', author: 'Got Questions Ministries', publisher: 'Got Questions Ministries', url: 'https://www.gotquestions.org/Indonesia/keguguran-menurut-Alkitab.html', available: true, lastVerifiedAt: '2026-09-28' },
      ru: { title: 'Что Библия говорит о выкидыше?', author: 'Got Questions Ministries', publisher: 'Got Questions Ministries', url: 'https://www.gotquestions.org/Russian/Russian-miscarriage-Bible.html', available: true, lastVerifiedAt: '2026-09-28' },
      ar: { title: 'ماذا يقول الكتاب المقدس عن الإجهاض؟', author: 'Got Questions Ministries', publisher: 'Got Questions Ministries', url: 'https://www.gotquestions.org/Arabic/Arabic-miscarriage-Bible.html', available: true, lastVerifiedAt: '2026-09-28' },
      fa: { title: 'کتاب مقدس در مورد سقط جنین خودبه خودی (غیرعمدی) چه می گوید؟', author: 'Got Questions Ministries', publisher: 'Got Questions Ministries', url: 'https://www.gotquestions.org/Farsi/Farsi-miscarriage-Bible.html', available: true, lastVerifiedAt: '2026-09-28' },
      hi: { title: 'बाइबल गर्भ गिरने के बारे में क्या कहती है?', author: 'Got Questions Ministries', publisher: 'Got Questions Ministries', url: 'https://www.gotquestions.org/Hindi/Hindi-miscarriage-Bible.html', available: true, lastVerifiedAt: '2026-09-28' },
      ja: { title: '聖書には流産についてなんと書いてありますか？', author: 'Got Questions Ministries', publisher: 'Got Questions Ministries', url: 'https://www.gotquestions.org/Japanese/Japanese-miscarriage-Bible.html', available: true, lastVerifiedAt: '2026-09-28' },
      ko: { title: '성경은 유산에 대해서 무엇을 말씀하시나요?', author: 'Got Questions Ministries', publisher: 'Got Questions Ministries', url: 'https://www.gotquestions.org/Korean/Korean-miscarriage-Bible.html', available: true, lastVerifiedAt: '2026-09-28' },
      tl: { title: 'Ano ang sinasabi ng Bibliya tungkol sa pagka-agas ng sanggol?', author: 'Got Questions Ministries', publisher: 'Got Questions Ministries', url: 'https://www.gotquestions.org/Tagalog/agas-makunan-bibliya.html', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'kraus-beremennost-i-poterya-rebenka',
    type: 'article',
    originalLanguage: 'ru',
    domains: ['relationships'],
    topics: ['miscarriage', 'grief'],
    perspective: ['orthodox'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'Gentle, practical counsel from an Orthodox priest’s wife on standing with parents after miscarriage, stillbirth or newborn death — what to say, what not to say, and why Christians may weep as Jesus wept. In Russian.',
      fr: 'Des conseils doux et concrets, par l’épouse d’un prêtre orthodoxe, pour entourer des parents après une fausse couche, une mort in utero ou le décès d’un nouveau-né — quoi dire, quoi éviter, et pourquoi les chrétiens peuvent pleurer comme Jésus a pleuré. En russe.',
    },
    editions: {
      ru: { title: 'Беременность и потеря ребенка', author: 'Деннис Краус', publisher: 'Правмир (Pravmir)', url: 'https://www.pravmir.ru/beremennost-i-poterya-rebenka/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'howard-pregnant-in-a-pandemic',
    type: 'article',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['pregnancy', 'fear'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'Written weeks before a due date when birth plans fell apart, it models casting anxiety on the Lord again and again, praying for the doctors and midwives, and trusting God without being promised an outcome.',
      fr: 'Écrit quelques semaines avant un terme, quand les projets d’accouchement s’effondraient, il montre comment remettre son anxiété au Seigneur encore et encore, prier pour les médecins et les sages-femmes, et faire confiance à Dieu sans qu’une issue soit promise. En anglais et en espagnol.',
    },
    editions: {
      en: { title: 'Pregnant in a Pandemic: Coping and Hoping', author: 'Betsy Childs Howard', publisher: 'The Gospel Coalition', url: 'https://www.thegospelcoalition.org/article/pregnant-in-pandemic/', available: true, lastVerifiedAt: '2026-09-28' },
      es: { title: 'El embarazo en la pandemia', author: 'Betsy Childs', publisher: 'Coalición por el Evangelio', url: 'https://www.coalicionporelevangelio.org/articulo/el-embarazo-en-la-pandemia/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'mame-meditations-au-fil-de-ma-grossesse',
    type: 'book',
    originalLanguage: 'fr',
    domains: ['relationships'],
    topics: ['pregnancy'],
    perspective: ['catholic'],
    status: 'needs_review',
    description: {
      en: 'A week-by-week pregnancy companion: each double page pairs the baby’s stage of growth with a Bible verse, a small practical step and a word to say to the child and to God, with closing prayers for hard days, siblings and the father. In French; Catholic.',
      fr: 'Un compagnon de grossesse semaine après semaine : chaque double page associe l’étape de croissance du bébé à un verset biblique, à un petit geste concret et à une parole à adresser à l’enfant et à Dieu, avec des prières finales pour les jours difficiles, les frères et sœurs et le papa. D’inspiration catholique.',
    },
    editions: {
      fr: { title: 'Méditations au fil de ma grossesse', author: 'Auteur non indiqué par l’éditeur (préface des Petites Sœurs des Maternités Catholiques)', publisher: 'Mame', url: 'https://www.mameeditions.com/9782728927975-meditations-au-fil-de-ma-grossesse.html', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'tombrella-dads-paternity-leave',
    type: 'article',
    originalLanguage: 'en',
    domains: ['relationships'],
    topics: ['pregnancy'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'For fathers-to-be: how to use the first weeks after a birth to care for the mother’s recovery, bond with the baby and start simple rhythms of prayer and Scripture at home.',
      fr: 'Pour les futurs pères : comment employer les premières semaines après une naissance à prendre soin du rétablissement de la mère, à s’attacher au bébé et à commencer de simples habitudes de prière et de lecture biblique à la maison. En anglais et en chinois.',
    },
    editions: {
      en: { title: 'Dads, Don’t Waste Your Paternity Leave', author: 'Rob Tombrella', publisher: 'The Gospel Coalition', url: 'https://www.thegospelcoalition.org/article/dads-paternity-leave/', available: true, lastVerifiedAt: '2026-09-28' },
      zh: { title: '爸爸们，不要浪费你的陪产假', author: '罗伯·汤姆布莱拉 (Rob Tombrella)', publisher: '福音联盟中文版 (The Gospel Coalition Chinese)', url: 'https://www.tgcchinese.org/article/dads-paternity-leave', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
  {
    id: 'topchretien-ne-me-volez-pas-mon-deuil',
    type: 'article',
    originalLanguage: 'fr',
    domains: ['relationships'],
    topics: ['miscarriage', 'grief', 'lament'],
    perspective: ['evangelical'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A French mother whose baby died in the womb at seventeen weeks asks those around grieving parents to recognise that this child existed, and tells how God met her after she voiced her anger to him. In French.',
      fr: 'Une mère dont le bébé est mort in utero à dix-sept semaines demande à l’entourage des parents endeuillés de reconnaître que cet enfant a existé, et raconte comment Dieu l’a consolée après qu’elle lui a dit sa colère.',
    },
    editions: {
      fr: { title: 'Ne me volez pas mon deuil !', author: 'FG (initiales seulement)', publisher: 'TopChrétien (TopMessages)', url: 'https://topmessages.topchretien.com/texte/ne-me-volez-pas-mon-deuil/', available: true, lastVerifiedAt: '2026-09-28' },
    },
  },
];
