// Candidates for womanOfGod21, researched 2026-09-29. NONE is approved: every entry is
// needs_review with no sign-off, so the resolver never shows it. See
// docs/resources/candidates/womanOfGod21.md for the verification worksheet.
//
// Tagging rule for this plan: the `christian-living` shelf is shared by seven
// "Growing in Christ" plans, including manOfGod21. A title written for women
// carries `womanhood` plus ONLY topics that no Man of God day uses (grief,
// abuse-safety, holy-spirit, hospitality, intercession, worship, singleness,
// evangelism), so it can never reach a Man of God day (tested). Titles for every
// Christian carry general topics and no `womanhood`. Roles-focused material is
// `sensitive` and deliberately omits `marriage-roles` (Man of God day 13 uses it).
const VERIFIED = '2026-09-29';
const BP = 'BibleProject';
// A BibleProject video edition. Languages without a dedicated video page link to
// BibleProject's own language hub, where the video is listed (title as listed)
// with in-page play, YouTube and download — the same pattern as psalms42/identity21.
const bp = (title, url, publisher = BP) => ({
  title, author: BP, publisher, url, available: true, lastVerifiedAt: VERIFIED,
});

export const WOMAN_OF_GOD21_CANDIDATES = [
  {
    id: 'wilkin-women-of-the-word',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['womanhood'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A Bible teacher’s short, practical method for women to read Scripture in context — with purpose, perspective, patience, process and prayer — so the women of the Bible are met on their own terms.',
      fr: 'Une méthode courte et pratique, écrite par une enseignante biblique pour les femmes, pour lire l’Écriture dans son contexte — avec un but, du recul, de la patience, une démarche et la prière.',
    },
    editions: {
      en: {
        title: 'Women of the Word: How to Study the Bible with Both Our Hearts and Our Minds (Second Edition)',
        author: 'Jen Wilkin',
        publisher: 'Crossway',
        url: 'https://www.crossway.org/books/women-of-the-word-tpb-2/',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
      fr: {
        title: 'Femmes de Parole : Lire la Bible avec la tête et le cœur',
        author: 'Jen Wilkin',
        publisher: 'La Maison de la Bible',
        url: 'https://maisonbible.fr/fr/70085-femmes-de-parole-lire-la-bible-avec-la-tete-et-le-coeur-9782826035275.html',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
      es: {
        title: 'Mujer de la Palabra: Cómo estudiar la Biblia con mente y corazón',
        author: 'Jen Wilkin',
        publisher: 'B&H Español (Lifeway)',
        url: 'https://www.lifeway.com/en/product/mujer-de-la-palabra-P006104456',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
      pt: {
        title: 'Mulheres da Palavra: Como estudar a Bíblia com nossa mente e coração',
        author: 'Jen Wilkin',
        publisher: 'Editora Fiel',
        url: 'https://editorafiel.com.br/mulheres/1045-mulheres-da-palavra-2-jen-wilkin.html',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
    },
  },
  {
    id: 'custis-james-gospel-of-ruth',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['womanhood', 'grief'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A close reading of Ruth that takes Naomi’s grief seriously and shows two women’s loyal love and courage at the centre of God’s story, with discussion questions for each chapter.',
      fr: 'Une lecture attentive du livre de Ruth qui prend au sérieux le deuil de Naomi et place l’amour fidèle et le courage de deux femmes au cœur de l’histoire de Dieu, avec des questions pour chaque chapitre.',
    },
    editions: {
      en: {
        title: 'The Gospel of Ruth: Loving God Enough to Break the Rules',
        author: 'Carolyn Custis James',
        publisher: 'Zondervan',
        url: 'https://carolyncustisjames.com/the-gospel-of-ruth/',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
    },
  },
  {
    id: 'custis-james-half-the-church',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['womanhood'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A call to see every woman — single or married, young or old — as God’s image-bearer and ezer, a “strong helper” called to take part in his mission, read against the suffering of women worldwide.',
      fr: 'Un appel à voir chaque femme — célibataire ou mariée, jeune ou âgée — comme porteuse de l’image de Dieu et « aide » (ezer) forte, appelée à prendre part à sa mission, face aux souffrances des femmes dans le monde.',
    },
    editions: {
      en: {
        title: 'Half the Church: Recapturing God’s Global Vision for Women',
        author: 'Carolyn Custis James',
        publisher: 'Zondervan',
        url: 'https://carolyncustisjames.com/half-the-church/',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
    },
  },
  {
    id: 'peppiatt-rediscovering-scriptures-vision-for-women',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['womanhood'],
    perspective: ['evangelical'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'One side of a disputed question, argued carefully: an egalitarian theologian reads Genesis, 1 Corinthians, Ephesians, 1 Timothy and 1 Peter and concludes that God calls women, like men, to serve and lead according to character and gifting.',
      fr: 'Un côté d’une question débattue, argumenté avec soin : une théologienne égalitarienne relit la Genèse, 1 Corinthiens, Éphésiens, 1 Timothée et 1 Pierre et conclut que Dieu appelle les femmes, comme les hommes, à servir et à diriger selon leur caractère et leurs dons.',
    },
    editions: {
      en: {
        title: 'Rediscovering Scripture’s Vision for Women: Fresh Perspectives on Disputed Texts',
        author: 'Lucy Peppiatt',
        publisher: 'IVP Academic',
        url: 'https://www.ivpress.com/rediscovering-scripture-s-vision-for-women',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
    },
  },
  {
    id: 'smith-gods-good-design',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['womanhood'],
    perspective: ['evangelical'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'The other side of the same question, argued carefully: a complementarian New Testament scholar works through seven key passages, from Genesis 1–3 and Proverbs 31 to 1 Timothy 2 and 1 Peter 3, with a discussion guide.',
      fr: 'L’autre côté de la même question, argumenté avec soin : une bibliste complémentarienne étudie sept passages clés, de Genèse 1–3 et Proverbes 31 à 1 Timothée 2 et 1 Pierre 3, avec un guide de discussion.',
    },
    editions: {
      en: {
        title: 'God’s Good Design: What the Bible Really Says about Men and Women (2nd edition)',
        author: 'Claire Smith',
        publisher: 'Matthias Media',
        url: 'https://matthiasmedia.com/products/gods-good-design',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
    },
  },
  {
    id: 'cbe-women-in-scripture-and-mission',
    type: 'podcast',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['womanhood', 'hospitality', 'evangelism'],
    perspective: ['evangelical'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'Short audio portraits from an egalitarian ministry of the women this plan studies — Eve, Hagar, Shiphrah and Puah, Deborah, Abigail, Ruth, Esther, Anna, Mary Magdalene, Lydia, Priscilla and Phoebe — each read in its biblical setting.',
      fr: 'De courts portraits audio, par un ministère égalitarien, des femmes étudiées dans ce parcours — Ève, Agar, Schiphra et Pua, Débora, Abigaïl, Ruth, Esther, Anne, Marie de Magdala, Lydie, Priscille et Phœbé — chacune lue dans son contexte biblique.',
    },
    editions: {
      en: {
        title: 'Women in Scripture and Mission (radio series)',
        author: 'CBE International (various speakers, incl. Ronald W. Pierce)',
        publisher: 'CBE International',
        url: 'https://www.cbeinternational.org/primary_page/women-in-scripture-and-mission/',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
      es: {
        title: 'Mujeres en las Escrituras y la misión',
        author: 'CBE International',
        publisher: 'CBE International',
        url: 'https://www.cbeinternational.org/primary_page/cbes-radio-series-women-in-ministry-en-espanol/',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
    },
  },
  {
    id: 'wilkin-in-his-image',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['character', 'holiness'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'Ten attributes of God — holy, loving, good, just, merciful, gracious, faithful, patient, truthful and wise — and how, in Christ, we are being made to reflect them; asks “who should I be?” before “what should I do?”.',
      fr: 'Dix attributs de Dieu — saint, aimant, bon, juste, miséricordieux, plein de grâce, fidèle, patient, vrai et sage — et comment, en Christ, nous sommes appelés à les refléter ; la question « qui devrais-je être ? » avant « que dois-je faire ? ».',
    },
    editions: {
      en: {
        title: 'In His Image: 10 Ways God Calls Us to Reflect His Character',
        author: 'Jen Wilkin',
        publisher: 'Crossway',
        url: 'https://www.crossway.org/books/in-his-image-tpb/',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
      es: {
        title: 'A Su imagen',
        author: 'Jen Wilkin',
        publisher: 'Poiema Publicaciones',
        url: 'https://poiema.co/products/a-su-imagen',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
      pt: {
        title: 'Renovadas: 10 maneiras de refletir os atributos de Deus',
        author: 'Jen Wilkin',
        publisher: 'Editora Fiel',
        url: 'https://www.editorafiel.com.br/renovadas-jen-wilkin',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
    },
  },
  {
    id: 'guthrie-even-better-than-eden',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['identity', 'gospel'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A Bible teacher traces nine threads from Genesis to Revelation — among them the image of God, clothing and shame, and the serpent’s defeat — to show how Christ restores what was lost in Eden and more; with discussion questions.',
      fr: 'Une enseignante biblique suit neuf fils de la Genèse à l’Apocalypse — dont l’image de Dieu, le vêtement et la honte, la défaite du serpent — pour montrer comment le Christ restaure ce qui fut perdu en Éden, et davantage ; avec des questions de discussion.',
    },
    editions: {
      en: {
        title: 'Even Better than Eden: Nine Ways the Bible’s Story Changes Everything about Your Story',
        author: 'Nancy Guthrie',
        publisher: 'Crossway',
        url: 'https://www.crossway.org/books/even-better-than-eden-tpb/',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
    },
  },
  {
    id: 'bibleproject-image-of-god',
    type: 'video',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['identity'],
    status: 'needs_review',
    description: {
      en: 'A six-minute animated theme video on what it means that every human — woman and man alike — is made in God’s image, how that calling was marred, and how Jesus restores it.',
      fr: 'Une vidéo animée de six minutes sur ce que signifie être créé à l’image de Dieu — pour chaque femme comme pour chaque homme —, comment cette vocation a été abîmée et comment Jésus la restaure.',
    },
    editions: {
      en: bp('Image of God', 'https://bibleproject.com/videos/image-of-god/'),
      fr: bp('Image de Dieu', 'https://bibleproject.com/fr/videos/image-de-dieu/'),
      es: bp('Imagen de Dios', 'https://bibleproject.com/es/videos/imagen-de-dios/'),
      pt: bp('Imagem de Deus', 'https://bibleproject.com/pt-br/videos/imagem-de-deus/'),
      de: bp('Ebenbild Gottes', 'https://bibleproject.visiomedia.org/video/ebenbild-gottes/', 'BibleProject – Deutsch (visiomedia)'),
      ru: bp('Образ Бога', 'https://bibleproject.com/ru/'),
      zh: bp('神的形象 - Image of God', 'https://bibleproject.com/zh-hans/'),
      ja: bp('神のかたち Image of God', 'https://bibleproject.com/ja/'),
      ko: bp('하나님의 형상 Image of God', 'https://bibleproject.com/ko/'),
      hi: bp('परमेश्वर का स्वरूप', 'https://bibleproject.com/hi/'),
      id: bp('Gambar Allah', 'https://bibleproject.com/id/'),
      sw: bp('Mfano wa Mungu', 'https://bibleproject.com/sw/'),
      tl: bp('Larawan ng Diyos', 'https://bibleproject.com/tl/'),
      am: bp('የእግዚአብሔር አምሳል Image of God', 'https://bibleproject.com/am/'),
    },
  },
  {
    id: 'bibleproject-ruth-overview',
    type: 'video',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['grief', 'friendship'],
    status: 'needs_review',
    description: {
      en: 'A seven-minute animated overview of Ruth: Naomi’s bitter losses, Ruth’s loyal love and Boaz’s kindness, and how God works through ordinary faithfulness to turn grief into joy.',
      fr: 'Un panorama animé de sept minutes du livre de Ruth : les pertes amères de Naomi, l’amour fidèle de Ruth, la bonté de Boaz, et comment Dieu agit par une fidélité ordinaire pour changer le deuil en joie.',
    },
    editions: {
      en: bp('Ruth', 'https://bibleproject.com/videos/ruth/'),
      fr: bp('Ruth', 'https://bibleproject.com/fr/videos/ruth/'),
      es: bp('Rut', 'https://bibleproject.com/es/videos/rut/'),
      pt: bp('Rute', 'https://bibleproject.com/pt-br/videos/rute/'),
      de: bp('Rut', 'https://bibleproject.visiomedia.org/video/rut/', 'BibleProject – Deutsch (visiomedia)'),
      ru: bp('Обзор: Руфь', 'https://bibleproject.com/ru/'),
      zh: bp('路得记 - Ruth', 'https://bibleproject.com/zh-hans/'),
      ja: bp('ルツ記 Ruth【概観】', 'https://bibleproject.com/ja/'),
      ko: bp('룻기 개요 Ruth', 'https://bibleproject.com/ko/'),
      ar: bp('نظرة عامّة: راعوث', 'https://bibleproject.com/arz/', 'BibleProject (Egyptian Arabic)'),
      fa: bp('Ruth مروری بر روت', 'https://bibleproject.com/fa/'),
      hi: bp('अवलोकन: रूत', 'https://bibleproject.com/hi/'),
      id: bp('Ringkasan: Rut', 'https://bibleproject.com/id/'),
      sw: bp('Muhtasari: Ruthu', 'https://bibleproject.com/sw/'),
      tl: bp('Buong-ideya: Ruth', 'https://bibleproject.com/tl/'),
      am: bp('ዳሰሳ፦ መጽሐፈ ሩት Ruth', 'https://bibleproject.com/am/'),
    },
  },
  {
    id: 'bibleproject-esther-overview',
    type: 'video',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['calling', 'justice'],
    status: 'needs_review',
    description: {
      en: 'A nine-minute animated overview of Esther: a book where God is never named yet is at work behind the scenes, as Esther risks her life to stand against Haman’s plot to destroy her people.',
      fr: 'Un panorama animé de neuf minutes du livre d’Esther : Dieu n’y est jamais nommé et pourtant il agit dans les coulisses, tandis qu’Esther risque sa vie pour s’opposer au complot d’Haman contre son peuple.',
    },
    editions: {
      en: bp('Esther', 'https://bibleproject.com/videos/esther/'),
      fr: bp('Esther', 'https://bibleproject.com/fr/videos/esther/'),
      es: bp('Ester', 'https://bibleproject.com/es/videos/ester/'),
      pt: bp('Ester', 'https://bibleproject.com/pt-br/videos/ester/'),
      de: bp('Ester', 'https://bibleproject.visiomedia.org/video/ester/', 'BibleProject – Deutsch (visiomedia)'),
      ru: bp('Обзор: Есфирь', 'https://bibleproject.com/ru/'),
      zh: bp('以斯帖记 - Esther', 'https://bibleproject.com/zh-hans/'),
      ja: bp('エステル記 Esther【概観】', 'https://bibleproject.com/ja/'),
      ko: bp('에스더 개요 Esther', 'https://bibleproject.com/ko/'),
      ar: bp('نظرة عامّة: أستير', 'https://bibleproject.com/arz/', 'BibleProject (Egyptian Arabic)'),
      fa: bp('مروری بر اِستر Esther', 'https://bibleproject.com/fa/'),
      hi: bp('अवलोकन: एस्तेर', 'https://bibleproject.com/hi/'),
      id: bp('Ringkasan: Ester', 'https://bibleproject.com/id/'),
      sw: bp('Muhtasari: Esta', 'https://bibleproject.com/sw/'),
      tl: bp('Buong-ideya: Ester', 'https://bibleproject.com/tl/'),
      am: bp('ዳሰሳ፦ መጽሐፈ አስቴር Esther', 'https://bibleproject.com/am/'),
    },
  },
  {
    id: 'ag-role-of-women-in-ministry',
    type: 'article',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['womanhood', 'holy-spirit'],
    perspective: ['pentecostal'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A Pentecostal denomination’s position paper: starting from “your sons and daughters will prophesy” (Acts 2), it surveys Miriam, Deborah, Philip’s daughters, Priscilla and Phoebe and concludes that the Spirit gifts women for ministry — one side of a disputed question, stated charitably.',
      fr: 'Le texte de position d’une dénomination pentecôtiste : à partir de « vos fils et vos filles prophétiseront » (Actes 2), il parcourt Miriam, Débora, les filles de Philippe, Priscille et Phœbé et conclut que l’Esprit donne aux femmes des dons pour le ministère — un côté d’une question débattue, exposé avec charité.',
    },
    editions: {
      en: {
        title: 'The Role of Women in Ministry as Described in Holy Scripture (position paper, 2010)',
        author: 'General Presbytery of the Assemblies of God (USA)',
        publisher: 'Assemblies of God (USA)',
        url: 'https://ag.org/-/media/AGORG/Beliefs/Position-Papers/PP_The_Role_of_Women_in_Ministry.pdf',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
    },
  },
  {
    id: 'strickland-is-it-abuse',
    type: 'book',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['abuse-safety'],
    perspective: ['reformed', 'evangelical'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A biblical counsellor’s guide to recognising domestic abuse — physical, sexual, emotional, spiritual and financial — and helping those harmed toward safety; it makes plain that Scripture never asks anyone to stay in danger.',
      fr: 'Le guide d’une conseillère biblique pour reconnaître la violence conjugale — physique, sexuelle, émotionnelle, spirituelle et financière — et accompagner les victimes vers la sécurité ; il montre clairement que l’Écriture ne demande à personne de rester en danger.',
    },
    editions: {
      en: {
        title: 'Is It Abuse? A Biblical Guide to Identifying Domestic Abuse and Helping Victims',
        author: 'Darby Strickland',
        publisher: 'P&R Publishing (listed by CCEF)',
        url: 'https://www.ccef.org/book/is-it-abuse-a-biblical-guide-to-identifying-domestic-abuse-and-helping-victims/',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
    },
  },
  {
    id: 'garn-image-bearers-what-women-need-to-know',
    type: 'article',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['womanhood'],
    perspective: ['evangelical'],
    status: 'needs_review',
    description: {
      en: 'A short article for women worn out by trying to measure up to an ideal of “the Christian woman”: our first calling is to bear God’s image, received as a gift rather than earned.',
      fr: 'Un court article pour les femmes épuisées de vouloir être à la hauteur d’un idéal de « femme chrétienne » : notre première vocation est de porter l’image de Dieu, reçue comme un don et non méritée.',
    },
    editions: {
      fr: {
        title: 'Porteuses de l’image de Dieu ? Ce que les femmes doivent savoir',
        author: 'Elizabeth Garn',
        publisher: 'Évangile 21 (The Gospel Coalition)',
        url: 'https://evangile21.thegospelcoalition.org/article/porteuses-image-de-dieu/',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
    },
  },
  {
    id: 'coalicion-la-mujer-y-la-biblia',
    type: 'study',
    originalLanguage: 'es',
    domains: ['christian-living'],
    topics: ['womanhood'],
    perspective: ['evangelical', 'reformed'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A free Spanish-language course by Latin American women Bible teachers — audio conversations, articles and reading lists on women as image-bearers, women studying Scripture, and faith in every season, married or single; written from a complementarian view.',
      fr: 'Un parcours gratuit en espagnol, animé par des enseignantes bibliques latino-américaines — conversations audio, articles et lectures sur la femme porteuse de l’image de Dieu, l’étude de l’Écriture et la foi à chaque saison de la vie, mariée ou célibataire ; d’un point de vue complémentarien.',
    },
    editions: {
      es: {
        title: 'La mujer y la Biblia (curso)',
        author: 'Coalición por el Evangelio (Patricia Namnún, Ana Ávila, Betsy Gómez y otras)',
        publisher: 'Coalición por el Evangelio (The Gospel Coalition en español)',
        url: 'https://www.coalicionporelevangelio.org/curso/la-mujer-y-la-biblia/',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
    },
  },
  {
    id: 'rourke-seven-womens-ministries',
    type: 'article',
    originalLanguage: 'en',
    domains: ['christian-living'],
    topics: ['womanhood', 'hospitality', 'evangelism'],
    perspective: ['evangelical', 'reformed'],
    status: 'needs_review',
    description: {
      en: 'A pastor’s short survey of the women who served in the New Testament church — patrons and hosts like Lydia and Priscilla, workers, teachers, witnesses like Mary Magdalene and the Samaritan woman, partners and caregivers — as an expectation, not an exception.',
      fr: 'Le court tour d’horizon, par un pasteur, des femmes qui ont servi dans l’Église du Nouveau Testament — bienfaitrices et hôtesses comme Lydie et Priscille, ouvrières, enseignantes, témoins comme Marie de Magdala et la Samaritaine, partenaires et soignantes — comme une attente, non une exception.',
    },
    editions: {
      en: {
        title: 'Seven Women’s Ministries in the New Testament',
        author: 'Jonathan Rourke',
        publisher: '9Marks',
        url: 'https://www.9marks.org/article/seven-womens-ministries-in-the-new-testament/',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
      pt: {
        title: 'Sete ministérios de mulheres no Novo Testamento',
        author: 'Jonathan Rourke (tradução: Paulo Reiss Junior)',
        publisher: 'Voltemos ao Evangelho',
        url: 'https://voltemosaoevangelho.com/blog/2021/02/sete-ministerios-de-mulheres-no-novo-testamento/',
        available: true,
        lastVerifiedAt: '2026-09-29',
      },
    },
  },
];
