// Relationship and family books added from the August 2026 editorial brief.
//
// Standard-topic books in this file are approved because the brief explicitly
// selected both the authors and the subjects. Books centred on sexuality,
// gender/role frameworks, marriage crisis, or disputed pastoral claims remain
// `needs_review`; the resolver will keep them invisible until the two sensitive
// sign-offs described in catalogue.js have been completed.

const VERIFIED_AT = '2026-08-28';

function relationshipBook({
  id,
  language = 'en',
  topics,
  lifeStages,
  status = 'approved',
  reviewLevel,
  replacementResourceId,
  description,
  title,
  author,
  publisher,
  url,
  // Out of print, or only obtainable secondhand. The resolver refuses to render
  // an unavailable edition, so this records the title for a human curator
  // without ever sending a reader to something they cannot get.
  available = true,
}) {
  return {
    id,
    type: 'book',
    originalLanguage: language,
    topics,
    lifeStages,
    status,
    ...(reviewLevel ? { reviewLevel } : {}),
    ...(replacementResourceId ? { replacementResourceId } : {}),
    description,
    editions: {
      [language]: {
        title,
        author,
        publisher,
        url,
        available,
        lastVerifiedAt: VERIFIED_AT,
      },
    },
  };
}

export const RELATIONSHIP_BOOKS = [
  // English-language books
  relationshipBook({
    id: 'chapman-five-love-languages',
    topics: ['communication', 'listening', 'friendship', 'marriage'],
    lifeStages: ['single', 'dating', 'engaged', 'married'],
    description: {
      en: 'A practical vocabulary for noticing how people tend to give and receive affection, best used as a conversation starter rather than a personality test.',
      fr: "Un vocabulaire pratique pour discerner comment chacun donne et reçoit l'affection, à utiliser comme point de départ d'une conversation plutôt que comme test de personnalité.",
    },
    title: 'The 5 Love Languages',
    author: 'Gary Chapman',
    publisher: 'Northfield Publishing',
    url: 'https://www.moodypublishers.com/the-5-love-languagesreg',
  }),
  relationshipBook({
    id: 'chapman-things-before-married',
    topics: ['premarital', 'communication', 'conflict', 'family-of-origin', 'finances'],
    lifeStages: ['dating', 'engaged'],
    description: {
      en: 'Prompts engaged couples to discuss expectations, conflict, money and family patterns before the wedding.',
      fr: "Invite les couples fiancés à parler des attentes, des conflits, de l'argent et des héritages familiaux avant le mariage.",
    },
    title: "Things I Wish I'd Known Before We Got Married",
    author: 'Gary Chapman',
    publisher: 'Northfield Publishing',
    url: 'https://www.moodypublishers.com/things-i-wish-id-known-before-we-got-married?variationCode=978-1-57567-922-8',
  }),
  relationshipBook({
    id: 'chapman-five-love-languages-singles',
    topics: ['singleness', 'dating', 'communication', 'friendship'],
    lifeStages: ['single', 'dating'],
    description: {
      en: 'Applies the love-languages framework to friendships, family relationships and dating during singleness.',
      fr: "Applique le cadre des langages de l'amour aux amitiés, aux relations familiales et aux fréquentations pendant le célibat.",
    },
    title: 'The 5 Love Languages: Singles Edition',
    author: 'Gary Chapman',
    publisher: 'Northfield Publishing',
    url: 'https://www.moodypublishers.com/the-5-love-languages-singles-edition?variationCode=978-0-8024-6785-0',
  }),
  relationshipBook({
    id: 'omartian-praying-couple',
    topics: ['prayer-together', 'spiritual-rhythms', 'marriage'],
    lifeStages: ['married'],
    description: {
      en: 'Offers short biblical reflections and prayers to help spouses begin or renew a shared rhythm of prayer.',
      fr: 'Propose de courtes méditations bibliques et des prières pour aider les époux à commencer ou renouveler un rythme de prière commune.',
    },
    title: 'The Power of a Praying Couple',
    author: 'Stormie Omartian',
    publisher: 'Harvest House Publishers',
    url: 'https://www.harvesthousepublishers.com/books/power-of-a-praying-couple-9780736982641/',
  }),
  relationshipBook({
    id: 'omartian-praying-parent',
    topics: ['prayer', 'parenting', 'children', 'family'],
    lifeStages: ['married'],
    description: {
      en: "Gives parents a structured way to entrust different seasons and concerns in their children's lives to God.",
      fr: "Donne aux parents une trame pour confier à Dieu les différentes saisons et préoccupations de la vie de leurs enfants.",
    },
    title: 'The Power of a Praying Parent',
    author: 'Stormie Omartian',
    publisher: 'Harvest House Publishers',
    url: 'https://www.harvesthousepublishers.com/books/power-of-a-praying-parent-9780736990219/',
  }),
  relationshipBook({
    id: 'cloud-townsend-boundaries',
    topics: ['boundaries', 'family-of-origin', 'character', 'healing'],
    lifeStages: ['single', 'dating', 'engaged', 'married'],
    description: {
      en: 'Explains responsibility, limits and saying no in ways that can clarify difficult family and relationship patterns.',
      fr: 'Explique la responsabilité, les limites et le refus afin de clarifier des dynamiques familiales et relationnelles difficiles.',
    },
    title: 'Boundaries, Updated and Expanded Edition',
    author: 'Henry Cloud and John Townsend',
    publisher: 'Zondervan',
    url: 'https://www.zondervan.com/9780310351801/boundaries-updated-and-expanded-edition/',
  }),
  relationshipBook({
    id: 'cloud-townsend-boundaries-marriage',
    topics: ['boundaries', 'communication', 'conflict', 'marriage'],
    lifeStages: ['married'],
    description: {
      en: 'Applies responsibility and healthy limits to recurring patterns between spouses.',
      fr: 'Applique la responsabilité et les limites saines aux dynamiques récurrentes entre époux.',
    },
    title: 'Boundaries in Marriage',
    author: 'Henry Cloud and John Townsend',
    publisher: 'Zondervan',
    url: 'https://www.zondervan.com/9780310243144/boundaries-in-marriage/',
  }),
  relationshipBook({
    id: 'parrott-saving-your-marriage',
    topics: ['premarital', 'communication', 'conflict', 'family-of-origin'],
    lifeStages: ['engaged'],
    description: {
      en: 'A premarital guide built around expectations, communication habits and the histories each partner brings into marriage.',
      fr: "Un guide prémarital sur les attentes, les habitudes de communication et l'histoire que chacun apporte au mariage.",
    },
    title: 'Saving Your Marriage Before It Starts',
    author: 'Les Parrott and Leslie Parrott',
    publisher: 'Zondervan',
    url: 'https://www.zondervan.com/9780310259824/saving-your-marriage-before-it-starts/',
  }),
  relationshipBook({
    id: 'parrott-good-fight',
    topics: ['conflict', 'forgiveness', 'communication', 'listening'],
    lifeStages: ['engaged', 'married'],
    description: {
      en: 'Frames ordinary disagreement as a skill couples can practise with honesty, repair and restraint.',
      fr: 'Présente les désaccords ordinaires comme une compétence que le couple peut travailler avec honnêteté, réparation et retenue.',
    },
    title: 'The Good Fight: How Conflict Can Bring You Closer',
    author: 'Les Parrott and Leslie Parrott',
    publisher: 'Worthy Books',
    url: 'https://www.hachettebookgroup.com/titles/dr-leslie-parrott/the-good-fight/9781617956614/',
  }),
  relationshipBook({
    id: 'todd-relationship-goals',
    topics: ['dating', 'marriage', 'sexuality', 'purity'],
    lifeStages: ['single', 'dating', 'engaged', 'married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'Addresses singleness, dating, marriage and sexual ethics in one accessible relationship overview.',
      fr: "Aborde le célibat, les fréquentations, le mariage et l'éthique sexuelle dans une vue d'ensemble accessible des relations.",
    },
    title: 'Relationship Goals: How to Win at Dating, Marriage, and Sex',
    author: 'Michael Todd',
    publisher: 'WaterBrook',
    url: 'https://www.penguinrandomhouse.com/books/624364/relationship-goals-movie-tie-in-by-michael-todd/9798217153367/',
  }),
  relationshipBook({
    id: 'thomas-sacred-search',
    topics: ['discernment', 'dating', 'premarital', 'character'],
    lifeStages: ['single', 'dating', 'engaged'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'Moves dating discernment away from finding a mythical perfect match and toward character, purpose and wise choice.',
      fr: "Déplace le discernement amoureux de la recherche d'une personne parfaite vers le caractère, la vocation et un choix sage.",
    },
    title: "The Sacred Search: What If It's Not about Who You Marry, But Why?",
    author: 'Gary Thomas',
    publisher: 'David C Cook',
    url: 'https://davidccook.org/books/the-sacred-search/',
  }),
  relationshipBook({
    id: 'thomas-cherish',
    topics: ['friendship', 'contentment', 'marriage'],
    lifeStages: ['engaged', 'married'],
    description: {
      en: 'Invites spouses to recover attention, gratitude and delight instead of taking one another for granted.',
      fr: "Invite les époux à retrouver l'attention, la gratitude et la joie plutôt qu'à considérer l'autre comme acquis.",
    },
    title: 'Cherish',
    author: 'Gary Thomas',
    publisher: 'Zondervan',
    url: 'https://www.zondervan.com/9780310347262/cherish/',
  }),
  relationshipBook({
    id: 'thomas-sacred-marriage',
    topics: ['marriage', 'covenant', 'spiritual-formation', 'sexual-intimacy'],
    lifeStages: ['engaged', 'married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'Explores how the ordinary demands of marriage can expose sin and form Christian character.',
      fr: 'Explore comment les exigences ordinaires du mariage peuvent révéler le péché et former le caractère chrétien.',
    },
    title: 'Sacred Marriage',
    author: 'Gary Thomas',
    publisher: 'Zondervan',
    url: 'https://www.zondervan.com/9780310337379/sacred-marriage/',
  }),
  relationshipBook({
    id: 'feldhahn-highly-happy-marriages',
    topics: ['friendship', 'communication', 'trust', 'marriage'],
    lifeStages: ['married'],
    description: {
      en: 'Summarises research on small habits and interpretations shared by couples who report strong marriages.',
      fr: 'Résume des recherches sur les petites habitudes et interprétations communes aux couples qui décrivent leur mariage comme solide.',
    },
    title: 'The Surprising Secrets of Highly Happy Marriages',
    author: 'Shaunti Feldhahn',
    publisher: 'Multnomah',
    url: 'https://www.penguinrandomhouse.com/books/48707/the-surprising-secrets-of-highly-happy-marriages-by-shaunti-feldhahn/',
  }),
  relationshipBook({
    id: 'feldhahn-secrets-sex-marriage',
    topics: ['sexual-intimacy', 'communication', 'trust'],
    lifeStages: ['married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'Uses survey research and clinical experience to help couples discuss desire, pressure and mutual understanding in sexual intimacy.',
      fr: "S'appuie sur des enquêtes et l'expérience clinique pour aider les couples à parler du désir, de la pression et de la compréhension mutuelle dans l'intimité sexuelle.",
    },
    title: 'Secrets of Sex & Marriage',
    author: 'Shaunti Feldhahn and Michael Sytsma',
    publisher: 'Bethany House',
    url: 'https://shaunti.com/shauntis-books/secrets-of-sex-marriage/',
  }),
  relationshipBook({
    id: 'eggerichs-love-respect',
    topics: ['communication', 'marriage', 'marriage-roles'],
    lifeStages: ['engaged', 'married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'Presents a strongly gendered love-and-respect framework for recurring communication patterns in marriage.',
      fr: "Présente un cadre fortement genré d'amour et de respect pour les schémas récurrents de communication dans le mariage.",
    },
    title: 'Love & Respect',
    author: 'Emerson Eggerichs',
    publisher: 'Thomas Nelson',
    url: 'https://www.loveandrespect.com/product/love-respect-book',
  }),
  relationshipBook({
    id: 'stuart-single-dating-engaged-married',
    topics: ['singleness', 'dating', 'premarital', 'marriage', 'purity', 'sexuality'],
    lifeStages: ['single', 'dating', 'engaged', 'married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'Traces purpose and practical decisions across singleness, dating, engagement and marriage in one continuous framework.',
      fr: "Suit la vocation et les choix pratiques du célibat au mariage, en passant par les fréquentations et les fiançailles, dans un même cadre.",
    },
    title: 'Single, Dating, Engaged, Married: Navigating Life and Love in the Modern Age',
    author: 'Ben Stuart',
    publisher: 'Thomas Nelson',
    url: 'https://www.singledatingengagedmarried.com/',
  }),
  relationshipBook({
    id: 'chan-you-and-me-forever',
    topics: ['covenant', 'mission', 'spiritual-formation', 'marriage'],
    lifeStages: ['engaged', 'married'],
    description: {
      en: "Places marriage inside Christ's larger call to discipleship, eternity and mission.",
      fr: "Replace le mariage dans l'appel plus vaste du Christ à devenir disciples, à vivre pour l'éternité et la mission.",
    },
    title: 'You and Me Forever: Marriage in Light of Eternity',
    author: 'Francis Chan and Lisa Chan',
    publisher: 'Claire Love Publishing',
    url: 'https://www.crazylove.org/youandmeforever',
  }),
  relationshipBook({
    id: 'tripp-parenting',
    topics: ['parenting', 'family-discipleship', 'character', 'family'],
    lifeStages: ['married'],
    description: {
      en: 'Organises parenting around gospel-shaped principles rather than a collection of behaviour-management techniques.',
      fr: "Organise l'éducation des enfants autour de principes façonnés par l'Évangile plutôt que d'une collection de techniques de gestion du comportement.",
    },
    title: 'Parenting: 14 Gospel Principles That Can Radically Change Your Family',
    author: 'Paul David Tripp',
    publisher: 'Crossway',
    url: 'https://www.crossway.org/books/parenting-hcj-2/',
  }),
  relationshipBook({
    id: 'wright-before-you-say-i-do',
    topics: ['premarital', 'discernment', 'communication', 'family-of-origin'],
    lifeStages: ['engaged'],
    description: {
      en: 'A discussion-based marriage-preparation guide for examining expectations, histories and readiness together.',
      fr: "Un guide de préparation au mariage fondé sur le dialogue pour examiner ensemble les attentes, les histoires personnelles et l'état de préparation.",
    },
    title: "Before You Say 'I Do': A Marriage Preparation Guide for Couples",
    author: 'H. Norman Wright and Wes Roberts',
    publisher: 'Harvest House Publishers',
    url: 'https://www.harvesthousepublishers.com/books/before-you-say-i-do-9780736975995/',
  }),

  // French-language books
  relationshipBook({
    id: 'poujol-vivre-a-deux',
    language: 'fr',
    topics: ['communication', 'conflict', 'listening', 'marriage'],
    lifeStages: ['engaged', 'married'],
    description: {
      en: 'A French pastoral-psychology guide to communication and conflict in life as a couple.',
      fr: 'Un guide de psychologie pastorale sur la communication et la gestion des conflits dans la vie à deux.',
    },
    title: 'Vivre à deux : Bien communiquer, gérer les conflits',
    author: 'Claire Poujol and Jacques Poujol',
    publisher: 'Empreinte temps présent',
    url: 'https://catalogue.bnf.fr/ark:/12148/cb42586857w',
  }),
  relationshipBook({
    id: 'poujol-dix-cles-vie-couple',
    language: 'fr',
    topics: ['marriage', 'communication', 'conflict', 'friendship'],
    lifeStages: ['engaged', 'married'],
    description: {
      en: 'Ten concise entry points for examining communication, difference and resilience as a couple.',
      fr: 'Dix portes d’entrée concises pour examiner la communication, les différences et la solidité du couple.',
    },
    title: '10 clés de la vie en couple',
    author: 'Jacques Poujol and Valérie Duval-Poujol',
    publisher: 'Empreinte temps présent',
    url: 'https://www.editions-empreinte.com/tous-nos-ouvrages/10-cl%C3%A9s-de-la-vie-en-couple-',
  }),
  relationshipBook({
    id: 'dufour-construire-mariage-epanoui',
    language: 'fr',
    topics: ['marriage', 'communication', 'conflict', 'sexual-intimacy'],
    lifeStages: ['engaged', 'married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A French pastoral resource spanning communication, conflict and intimacy in marriage.',
      fr: "Une ressource pastorale francophone qui aborde la communication, les conflits et l'intimité dans le mariage.",
    },
    title: 'Construire un mariage épanoui',
    author: 'Éric Dufour and Rachel Dufour',
    publisher: 'Éric & Rachel Dufour',
    url: 'https://www.ericracheldufour.com/ressources',
  }),
  relationshipBook({
    id: 'dufour-de-a-a-sexe',
    language: 'fr',
    topics: ['sexuality', 'sexual-intimacy', 'purity'],
    lifeStages: ['single', 'dating', 'engaged', 'married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A direct French-language treatment of sexuality for Christian singles and couples.',
      fr: 'Un traitement direct de la sexualité destiné aux célibataires et aux couples chrétiens.',
    },
    title: 'De A à Sexe',
    author: 'Éric Dufour and Rachel Dufour',
    publisher: 'Éric & Rachel Dufour',
    url: 'https://www.ericracheldufour.com/products-list',
  }),
  relationshipBook({
    id: 'jouvet-du-celibat-vie-couple',
    language: 'fr',
    topics: ['singleness', 'dating', 'discernment', 'contentment'],
    lifeStages: ['single', 'dating'],
    status: 'needs_review',
    description: {
      en: 'A testimony-led guide to Christian singleness and the possible transition into a relationship; its framing of singleness awaits pastoral review.',
      fr: "Un guide fondé sur le témoignage autour du célibat chrétien et du passage possible à la vie de couple ; sa manière de présenter le célibat attend une relecture pastorale.",
    },
    title: 'Du célibat à la vie de couple : Le guide des futurs ex-célibataires',
    author: 'Pauline Jouvet',
    publisher: 'RDF Editions',
    url: 'https://www.clcfrance.com/produit/du-celibat-a-la-vie-de-couple-pauline-jouvet-rdfd060-9782882720771',
  }),
  relationshipBook({
    id: 'karambiri-avant-dire-oui',
    language: 'fr',
    topics: ['premarital', 'communication', 'covenant'],
    lifeStages: ['engaged'],
    description: {
      en: 'A concise Francophone premarital guide built around questions, mutual understanding and shared convictions.',
      fr: 'Un guide prémarital francophone concis autour des bonnes questions, de la connaissance mutuelle et des convictions partagées.',
    },
    title: 'Avant de dire oui pour le mariage',
    author: 'Hortense Karambiri',
    publisher: 'Association Parakletos',
    url: 'https://eglise.shop/produit/avant-de-dire-oui-pour-le-mariage/',
  }),
  relationshipBook({
    id: 'karambiri-bien-choisir-conjoint',
    language: 'fr',
    topics: ['discernment', 'dating', 'prayer'],
    lifeStages: ['single', 'dating'],
    description: {
      en: 'Offers Francophone readers biblical questions and practices for slowing down the choice of a future spouse.',
      fr: "Propose aux lecteurs francophones des questions bibliques et des pratiques pour prendre le temps de discerner le choix d'un futur conjoint.",
    },
    title: 'Bien choisir votre futur conjoint',
    author: 'Hortense Karambiri',
    publisher: 'Association Parakletos',
    url: 'https://eglise.shop/produit/bien-choisir-votre-futur-conjoint/',
  }),
  relationshipBook({
    id: 'karambiri-premieres-annees',
    language: 'fr',
    topics: ['marriage', 'communication', 'sexual-intimacy', 'family-of-origin', 'marriage-roles', 'abuse-safety'],
    lifeStages: ['married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A wide-ranging guide for newlyweds that includes communication, intimacy, roles, in-laws, money and destructive patterns.',
      fr: "Un guide étendu pour jeunes mariés qui aborde la communication, l'intimité, les rôles, les belles-familles, l'argent et les dynamiques destructrices.",
    },
    title: 'Vos premières années de vie conjugale',
    author: 'Hortense Karambiri',
    publisher: 'Association Parakletos',
    url: 'https://eglise.shop/produit/vos-premieres-annees-de-vie-conjugale/',
  }),
  relationshipBook({
    id: 'karambiri-sept-regles-couple',
    language: 'fr',
    topics: ['marriage-crisis', 'communication', 'forgiveness', 'marriage'],
    lifeStages: ['married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A short restoration-oriented guide for couples who want to examine recurring habits in their relationship.',
      fr: 'Un guide court orienté vers la restauration pour les couples qui veulent examiner les habitudes récurrentes de leur relation.',
    },
    title: "7 règles d'or pour améliorer votre vie de couple",
    author: 'Hortense Karambiri',
    publisher: 'Association Parakletos',
    url: 'https://eglise.shop/produit/7-regles-dor-pour-ameliorer-votre-vie-de-couple/',
  }),
  relationshipBook({
    id: 'sanogo-six-sagesses-mariage',
    language: 'fr',
    topics: ['marriage-crisis', 'spiritual-formation', 'marriage'],
    lifeStages: ['engaged', 'married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'Uses the wedding at Cana as a framework for spiritual preparation and renewal in marriage.',
      fr: 'Utilise les noces de Cana comme cadre de préparation spirituelle et de renouvellement du mariage.',
    },
    title: '6 sagesses pour révolutionner ton mariage (Tome 2)',
    author: 'Mohammed Sanogo',
    publisher: 'Sanogo Books',
    url: 'https://www.sanogobooks.com/products/6-sagesses-pour-revolutionner-ton-mariage-tome-2-mohammed-sanogo',
  }),
  relationshipBook({
    id: 'lilliane-sanogo-sept-alertes',
    language: 'fr',
    topics: ['marriage-crisis', 'communication', 'trust'],
    lifeStages: ['married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'Names warning signs that may precede a serious rupture in a couple and therefore requires careful safety review.',
      fr: "Nomme des signaux d'alerte pouvant précéder une rupture grave du couple et nécessite donc une relecture attentive de sécurité.",
    },
    title: '7 alertes avant que ton couple ne se brise',
    author: 'Lilliane Sanogo',
    publisher: 'Sanogo Books',
    url: 'https://www.sanogobooks.com/collections/lilliane-sanogo',
  }),
  relationshipBook({
    id: 'castanou-vous-pensez-mariage',
    language: 'fr',
    topics: ['premarital', 'discernment', 'dating', 'covenant'],
    lifeStages: ['single', 'dating', 'engaged'],
    description: {
      en: 'A Francophone guide for examining the choice of a spouse and the foundations needed before marriage.',
      fr: "Un guide francophone pour examiner le choix d'un conjoint et les fondements nécessaires avant le mariage.",
    },
    title: 'Vous pensez mariage ?',
    author: 'Yvan Castanou',
    publisher: 'Metanoia & Vie',
    url: 'https://impactxapp.com/w/vous-pensez-mariage',
  }),
  relationshipBook({
    id: 'tsengue-preparer-reussir-mariage',
    language: 'fr',
    topics: ['singleness', 'premarital', 'family-of-origin', 'marriage-crisis', 'divorce'],
    lifeStages: ['single', 'dating', 'engaged', 'married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'Spans singleness, engagement customs, marriage preparation, couple crises and divorce in a Francophone African context.',
      fr: 'Parcourt le célibat, les coutumes de fiançailles, la préparation au mariage, les crises de couple et le divorce dans un contexte africain francophone.',
    },
    title: 'Se préparer à réussir son mariage',
    author: 'Alain Patrick Tsengue',
    publisher: 'ACER Paris',
    url: 'https://www.acerparis.fr/project/se-preparer-a-reussir-son-mariage/',
  }),

  // English-language books from African authors and ministries
  relationshipBook({
    id: 'okonkwo-who-should-i-marry',
    topics: ['discernment', 'dating', 'premarital'],
    lifeStages: ['single', 'dating'],
    description: {
      en: 'A concise Nigerian guide to the questions involved in choosing a marriage partner.',
      fr: "Un guide nigérian concis sur les questions à examiner dans le choix d'un conjoint.",
    },
    title: 'Who Should I Marry?',
    author: 'Kingsley Okonkwo',
    publisher: 'Life Design Ministry',
    url: 'https://www.ldmwithpk.org/ustbooks/',
  }),
  relationshipBook({
    id: 'okonkwo-when-am-i-ready',
    topics: ['singleness', 'dating', 'discernment', 'character'],
    lifeStages: ['single', 'dating'],
    description: {
      en: 'Focuses discernment on personal readiness and character before beginning or deepening a relationship.',
      fr: "Centre le discernement sur la maturité personnelle et le caractère avant de commencer ou d'approfondir une relation.",
    },
    title: 'When Am I Ready?',
    author: 'Kingsley Okonkwo',
    publisher: 'Life Design Ministry',
    url: 'https://www.ldmwithpk.org/ustbooks/',
  }),
  relationshipBook({
    id: 'adewale-before-you-say-i-do',
    topics: ['premarital', 'communication', 'family-of-origin'],
    lifeStages: ['engaged'],
    description: {
      en: 'A Nigerian premarital guide for discussing readiness and the practical foundations of a shared home.',
      fr: "Un guide prémarital nigérian pour parler de la préparation et des fondements pratiques d'un foyer commun.",
    },
    title: 'Before You Say I Do',
    author: 'Bisi Adewale',
    publisher: 'Family Booster Ministries',
    url: 'https://bisiadewale.com/books',
  }),
  relationshipBook({
    id: 'adewale-just-after-you-say-i-do',
    topics: ['marriage', 'communication', 'friendship'],
    lifeStages: ['married'],
    description: {
      en: 'Addresses the early adjustments, habits and conversations of newly married life.',
      fr: "Aborde les premiers ajustements, habitudes et conversations de la vie de jeunes mariés.",
    },
    title: 'Just After You Say I Do',
    author: 'Bisi Adewale',
    publisher: 'Family Booster Ministries',
    url: 'https://bisiadewale.com/books',
  }),
  relationshipBook({
    id: 'emmanuel-love-is-not-enough',
    topics: ['discernment', 'dating', 'character'],
    lifeStages: ['single', 'dating'],
    description: {
      en: 'Challenges singles to examine maturity, compatibility and preparation beyond romantic feeling alone.',
      fr: 'Invite les célibataires à examiner la maturité, la compatibilité et la préparation au-delà du seul sentiment amoureux.',
    },
    title: 'Love Is Not Enough',
    author: 'Olumide Emmanuel',
    publisher: 'Xulon Press',
    url: 'https://bookstore.xulonpress.com/bookdetail.php?PB_ISBN=9781619047495',
  }),
  relationshipBook({
    id: 'fowowe-unbroken',
    topics: ['marriage', 'conflict', 'forgiveness', 'family'],
    lifeStages: ['married'],
    description: {
      en: 'A marriage-strengthening resource written from an African family-systems and coaching perspective.',
      fr: 'Une ressource pour fortifier le mariage écrite dans une perspective africaine de systèmes familiaux et de coaching.',
    },
    title: 'UNBROKEN: How Couples Can Build Marriages That Last Forever',
    author: 'Praise Fowowe',
    publisher: 'Family House Africa',
    url: 'https://www.familyhouseafrica.com/store',
  }),
  relationshipBook({
    id: 'fowowe-out-of-box-parenting',
    topics: ['parenting', 'children', 'family-discipleship', 'family'],
    lifeStages: ['married'],
    description: {
      en: "Helps parents examine a child's strengths, the surrounding family system and intentional ways to build connection.",
      fr: "Aide les parents à discerner les forces de l'enfant, le système familial qui l'entoure et des moyens intentionnels de créer du lien.",
    },
    title: 'Out of the Box Parenting',
    author: 'Praise Fowowe',
    publisher: 'Family House Africa',
    url: 'https://www.familyhouseafrica.com/store',
  }),
  relationshipBook({
    id: 'heward-mills-model-marriage',
    topics: ['marriage', 'sexual-intimacy', 'marriage-roles', 'family'],
    lifeStages: ['engaged', 'married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A broad marriage manual that includes intimacy and husband-and-wife roles and therefore remains behind sensitive review.',
      fr: "Un manuel général sur le mariage qui comprend l'intimité et les rôles des époux et reste donc soumis à une relecture sensible.",
    },
    title: 'Model Marriage',
    author: 'Dag Heward-Mills',
    publisher: 'Parchment House',
    url: 'https://daghewardmillsbooks.org/new/product-category/marriage/',
  }),
  relationshipBook({
    id: 'funke-adejumo-marriage-destiny',
    topics: ['covenant', 'mission', 'marriage', 'marriage-roles'],
    lifeStages: ['engaged', 'married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'Connects marriage with calling and destiny; its role framework needs review before recommendation.',
      fr: 'Relie le mariage à la vocation et à la destinée ; son cadre sur les rôles doit être relu avant toute recommandation.',
    },
    title: 'Marriage Is for Destiny',
    author: 'Funke Felix-Adejumo',
    publisher: 'Funke Felix-Adejumo',
    url: 'https://funkefelixadejumo.org/product/marriage-is-for-destiny/',
  }),
  relationshipBook({
    id: 'felix-adejumo-woman-in-your-house',
    topics: ['marriage', 'communication', 'marriage-roles'],
    lifeStages: ['married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      en: 'A husband-and-wife roles title recorded for review before it can be matched to role-sensitive marriage days.',
      fr: "Un titre sur les rôles de l'époux et de l'épouse, enregistré pour relecture avant toute recommandation dans les jours sensibles aux rôles.",
    },
    title: 'The Woman in Your House',
    author: 'Felix Adejumo',
    publisher: 'Felix Adejumo Ministries',
    url: 'https://felixadejumo.com/about-felix-adejumo/',
  }),

  // ───────────────────────────────────────────────────────────────────────────
  // German-language books
  // ───────────────────────────────────────────────────────────────────────────
  // These are NOT translations of the English list — they are what a German
  // reader would actually be handed in a German-speaking church, which is the
  // point of the per-language tiers in src/lib/resources.js. Publisher pages
  // were checked individually on the date in VERIFIED_AT; titles whose print
  // run has ended carry `available: false` rather than a link to a shop that
  // will tell the reader "vergriffen".
  relationshipBook({
    id: 'berger-partner-fuers-leben',
    language: 'de',
    topics: ['discernment', 'dating', 'future-spouse', 'character'],
    lifeStages: ['single', 'dating'],
    description: {
      de: 'Ein Paartherapeut zeigt, wie Beziehungsfähigkeit wächst und wie man bei der Partnerwahl klug hinschaut, statt nur auf Gefühle zu setzen.',
      en: 'A couples therapist on growing the capacity for relationship and choosing a partner with open eyes rather than on feeling alone.',
      fr: "Un thérapeute de couple montre comment grandir en capacité relationnelle et choisir un conjoint avec lucidité plutôt que sur le seul ressenti.",
    },
    title: 'Den Partner fürs Leben finden: Beziehungsfähig werden und klug wählen',
    author: 'Jörg Berger',
    publisher: 'Francke',
    url: 'https://www.francke-buch.de/buecher/0/2271/0/joerg-berger-den-partner-fuers-leben-finden/',
  }),
  relationshipBook({
    id: 'berger-mit-offenen-augen-lieben',
    language: 'de',
    topics: ['discernment', 'dating', 'future-spouse'],
    lifeStages: ['single', 'dating'],
    // The publisher describes "Den Partner fürs Leben finden" as the expanded
    // new edition of this title, so it is retired rather than listed twice.
    status: 'retired',
    replacementResourceId: 'berger-partner-fuers-leben',
    available: false,
    description: {
      de: 'Die frühere Ausgabe von „Den Partner fürs Leben finden“ – bitte die erweiterte Neuausgabe verwenden.',
      en: 'The earlier edition of “Den Partner fürs Leben finden” — use the expanded new edition instead.',
      fr: "L'édition antérieure de « Den Partner fürs Leben finden » : utiliser la nouvelle édition augmentée.",
    },
    title: 'Mit offenen Augen lieben',
    author: 'Jörg Berger',
    publisher: 'Francke',
    url: 'https://www.francke-buch.de/buecher/0/2271/0/joerg-berger-den-partner-fuers-leben-finden/',
  }),
  relationshipBook({
    id: 'berger-stacheln-partnerschaft',
    language: 'de',
    topics: ['conflict', 'forgiveness', 'boundaries', 'trust', 'marriage'],
    lifeStages: ['dating', 'engaged', 'married'],
    description: {
      de: 'Benennt sieben wiederkehrende Verletzungsmuster zwischen Partnern – Grenzüberschreitung, Abwertung, Rückzug, Rache – und wie man ihnen begegnet.',
      en: 'Names seven recurring ways partners wound each other — boundary-crossing, belittling, withdrawal, revenge — and how to meet each one.',
      fr: "Nomme sept blessures récurrentes entre conjoints — franchissement des limites, dévalorisation, retrait, vengeance — et comment y répondre.",
    },
    title: 'Stacheln in der Partnerschaft: Wie Sie Ihre Liebe vor Verletzungen schützen',
    author: 'Jörg Berger',
    publisher: 'Francke',
    url: 'https://www.francke-buch.de/buecher/0/2411/0/joerg-berger-stacheln-in-der-partnerschaft/',
  }),
  relationshipBook({
    id: 'berger-garten-der-liebe',
    language: 'de',
    topics: ['marriage', 'spiritual-formation', 'communication', 'friendship'],
    lifeStages: ['engaged', 'married'],
    // Print run ended; the publisher still lists an e-book. A curator should
    // decide whether to point at the e-book edition before this goes live.
    status: 'needs_review',
    available: false,
    description: {
      de: 'Kurze Kapitel mit Checklisten und Gesprächsimpulsen darüber, wie Liebe – wie ein Garten – gepflegt und geschützt sein will.',
      en: 'Short chapters with checklists and conversation starters on tending love the way a garden is tended and protected.',
      fr: "De courts chapitres, avec listes et amorces de conversation, sur l'amour qui se cultive et se protège comme un jardin.",
    },
    title: 'Der Garten der Liebe: Anleitung zur blühenden Zweisamkeit',
    author: 'Jörg Berger',
    publisher: 'SCM Hänssler',
    url: 'https://www.scm-shop.de/der-garten-der-liebe.html',
  }),
  relationshipBook({
    id: 'berger-liebe-laesst-sich-lernen',
    language: 'de',
    topics: ['marriage', 'communication', 'conflict'],
    lifeStages: ['dating', 'engaged', 'married'],
    // General-market psychology from an academic publisher, with no faith
    // frame and a host that puts the reader through a login redirect. Recorded
    // for a curator rather than published.
    status: 'needs_review',
    description: {
      de: 'Paarpsychologie ohne Glaubensbezug, beim Wissenschaftsverlag erschienen – vor einer Empfehlung zu prüfen.',
      en: 'Couple psychology with no faith frame, from an academic publisher — to be checked before it is recommended here.',
      fr: "Psychologie du couple sans cadre de foi, chez un éditeur scientifique — à vérifier avant toute recommandation ici.",
    },
    title: 'Liebe lässt sich lernen: Wege zu einer tragfähigen Paarbeziehung',
    author: 'Jörg Berger',
    publisher: 'Springer',
    url: 'https://www.springer.com/de/book/9783642376979',
  }),
  relationshipBook({
    id: 'schmidt-liebeslust',
    language: 'de',
    topics: ['sexual-intimacy', 'sexuality', 'marriage'],
    lifeStages: ['married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      de: 'Eine Sexologin über erschöpfte Sexualität in langen Ehen; wegen der Thematik erst nach den beiden Freigaben empfehlbar.',
      en: 'A sexologist on tired sexuality in long marriages; the subject means it needs both sign-offs before it can be recommended.',
      fr: "Une sexologue sur la sexualité épuisée des longs mariages ; le sujet exige les deux validations avant toute recommandation.",
    },
    title: 'Liebeslust: Unverschämt und echt genießen',
    author: 'Veronika Schmidt',
    publisher: 'SCM Hänssler',
    url: 'https://www.scm-shop.de/liebeslust.html',
  }),
  relationshipBook({
    id: 'schmidt-alltagslust',
    language: 'de',
    topics: ['sexual-intimacy', 'marriage', 'communication'],
    lifeStages: ['married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      de: 'Über Nähe, die im Alltag von Langzeitpaaren verloren geht; wegen der Thematik erst nach den beiden Freigaben empfehlbar.',
      en: 'On the closeness long-term couples lose to daily life; the subject means it needs both sign-offs first.',
      fr: "Sur l'intimité que la vie quotidienne fait perdre aux couples de longue date ; les deux validations sont requises.",
    },
    title: 'Alltagslust',
    author: 'Veronika Schmidt',
    publisher: 'adeo',
    url: 'https://www.adeo-verlag.de/alltagslust.html',
  }),
  relationshipBook({
    id: 'schmidt-endlich-gleich',
    language: 'de',
    topics: ['marriage-roles', 'identity', 'church'],
    lifeStages: ['single', 'dating', 'engaged', 'married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      de: 'Eine pointierte Auseinandersetzung mit Geschlechterrollen in konservativen Gemeinden; als Rollenthema freigabepflichtig.',
      en: 'A pointed argument about gender roles in conservative churches; a roles title, so it is sign-off gated.',
      fr: "Une prise de position sur les rôles de genre dans les Églises conservatrices ; sujet de rôles, donc soumis à validation.",
    },
    title: 'Endlich gleich! Warum Gott schon immer mit Männern und Frauen rechnet',
    author: 'Veronika Schmidt',
    publisher: 'SCM Hänssler',
    url: 'https://www.scm-shop.de/endlich-gleich.html',
  }),
  relationshipBook({
    id: 'hartl-kunst-frau-lieben',
    language: 'de',
    topics: ['marriage-roles', 'marriage', 'character'],
    lifeStages: ['dating', 'engaged', 'married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      de: 'Ein kurzer, bildstarker Essay darüber, wie ein Mann das Herz einer Frau achten lernt; als Rollenthema freigabepflichtig.',
      en: 'A short, image-rich essay on how a man learns to honour a woman’s heart; a roles title, so it is sign-off gated.',
      fr: "Un court essai très imagé sur la manière dont un homme apprend à honorer le cœur d'une femme ; soumis à validation.",
    },
    title: 'Die Kunst, eine Frau zu lieben: Das große Geheimnis verstehen',
    author: 'Johannes Hartl',
    publisher: 'adeo',
    url: 'https://www.adeo-verlag.de/die-kunst-eine-frau-zu-lieben-7552178.html',
  }),
  relationshipBook({
    id: 'hartl-kunst-mann-lieben',
    language: 'de',
    topics: ['marriage-roles', 'marriage', 'character'],
    lifeStages: ['dating', 'engaged', 'married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      de: 'Das Gegenstück mit konkreten Anregungen, den eigenen Mann zu lieben; als Rollenthema freigabepflichtig.',
      en: 'The companion volume, with concrete suggestions for loving one’s husband; a roles title, so it is sign-off gated.',
      fr: "Le volume jumeau, avec des suggestions concrètes pour aimer son mari ; sujet de rôles, donc soumis à validation.",
    },
    title: 'Die Kunst, meinen Mann zu lieben',
    author: 'Johannes Hartl',
    publisher: 'adeo',
    url: 'https://www.adeo-verlag.de/die-kunst-meinen-mann-zu-lieben-7514571.html',
  }),
  relationshipBook({
    id: 'trobisch-mit-freuden-frau-sein',
    language: 'de',
    topics: ['sexuality', 'identity', 'family'],
    lifeStages: ['single', 'married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    available: false,
    description: {
      de: 'Ein Klassiker von 1977 über Frausein, Zyklus und Fruchtbarkeit; nur noch antiquarisch, medizinisch teils überholt.',
      en: 'A 1977 classic on womanhood, cycle and fertility; secondhand only, and medically dated in places.',
      fr: "Un classique de 1977 sur la féminité, le cycle et la fertilité ; introuvable neuf et médicalement daté par endroits.",
    },
    title: 'Mit Freuden Frau sein: Und was der Mann dazu tun kann',
    author: 'Ingrid Trobisch und Elisabeth Rötzer',
    publisher: 'R. Brockhaus',
    url: 'https://de.wikipedia.org/wiki/Ingrid_Trobisch',
  }),
  relationshipBook({
    id: 'trobisch-allein-leben-lernen',
    language: 'de',
    topics: ['singleness', 'contentment', 'grief'],
    lifeStages: ['single'],
    status: 'needs_review',
    available: false,
    description: {
      de: 'Über das Alleinleben nach Verlust, aus der Erfahrung einer früh verwitweten Autorin; nur noch antiquarisch erhältlich.',
      en: 'On learning to live alone after loss, from an author widowed early; available secondhand only.',
      fr: "Sur l'apprentissage de la vie seule après une perte, par une autrice veuve jeune ; disponible seulement d'occasion.",
    },
    title: 'Allein leben lernen',
    author: 'Ingrid Trobisch',
    publisher: 'R. Brockhaus',
    url: 'https://de.wikipedia.org/wiki/Ingrid_Trobisch',
  }),
  relationshipBook({
    id: 'trobisch-du-bist-mir-wichtig',
    language: 'de',
    topics: ['friendship', 'identity', 'listening'],
    lifeStages: ['single', 'dating', 'engaged', 'married'],
    status: 'needs_review',
    available: false,
    description: {
      de: 'Über das Gestalten tragfähiger Beziehungen als Frau; nur noch antiquarisch erhältlich.',
      en: 'On shaping durable relationships as a woman; available secondhand only.',
      fr: "Sur la construction de relations durables en tant que femme ; disponible seulement d'occasion.",
    },
    title: 'Du bist mir wichtig: Als Frau Beziehungen gestalten',
    author: 'Ingrid Trobisch',
    publisher: 'R. Brockhaus',
    url: 'https://de.wikipedia.org/wiki/Ingrid_Trobisch',
  }),
  relationshipBook({
    id: 'ruthe-wie-liebe-gelingt',
    language: 'de',
    topics: ['marriage', 'communication', 'conflict', 'covenant', 'premarital'],
    lifeStages: ['engaged', 'married'],
    description: {
      de: 'Siebenundzwanzig Empfehlungen aus fünfzig Jahren Eheberatung, knapp und ohne Umschweife formuliert.',
      en: 'Twenty-seven recommendations distilled from fifty years of marriage counselling, put plainly and without padding.',
      fr: "Vingt-sept recommandations tirées de cinquante ans de conseil conjugal, formulées sans détour.",
    },
    title: 'Wie Liebe ein Leben lang gelingt: Meine wichtigsten Empfehlungen aus 50 Jahren Eheberatung',
    author: 'Reinhold Ruthe',
    publisher: 'Kawohl',
    url: 'https://www.fontis-shop.de/products/wie-liebe-ein-leben-lang-gelingt',
  }),
  relationshipBook({
    id: 'ruthe-so-stell-ich-mir-die-liebe-vor',
    language: 'de',
    topics: ['dating', 'discernment', 'character'],
    lifeStages: ['single', 'dating'],
    status: 'needs_review',
    available: false,
    description: {
      de: 'Ein frühes Werk über Verliebtsein und Partnerwahl; vergriffen und vom Autor später als „Mehr als ein Gefühl“ überarbeitet.',
      en: 'An early title on falling in love and choosing a partner; out of print, later reworked by the author as “Mehr als ein Gefühl”.',
      fr: "Un titre ancien sur l'amour naissant et le choix du conjoint ; épuisé, remanié plus tard sous le titre « Mehr als ein Gefühl ».",
    },
    title: "So stell' ich mir die Liebe vor",
    author: 'Reinhold Ruthe',
    publisher: 'Herder',
    url: 'https://de.wikipedia.org/wiki/Reinhold_Ruthe',
  }),
  relationshipBook({
    id: 'ruthe-mimosen-und-dickhaeuter',
    language: 'de',
    topics: ['character', 'communication', 'conflict'],
    lifeStages: ['dating', 'engaged', 'married'],
    status: 'needs_review',
    available: false,
    description: {
      de: 'Über sehr unterschiedliche Empfindsamkeiten in einer Beziehung; vergriffen, nur noch antiquarisch.',
      en: 'On very different thresholds of sensitivity inside one relationship; out of print, secondhand only.',
      fr: "Sur des seuils de sensibilité très différents au sein d'une même relation ; épuisé, seulement d'occasion.",
    },
    title: 'Mimosen und Dickhäuter',
    author: 'Reinhold Ruthe',
    publisher: 'Brendow',
    url: 'https://de.wikipedia.org/wiki/Reinhold_Ruthe',
  }),
  relationshipBook({
    id: 'ruthe-intim-gefragt',
    language: 'de',
    topics: ['sexuality', 'purity'],
    lifeStages: ['single', 'dating', 'engaged', 'married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    available: false,
    description: {
      de: 'Ein Aufklärungsbuch aus den 1960er-Jahren; vergriffen und inhaltlich deutlich zeitgebunden.',
      en: 'A sex-education title from the 1960s; out of print and visibly of its time.',
      fr: "Un ouvrage d'éducation sexuelle des années 1960 ; épuisé et nettement daté.",
    },
    title: 'Intim gefragt, offen geantwortet',
    author: 'Reinhold Ruthe',
    publisher: 'Aussaat',
    url: 'https://de.wikipedia.org/wiki/Reinhold_Ruthe',
  }),
  relationshipBook({
    id: 'lehmann-wenn-kinder-andere-wege-gehen',
    language: 'de',
    topics: ['parenting', 'children', 'family-discipleship'],
    lifeStages: ['married'],
    description: {
      de: 'Für Eltern, deren erwachsene Kinder sich vom Glauben abgewandt haben: wie Beziehung in Klarheit und Liebe offen bleibt.',
      en: 'For parents whose grown children have turned away from faith: how the relationship stays open, in clarity and love.',
      fr: "Pour les parents dont les enfants adultes se sont détournés de la foi : comment garder la relation ouverte, avec clarté et amour.",
    },
    title: 'Wenn Kinder andere Wege gehen: Wie Beziehungen in Klarheit und Liebe möglich bleiben',
    author: 'Regula Lehmann und Nicola Vollkommer',
    publisher: 'Fontis',
    url: 'https://www.fontis-shop.de/products/wenn-kinder-andere-wege-gehen',
  }),
  relationshipBook({
    id: 'lehmann-sexualerziehung-familiensache',
    language: 'de',
    topics: ['parenting', 'sexuality', 'children', 'family'],
    lifeStages: ['married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      de: 'Für Eltern, die Sexualerziehung selbst in die Hand nehmen wollen; als Sexualthema freigabepflichtig.',
      en: 'For parents who want to take sex education into their own hands; a sexuality title, so it is sign-off gated.',
      fr: "Pour les parents qui veulent assumer eux-mêmes l'éducation sexuelle ; sujet de sexualité, donc soumis à validation.",
    },
    title: 'Sexualerziehung bleibt Familiensache',
    author: 'Regula Lehmann',
    publisher: 'Fontis',
    url: 'https://www.fontis-shop.ch/products/sexualerziehung-bleibt-familiensache',
  }),
  relationshipBook({
    id: 'lehmann-wir-powergirls',
    language: 'de',
    topics: ['parenting', 'sexuality', 'children'],
    lifeStages: ['married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      de: 'Ein Aufklärungsbuch, das Eltern ihren Töchtern vor der Pubertät in die Hand geben; als Sexualthema freigabepflichtig.',
      en: 'A puberty book parents hand to their daughters; written for the child, so a parent should read it first — sign-off gated.',
      fr: "Un livre sur la puberté que les parents remettent à leurs filles ; écrit pour l'enfant, donc soumis à validation.",
    },
    title: 'Wir Powergirls',
    author: 'Regula Lehmann und Pascal Gläser',
    publisher: 'Fontis',
    url: 'https://www.fontis-shop.de/products/wir-powergirls',
  }),
  relationshipBook({
    id: 'lehmann-rakete-startklar',
    language: 'de',
    topics: ['parenting', 'sexuality', 'children'],
    lifeStages: ['married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      de: 'Das Gegenstück für Jungen zwischen zehn und dreizehn; als Sexualthema freigabepflichtig.',
      en: 'The companion volume for boys aged ten to thirteen; written for the child, and sign-off gated.',
      fr: "Le volume jumeau pour les garçons de dix à treize ans ; écrit pour l'enfant, et soumis à validation.",
    },
    title: 'Rakete startklar!',
    author: 'Regula Lehmann und Pascal Gläser',
    publisher: 'Fontis',
    url: 'https://www.fontis-shop.at/products/rakete-startklar',
  }),
  relationshipBook({
    id: 'mockler-emma-prinzip',
    language: 'de',
    topics: ['marriage', 'conflict', 'communication', 'character', 'premarital'],
    lifeStages: ['engaged', 'married'],
    description: {
      de: 'Sieben Schlüssel zu einer guten Ehe, getragen von einem Gedanken: einer muss mal anfangen – und das kannst du sein.',
      en: 'Seven keys to a good marriage, built on one idea: someone has to start — and it can be you.',
      fr: "Sept clés pour un bon mariage, portées par une idée : il faut bien que quelqu'un commence — et ce peut être vous.",
    },
    title: 'Das Emma*-Prinzip: Sieben Schlüssel zu einer richtig guten Ehe',
    author: 'Susanne und Marcus Mockler',
    publisher: 'adeo',
    url: 'https://www.scm-shop.de/das-emma-prinzip.html',
  }),
  relationshipBook({
    id: 'mockler-da-geht-noch-was',
    language: 'de',
    topics: ['marriage', 'communication', 'friendship', 'conflict'],
    lifeStages: ['married'],
    description: {
      de: 'Sieben konkrete Impulse für Paare, die schon lange zusammen sind und merken, dass Nähe nicht von allein bleibt.',
      en: 'Seven concrete prompts for couples long together who notice that closeness does not maintain itself.',
      fr: "Sept pistes concrètes pour les couples de longue date qui constatent que l'intimité ne se maintient pas toute seule.",
    },
    title: 'Da geht noch was! 7 Liebes-Booster für Langzeitpaare',
    author: 'Susanne und Marcus Mockler',
    publisher: 'adeo',
    url: 'https://www.adeo-verlag.de/da-geht-noch-was-7593506.html',
  }),
  relationshipBook({
    id: 'bangert-wo-bleibt-mein-prinz',
    language: 'de',
    topics: ['singleness', 'contentment', 'trust', 'future-spouse', 'identity'],
    lifeStages: ['single'],
    description: {
      de: 'Von einer lange alleinstehenden Autorin an alleinstehende Frauen: über Sehnsucht, Warten und Vertrauen, ohne fromme Vertröstung.',
      en: 'From an author long single to single women: on longing, waiting and trust, without pious consolation.',
      fr: "D'une autrice longtemps célibataire aux femmes célibataires : sur le désir, l'attente et la confiance, sans consolation pieuse.",
    },
    title: 'Wo bleibt mein Prinz? Warum du Gott voll und ganz vertrauen kannst',
    author: 'Nelli Bangert',
    publisher: 'Gerth Medien',
    url: 'https://www.scm-shop.de/wo-bleibt-mein-prinz-ebook.html',
  }),
  relationshipBook({
    id: 'kuenkler-christliche-singles',
    language: 'de',
    topics: ['singleness', 'church', 'community', 'dating'],
    lifeStages: ['single', 'dating'],
    description: {
      de: 'Eine Studie unter mehr als 3 200 christlichen Singles – hilfreich gegen das Gefühl, mit den eigenen Fragen allein zu sein.',
      en: 'A study of more than 3,200 Christian singles — useful against the sense of being alone with your own questions.',
      fr: "Une étude auprès de plus de 3 200 célibataires chrétiens — utile contre le sentiment d'être seul avec ses questions.",
    },
    title: 'Christliche Singles: Wie sie leben, glauben und lieben',
    author: 'Tobias Künkler, Tobias Faix und Johanna Weddigen',
    publisher: 'SCM R. Brockhaus',
    url: 'https://www.scm-shop.de/christliche-singles.html',
  }),
  relationshipBook({
    id: 'faix-date-your-singles',
    language: 'de',
    topics: ['singleness', 'church', 'community'],
    lifeStages: ['single'],
    description: {
      de: 'Für Gemeinden, die Singles übersehen – und für Singles, die dort ihre Erfahrung wiedererkennen und benennen möchten.',
      en: 'For churches that overlook their singles — and for singles who want their experience named.',
      fr: "Pour les Églises qui oublient leurs célibataires — et pour les célibataires qui veulent voir leur vécu nommé.",
    },
    title: 'Date Your Singles! Wie Gemeinden und Singles endlich zueinanderfinden',
    author: 'Tobias Faix und Johanna Weddigen (Hrsg.)',
    publisher: 'SCM R. Brockhaus',
    url: 'https://www.scm-shop.de/date-your-singles.html',
  }),
  relationshipBook({
    id: 'buth-frau-sein',
    language: 'de',
    topics: ['sexuality', 'identity', 'singleness', 'marriage'],
    lifeStages: ['single', 'dating', 'engaged', 'married'],
    status: 'needs_review',
    reviewLevel: 'sensitive',
    description: {
      de: 'Eine Frauenärztin und Sexualberaterin über weibliche Sexualität und Identität; als Sexualthema freigabepflichtig.',
      en: 'A gynaecologist and sexual counsellor on female sexuality and identity; a sexuality title, so it is sign-off gated.',
      fr: "Une gynécologue et conseillère en sexualité sur la sexualité et l'identité féminines ; soumis à validation.",
    },
    title: 'Frau sein – Sexualität mit Leib und Seele',
    author: 'Ute Buth',
    publisher: 'BoD – Books on Demand',
    url: 'https://buchshop.bod.de/frau-sein-dr-med-ute-buth-9783748147978',
  }),
];

export default RELATIONSHIP_BOOKS;
