// Original commentary and prayer, never generated Scripture text.
// Each day's related references are part of the reading, including the next chapter.
const L = (en, fr) => ({ en, fr });

// [readings, title, reflection, observation, application, practice, prayer]
const curriculum = [
  [
    ['Proverbs 1', 'Proverbs 2', 'James 1:5-8'],
    L('Ask for wisdom', 'Demander la sagesse'),
    L('Proverbs begins with reverence for God and a willingness to learn. James invites those who lack wisdom to ask God: growth begins with dependence, not self-sufficiency.', 'Les Proverbes commencent par le respect de Dieu et la disposition à apprendre. Jacques invite celui qui manque de sagesse à la demander à Dieu : grandir commence par la dépendance et non par la suffisance.'),
    L('Which attitudes towards wisdom do Proverbs 1–2 encourage?', 'Quelles attitudes envers la sagesse Proverbes 1–2 encouragent-ils ?'),
    L('Where do you need wisdom rather than a quick answer?', 'Dans quelle situation as-tu besoin de sagesse plutôt que d’une réponse rapide ?'),
    L('Write one decision in your journal and bring it to God before acting.', 'Note une décision dans ton carnet et présente-la à Dieu avant d’agir.'),
    L('Lord, give me a teachable heart and wisdom for the decision before me.', 'Seigneur, donne-moi un cœur enseignable et la sagesse pour la décision qui m’attend.'),
  ],
  [
    ['Proverbs 3', 'Proverbs 4', 'Matthew 7:24-27'],
    L('Build by practising', 'Construire en mettant en pratique'),
    L('Trust in God shapes the path we take and what we guard in our hearts. Jesus describes a firm foundation as hearing his words and doing them; both houses still face the storm.', 'La confiance en Dieu façonne notre chemin et ce que nous gardons dans notre cœur. Jésus décrit un fondement solide : entendre ses paroles et les pratiquer ; les deux maisons affrontent pourtant la tempête.'),
    L('What distinguishes the two builders in Jesus’ illustration?', 'Qu’est-ce qui distingue les deux bâtisseurs dans l’illustration de Jésus ?'),
    L('Which teaching do you understand but rarely practise?', 'Quel enseignement comprends-tu sans le mettre souvent en pratique ?'),
    L('Choose one instruction from today’s reading and act on it before evening.', 'Choisis une instruction de la lecture et mets-la en pratique avant ce soir.'),
    L('Jesus, help me build my habits on your words.', 'Jésus, aide-moi à bâtir mes habitudes sur tes paroles.'),
  ],
  [
    ['Proverbs 5', 'Proverbs 6', '1 Thessalonians 4:1-8'],
    L('Practise faithfulness', 'Pratiquer la fidélité'),
    L('These chapters connect desire and daily choices with their consequences for others. Paul connects holiness with honouring others rather than exploiting them.', 'Ces chapitres relient les désirs et les choix quotidiens à leurs conséquences pour les autres. Paul associe la sainteté au respect d’autrui plutôt qu’à son exploitation.'),
    L('How do these readings connect private choices with harm to others?', 'Comment ces lectures relient-elles les choix privés au tort causé à autrui ?'),
    L('What boundary would help you live with greater integrity?', 'Quelle limite t’aiderait à vivre avec davantage d’intégrité ?'),
    L('Identify one situation that weakens your integrity and choose a practical boundary.', 'Identifie une situation qui fragilise ton intégrité et choisis une limite concrète.'),
    L('Lord, teach me to honour others in my desires and actions.', 'Seigneur, apprends-moi à respecter les autres dans mes désirs et mes actes.'),
  ],
  [
    ['Proverbs 7', 'Proverbs 8', 'James 1:13-18'],
    L('Recognise competing invitations', 'Reconnaître les invitations concurrentes'),
    L('Proverbs contrasts seductive speech with wisdom’s public invitation. James traces temptation through desire and distinguishes it from God’s good gifts.', 'Les Proverbes opposent les paroles séductrices à l’appel public de la sagesse. Jacques décrit le chemin de la tentation à partir du désir et la distingue des bons dons de Dieu.'),
    L('What makes the invitations in Proverbs 7 and 8 different?', 'Qu’est-ce qui distingue les invitations de Proverbes 7 et 8 ?'),
    L('Which attractive promise deserves closer examination in your life?', 'Quelle promesse séduisante mérite un examen plus attentif dans ta vie ?'),
    L('Pause before one tempting choice and write its likely consequences for yourself and others.', 'Avant un choix tentant, note ses conséquences probables pour toi et pour les autres.'),
    L('Father, help me recognise temptation and receive what is good.', 'Père, aide-moi à reconnaître la tentation et à accueillir ce qui est bon.'),
  ],
  [
    ['Proverbs 9', 'Proverbs 10', 'Psalm 111'],
    L('Revere God and learn', 'Respecter Dieu et apprendre'),
    L('Wisdom welcomes correction while folly resists it. Psalm 111 places the fear of the Lord alongside his works, faithfulness and justice: reverence grows through attending to who God is.', 'La sagesse accueille la correction tandis que la folie lui résiste. Le Psaume 111 rapproche la crainte du Seigneur de ses œuvres, de sa fidélité et de sa justice : le respect grandit lorsque nous prêtons attention à qui est Dieu.'),
    L('How does Psalm 111 describe the God whom we are called to revere?', 'Comment le Psaume 111 décrit-il le Dieu que nous sommes appelés à respecter ?'),
    L('How does your view of God affect your response to correction?', 'Comment ta vision de Dieu influence-t-elle ta réaction à la correction ?'),
    L('Name one work or quality of God in the psalm and thank him for it.', 'Relève une œuvre ou une qualité de Dieu dans le psaume et remercie-le pour elle.'),
    L('Lord, deepen my reverence through knowing your faithfulness.', 'Seigneur, approfondis mon respect pour toi par la connaissance de ta fidélité.'),
  ],
  [
    ['Proverbs 11', 'Proverbs 12', 'Philippians 2:1-11'],
    L('Choose humility', 'Choisir l’humilité'),
    L('Proverbs links honest conduct with the good of a community. Paul directs the church towards the humility of Christ, whose self-giving challenges rivalry and vanity.', 'Les Proverbes relient la conduite intègre au bien de la communauté. Paul oriente l’Église vers l’humilité du Christ, dont le don de soi remet en question la rivalité et la vanité.'),
    L('What does Paul ask believers to change in their relationships?', 'Que demande Paul aux croyants de changer dans leurs relations ?'),
    L('Where does the desire to be noticed shape your behaviour?', 'Dans quel domaine le désir d’être remarqué façonne-t-il ton comportement ?'),
    L('Do one useful act of service without seeking recognition.', 'Accomplis un service utile sans chercher à être reconnu.'),
    L('Jesus, shape my relationships through your humility.', 'Jésus, façonne mes relations par ton humilité.'),
  ],
  [
    ['Proverbs 13', 'Proverbs 14', 'Hebrews 12:5-11'],
    L('Remain teachable', 'Rester enseignable'),
    L('The wise person learns instead of treating correction as an enemy. Hebrews speaks of God’s formative discipline; it does not give us permission to declare every hardship a punishment for a particular fault.', 'La personne sage apprend au lieu de considérer la correction comme une ennemie. Hébreux parle de la discipline formatrice de Dieu ; cela ne nous autorise pas à déclarer chaque difficulté punition d’une faute particulière.'),
    L('What fruit does Hebrews associate with discipline?', 'Quel fruit Hébreux associe-t-il à la discipline ?'),
    L('Which helpful correction have you been resisting?', 'À quelle correction utile résistes-tu ?'),
    L('Review this week’s notes and choose one habit to continue practising.', 'Relis tes notes de la semaine et choisis une habitude à continuer de pratiquer.'),
    L('Father, help me receive correction that leads towards righteousness and peace.', 'Père, aide-moi à recevoir la correction qui conduit vers la justice et la paix.'),
  ],
  [
    ['Proverbs 15', 'Proverbs 16', 'James 3:1-12'],
    L('Speak with care', 'Parler avec attention'),
    L('A gentle answer can change the direction of a conflict. James exposes the contradiction of blessing God while cursing people made in his likeness.', 'Une réponse douce peut changer la direction d’un conflit. Jacques expose la contradiction qui consiste à bénir Dieu tout en maudissant des personnes faites à sa ressemblance.'),
    L('Which images does James use to show the influence of speech?', 'Quelles images Jacques emploie-t-il pour montrer l’influence de la parole ?'),
    L('Which pattern in your speech needs to change?', 'Quelle habitude dans tes paroles a besoin de changer ?'),
    L('Before a difficult conversation, prepare one truthful and gentle sentence.', 'Avant une conversation difficile, prépare une phrase vraie et douce.'),
    L('Lord, make my words truthful and life-giving.', 'Seigneur, rends mes paroles vraies et bienfaisantes.'),
  ],
  [
    ['Proverbs 17', 'Proverbs 18', 'James 1:19-20'],
    L('Listen before answering', 'Écouter avant de répondre'),
    L('Proverbs warns against answering before listening and trusting the first account without examination. James places listening ahead of speech and anger.', 'Les Proverbes mettent en garde contre la réponse avant l’écoute et l’acceptation d’un premier récit sans examen. Jacques place l’écoute avant la parole et la colère.'),
    L('What errors follow from speaking before understanding?', 'Quelles erreurs découlent du fait de parler avant de comprendre ?'),
    L('Who needs your attention more than your advice?', 'Qui a davantage besoin de ton attention que de tes conseils ?'),
    L('In one conversation, summarise what you heard before giving your opinion.', 'Dans une conversation, reformule ce que tu as entendu avant de donner ton avis.'),
    L('Lord, slow my reactions and teach me to listen.', 'Seigneur, ralentis mes réactions et apprends-moi à écouter.'),
  ],
  [
    ['Proverbs 19', 'Proverbs 20', 'Romans 12:17-21'],
    L('Respond without revenge', 'Répondre sans vengeance'),
    L('Patience restrains the impulse to retaliate. Paul calls believers to overcome evil with good, while recognising that peace does not depend on one person alone.', 'La patience retient l’impulsion de rendre le mal. Paul appelle les croyants à surmonter le mal par le bien, tout en reconnaissant que la paix ne dépend pas d’une seule personne.'),
    L('What does Paul ask us to do, and what does he entrust to God?', 'Que nous demande Paul de faire, et que remet-il à Dieu ?'),
    L('Where are you tempted to repay an injury?', 'Où es-tu tenté de rendre une offense ?'),
    L('Choose a response that refuses retaliation while preserving appropriate boundaries.', 'Choisis une réponse qui refuse la vengeance tout en gardant des limites appropriées.'),
    L('God of justice, free me from revenge and guide my response.', 'Dieu de justice, libère-moi de la vengeance et guide ma réponse.'),
  ],
  [
    ['Proverbs 21', 'Proverbs 22', 'James 2:1-9'],
    L('Honour people without favouritism', 'Respecter chacun sans favoritisme'),
    L('Proverbs gives attention to justice and the poor. James confronts a community that gives better treatment to the wealthy, making love of neighbour a test of its conduct.', 'Les Proverbes portent attention à la justice et aux pauvres. Jacques confronte une communauté qui traite mieux les riches, faisant de l’amour du prochain un critère de sa conduite.'),
    L('How does James expose the reasoning behind favouritism?', 'Comment Jacques révèle-t-il le raisonnement qui nourrit le favoritisme ?'),
    L('Whose status influences the attention you give them?', 'Le statut de qui influence-t-il l’attention que tu lui accordes ?'),
    L('Give time and attention to someone you tend to overlook.', 'Accorde du temps et de l’attention à quelqu’un que tu as tendance à négliger.'),
    L('Lord, teach me to see and honour my neighbour.', 'Seigneur, apprends-moi à voir et à respecter mon prochain.'),
  ],
  [
    ['Proverbs 23', 'Proverbs 24', 'Luke 12:13-21'],
    L('Examine your ambitions', 'Examiner ses ambitions'),
    L('Proverbs warns against exhausting ourselves to become rich and envying the wicked. Jesus’ parable questions security built on possessions without being rich towards God.', 'Les Proverbes avertissent contre l’épuisement pour devenir riche et l’envie des méchants. La parabole de Jésus interroge une sécurité fondée sur les biens sans être riche pour Dieu.'),
    L('What does the rich man assume about his future?', 'Que suppose l’homme riche au sujet de son avenir ?'),
    L('Which ambition risks crowding out faithfulness?', 'Quelle ambition risque de prendre la place de la fidélité ?'),
    L('Review one spending or work decision in light of generosity and your actual limits.', 'Examine une décision de dépense ou de travail à la lumière de la générosité et de tes limites réelles.'),
    L('Father, reorder my ambitions around what matters to you.', 'Père, réoriente mes ambitions vers ce qui compte à tes yeux.'),
  ],
  [
    ['Proverbs 25', 'Proverbs 26', 'Colossians 4:5-6'],
    L('Discern how to answer', 'Discerner comment répondre'),
    L('Proverbs 26:4–5 places two different responses to folly side by side. Wisdom considers the situation; Paul likewise calls for gracious speech suited to each person.', 'Proverbes 26.4–5 place côte à côte deux réponses différentes à la folie. La sagesse considère la situation ; Paul appelle lui aussi à une parole pleine de grâce adaptée à chacun.'),
    L('What different dangers do Proverbs 26:4 and 26:5 address?', 'À quels dangers différents Proverbes 26.4 et 26.5 répondent-ils ?'),
    L('When would your response help, and when would it merely fuel an argument?', 'Quand ta réponse aiderait-elle, et quand alimenterait-elle seulement une dispute ?'),
    L('Pause before replying to a provocative message and decide whether an answer serves the good.', 'Marque une pause avant de répondre à un message provocateur et détermine si une réponse sert le bien.'),
    L('Lord, give me discernment about when and how to speak.', 'Seigneur, donne-moi le discernement pour savoir quand et comment parler.'),
  ],
  [
    ['Proverbs 27', 'Proverbs 28', 'Galatians 6:1-5'],
    L('Receive faithful friendship', 'Accueillir une amitié fidèle'),
    L('Faithful friendship can include uncomfortable truth. Paul joins restoration with gentleness and self-examination, so helping another never becomes an excuse for superiority.', 'Une amitié fidèle peut comporter une vérité inconfortable. Paul associe le relèvement à la douceur et à l’examen de soi, afin que l’aide à autrui ne devienne jamais un prétexte à la supériorité.'),
    L('What safeguards does Galatians give to those who correct others?', 'Quelles précautions Galates donne-t-il à ceux qui corrigent autrui ?'),
    L('Can someone close to you speak honestly without fear of your reaction?', 'Un proche peut-il te parler honnêtement sans craindre ta réaction ?'),
    L('Review the week and ask a trusted person for feedback on one specific habit.', 'Fais le bilan de la semaine et demande à une personne de confiance un avis sur une habitude précise.'),
    L('Jesus, make me a gentle friend who can also receive the truth.', 'Jésus, fais de moi un ami doux qui sait aussi recevoir la vérité.'),
  ],
  [
    ['Proverbs 29', 'Proverbs 30', 'Proverbs 31', 'Mark 10:42-45'],
    L('Use responsibility to serve', 'Exercer ses responsabilités pour servir'),
    L('These chapters connect leadership with justice, acknowledge human limits and portray wise work and generosity. Jesus defines greatness through service rather than domination.', 'Ces chapitres relient la direction à la justice, reconnaissent les limites humaines et décrivent le travail sage et généreux. Jésus définit la grandeur par le service plutôt que par la domination.'),
    L('Who benefits from the wise use of influence in these readings?', 'Qui bénéficie d’un usage sage de l’influence dans ces lectures ?'),
    L('How could your responsibility become a form of service today?', 'Comment ta responsabilité pourrait-elle devenir une forme de service aujourd’hui ?'),
    L('Use one resource or responsibility to meet another person’s concrete need.', 'Emploie une ressource ou une responsabilité pour répondre au besoin concret d’une autre personne.'),
    L('Jesus, teach me to lead and work as one who serves.', 'Jésus, apprends-moi à diriger et à travailler en serviteur.'),
  ],
  [
    ['Ecclesiastes 1', 'Ecclesiastes 2', 'Matthew 6:19-24'],
    L('Examine what lasts', 'Examiner ce qui demeure'),
    L('Ecclesiastes tests pleasure, achievement and wisdom against mortality and the inability to keep the fruits of our work. Jesus asks where our treasure and allegiance lie.', 'L’Ecclésiaste confronte le plaisir, les réalisations et la sagesse à la mortalité et à l’impossibilité de garder le fruit de notre travail. Jésus demande où se trouvent notre trésor et notre allégeance.'),
    L('What can the pursuits in Ecclesiastes provide, and what can they not secure?', 'Que peuvent apporter les recherches de l’Ecclésiaste, et que ne peuvent-elles pas garantir ?'),
    L('What are you asking achievement to give you?', 'Qu’attends-tu de tes réussites ?'),
    L('Write down your three main pursuits and examine what each promises you.', 'Note tes trois principales recherches et examine ce que chacune te promet.'),
    L('Lord, help me treasure what draws my heart towards you.', 'Seigneur, aide-moi à chérir ce qui rapproche mon cœur de toi.'),
  ],
  [
    ['Ecclesiastes 3', 'Ecclesiastes 4', 'Romans 12:9-16'],
    L('Live your season with others', 'Vivre sa saison avec les autres'),
    L('Ecclesiastes names changing seasons, oppression and the help of companionship. Romans gives relational shape to faithful living through hospitality, shared joy and shared sorrow.', 'L’Ecclésiaste nomme les saisons changeantes, l’oppression et l’aide de la compagnie. Romains donne une forme relationnelle à la fidélité par l’hospitalité, la joie partagée et les larmes partagées.'),
    L('How does companionship answer some of the troubles in Ecclesiastes 4?', 'Comment la compagnie répond-elle à certaines difficultés d’Ecclésiaste 4 ?'),
    L('Who could walk with you in your present season?', 'Qui pourrait marcher avec toi dans ta saison actuelle ?'),
    L('Make room for a conversation in which you share a real joy or burden.', 'Fais place à une conversation où tu partages une joie ou un fardeau réel.'),
    L('Father, teach me to receive and offer faithful companionship.', 'Père, apprends-moi à recevoir et à offrir une présence fidèle.'),
  ],
  [
    ['Ecclesiastes 5', 'Ecclesiastes 6', '1 Timothy 6:6-10', '1 Timothy 6:17-19'],
    L('Receive enough with gratitude', 'Recevoir le nécessaire avec reconnaissance'),
    L('Wealth cannot guarantee satisfaction or even the ability to enjoy it. Paul joins contentment to generosity and directs hope towards God rather than uncertain riches.', 'La richesse ne garantit ni la satisfaction ni même la capacité d’en profiter. Paul associe le contentement à la générosité et oriente l’espérance vers Dieu plutôt que vers des richesses incertaines.'),
    L('What distinguishes possessing wealth from placing hope in it?', 'Qu’est-ce qui distingue le fait de posséder des biens de celui d’y placer son espérance ?'),
    L('Where is comparison making it hard for you to recognise enough?', 'Où la comparaison t’empêche-t-elle de reconnaître ce qui est suffisant ?'),
    L('Name three gifts you already enjoy and choose one realistic act of generosity.', 'Nomme trois dons dont tu profites déjà et choisis un acte de générosité à ta portée.'),
    L('God, grow gratitude and generosity in the way I use what I have.', 'Dieu, fais grandir la reconnaissance et la générosité dans mon usage de ce que je possède.'),
  ],
  [
    ['Ecclesiastes 7', 'Ecclesiastes 8', 'James 3:13-18'],
    L('Recognise wisdom by its fruit', 'Reconnaître la sagesse à ses fruits'),
    L('Ecclesiastes challenges pretended mastery and admits the difficulty of understanding God’s work. James identifies wisdom through humble conduct, mercy and peace rather than rivalry.', 'L’Ecclésiaste remet en question la prétention à tout maîtriser et reconnaît la difficulté de comprendre l’œuvre de Dieu. Jacques reconnaît la sagesse à la conduite humble, à la miséricorde et à la paix plutôt qu’à la rivalité.'),
    L('What qualities distinguish the two kinds of wisdom in James?', 'Quelles qualités distinguent les deux sortes de sagesse chez Jacques ?'),
    L('What fruit is your present way of handling conflict producing?', 'Quels fruits ta manière actuelle de gérer les conflits produit-elle ?'),
    L('Choose one quality from James 3:17 to practise in a difficult relationship.', 'Choisis une qualité de Jacques 3.17 à pratiquer dans une relation difficile.'),
    L('Lord, form in me wisdom that is gentle, merciful and peaceable.', 'Seigneur, forme en moi une sagesse douce, miséricordieuse et paisible.'),
  ],
  [
    ['Ecclesiastes 9', 'Ecclesiastes 10', 'Ephesians 5:15-20'],
    L('Use your time wisely', 'Employer son temps avec sagesse'),
    L('Ecclesiastes urges wholehearted living within an unpredictable world. Ephesians calls for careful living, understanding the Lord’s will and a life of thanksgiving.', 'L’Ecclésiaste invite à vivre pleinement dans un monde imprévisible. Éphésiens appelle à une conduite attentive, à la recherche de la volonté du Seigneur et à une vie de reconnaissance.'),
    L('How do these readings combine urgency with ordinary daily life?', 'Comment ces lectures associent-elles l’urgence à la vie quotidienne ordinaire ?'),
    L('Which use of time is out of step with your stated priorities?', 'Quel usage de ton temps contredit les priorités que tu affirmes ?'),
    L('Adjust one part of tomorrow’s schedule to make space for a neglected responsibility or relationship.', 'Ajuste une partie du programme de demain pour une responsabilité ou une relation négligée.'),
    L('Lord, teach me to use today attentively and gratefully.', 'Seigneur, apprends-moi à vivre aujourd’hui avec attention et reconnaissance.'),
  ],
  [
    ['Ecclesiastes 11', 'Ecclesiastes 12', 'Psalm 90:12-17'],
    L('Act without controlling everything', 'Agir sans tout maîtriser'),
    L('Ecclesiastes encourages action even when outcomes remain unknown and closes with accountability before God. Psalm 90 turns the brevity of life into a prayer for wisdom and meaningful work.', 'L’Ecclésiaste encourage l’action même lorsque les résultats restent inconnus et se termine sur notre responsabilité devant Dieu. Le Psaume 90 transforme la brièveté de la vie en une prière pour la sagesse et un travail qui porte du fruit.'),
    L('What does the psalm ask God to do in the face of human limits?', 'Que demande le psaume à Dieu face aux limites humaines ?'),
    L('What good action are you postponing until you feel completely certain?', 'Quelle bonne action reportes-tu jusqu’à te sentir entièrement certain ?'),
    L('Review this week and take one modest, responsible step you have been delaying.', 'Fais le bilan de la semaine et accomplis un petit pas responsable que tu reportais.'),
    L('Lord, teach me to number my days and establish the work of my hands.', 'Seigneur, apprends-moi à compter mes jours et affermis l’œuvre de mes mains.'),
  ],
  [
    ['Job 1', 'Job 2', 'Romans 12:15'],
    L('Be present in suffering', 'Être présent dans la souffrance'),
    L('The narrator presents Job as upright before describing his losses. His friends initially sit with him in silence; Romans calls us to weep with those who weep.', 'Le narrateur présente Job comme intègre avant de décrire ses pertes. Ses amis s’assoient d’abord avec lui en silence ; Romains nous appelle à pleurer avec ceux qui pleurent.'),
    L('What does the narrator tell the reader that Job himself does not know?', 'Que dit le narrateur au lecteur que Job lui-même ne sait pas ?'),
    L('Can you be present without having an explanation to offer?', 'Peux-tu être présent sans avoir d’explication à offrir ?'),
    L('Offer a grieving person a concrete form of support, allowing them to decline.', 'Propose une aide concrète à une personne éprouvée, en lui laissant la liberté de refuser.'),
    L('God of compassion, teach me to accompany pain with tenderness.', 'Dieu de compassion, apprends-moi à accompagner la douleur avec tendresse.'),
  ],
  [
    ['Job 3', 'Job 4', 'Psalm 13'],
    L('Bring your lament to God', 'Présenter sa plainte à Dieu'),
    L('Job gives voice to devastating anguish, while Eliphaz begins to interpret his condition. Psalm 13 shows that questions and cries for help can belong within prayer.', 'Job exprime une angoisse dévastatrice tandis qu’Éliphaz commence à interpréter sa situation. Le Psaume 13 montre que les questions et les appels au secours peuvent faire partie de la prière.'),
    L('How does the psalm move between distress, petition and trust?', 'Comment le psaume passe-t-il de la détresse à la demande et à la confiance ?'),
    L('Which honest words have you been withholding from prayer?', 'Quelles paroles honnêtes retiens-tu dans ta prière ?'),
    L('Write a short lament naming your pain and what you ask of God.', 'Écris une courte plainte qui nomme ta douleur et ce que tu demandes à Dieu.'),
    L('Lord, receive the pain I struggle to put into words.', 'Seigneur, accueille la douleur que je peine à mettre en mots.'),
  ],
  [
    ['Job 5', 'Job 6', '2 Corinthians 1:3-7'],
    L('Offer genuine comfort', 'Offrir une consolation véritable'),
    L('Eliphaz offers explanations, but Job asks for loyal kindness in his distress. Paul describes comfort received from God that equips believers to comfort others.', 'Éliphaz propose des explications, mais Job demande une bonté fidèle dans sa détresse. Paul décrit une consolation reçue de Dieu qui rend les croyants capables de consoler autrui.'),
    L('What does Job say he needs from his friends?', 'De quoi Job dit-il avoir besoin de la part de ses amis ?'),
    L('Does your comfort leave room for another person’s experience?', 'Ta consolation laisse-t-elle place à l’expérience de l’autre ?'),
    L('Replace a ready-made explanation with a sincere offer to listen.', 'Remplace une explication toute faite par une offre sincère d’écoute.'),
    L('Father of compassion, make me a considerate bearer of comfort.', 'Père de compassion, fais de moi un porteur attentif de consolation.'),
  ],
  [
    ['Job 7', 'Job 8', 'John 9:1-3'],
    L('Refuse hasty blame', 'Refuser les accusations hâtives'),
    L('Bildad treats suffering as evidence for his explanation of justice. Jesus rejects the disciples’ proposed link between one man’s blindness and a specific sin by him or his parents.', 'Bildad traite la souffrance comme une preuve de son explication de la justice. Jésus rejette le lien proposé par les disciples entre la cécité d’un homme et un péché précis de cet homme ou de ses parents.'),
    L('What assumptions do Bildad and the disciples bring to suffering?', 'Quelles suppositions Bildad et les disciples apportent-ils à la souffrance ?'),
    L('Where have you confused someone’s hardship with proof of guilt?', 'Où as-tu confondu la difficulté de quelqu’un avec une preuve de culpabilité ?'),
    L('Identify one judgement you need to withdraw because you do not know the facts.', 'Identifie un jugement à retirer parce que tu ne connais pas les faits.'),
    L('Jesus, free me from blame that outruns understanding.', 'Jésus, libère-moi des accusations qui dépassent ce que je comprends.'),
  ],
  [
    ['Job 9', 'Job 10', 'Hebrews 4:14-16'],
    L('Approach God in weakness', 'S’approcher de Dieu dans la faiblesse'),
    L('Job struggles with the distance he feels between himself and God and longs for someone to stand between them. Hebrews invites Christians to approach God through Jesus, the compassionate high priest; it does not claim Job already understood that fulfilment.', 'Job lutte avec la distance qu’il ressent entre lui et Dieu et désire quelqu’un qui se tienne entre eux. Hébreux invite les chrétiens à s’approcher de Dieu par Jésus, grand prêtre compatissant ; cela ne signifie pas que Job comprenait déjà cet accomplissement.'),
    L('On what basis does Hebrews invite believers to approach God confidently?', 'Sur quel fondement Hébreux invite-t-il les croyants à s’approcher de Dieu avec assurance ?'),
    L('What weakness makes you hesitate to pray?', 'Quelle faiblesse te fait hésiter à prier ?'),
    L('Bring one need plainly to God without trying to sound stronger than you feel.', 'Présente simplement un besoin à Dieu sans essayer de paraître plus fort que tu ne te sens.'),
    L('Jesus, help me approach the Father for mercy and grace.', 'Jésus, aide-moi à m’approcher du Père pour recevoir miséricorde et grâce.'),
  ],
  [
    ['Job 11', 'Job 12', 'Romans 11:33-36'],
    L('Acknowledge the limits of knowledge', 'Reconnaître les limites du savoir'),
    L('Zophar speaks confidently, and Job challenges his friends’ claim to superior understanding. Paul’s praise of God’s wisdom invites humility before what we cannot fully trace.', 'Tsophar parle avec assurance, et Job conteste la prétention de ses amis à une compréhension supérieure. La louange de Paul devant la sagesse de Dieu invite à l’humilité face à ce que nous ne pouvons pas entièrement saisir.'),
    L('How does Job resist the claim that his friends alone understand wisdom?', 'Comment Job résiste-t-il à la prétention de ses amis de comprendre seuls la sagesse ?'),
    L('Where would saying “I do not know” be more truthful?', 'Où serait-il plus vrai de dire « Je ne sais pas » ?'),
    L('Separate one conviction grounded in Scripture from one explanation you have inferred.', 'Distingue une conviction fondée sur l’Écriture d’une explication que tu as déduite.'),
    L('God, keep my confidence in you greater than my confidence in my explanations.', 'Dieu, que ma confiance en toi dépasse ma confiance dans mes explications.'),
  ],
  [
    ['Job 13', 'Job 14', 'Psalm 42'],
    L('Keep speaking to God', 'Continuer de parler à Dieu'),
    L('Job continues his appeal amid uncertainty and the fragility of human life. Psalm 42 holds longing, tears and renewed hope together without pretending that distress has disappeared.', 'Job poursuit son appel au milieu de l’incertitude et de la fragilité de la vie humaine. Le Psaume 42 tient ensemble le désir, les larmes et une espérance renouvelée sans prétendre que la détresse a disparu.'),
    L('What repeated movement do you notice in Psalm 42?', 'Quel mouvement répété remarques-tu dans le Psaume 42 ?'),
    L('What helps you remain in conversation with God when hope is fragile?', 'Qu’est-ce qui t’aide à rester en conversation avec Dieu lorsque l’espérance est fragile ?'),
    L('Review the week and write one unresolved question you will continue bringing to God.', 'Relis la semaine et note une question non résolue que tu continueras de présenter à Dieu.'),
    L('Lord, meet me in my longing and sustain my hope.', 'Seigneur, rejoins-moi dans mon désir et soutiens mon espérance.'),
  ],
  [
    ['Job 15', 'Job 16', 'Colossians 3:12-15'],
    L('Clothe your words with compassion', 'Revêtir ses paroles de compassion'),
    L('Job describes his friends as miserable comforters and imagines strengthening them if their positions were reversed. Colossians places compassion, patience and love at the centre of community life.', 'Job décrit ses amis comme de pénibles consolateurs et imagine les fortifier si leurs places étaient inversées. Colossiens place la compassion, la patience et l’amour au centre de la vie communautaire.'),
    L('What contrast does Job draw between his friends’ speech and the comfort he wants?', 'Quel contraste Job fait-il entre les paroles de ses amis et la consolation qu’il souhaite ?'),
    L('Would your words feel different if you were in the other person’s place?', 'Tes paroles te paraîtraient-elles différentes si tu étais à la place de l’autre ?'),
    L('Rewrite one harsh response with both honesty and compassion.', 'Reformule une réponse dure en gardant à la fois la vérité et la compassion.'),
    L('Lord, let compassion govern the truth I speak.', 'Seigneur, que la compassion guide la vérité que je prononce.'),
  ],
  [
    ['Job 17', 'Job 18', 'Psalm 88'],
    L('Make room for unresolved grief', 'Faire place à une douleur non résolue'),
    L('Job’s despair meets another speech about the fate of the wicked. Psalm 88 ends in darkness, reminding us that Scripture gives space to prayers without a quick emotional resolution.', 'Le désespoir de Job rencontre un nouveau discours sur le sort des méchants. Le Psaume 88 se termine dans l’obscurité, rappelant que l’Écriture fait place à des prières sans résolution émotionnelle rapide.'),
    L('What does the ending of Psalm 88 allow a suffering person to express?', 'Qu’est-ce que la fin du Psaume 88 permet à une personne souffrante d’exprimer ?'),
    L('Do you feel pressure to make every conversation end positively?', 'Ressens-tu le besoin de terminer chaque conversation sur une note positive ?'),
    L('Give a painful concern space in your journal without adding a forced conclusion.', 'Fais place à une préoccupation douloureuse dans ton carnet sans ajouter de conclusion forcée.'),
    L('God, hear the prayer that still has no words of resolution.', 'Dieu, entends la prière qui ne trouve pas encore de mots de résolution.'),
  ],
  [
    ['Job 19', 'Job 20', 'John 11:17-27'],
    L('Anchor hope in Christ', 'Ancrer l’espérance en Christ'),
    L('Job longs for vindication and speaks of a living redeemer amid abandonment. In John, Jesus explicitly grounds resurrection hope in himself; read that promise without assuming Job possessed the same clarity.', 'Job désire être reconnu juste et parle d’un défenseur vivant au milieu de l’abandon. Dans Jean, Jésus fonde explicitement l’espérance de la résurrection en lui-même ; lis cette promesse sans supposer que Job possédait la même clarté.'),
    L('What does Jesus say to Martha while her grief is still present?', 'Que dit Jésus à Marthe alors que son deuil est encore présent ?'),
    L('How does hope in Jesus differ from confidence that every situation will improve now?', 'En quoi l’espérance en Jésus diffère-t-elle de la certitude que toute situation va s’améliorer maintenant ?'),
    L('Write one sentence of hope grounded in what Jesus actually says in this passage.', 'Écris une phrase d’espérance fondée sur ce que Jésus dit réellement dans ce passage.'),
    L('Jesus, root my hope in you through grief and uncertainty.', 'Jésus, enracine mon espérance en toi au travers du deuil et de l’incertitude.'),
  ],
  [
    ['Job 21', 'Job 22', 'Matthew 5:43-48'],
    L('Do not measure faith by prosperity', 'Ne pas mesurer la foi à la prospérité'),
    L('Job points to the prosperity of the wicked, challenging his friends’ simple equation of conduct and circumstances. Jesus describes the Father’s gifts of sun and rain to both the just and the unjust.', 'Job souligne la prospérité des méchants, contestant l’équation simple de ses amis entre conduite et circonstances. Jésus décrit les dons du Père, soleil et pluie, accordés aux justes comme aux injustes.'),
    L('Which observations in Job 21 challenge the explanations of his friends?', 'Quelles observations de Job 21 remettent en question les explications de ses amis ?'),
    L('Do you treat success as proof of God’s approval?', 'Considères-tu la réussite comme une preuve de l’approbation de Dieu ?'),
    L('Reconsider one judgement about someone that rests mainly on their success or hardship.', 'Réexamine un jugement sur quelqu’un qui repose surtout sur sa réussite ou ses difficultés.'),
    L('Father, teach me to love without judging hearts by outward circumstances.', 'Père, apprends-moi à aimer sans juger les cœurs d’après les circonstances extérieures.'),
  ],
  [
    ['Job 23', 'Job 24', 'Luke 18:1-8'],
    L('Persevere in seeking justice', 'Persévérer dans la recherche de justice'),
    L('Job searches for God and names oppression that seems unanswered. Jesus encourages persistent prayer for justice; the parable does not make God identical to the unjust judge.', 'Job cherche Dieu et nomme une oppression qui semble sans réponse. Jésus encourage la prière persévérante pour la justice ; la parabole n’identifie pas Dieu au juge injuste.'),
    L('How does Jesus contrast God with the judge in the story?', 'Comment Jésus oppose-t-il Dieu au juge du récit ?'),
    L('Which injustice are you tempted to stop bringing before God?', 'Quelle injustice es-tu tenté de cesser de présenter à Dieu ?'),
    L('Pray for one concrete injustice and identify a responsible way to support those affected.', 'Prie pour une injustice concrète et identifie un moyen responsable de soutenir les personnes touchées.'),
    L('God of justice, sustain faithful prayer and responsible action.', 'Dieu de justice, soutiens la prière fidèle et l’action responsable.'),
  ],
  [
    ['Job 25', 'Job 26', 'Psalm 8'],
    L('Hold humility and dignity together', 'Tenir ensemble humilité et dignité'),
    L('Bildad stresses human smallness, and Job describes the vastness of God’s power. Psalm 8 joins wonder at human smallness with the honour and responsibility God gives humanity.', 'Bildad souligne la petitesse humaine et Job décrit l’immensité de la puissance de Dieu. Le Psaume 8 associe l’émerveillement devant la petitesse humaine à l’honneur et à la responsabilité que Dieu accorde à l’humanité.'),
    L('How does Psalm 8 speak about both human limits and human worth?', 'Comment le Psaume 8 parle-t-il à la fois des limites et de la valeur humaines ?'),
    L('Do you confuse humility with treating yourself or others as worthless?', 'Confonds-tu l’humilité avec le fait de te considérer ou de considérer autrui comme sans valeur ?'),
    L('Name one limit to accept and one responsibility to exercise with care.', 'Nomme une limite à accepter et une responsabilité à exercer avec attention.'),
    L('Creator, help me live humbly without forgetting the dignity you give.', 'Créateur, aide-moi à vivre humblement sans oublier la dignité que tu accordes.'),
  ],
  [
    ['Job 27', 'Job 28', '1 Corinthians 1:18-31'],
    L('Seek wisdom beyond human achievement', 'Chercher la sagesse au-delà des exploits humains'),
    L('Job 28 contrasts humanity’s skill in uncovering hidden treasures with its inability to acquire wisdom by those means. Paul points to Christ crucified as God’s wisdom, overturning human boasting.', 'Job 28 oppose l’habileté humaine à découvrir des trésors cachés à son incapacité d’acquérir la sagesse par ces moyens. Paul présente le Christ crucifié comme sagesse de Dieu, renversant l’orgueil humain.'),
    L('Where does Job 28 finally locate wisdom, and how does Paul challenge boasting?', 'Où Job 28 situe-t-il finalement la sagesse, et comment Paul conteste-t-il l’orgueil ?'),
    L('What does the cross challenge in your definition of strength or success?', 'Que remet la croix en question dans ta définition de la force ou de la réussite ?'),
    L('Review this week and rewrite your definition of wisdom using both readings.', 'Fais le bilan de la semaine et réécris ta définition de la sagesse à partir des deux lectures.'),
    L('Jesus crucified, teach me the wisdom that leads away from boasting.', 'Jésus crucifié, enseigne-moi la sagesse qui détourne de l’orgueil.'),
  ],
  [
    ['Job 29', 'Job 30', 'Philippians 4:10-13'],
    L('Remain faithful through change', 'Rester fidèle au travers du changement'),
    L('Job contrasts former honour and service with present humiliation. Paul describes learning contentment in abundance and need; his strength in Christ concerns these circumstances, not unlimited achievement.', 'Job oppose l’honneur et le service passés à son humiliation présente. Paul décrit l’apprentissage du contentement dans l’abondance et le besoin ; sa force en Christ concerne ces circonstances, non une réussite sans limites.'),
    L('Which circumstances does Paul name around his statement about strength in Christ?', 'Quelles circonstances Paul nomme-t-il autour de son affirmation sur la force en Christ ?'),
    L('What change has shaken your sense of identity?', 'Quel changement a ébranlé ton sentiment d’identité ?'),
    L('Name one faithful action still possible in your current circumstances.', 'Nomme une action fidèle encore possible dans tes circonstances actuelles.'),
    L('Christ, strengthen me for faithfulness in the life I have today.', 'Christ, fortifie-moi pour être fidèle dans la vie qui est la mienne aujourd’hui.'),
  ],
  [
    ['Job 31', 'Job 32', 'Psalm 139:23-24'],
    L('Invite honest examination', 'Inviter un examen honnête'),
    L('Job examines his conduct towards vulnerable people, wealth and his own desires before Elihu enters the discussion. The psalm invites God to search us; self-examination need not invent guilt to explain suffering.', 'Job examine sa conduite envers les personnes vulnérables, les richesses et ses désirs avant qu’Élihu entre dans la discussion. Le psaume invite Dieu à nous sonder ; l’examen de soi n’a pas à inventer une culpabilité pour expliquer la souffrance.'),
    L('Which concrete areas of conduct does Job bring into his examination?', 'Quels domaines concrets de conduite Job inclut-il dans son examen ?'),
    L('Which area of your life do you rarely examine honestly?', 'Quel domaine de ta vie examines-tu rarement avec honnêteté ?'),
    L('Review one relationship or responsibility and name any specific repair that is needed.', 'Examine une relation ou une responsabilité et nomme, si nécessaire, une réparation précise.'),
    L('God, search my heart and guide me in a faithful way.', 'Dieu, sonde mon cœur et guide-moi sur un chemin fidèle.'),
  ],
  [
    ['Job 33', 'Job 34', '1 Thessalonians 5:19-22'],
    L('Test the counsel you receive', 'Éprouver les conseils reçus'),
    L('Elihu offers another explanation of God’s dealings with people. His confidence does not remove the need to examine his claims; Paul calls believers to test what they receive and hold fast to what is good.', 'Élihu propose une autre explication de la manière dont Dieu agit avec les humains. Son assurance ne supprime pas la nécessité d’examiner ses affirmations ; Paul appelle les croyants à éprouver ce qu’ils reçoivent et à retenir ce qui est bon.'),
    L('Which claims does Elihu make, and what evidence does he offer?', 'Quelles affirmations Élihu fait-il, et quels appuis leur donne-t-il ?'),
    L('Do you mistake a speaker’s certainty for reliability?', 'Confonds-tu l’assurance d’une personne avec sa fiabilité ?'),
    L('Check one piece of spiritual advice against a passage read in its context.', 'Examine un conseil spirituel à la lumière d’un passage lu dans son contexte.'),
    L('Lord, help me receive what is good with discernment.', 'Seigneur, aide-moi à recevoir ce qui est bon avec discernement.'),
  ],
  [
    ['Job 35', 'Job 36', 'James 1:2-5'],
    L('Ask for endurance and wisdom', 'Demander persévérance et sagesse'),
    L('Elihu discusses suffering and God’s greatness, but his account remains part of the dialogue. James invites believers in trials to seek endurance and wisdom without calling the harm itself good.', 'Élihu parle de la souffrance et de la grandeur de Dieu, mais son propos reste une partie du dialogue. Jacques invite les croyants éprouvés à rechercher persévérance et sagesse sans appeler le mal lui-même un bien.'),
    L('How does James connect trials, endurance and the request for wisdom?', 'Comment Jacques relie-t-il l’épreuve, la persévérance et la demande de sagesse ?'),
    L('What would faithful endurance look like in your situation?', 'À quoi ressemblerait une persévérance fidèle dans ta situation ?'),
    L('Choose one sustainable step and identify support that could help you take it.', 'Choisis un pas soutenable et identifie le soutien qui pourrait t’aider à l’accomplir.'),
    L('Father, give me wisdom and endurance for the next faithful step.', 'Père, donne-moi sagesse et persévérance pour le prochain pas fidèle.'),
  ],
  [
    ['Job 37', 'Job 38', 'Matthew 6:25-34'],
    L('Attend to God’s creation', 'Prêter attention à la création de Dieu'),
    L('God begins to answer Job with questions about a world Job neither made nor governs. Jesus points to birds and flowers to invite trust in the Father’s care, not to shame those who feel anxious.', 'Dieu commence à répondre à Job par des questions sur un monde que Job n’a ni créé ni gouverné. Jésus montre les oiseaux et les fleurs pour inviter à la confiance dans les soins du Père, non pour humilier les personnes inquiètes.'),
    L('How do the questions in Job 38 change the scale of the conversation?', 'Comment les questions de Job 38 changent-elles l’échelle de la conversation ?'),
    L('What are you trying to control that lies beyond your responsibility?', 'Qu’essaies-tu de maîtriser qui dépasse ta responsabilité ?'),
    L('Observe something in creation and distinguish today’s responsibility from tomorrow’s uncertainties.', 'Observe un élément de la création et distingue ta responsabilité d’aujourd’hui des incertitudes de demain.'),
    L('Creator and Father, help me trust your care while doing today’s work.', 'Créateur et Père, aide-moi à me confier en tes soins tout en accomplissant le travail d’aujourd’hui.'),
  ],
  [
    ['Job 39', 'Job 40', 'Colossians 2:1-3'],
    L('Seek wisdom in Christ', 'Chercher la sagesse en Christ'),
    L('God’s questions continue to expose the limits of Job’s reach and judgement. Colossians directs the church towards Christ, in whom wisdom is found, within a life of encouragement and love.', 'Les questions de Dieu continuent de révéler les limites de la portée et du jugement de Job. Colossiens oriente l’Église vers Christ, en qui se trouve la sagesse, dans une vie d’encouragement et d’amour.'),
    L('What does Paul desire for the community as it comes to know Christ?', 'Que désire Paul pour la communauté qui apprend à connaître Christ ?'),
    L('How can knowing Christ reshape the way you make decisions?', 'Comment connaître Christ peut-il transformer ta manière de décider ?'),
    L('Revisit your decision from day one and describe how the readings have shaped your approach.', 'Reprends ta décision du premier jour et décris comment les lectures ont façonné ton approche.'),
    L('Jesus, deepen my knowledge of you and shape my judgement through your love.', 'Jésus, approfondis ma connaissance de toi et façonne mon jugement par ton amour.'),
  ],
  [
    ['Job 41', 'Job 42', 'James 5:7-11'],
    L('Continue walking in wisdom', 'Continuer de marcher dans la sagesse'),
    L('Job encounters God, his friends are corrected, and he prays for them. James recalls endurance and the Lord’s compassion; Job’s restoration does not promise every sufferer a material compensation or erase those who died.', 'Job rencontre Dieu, ses amis sont repris et il prie pour eux. Jacques rappelle la persévérance et la compassion du Seigneur ; la restauration de Job ne promet pas à chaque personne souffrante une compensation matérielle et n’efface pas ceux qui sont morts.'),
    L('What does God correct in Job 42:7, and what does James ask readers to remember?', 'Que corrige Dieu en Job 42.7, et que demande Jacques aux lecteurs de retenir ?'),
    L('What has changed in your understanding of wisdom since day one?', 'Qu’est-ce qui a changé dans ta compréhension de la sagesse depuis le premier jour ?'),
    L('Choose three practices to continue for the next month, each anchored in a passage from this plan.', 'Choisis trois pratiques à poursuivre pendant le mois à venir, chacune ancrée dans un passage de ce parcours.'),
    L('Lord, keep forming in me a humble, compassionate and faithful wisdom.', 'Seigneur, continue de former en moi une sagesse humble, compatissante et fidèle.'),
  ],
];

export const DAYS = curriculum.map(([refs, theme, reflection, observation, application, practice, prayer], index) => ({
  theme,
  ref: refs[0],
  related: refs.slice(1),
  movement: `week${Math.floor(index / 7) + 1}`,
  resourceTopics: ['wisdom-literature', ...(refs.some((ref) => ref.startsWith('James ')) ? ['wisdom-james'] : [])],
  reflection,
  study: {
    questions: [observation, application],
    synthesis: practice,
    prayer,
  },
}));
