// Authored day titles; prose remains en/fr until real overlays are reviewed.
// Each language follows the same twelve character studies, never a different curriculum.
const titles = {
  en: ['God looks at the heart', 'Trust that becomes courage', 'Seeking God before deciding', 'Waiting without seizing power', 'Accepting correction', 'Keeping faith with others', 'Listening to conscience', 'Repenting without excuses', 'Delighting in God’s presence', 'Receiving everything as grace', 'Sharing with justice', 'Surrendering control to God'],
  fr: ['Dieu regarde au cœur', 'Une confiance qui devient courage', 'Chercher Dieu avant de décider', 'Attendre sans prendre le pouvoir', 'Accepter la correction', 'Rester fidèle à ses engagements', 'Écouter sa conscience', 'Se repentir sans se justifier', 'Se réjouir de la présence de Dieu', 'Tout recevoir comme une grâce', 'Partager avec justice', 'Renoncer à tout maîtriser'],
  de: ['Gott sieht das Herz an', 'Vertrauen, das Mut macht', 'Gott vor Entscheidungen suchen', 'Warten, ohne nach der Macht zu greifen', 'Korrektur annehmen', 'Zusagen treu bleiben', 'Auf das Gewissen hören', 'Umkehren ohne Ausreden', 'Freude an Gottes Gegenwart', 'Alles als Gnade empfangen', 'Gerecht teilen', 'Gott die Kontrolle überlassen'],
  es: ['Dios mira el corazón', 'Una confianza que se vuelve valentía', 'Buscar a Dios antes de decidir', 'Esperar sin tomar el poder', 'Aceptar la corrección', 'Ser fiel a los compromisos', 'Escuchar la conciencia', 'Arrepentirse sin excusas', 'Gozarse en la presencia de Dios', 'Recibir todo como gracia', 'Compartir con justicia', 'Renunciar a controlarlo todo'],
  pt: ['Deus olha para o coração', 'Uma confiança que se torna coragem', 'Buscar a Deus antes de decidir', 'Esperar sem tomar o poder', 'Aceitar a correção', 'Ser fiel aos compromissos', 'Ouvir a consciência', 'Arrepender-se sem desculpas', 'Alegrar-se na presença de Deus', 'Receber tudo como graça', 'Partilhar com justiça', 'Abrir mão do controle'],
  ru: ['Бог смотрит на сердце', 'Доверие, рождающее смелость', 'Искать Бога перед решением', 'Ждать, не захватывая власть', 'Принимать исправление', 'Хранить верность обещаниям', 'Слушать совесть', 'Каяться без оправданий', 'Радоваться Божьему присутствию', 'Принимать всё как благодать', 'Делиться по справедливости', 'Доверить Богу контроль'],
  zh: ['神看重内心', '信靠生出勇气', '决定之前寻求神', '等候而不夺权', '接受劝诫', '信守承诺', '聆听良心', '悔改而不辩解', '以神的同在为乐', '将一切视为恩典', '公正地分享', '放下掌控，交托给神'],
  ja: ['神は心をご覧になる', '勇気を生む信頼', '決断の前に神を求める', '権力を奪わずに待つ', '忠告を受け入れる', '約束を守り続ける', '良心の声を聞く', '言い訳せずに悔い改める', '神の臨在を喜ぶ', 'すべてを恵みとして受け取る', '公平に分かち合う', '支配を手放し神に委ねる'],
  ko: ['하나님은 마음을 보신다', '용기가 되는 신뢰', '결정하기 전에 하나님을 구하기', '권력을 빼앗지 않고 기다리기', '책망을 받아들이기', '약속에 신실하기', '양심의 소리에 귀 기울이기', '변명 없이 회개하기', '하나님의 임재를 기뻐하기', '모든 것을 은혜로 받기', '공정하게 나누기', '통제를 내려놓고 하나님께 맡기기'],
  ar: ['الله ينظر إلى القلب', 'ثقة تتحوّل إلى شجاعة', 'طلب الله قبل اتخاذ القرار', 'الانتظار دون الاستيلاء على السلطة', 'قبول التصحيح', 'الوفاء بالعهود', 'الإصغاء إلى الضمير', 'التوبة دون تبرير', 'الفرح بحضور الله', 'قبول كل شيء كنعمة', 'المشاركة بالعدل', 'التخلّي عن السيطرة لله'],
  fa: ['خدا به دل می‌نگرد', 'اعتمادی که به شجاعت بدل می‌شود', 'جستن خدا پیش از تصمیم‌گیری', 'انتظار بدون تصاحب قدرت', 'پذیرفتن اصلاح', 'وفاداری به تعهدها', 'گوش سپردن به وجدان', 'توبه بدون بهانه', 'شادمانی در حضور خدا', 'پذیرفتن همه چیز همچون فیض', 'تقسیم کردن با عدالت', 'سپردن کنترل به خدا'],
  hi: ['परमेश्वर हृदय को देखता है', 'विश्वास जो साहस बनता है', 'निर्णय से पहले परमेश्वर को खोजना', 'सत्ता छीने बिना प्रतीक्षा करना', 'सुधार को स्वीकार करना', 'वचनों के प्रति निष्ठावान रहना', 'विवेक की आवाज़ सुनना', 'बिना बहाने पश्चाताप करना', 'परमेश्वर की उपस्थिति में आनंदित होना', 'सब कुछ अनुग्रह के रूप में पाना', 'न्याय के साथ बाँटना', 'नियंत्रण परमेश्वर को सौंपना'],
  id: ['Allah melihat hati', 'Kepercayaan yang menjadi keberanian', 'Mencari Allah sebelum memutuskan', 'Menanti tanpa merebut kekuasaan', 'Menerima teguran', 'Setia pada janji', 'Mendengarkan hati nurani', 'Bertobat tanpa membela diri', 'Bersukacita dalam hadirat Allah', 'Menerima segalanya sebagai anugerah', 'Berbagi dengan adil', 'Menyerahkan kendali kepada Allah'],
  sw: ['Mungu huangalia moyo', 'Imani inayoleta ujasiri', 'Kumtafuta Mungu kabla ya kuamua', 'Kusubiri bila kunyakua mamlaka', 'Kukubali kurekebishwa', 'Kuwa mwaminifu kwa ahadi', 'Kusikiliza dhamiri', 'Kutubu bila visingizio', 'Kufurahia uwepo wa Mungu', 'Kupokea vyote kama neema', 'Kugawana kwa haki', 'Kumwachia Mungu udhibiti'],
  tl: ['Tinitingnan ng Diyos ang puso', 'Pagtitiwalang nagiging tapang', 'Hanapin ang Diyos bago magpasya', 'Maghintay nang hindi inaagaw ang kapangyarihan', 'Tanggapin ang pagtutuwid', 'Manatiling tapat sa mga pangako', 'Makinig sa konsensya', 'Magsisi nang walang dahilan', 'Magalak sa presensya ng Diyos', 'Tanggapin ang lahat bilang biyaya', 'Magbahagi nang makatarungan', 'Ipaubaya sa Diyos ang pamamahala'],
  am: ['እግዚአብሔር ልብን ይመለከታል', 'ድፍረት የሚያፈራ እምነት', 'ከመወሰን በፊት እግዚአብሔርን መፈለግ', 'ሥልጣንን ሳይነጥቁ መጠበቅ', 'እርማትን መቀበል', 'ለቃል ኪዳን ታማኝ መሆን', 'ሕሊናን ማዳመጥ', 'ያለ ማመካኛ ንስሐ መግባት', 'በእግዚአብሔር መገኘት መደሰት', 'ሁሉን እንደ ጸጋ መቀበል', 'በፍትሕ መካፈል', 'ቁጥጥርን ለእግዚአብሔር መተው'],
};

export const DAVID_THEMES = titles.en.map((_, index) => Object.fromEntries(
  Object.entries(titles).map(([lang, days]) => [lang, days[index]]),
));
