// The 21 days of "Healing from Church Hurt" (see ./healingFromChurchHurt.js for
// the plan meta, the movements and the guardrails this content is held to).
//
// Each day follows one rhythm: receive (reflection), pray (prompts), respond
// (practice). Safety notes sit on the opening day, the day on harmful
// shepherds, every forgiveness day, the justice/reporting days, the
// repentance day, the return-to-community day and the closing day.
// Prose is authored in en + fr; `theme` is authored in all 16 languages.
// Scripture is stored as references only — no Bible text lives in this file.
const L = (en, fr) => ({ en, fr });

export const DAYS = [
  // ── Name the wound and lament (1–5) ────────────────────────────────────────
  {
    movement: 'lament',
    theme: { en: 'A place for your wound', fr: 'Une place pour ta blessure', es: 'Un lugar para tu herida', pt: 'Um lugar para a tua ferida', de: 'Raum für deine Verletzung', ru: 'Место для твоей боли', zh: '让伤痛有处可诉', ja: '傷ついた心の居場所', ko: '상처를 내어놓는 자리', ar: 'مكان لجرحك', fa: 'جایی برای زخم تو', hi: 'तुम्हारे घाव के लिए जगह', id: 'Ruang bagi lukamu', sw: 'Nafasi kwa jeraha lako', tl: 'Puwang para sa iyong sugat', am: 'ለቁስልህ ቦታ' },
    ref: 'Psalm 34:15-22',
    related: [],
    reflection: L('Psalm 34 holds together God’s attention to broken hearts and the real troubles of His people. Pain in a church may come from disappointment or conflict, or from spiritual, emotional, sexual or financial abuse; these need different responses. You do not have to minimise what happened, label it immediately, or recount it here. Begin with what you can safely bring before God.', 'Le Psaume 34 parle à la fois de l’attention de Dieu aux cœurs brisés et des épreuves réelles de Son peuple. Une blessure vécue dans l’Église peut venir d’une déception ou d’un conflit, ou de violences spirituelles, psychologiques, sexuelles ou financières ; les réponses nécessaires diffèrent. Tu n’as pas à minimiser les faits, à les qualifier tout de suite ni à les raconter ici. Commence par ce que tu peux confier à Dieu sans te mettre en danger.'),
    prompts: [
      L('Tell God what hurts, with as few words as you need.', 'Dis à Dieu ce qui te fait mal, même en quelques mots.'),
      L('Ask Jesus for help to receive care without having to prove your pain.', 'Demande à Jésus de t’aider à recevoir du soutien sans devoir prouver ta souffrance.'),
      L('Pray for one trustworthy person who can help you take a safe next step.', 'Prie pour trouver une personne digne de confiance qui puisse t’aider à avancer en sécurité.'),
    ],
    practice: L('If it is safe, identify one person outside the situation whom you could contact for support. You may pause this plan at any time.', 'Si tu peux le faire sans danger, repère une personne extérieure à la situation que tu pourrais contacter pour recevoir du soutien. Tu peux interrompre ce parcours à tout moment.'),
    safetyNote: L('If you are in immediate danger, contact local emergency services or police. If you have been abused, you deserve safety and help from an independent safeguarding body, a trusted counsellor or a medical professional. Suspected abuse of a child or a vulnerable adult must be reported to the appropriate protection services or police; seek local safeguarding advice without waiting for church permission.', 'Si tu es en danger immédiat, contacte les services d’urgence ou la police de ton pays. Si tu as subi des violences, tu mérites sécurité et soutien auprès d’un organisme indépendant de protection des personnes, d’un professionnel de l’accompagnement ou de la santé. Tout soupçon de maltraitance d’un enfant ou d’un adulte vulnérable doit être signalé aux services de protection compétents ou à la police ; demande conseil localement sans attendre l’autorisation d’une Église.'),
    resourceTopics: ['church-hurt', 'lament', 'abuse-safety'],
  },
  {
    movement: 'lament',
    theme: { en: 'When a companion betrays', fr: 'Quand un proche trahit', es: 'Cuando un compañero traiciona', pt: 'Quando um companheiro trai', de: 'Wenn ein Vertrauter dich verrät', ru: 'Когда предаёт близкий', zh: '当同伴背叛时', ja: '仲間に裏切られたとき', ko: '동료에게 배신당했을 때', ar: 'حين يخون الرفيق', fa: 'وقتی همراهی خیانت می‌کند', hi: 'जब कोई साथी विश्वास तोड़े', id: 'Ketika sahabat mengkhianati', sw: 'Mwenzako anapokusaliti', tl: 'Kapag nagtaksil ang kasama', am: 'ወዳጅ ሲከዳ' },
    ref: 'Psalm 55:12-23',
    related: [],
    reflection: L('The singer of Psalm 55 remembers worship shared with someone who has betrayed him. That shared history makes the wound sharper; remembering good moments does not erase wrongdoing. This prayer brings fear and fierce anger to God rather than making them a plan for retaliation. You can grieve both the harm and the friendship or community you thought you had.', 'Dans le Psaume 55, celui qui prie se souvient d’avoir adoré Dieu avec la personne qui l’a trahi. Ce passé commun rend la blessure plus vive ; les bons souvenirs n’effacent pas le mal commis. La prière confie à Dieu la peur et une colère intense, sans en faire un projet de vengeance. Tu peux pleurer à la fois le tort subi et l’amitié ou la communauté que tu croyais connaître.'),
    prompts: [
      L('Bring God the confusion of good memories mixed with betrayal.', 'Confie à Dieu le trouble de ces bons souvenirs mêlés à la trahison.'),
      L('Ask Him to hold your anger without letting it become retaliation.', 'Demande-Lui d’accueillir ta colère et de t’aider à ne pas te venger.'),
      L('Pray for support as you grieve what this relationship has cost you.', 'Prie pour recevoir du soutien dans le deuil de ce que cette relation t’a coûté.'),
    ],
    practice: L('If helpful, name one thing you miss and one thing that was harmful, silently or in a private place that is safe for you.', 'Si cela t’aide, nomme une chose qui te manque et une chose qui t’a fait du mal, intérieurement ou dans un endroit privé où tu es en sécurité.'),
    resourceTopics: ['church-hurt', 'lament', 'trust'],
  },
  {
    movement: 'lament',
    theme: { en: 'Questions that belong in prayer', fr: 'Des questions à porter dans la prière', es: 'Preguntas que caben en la oración', pt: 'Perguntas que cabem na oração', de: 'Fragen haben im Gebet Platz', ru: 'Вопросам есть место в молитве', zh: '把疑问带进祷告', ja: '問いも祈りにしてよい', ko: '질문도 기도가 된다', ar: 'أسئلة لها مكان في الصلاة', fa: 'پرسش‌هایی که در دعا جا دارند', hi: 'प्रार्थना में प्रश्नों की भी जगह है', id: 'Pertanyaan yang boleh dibawa dalam doa', sw: 'Maswali yenye nafasi katika maombi', tl: 'Mga tanong na may lugar sa panalangin', am: 'በጸሎት ቦታ ያላቸው ጥያቄዎች' },
    ref: 'Psalm 13',
    related: [],
    reflection: L('Psalm 13 asks about God’s apparent absence before it speaks of trust. Its movement toward praise does not prescribe how quickly your feelings must change. Questions about what God allowed, or why leaders failed to act, can enter prayer without a tidy explanation. Faith can turn toward Him with unfinished questions, and tomorrow may still need the language of lament.', 'Le Psaume 13 interroge l’apparente absence de Dieu avant d’exprimer la confiance. Son chemin vers la louange ne fixe aucun délai à tes émotions. Tes questions sur ce que Dieu a permis ou sur l’inaction de responsables peuvent entrer dans la prière sans explication toute faite. La foi peut se tourner vers Lui avec des questions ouvertes ; demain, tu auras peut-être encore besoin de te lamenter.'),
    prompts: [
      L('Tell God one question you have been afraid to ask.', 'Dis à Dieu une question que tu n’osais pas Lui poser.'),
      L('Ask Him for enough light for today, without forcing an explanation.', 'Demande-Lui assez de lumière pour aujourd’hui, sans te forcer à trouver une explication.'),
      L('Pray for patient companions who will listen before offering answers.', 'Prie pour des compagnons patients qui écoutent avant de proposer des réponses.'),
    ],
    practice: L('If you wish, pray one honest question from your own life and leave a quiet moment after it. No answer needs to be recorded.', 'Si tu le souhaites, pose à Dieu une question honnête liée à ta vie, puis garde un moment de silence. Tu n’as aucune réponse à noter.'),
    resourceTopics: ['lament', 'suffering', 'church-hurt'],
  },
  {
    movement: 'lament',
    theme: { en: 'Loneliness can speak', fr: 'Dire la solitude', es: 'La soledad puede hablar', pt: 'A solidão pode falar', de: 'Einsamkeit darf Worte finden', ru: 'Одиночество может говорить', zh: '诉说孤独', ja: '孤独を言葉にする', ko: '외로움을 말해도 된다', ar: 'للوحدة صوت', fa: 'تنهایی هم می‌تواند سخن بگوید', hi: 'अकेलापन भी बोल सकता है', id: 'Kesepian boleh bersuara', sw: 'Upweke unaweza kusema', tl: 'Maaaring ipahayag ang pag-iisa', am: 'ብቸኝነትን መናገር' },
    ref: 'Psalm 142',
    related: [],
    reflection: L('Psalm 142 gives words to the feeling that nobody notices or cares. The prayer names isolation while asking God for refuge and a future among His people. Losing familiar relationships can be painful even when distance is necessary for safety. Asking for company does not commit you to returning to the place that hurt you, or to telling your whole story.', 'Le Psaume 142 met des mots sur le sentiment de ne compter pour personne. La prière nomme l’isolement et demande à Dieu un refuge ainsi qu’un avenir parmi Son peuple. Perdre des liens familiers peut faire souffrir, même lorsque la distance est nécessaire pour ta sécurité. Demander une présence ne t’engage ni à retourner là où tu as été blessé, ni à raconter toute ton histoire.'),
    prompts: [
      L('Tell the Lord where you feel forgotten.', 'Dis au Seigneur où tu te sens oublié.'),
      L('Ask for a dependable person who will respect what you choose to share.', 'Demande une personne fiable qui respecte ce que tu choisis de confier.'),
      L('Pray for others who lost friendships when they raised a concern.', 'Prie pour ceux qui ont perdu des amitiés après avoir signalé un problème.'),
    ],
    practice: L('If you feel ready, arrange a brief call or walk with someone you trust outside the harmful setting; you can ask simply for company.', 'Si tu te sens prêt, propose un bref appel ou une promenade à une personne de confiance extérieure au milieu qui t’a fait du mal ; tu peux simplement demander sa présence.'),
    resourceTopics: ['lament', 'community', 'church-hurt'],
  },
  {
    movement: 'lament',
    theme: { en: 'God confronts harmful shepherds', fr: 'Dieu reprend les bergers qui font du mal', es: 'Dios confronta a los pastores que dañan', pt: 'Deus confronta pastores que ferem', de: 'Gott stellt schädigende Hirten zur Rede', ru: 'Бог обличает жестоких пастырей', zh: '神责备伤害羊群的牧人', ja: '神は傷つける牧者を責められる', ko: '해치는 목자를 책망하시는 하나님', ar: 'الله يواجه الرعاة المؤذين', fa: 'خدا شبانان آسیب‌رسان را بازخواست می‌کند', hi: 'परमेश्वर हानि पहुँचाने वाले चरवाहों को टोकता है', id: 'Allah menegur gembala yang melukai', sw: 'Mungu anawakemea wachungaji wanaodhuru', tl: 'Sinisita ng Diyos ang mga pastol na nananakit', am: 'እግዚአብሔር ጎጂ እረኞችን ይወቅሳል' },
    ref: 'Ezekiel 34:1-16',
    related: [],
    reflection: L('Ezekiel addresses Israel’s shepherds who fed themselves while neglecting and ruling harshly over the flock. God holds those leaders responsible rather than blaming scattered sheep for their wounds. The passage exposes exploitation beneath a respected office and prepares us to look for His own shepherding care. Spiritual authority never excuses abuse or coercion; leaving abuse is not rebellion against God.', 'Ézéchiel s’adresse aux bergers d’Israël qui se nourrissent eux-mêmes tout en négligeant le troupeau et en le gouvernant avec dureté. Dieu tient ces responsables pour coupables sans accuser les brebis dispersées de leurs blessures. Le passage dénonce l’exploitation derrière une fonction respectée et nous tourne vers les soins de Dieu Lui-même. L’autorité spirituelle n’excuse jamais les violences ni la contrainte ; quitter un milieu abusif n’est pas se rebeller contre Dieu.'),
    prompts: [
      L('Thank God that He sees what respected leaders may hide.', 'Remercie Dieu de voir ce que des responsables respectés peuvent cacher.'),
      L('Ask Him to loosen the fear that seeking safety means abandoning Him.', 'Demande-Lui d’apaiser la peur que chercher la sécurité reviendrait à L’abandonner.'),
      L('Pray for protection for people whose concerns have been silenced.', 'Prie pour la protection des personnes dont les alertes ont été étouffées.'),
    ],
    practice: L('If helpful, identify one demand that made you afraid to say no, and discuss it with a safe, independent support person.', 'Si cela t’aide, repère une exigence à laquelle tu avais peur de dire non et parles-en à une personne de soutien indépendante et sûre.'),
    safetyNote: L('Threats, coercion or abuse need help beyond the authority of the person involved. An independent safeguarding professional or victim-support service can help you consider safe options; do not meet the person alone to complete this practice.', 'Les menaces, la contrainte ou les violences nécessitent une aide indépendante de l’autorité de la personne en cause. Un professionnel de la protection des personnes ou un service d’aide aux victimes peut t’aider à envisager des démarches sûres ; cette pratique ne demande pas de rencontrer seul la personne concernée.'),
    resourceTopics: ['spiritual-abuse', 'abuse-safety', 'pastoral-care'],
  },
  // ── Look again at Jesus, the Good Shepherd (6–10) ─────────────────────────
  {
    movement: 'shepherd',
    theme: { en: 'The Good Shepherd is no hired hand', fr: 'Le bon Berger n’est pas un mercenaire', es: 'El buen Pastor no es un asalariado', pt: 'O bom Pastor não é um mercenário', de: 'Der gute Hirte ist kein Mietling', ru: 'Добрый Пастырь — не наёмник', zh: '好牧人不是雇工', ja: '良い羊飼いは雇い人ではない', ko: '선한 목자는 삯꾼이 아니다', ar: 'الراعي الصالح ليس أجيرًا', fa: 'شبان نیکو مزدور نیست', hi: 'अच्छा चरवाहा मज़दूर नहीं है', id: 'Gembala yang baik bukan orang upahan', sw: 'Mchungaji mwema si mtu wa mshahara', tl: 'Ang mabuting Pastol ay hindi upahan', am: 'መልካሙ እረኛ ምንደኛ አይደለም' },
    ref: 'John 10:1-15',
    related: ['Psalm 23'],
    reflection: L('In John 10 Jesus sets Himself apart from the thief, who comes to take and destroy, and from the hired hand, who runs from the wolf because he does not care for the sheep. The Good Shepherd knows His own by name and lays down His life for them. In the same passage, sheep that refuse to follow a stranger’s voice are not scolded for it. Harm done to you in His name did not come from His voice.', 'En Jean 10, Jésus se distingue du voleur, qui vient pour prendre et détruire, et du mercenaire, qui s’enfuit devant le loup parce que les brebis ne lui importent pas. Le bon Berger connaît les siens par leur nom et donne Sa vie pour eux. Dans ce même passage, les brebis qui refusent de suivre la voix d’un étranger ne reçoivent aucun reproche. Le mal qu’on t’a fait en Son nom ne venait pas de Sa voix.'),
    prompts: [
      L('Thank Jesus that He knows you by name and cares for you without asking anything in return.', 'Remercie Jésus de te connaître par ton nom et de prendre soin de toi sans rien exiger en retour.'),
      L('Ask Him to help you tell His voice apart from other voices that have spoken in His name.', 'Demande-Lui de t’aider à distinguer Sa voix des autres voix qui ont parlé en Son nom.'),
      L('Pray for people still led by those who use the flock instead of serving it.', 'Prie pour les personnes encore conduites par des responsables qui se servent du troupeau au lieu de le servir.'),
    ],
    practice: L('Read Psalm 23 slowly and notice one thing the Shepherd does there that was missing in what you experienced.', 'Lis lentement le Psaume 23 et remarque une chose que le Berger y fait et qui a manqué dans ce que tu as vécu.'),
    resourceTopics: ['church-hurt', 'trust', 'healing'],
  },
  {
    movement: 'shepherd',
    theme: { en: 'The yoke of a gentle Master', fr: 'Le joug d’un Maître doux et humble', es: 'El yugo de un Maestro manso y humilde', pt: 'O jugo de um Mestre manso e humilde', de: 'Das Joch des sanftmütigen Meisters', ru: 'Иго кроткого и смиренного Учителя', zh: '心里柔和谦卑的主', ja: '柔和な主の負いやすいくびき', ko: '온유하고 겸손한 주님의 멍에', ar: 'نير المعلّم الوديع المتواضع', fa: 'یوغ خداوندِ حلیم و فروتن', hi: 'नम्र और दीन स्वामी का जूआ', id: 'Kuk dari Guru yang lemah lembut', sw: 'Nira ya Bwana mpole na mnyenyekevu', tl: 'Pamatok ng maamo at mababang-loob na Guro', am: 'የየዋሁና የትሑቱ ጌታ ቀንበር' },
    ref: 'Matthew 11:28-30',
    related: ['Matthew 23:4'],
    reflection: L('Jesus invites the weary and burdened to learn from Him, and He describes Himself as gentle and humble in heart. In Matthew 23 He criticises religious teachers who load heavy burdens onto other people’s shoulders and will not lift a finger to help. If faith became a constant effort to satisfy a leader, a system or a reputation, that load was not His yoke. His rest does not depend on how much you manage to carry.', 'Jésus invite ceux qui sont fatigués et chargés à se mettre à Son école, et Il se décrit comme doux et humble de cœur. En Matthieu 23, Il reproche aux maîtres religieux de charger les épaules des autres de lourds fardeaux sans lever le petit doigt pour les aider. Si ta foi est devenue un effort permanent pour satisfaire un responsable, un système ou une réputation, ce fardeau n’était pas Son joug. Son repos ne dépend pas de ce que tu parviens à porter.'),
    prompts: [
      L('Tell Jesus plainly which burdens you are tired of carrying.', 'Dis simplement à Jésus quels fardeaux tu es las de porter.'),
      L('Ask Him to show you what His gentleness toward you looks like today.', 'Demande-Lui de te montrer comment Sa douceur envers toi se manifeste aujourd’hui.'),
      L('Pray for anyone who still believes they must please a leader in order to please God.', 'Prie pour ceux qui pensent encore devoir contenter un responsable pour plaire à Dieu.'),
    ],
    practice: L('Write down one demand you still hear in your head, then write beside it what Jesus actually offers in this passage of Matthew 11.', 'Note une exigence qui résonne encore dans ta tête, puis écris à côté ce que Jésus offre réellement dans ce passage de Matthieu 11.'),
    resourceTopics: ['spiritual-abuse', 'church-hurt', 'identity'],
  },
  {
    movement: 'shepherd',
    theme: { en: 'Greatness that serves', fr: 'La grandeur qui sert', es: 'La grandeza que sirve', pt: 'A grandeza que serve', de: 'Größe, die dient', ru: 'Величие, которое служит', zh: '真正的伟大在于服侍', ja: '仕える者こそ偉大', ko: '섬김으로 드러나는 위대함', ar: 'العظمة التي تخدم', fa: 'بزرگی در خدمت است', hi: 'सेवा करने वाली महानता', id: 'Kebesaran yang melayani', sw: 'Ukuu wa kuwatumikia wengine', tl: 'Kadakilaang naglilingkod', am: 'የሚያገለግል ታላቅነት' },
    ref: 'Mark 10:42-45',
    related: ['John 13:12-17'],
    reflection: L('When James and John asked for places of honour, Jesus contrasted the rulers of the nations, who lord it over others, with His own way: whoever wants to be great must become a servant. He did not abolish leadership; He redefined it by His own life, given as a ransom for many. Authority that demands to be served, imposes secrecy or requires unquestioning loyalty runs against His words, whatever title it carries.', 'Quand Jacques et Jean réclamaient les places d’honneur, Jésus a opposé les chefs des nations, qui dominent sur les autres, à Sa propre voie : celui qui veut être grand doit se faire serviteur. Il n’a pas aboli l’autorité ; Il l’a redéfinie par Sa propre vie, donnée en rançon pour beaucoup. Une autorité qui exige d’être servie, impose le secret ou réclame une loyauté aveugle va à l’encontre de Ses paroles, quel que soit le titre de celui qui l’exerce.'),
    prompts: [
      L('Thank Jesus that He used His authority to serve and to give His life.', 'Remercie Jésus d’avoir exercé Son autorité pour servir et pour donner Sa vie.'),
      L('Ask Him to renew the way you see authority, so you can recognise both healthy and harmful leadership.', 'Demande-Lui de renouveler ton regard sur l’autorité, pour reconnaître une autorité saine comme une autorité nuisible.'),
      L('Pray for church leaders you know, that they would serve rather than expect to be served.', 'Prie pour des responsables d’Église que tu connais, afin qu’ils servent au lieu d’attendre d’être servis.'),
    ],
    practice: L('Note two marks of servant leadership from this passage and keep them where you can use them to assess a church or a leader in the future.', 'Note deux marques d’une autorité qui sert d’après ce passage, et garde-les pour évaluer à l’avenir une Église ou un responsable.'),
    resourceTopics: ['leadership', 'spiritual-abuse', 'church'],
  },
  {
    movement: 'shepherd',
    theme: { en: 'Jesus names religious hypocrisy', fr: 'Jésus dénonce l’hypocrisie religieuse', es: 'Jesús denuncia la hipocresía religiosa', pt: 'Jesus denuncia a hipocrisia religiosa', de: 'Jesus benennt religiöse Heuchelei', ru: 'Иисус обличает религиозное лицемерие', zh: '耶稣揭露宗教上的假冒为善', ja: '主は宗教的な偽善を責められる', ko: '종교적 위선을 꾸짖으신 예수님', ar: 'يسوع يفضح الرياء الديني', fa: 'عیسی ریاکاری دینی را افشا می‌کند', hi: 'यीशु धार्मिक पाखंड को उजागर करते हैं', id: 'Yesus menegur kemunafikan agama', sw: 'Yesu anakemea unafiki wa kidini', tl: 'Inilantad ni Jesus ang pagkukunwaring relihiyoso', am: 'ኢየሱስ ሃይማኖታዊ ግብዝነትን ገለጠ' },
    ref: 'Matthew 23:23-28',
    related: ['Matthew 23:8-12'],
    reflection: L('Jesus spoke openly against religious leaders who tithed with great care yet neglected justice, mercy and faithfulness, and who looked clean outside while being full of greed and self-indulgence. His words show that naming a leader’s wrongdoing is not automatically gossip or rebellion; sometimes it is the truth that protects others. Misusing people’s money, trust or bodies behind a respectable image is the kind of hidden corruption He exposed.', 'Jésus s’est élevé ouvertement contre des chefs religieux qui payaient la dîme avec un soin scrupuleux mais négligeaient la justice, la miséricorde et la fidélité, et qui paraissaient purs au-dehors tout en étant pleins de cupidité et d’excès. Ses paroles montrent que dénoncer la faute d’un responsable n’est pas forcément de la médisance ou de la rébellion ; c’est parfois la vérité qui protège les autres. Abuser de l’argent, de la confiance ou du corps des gens derrière une image respectable, c’est la corruption cachée qu’Il a mise au jour.'),
    prompts: [
      L('Thank Jesus that He valued justice and mercy above the protection of appearances.', 'Remercie Jésus d’avoir accordé plus de prix à la justice et à la miséricorde qu’à la préservation des apparences.'),
      L('Ask Him for courage to speak truthfully, and for wisdom about when, where and to whom.', 'Demande-Lui le courage de dire la vérité, et la sagesse de savoir quand, où et à qui la dire.'),
      L('Pray that churches would value justice, mercy and faithfulness above their image.', 'Prie pour que les Églises placent la justice, la miséricorde et la fidélité au-dessus de leur image.'),
    ],
    practice: L('Write one sentence that describes what happened as plainly as you can, without softening or exaggerating it, and keep it somewhere safe and private unless you choose to share it.', 'Écris une phrase qui décrit ce qui s’est passé aussi simplement que possible, sans l’atténuer ni l’exagérer ; garde-la en lieu sûr, pour toi seul, à moins que tu ne choisisses de la partager.'),
    resourceTopics: ['spiritual-abuse', 'justice', 'church-hurt'],
  },
  {
    movement: 'shepherd',
    theme: { en: 'Anointed to set the oppressed free', fr: 'Oint pour libérer les opprimés', es: 'Ungido para liberar a los oprimidos', pt: 'Ungido para libertar os oprimidos', de: 'Gesalbt, um Unterdrückte zu befreien', ru: 'Помазан, чтобы освободить угнетённых', zh: '受膏叫受压制的得自由', ja: '圧迫されている人を自由にするために', ko: '눌린 자를 자유롭게 하시려고', ar: 'مُسِح ليطلق المنسحقين أحرارًا', fa: 'مسح شد تا ستم‌دیدگان را آزاد کند', hi: 'कुचले हुओं को छुड़ाने के लिए अभिषिक्त', id: 'Diurapi untuk membebaskan yang tertindas', sw: 'Ametiwa mafuta kuwaacha huru walioonewa', tl: 'Pinahiran upang palayain ang mga inaapi', am: 'የተጨቆኑትን ነጻ ለማውጣት የተቀባ' },
    ref: 'Luke 4:16-21',
    related: ['Isaiah 42:1-4'],
    reflection: L('In Nazareth Jesus read from Isaiah and announced that the Spirit of the Lord had anointed Him to bring good news to the poor and freedom to the oppressed. His anointing moved toward the vulnerable; He never used it to enlarge Himself. Isaiah 42 describes the Servant who will not break a reed that is already bruised. If a claim to anointing was used to silence or control you, it did not reflect this Spirit-filled Messiah.', 'À Nazareth, Jésus a lu le livre d’Ésaïe et annoncé que l’Esprit du Seigneur L’avait oint pour porter la bonne nouvelle aux pauvres et la liberté aux opprimés. Son onction allait vers les plus vulnérables ; Il ne s’en est jamais servi pour se grandir. Ésaïe 42 décrit le Serviteur qui ne brise pas le roseau déjà froissé. Si quelqu’un s’est réclamé d’une onction pour te faire taire ou te contrôler, cela ne ressemblait pas à ce Messie rempli de l’Esprit.'),
    prompts: [
      L('Thank Jesus that the Spirit’s anointing on Him brought release, not domination.', 'Remercie Jésus : l’onction de l’Esprit sur Lui apportait la libération, non la domination.'),
      L('Ask the Holy Spirit to bring His comfort where you feel bruised and fragile.', 'Demande au Saint-Esprit d’apporter Son réconfort là où tu te sens meurtri et fragile.'),
      L('Pray for people held under control in the name of an anointing or of spiritual gifts.', 'Prie pour les personnes maintenues sous emprise au nom d’une onction ou de dons spirituels.'),
    ],
    practice: L('Read Luke 4:18 aloud or silently, and note the phrase that gives you the most hope today.', 'Lis Luc 4.18, à voix haute ou en silence, et note l’expression qui te donne le plus d’espérance aujourd’hui.'),
    resourceTopics: ['spiritual-abuse', 'healing', 'justice'],
  },
  // ── Forgiveness, justice and boundaries (11–15) ────────────────────────────
  {
    movement: 'boundaries',
    theme: { en: 'Forgiveness is not pretending', fr: 'Pardonner n’est pas faire semblant', es: 'Perdonar no es fingir', pt: 'Perdoar não é fingir', de: 'Vergeben heißt nicht verharmlosen', ru: 'Прощение — не притворство', zh: '饶恕不是假装没事', ja: '赦しは見て見ぬふりではない', ko: '용서는 없던 일로 하는 것이 아니다', ar: 'الغفران ليس تظاهرًا', fa: 'بخشیدن وانمود کردن نیست', hi: 'क्षमा करना दिखावा नहीं है', id: 'Mengampuni bukan berpura-pura', sw: 'Kusamehe si kujifanya', tl: 'Ang pagpapatawad ay hindi pagkukunwari', am: 'ይቅርታ ማስመሰል አይደለም' },
    ref: 'Ephesians 4:25-32',
    related: ['Isaiah 5:20'],
    reflection: L('Paul’s call to forgive in Ephesians 4 begins with laying aside lies and telling the truth. It leaves room for anger that does not turn into sin, and asks that bitterness and malice be put away. Forgiveness is not denial: it does not call evil good or require you to hurry your feelings. It entrusts the debt to God instead of pursuing revenge. After a small hurt that may come quickly; after deep harm it is often a long process.', 'En Éphésiens 4, l’appel de Paul au pardon commence par le rejet du mensonge et le choix de la vérité. Il laisse place à une colère qui ne devient pas péché et demande de rejeter l’amertume et la méchanceté. Le pardon n’est pas un déni : il n’appelle pas le mal bien et ne t’oblige pas à brusquer tes émotions. Il remet la dette à Dieu au lieu de chercher la vengeance. Après une petite blessure, cela peut venir vite ; après un tort profond, c’est souvent un long chemin.'),
    prompts: [
      L('Tell God honestly what this has cost you, including the anger you still feel.', 'Dis honnêtement à Dieu ce que cela t’a coûté, y compris la colère que tu ressens encore.'),
      L('If you are ready, ask Him to help you release the desire for revenge; if not, ask Him to meet you where you are.', 'Si tu es prêt, demande-Lui de t’aider à renoncer au désir de vengeance ; sinon, demande-Lui de te rejoindre là où tu en es.'),
      L('Thank God that His forgiveness in Christ took sin seriously enough to go through the cross.', 'Remercie Dieu : en Christ, Son pardon a pris le péché assez au sérieux pour passer par la croix.'),
    ],
    practice: L('Make two short lists: what forgiveness asks of you, and what it does not ask of you, such as silence, contact or pretending.', 'Fais deux courtes listes : ce que le pardon te demande, et ce qu’il ne te demande pas, comme le silence, le contact ou le faire-semblant.'),
    safetyNote: L('Forgiveness never requires you to stay silent about abuse, to remain in contact, or to stay in a place where you are not safe. If you are being pressed to forgive quickly, to meet the person or to drop a complaint, talk with an independent counsellor, a safeguarding professional or a trusted pastor outside the situation.', 'Le pardon ne t’oblige jamais à taire des violences, à garder le contact ni à rester dans un lieu où tu n’es pas en sécurité. Si l’on te presse de pardonner vite, de rencontrer la personne ou de retirer une plainte, parles-en à un conseiller indépendant, à un professionnel de la protection des personnes ou à un pasteur de confiance extérieur à la situation.'),
    resourceTopics: ['forgiveness', 'church-hurt', 'boundaries'],
  },
  {
    movement: 'boundaries',
    theme: { en: 'Forgiving without reopening the door', fr: 'Pardonner sans rouvrir la porte', es: 'Perdonar sin volver a abrir la puerta', pt: 'Perdoar sem reabrir a porta', de: 'Vergeben, ohne die Tür wieder zu öffnen', ru: 'Прощать, не открывая дверь снова', zh: '饶恕不等于重新敞开门', ja: '赦しても扉を開け直さなくてよい', ko: '용서해도 다시 문을 열 필요는 없다', ar: 'أن تغفر دون أن تفتح الباب من جديد', fa: 'بخشیدن بدون باز کردنِ دوبارهٔ در', hi: 'क्षमा, पर फिर से दरवाज़ा खोले बिना', id: 'Mengampuni tanpa membuka pintu lagi', sw: 'Kusamehe bila kufungua mlango tena', tl: 'Magpatawad nang hindi muling binubuksan ang pinto', am: 'በሩን እንደገና ሳይከፍቱ ይቅር ማለት' },
    ref: '2 Timothy 4:14-18',
    related: ['Proverbs 22:3'],
    reflection: L('Near the end of his life Paul names the great harm Alexander the metalworker did him. He leaves repayment to the Lord, yet he warns Timothy to be on guard against the man; of friends who deserted him, he asks that it not be held against them. Forgiveness does not automatically restore trust, and it does not require continued access. Trust, if it is ever rebuilt, grows slowly through changed behaviour tested over time.', 'À la fin de sa vie, Paul mentionne le grand mal que lui a fait Alexandre, le forgeron. Il laisse au Seigneur le soin de rétribuer, tout en avertissant Timothée de se méfier de cet homme ; quant aux amis qui l’ont abandonné, il demande que cela ne leur soit pas imputé. Le pardon ne rétablit pas automatiquement la confiance et n’exige pas de maintenir l’accès à ta vie. Si la confiance se reconstruit un jour, c’est lentement, par un changement de comportement vérifié dans la durée.'),
    prompts: [
      L('Thank God that He stands with you, as Paul says the Lord stood by him when others left.', 'Remercie Dieu de se tenir à tes côtés, comme Paul dit que le Seigneur s’est tenu près de lui quand les autres l’ont quitté.'),
      L('Ask for wisdom to tell the difference between forgiving someone and trusting them again.', 'Demande la sagesse de faire la différence entre pardonner à quelqu’un et lui refaire confiance.'),
      L('Hand the person over to God’s justice, and ask Him to guard you from bitterness while you keep the distance you need.', 'Remets cette personne à la justice de Dieu, et demande-Lui de te préserver de l’amertume tout en maintenant la distance nécessaire.'),
    ],
    practice: L('Choose one boundary that protects you, such as not replying to certain messages or not attending a particular meeting, and tell a trusted person about it.', 'Choisis une limite qui te protège, par exemple ne pas répondre à certains messages ou ne pas assister à telle réunion, et parles-en à une personne de confiance.'),
    safetyNote: L('You may decline contact with someone who harmed you, even if they ask for forgiveness or say they have changed. If they keep contacting, following or threatening you, keep a record and ask the police, a victim-support service or a legal adviser about protective measures.', 'Tu peux refuser tout contact avec une personne qui t’a fait du mal, même si elle demande pardon ou affirme avoir changé. Si elle continue à te contacter, à te suivre ou à te menacer, garde une trace des faits et renseigne-toi auprès de la police, d’un service d’aide aux victimes ou d’un conseiller juridique sur les mesures de protection possibles.'),
    resourceTopics: ['forgiveness', 'boundaries', 'trust'],
  },
  {
    movement: 'boundaries',
    theme: { en: 'Leaving vengeance to God is not silence', fr: 'Laisser la vengeance à Dieu n’est pas se taire', es: 'Dejar la venganza a Dios no es callar', pt: 'Deixar a vingança a Deus não é calar-se', de: 'Die Rache Gott überlassen heißt nicht schweigen', ru: 'Оставить месть Богу — не значит молчать', zh: '把伸冤交给神不等于沉默', ja: '復讐を神に委ねることは沈黙ではない', ko: '원수 갚음을 맡기는 것은 침묵이 아니다', ar: 'ترك الانتقام لله ليس صمتًا', fa: 'واگذاشتن انتقام به خدا سکوت نیست', hi: 'बदला परमेश्वर पर छोड़ना चुप रहना नहीं', id: 'Menyerahkan pembalasan kepada Allah bukan berarti diam', sw: 'Kumwachia Mungu kisasi si kunyamaza', tl: 'Ang pag-iwan ng paghihiganti sa Diyos ay hindi pananahimik', am: 'በቀልን ለእግዚአብሔር መተው ዝም ማለት አይደለም' },
    ref: 'Romans 12:17-21',
    related: ['Romans 13:3-4'],
    reflection: L('Paul forbids repaying evil for evil and tells believers to leave room for God’s wrath. In the next chapter he describes governing authorities as God’s servants for good, appointed to act against wrongdoing. Refusing revenge therefore does not mean refusing justice: a police investigation or a safeguarding process can be one of the ways God’s justice works. Paul’s call to live at peace comes with a condition that admits peace is not always in your power; reconciliation may not be appropriate or possible.', 'Paul interdit de rendre le mal pour le mal et invite à laisser agir la colère de Dieu. Au chapitre suivant, il présente les autorités comme servantes de Dieu pour le bien, chargées d’agir contre celui qui fait le mal. Renoncer à la vengeance ne veut donc pas dire renoncer à la justice : une enquête de police ou une procédure de protection peut être l’un des moyens par lesquels la justice de Dieu s’exerce. L’appel de Paul à vivre en paix est assorti d’une condition qui reconnaît que la paix ne dépend pas toujours de toi ; la réconciliation peut ne pas être appropriée, ni même possible.'),
    prompts: [
      L('Tell God about the justice you long for, and hand Him any revenge you are tempted to take.', 'Parle à Dieu de la justice que tu attends, et remets-Lui toute vengeance que tu serais tenté d’exercer.'),
      L('Ask for wisdom and courage about whether and how to report what happened.', 'Demande la sagesse et le courage de discerner s’il faut signaler ce qui s’est passé, et comment.'),
      L('Pray for police officers, courts and safeguarding teams to act with truth, skill and compassion.', 'Prie pour que les policiers, les tribunaux et les équipes de protection agissent avec vérité, compétence et compassion.'),
    ],
    practice: L('If a report may be needed, find the contact details of the police or an independent safeguarding or victim-support service near you and keep them somewhere safe. If not, write down what a fair outcome would look like.', 'Si un signalement peut s’avérer nécessaire, trouve les coordonnées de la police ou d’un service indépendant de protection ou d’aide aux victimes près de chez toi, et garde-les en lieu sûr. Sinon, écris à quoi ressemblerait une issue juste.'),
    safetyNote: L('Reporting abuse is not unforgiveness. Crimes can be reported to the police, and suspected abuse of a child or a vulnerable adult must be reported to the police or the relevant protection services, even if church leaders would prefer to handle it internally. An independent safeguarding body, a victim-support service or a lawyer can explain your options; if anyone is in immediate danger, call emergency services.', 'Signaler des violences n’est pas un manque de pardon. Les délits peuvent être signalés à la police, et tout soupçon de maltraitance d’un enfant ou d’un adulte vulnérable doit être signalé à la police ou aux services de protection compétents, même si des responsables d’Église préfèrent régler l’affaire en interne. Un organisme indépendant de protection, un service d’aide aux victimes ou un avocat peut t’expliquer tes options ; si quelqu’un est en danger immédiat, appelle les services d’urgence.'),
    resourceTopics: ['justice', 'abuse-safety', 'forgiveness'],
  },
  {
    movement: 'boundaries',
    theme: { en: 'Jesus guards the little ones', fr: 'Jésus protège les petits', es: 'Jesús protege a los pequeños', pt: 'Jesus protege os pequeninos', de: 'Jesus schützt die Kleinen', ru: 'Иисус защищает малых сих', zh: '耶稣护卫弱小的人', ja: '主は小さな者を守られる', ko: '작은 자를 지키시는 예수님', ar: 'يسوع يحمي الصغار', fa: 'عیسی از کوچکان محافظت می‌کند', hi: 'यीशु छोटों की रक्षा करते हैं', id: 'Yesus melindungi yang kecil', sw: 'Yesu huwalinda wadogo', tl: 'Iniingatan ni Jesus ang maliliit', am: 'ኢየሱስ ታናናሾችን ይጠብቃል' },
    ref: 'Matthew 18:1-6',
    related: ['Matthew 18:15-17'],
    reflection: L('Jesus placed a child among His disciples and warned, in the strongest terms, against causing one of these little ones to stumble. Later in the chapter He gives steps for when a brother or sister sins against you, beginning with a private conversation. Those steps suit ordinary offences between people who can speak as equals; they never require anyone to confront an abuser alone. Criminal conduct must not be concealed under church discipline: harm to the vulnerable belongs with the police and safeguarding professionals.', 'Jésus a placé un enfant au milieu de Ses disciples et a mis en garde, dans les termes les plus sévères, contre le fait de faire tomber l’un de ces petits. Plus loin dans le chapitre, Il indique une démarche lorsqu’un frère ou une sœur pèche contre toi, en commençant par un entretien seul à seul. Cette démarche convient aux offenses ordinaires entre personnes qui peuvent se parler d’égal à égal ; elle n’oblige jamais personne à confronter seul un agresseur. Des actes criminels ne doivent jamais être dissimulés sous couvert de discipline d’Église : le tort fait aux plus vulnérables relève de la police et des professionnels de la protection.'),
    prompts: [
      L('Thank Jesus that He takes harm to the vulnerable more seriously than any institution’s reputation.', 'Remercie Jésus de prendre le tort fait aux plus vulnérables plus au sérieux que la réputation de n’importe quelle institution.'),
      L('Ask Him to free you from any pressure to face alone someone who has power over you.', 'Demande-Lui de te libérer de toute pression à affronter seul quelqu’un qui a du pouvoir sur toi.'),
      L('Pray for children and vulnerable adults in churches, that leaders would protect them and report every concern.', 'Prie pour les enfants et les adultes vulnérables dans les Églises, afin que les responsables les protègent et signalent toute inquiétude.'),
    ],
    practice: L('If you have a concern about a child or a vulnerable adult, write down what you saw or heard, with dates, and contact the police or protection services today. Otherwise, find out whether a church you know has a safeguarding policy.', 'Si tu as une inquiétude au sujet d’un enfant ou d’un adulte vulnérable, note ce que tu as vu ou entendu, avec les dates, et contacte aujourd’hui la police ou les services de protection. Sinon, renseigne-toi pour savoir si une Église que tu connais a une politique de protection des personnes.'),
    safetyNote: L('If someone with power over you harmed you, you do not have to meet them first, alone or with church leaders, before seeking help. Sexual abuse, violence, threats and financial exploitation can be reported directly to the police; a safeguarding body, a victim-support service or a lawyer can advise you. If a child or a vulnerable adult may be at risk, report it without delay.', 'Si quelqu’un qui avait du pouvoir sur toi t’a fait du mal, tu n’as pas à le rencontrer d’abord, seul ou avec des responsables d’Église, avant de chercher de l’aide. Les violences sexuelles, les violences physiques, les menaces et l’exploitation financière peuvent être signalées directement à la police ; un organisme de protection, un service d’aide aux victimes ou un avocat peut te conseiller. Si un enfant ou un adulte vulnérable est peut-être en danger, signale-le sans attendre.'),
    resourceTopics: ['abuse-safety', 'justice', 'spiritual-abuse'],
  },
  {
    movement: 'boundaries',
    theme: { en: 'What real repentance looks like', fr: 'À quoi ressemble une vraie repentance', es: 'Cómo es el verdadero arrepentimiento', pt: 'Como é o verdadeiro arrependimento', de: 'Woran man echte Umkehr erkennt', ru: 'Каким бывает настоящее покаяние', zh: '真正的悔改是什么样子', ja: '真の悔い改めとは', ko: '진정한 회개의 모습', ar: 'كيف تبدو التوبة الحقيقية', fa: 'توبهٔ واقعی چگونه است', hi: 'सच्चा पश्चाताप कैसा दिखता है', id: 'Seperti apa pertobatan sejati', sw: 'Jinsi toba ya kweli inavyoonekana', tl: 'Ang anyo ng tunay na pagsisisi', am: 'እውነተኛ ንስሐ ምን ይመስላል' },
    ref: 'Luke 19:1-10',
    related: ['2 Corinthians 7:10-11'],
    reflection: L('Welcomed by Jesus, Zacchaeus promised to give half his possessions to the poor and to repay anyone he had cheated four times over. He did not ask the people he had wronged to trust him or to keep quiet. Paul likewise describes godly sorrow as eager to put things right and to see justice done. This gives you a measure for any apology you receive. And if you know you have also wounded others, perhaps as a leader or out of your own pain, the same grace invites honest responsibility, without cancelling what was done to you.', 'Accueilli par Jésus, Zachée a promis de donner la moitié de ses biens aux pauvres et de rendre le quadruple à quiconque il avait lésé. Il n’a demandé à ceux qu’il avait trompés ni de lui faire confiance ni de se taire. Paul décrit, lui aussi, une tristesse selon Dieu qui s’empresse de réparer et de voir la justice rendue. Tu as là une mesure pour évaluer les excuses que tu pourrais recevoir. Et si tu sais avoir toi aussi blessé d’autres personnes, peut-être comme responsable ou à cause de ta propre souffrance, la même grâce t’invite à assumer honnêtement tes actes, sans rien effacer de ce que tu as subi.'),
    prompts: [
      L('Ask God for clear sight to tell genuine repentance from words that seek to regain control.', 'Demande à Dieu un regard clair pour distinguer une vraie repentance de paroles qui cherchent à reprendre le contrôle.'),
      L('Pray that those who caused harm would take full responsibility and make amends without demanding anything from you.', 'Prie pour que ceux qui ont causé du tort en assument pleinement la responsabilité et réparent sans rien exiger de toi.'),
      L('If you have hurt others, tell God honestly, and ask for courage to take responsibility in a way that is safe for them.', 'Si tu as blessé d’autres personnes, dis-le honnêtement à Dieu et demande le courage d’en assumer la responsabilité d’une manière sûre pour elles.'),
    ],
    practice: L('Write down three signs of genuine repentance from these passages, such as taking responsibility, making amends and accepting consequences.', 'Note trois signes d’une vraie repentance tirés de ces passages, comme assumer la responsabilité, réparer et accepter les conséquences.'),
    safetyNote: L('You are not obliged to meet someone who harmed you in order to hear an apology. If that person, especially a leader, wants to make amends, it is wise for this to go through an independent safeguarding process or a trusted third party. If you have abused someone yourself, speak with a pastor, a safeguarding professional or a lawyer about how to take responsibility properly.', 'Tu n’es pas obligé de rencontrer une personne qui t’a fait du mal pour entendre ses excuses. Si elle souhaite réparer, surtout s’il s’agit d’un responsable, il est sage que cela passe par une procédure de protection indépendante ou par un tiers de confiance. Si tu as toi-même commis des abus, parles-en à un pasteur, à un professionnel de la protection des personnes ou à un avocat pour assumer ta responsabilité comme il se doit.'),
    resourceTopics: ['forgiveness', 'justice', 'trust'],
  },
  // ── Discernment, community and hope (16–21) ────────────────────────────────
  {
    movement: 'hope',
    theme: { en: 'Watchful, not cynical', fr: 'Vigilant sans devenir cynique', es: 'Vigilante sin volverte cínico', pt: 'Vigilante sem se tornar cínico', de: 'Wachsam, ohne zynisch zu werden', ru: 'Бдительность без цинизма', zh: '警醒而不愤世嫉俗', ja: '冷笑せずに目を覚ましている', ko: '냉소 없이 깨어 있기', ar: 'اليقظة من دون تهكّم', fa: 'هشیاری بدون بدبینی', hi: 'सतर्क रहो, कटु नहीं', id: 'Waspada tanpa menjadi sinis', sw: 'Kukesha bila kuwa na dharau', tl: 'Mapagbantay, hindi mapang-uyam', am: 'በመራርነት ሳይሆን በንቃት' },
    ref: 'Acts 20:28-31',
    related: ['Matthew 7:15-20'],
    reflection: L('Paul told the Ephesian elders to keep watch over themselves as well as the flock, warning that some from their own number would distort the truth to draw disciples after them. The New Testament expected that harm could arise inside leadership, so watchfulness is not disloyalty. Jesus pointed to fruit as the test of a teacher. Discernment asks what a ministry produces over time; cynicism assumes every leader is the same. You can ask for the first without settling into the second.', 'Paul a demandé aux anciens d’Éphèse de veiller sur eux-mêmes comme sur le troupeau, en les avertissant que certains d’entre eux fausseraient la vérité pour entraîner des disciples à leur suite. Le Nouveau Testament s’attendait donc à ce que le mal puisse surgir au sein même des responsables : la vigilance n’est pas de la déloyauté. Jésus a désigné les fruits comme le critère d’un enseignant. Le discernement regarde ce qu’un ministère produit dans la durée ; le cynisme suppose que tous les responsables se valent. Tu peux demander le premier sans t’installer dans le second.'),
    prompts: [
      L('Ask the Holy Spirit for discernment that sees clearly without making your heart hard.', 'Demande au Saint-Esprit un discernement lucide qui ne rende pas ton cœur dur.'),
      L('Tell God where suspicion now makes it hard to trust anyone, and ask Him to restore trust at His pace.', 'Dis à Dieu où la méfiance t’empêche aujourd’hui de faire confiance à qui que ce soit, et demande-Lui de restaurer ta confiance à Son rythme.'),
      L('Pray for elders and pastors to watch over themselves as carefully as they watch over others.', 'Prie pour que les anciens et les pasteurs veillent sur eux-mêmes avec autant de soin que sur les autres.'),
    ],
    practice: L('List a few fruits you would hope to see in a healthy church, such as honesty about failure, accountability and care for the vulnerable.', 'Dresse une courte liste des fruits que tu espères voir dans une Église saine, comme l’honnêteté face aux échecs, la redevabilité et le soin des plus vulnérables.'),
    resourceTopics: ['discernment', 'church', 'spiritual-abuse'],
  },
  {
    movement: 'hope',
    theme: { en: 'Healthy or controlling leadership', fr: 'Autorité saine ou autorité qui contrôle', es: 'Liderazgo sano o controlador', pt: 'Liderança saudável ou controladora', de: 'Gesunde oder kontrollierende Leitung', ru: 'Здоровое или властное руководство', zh: '健康的带领与控制的辖制', ja: '健全な指導と支配的な指導', ko: '건강한 리더십과 통제하는 리더십', ar: 'قيادة سليمة أم قيادة متسلّطة', fa: 'رهبری سالم یا رهبری سلطه‌جو', hi: 'स्वस्थ या नियंत्रक नेतृत्व', id: 'Kepemimpinan sehat atau mengekang', sw: 'Uongozi mzuri au wa kutawala', tl: 'Malusog o mapaniil na pamumuno', am: 'ጤናማ ወይስ ተቆጣጣሪ አመራር' },
    ref: '3 John 1:9-11',
    related: ['1 Peter 5:1-4', 'Hebrews 13:17'],
    reflection: L('John describes Diotrephes, who loved to be first, spread malicious talk, refused hospitality and put people out of the church. Peter describes elders who shepherd willingly, not for dishonest gain, not domineering over those in their care, but as examples. Hebrews 13:17 asks believers to trust leaders who keep watch as people who will give an account; it assumes accountable leaders who care for souls, and it never asks anyone to submit to abuse. John’s counsel is simple: imitate what is good.', 'Jean décrit Diotrèphe, qui aimait être le premier, répandait des propos malveillants, refusait l’hospitalité et chassait des gens de l’Église. Pierre décrit des anciens qui paissent le troupeau de bon gré, sans chercher un gain malhonnête, sans dominer sur ceux qui leur sont confiés, mais en étant des modèles. Hébreux 13.17 invite à faire confiance aux conducteurs qui veillent comme devant rendre compte ; ce texte suppose des responsables redevables qui prennent soin des âmes, et il ne demande jamais à personne de se soumettre à des abus. Le conseil de Jean est simple : imite ce qui est bien.'),
    prompts: [
      L('Thank God for any leader who has served you with humility and honesty, even briefly.', 'Remercie Dieu pour tout responsable qui t’a servi avec humilité et honnêteté, même brièvement.'),
      L('Ask Him to help you notice the difference between being led and being controlled.', 'Demande-Lui de t’aider à percevoir la différence entre être conduit et être contrôlé.'),
      L('Pray for those who were put out of a church for asking questions or raising concerns.', 'Prie pour ceux qui ont été écartés d’une Église pour avoir posé des questions ou exprimé des inquiétudes.'),
    ],
    practice: L('Compare the leadership you experienced with 1 Peter 5:1-4, noting where it matched and where it did not.', 'Compare l’autorité que tu as connue avec 1 Pierre 5.1-4, en notant où elle y correspondait et où elle s’en écartait.'),
    resourceTopics: ['spiritual-abuse', 'leadership', 'discernment'],
  },
  {
    movement: 'hope',
    theme: { en: 'A flock that need not fear', fr: 'Un troupeau qui n’a plus à craindre', es: 'Un rebaño que no tiene que temer', pt: 'Um rebanho que não precisa temer', de: 'Eine Herde ohne Angst', ru: 'Стадо, которому не нужно бояться', zh: '不再惧怕的羊群', ja: 'もう恐れなくてよい群れ', ko: '더 이상 두려워하지 않는 양 떼', ar: 'قطيع لا يحتاج أن يخاف', fa: 'گله‌ای که دیگر نباید بترسد', hi: 'भेड़ें जिन्हें अब डरना नहीं', id: 'Kawanan yang tak perlu takut lagi', sw: 'Kundi lisilohitaji kuogopa', tl: 'Kawang hindi na kailangang matakot', am: 'መፍራት የማያስፈልገው መንጋ' },
    ref: 'Jeremiah 23:1-4',
    related: ['John 21:15-17'],
    reflection: L('Jeremiah pronounces woe on shepherds who destroy and scatter the flock, then gives God’s intention: He will gather His sheep and raise up shepherds who tend them, so that they no longer live in fear or terror and none go missing. Fear is not meant to be what holds a church together. When the risen Jesus commissioned Peter, He spoke of the sheep as His own; leaders tend Christ’s flock and never own it. This is God’s purpose for His people, not a deadline for you to find such a place.', 'Jérémie prononce un malheur contre les bergers qui détruisent et dispersent le troupeau, puis annonce l’intention de Dieu : rassembler Ses brebis et susciter des bergers qui en prendront soin, afin qu’elles ne vivent plus dans la peur ni l’effroi et qu’aucune ne manque. La peur n’est pas faite pour tenir une Église ensemble. Quand Jésus ressuscité a confié une mission à Pierre, Il a parlé des brebis comme des Siennes ; les responsables prennent soin du troupeau du Christ, ils ne le possèdent jamais. C’est le dessein de Dieu pour Son peuple, non un délai imposé pour trouver un tel lieu.'),
    prompts: [
      L('Thank God that His purpose for His people is care without fear.', 'Remercie Dieu : Son dessein pour Son peuple, c’est un soin qui ne s’appuie pas sur la peur.'),
      L('Tell Him honestly what you would need to see before you could trust a church again.', 'Dis-Lui franchement ce que tu aurais besoin de voir avant de pouvoir refaire confiance à une Église.'),
      L('Pray for pastors who are tending wounded sheep with patience and integrity.', 'Prie pour les pasteurs qui prennent soin de brebis blessées avec patience et intégrité.'),
    ],
    practice: L('Write down two or three signs that would help you feel safer in a church, such as a clear safeguarding policy, openness about money or freedom to ask questions.', 'Note deux ou trois signes qui t’aideraient à te sentir plus en sécurité dans une Église : une vraie politique de protection des personnes, la transparence financière ou la liberté de poser des questions.'),
    resourceTopics: ['church', 'pastoral-care', 'healing'],
  },
  {
    movement: 'hope',
    theme: { en: 'Small steps toward safe community', fr: 'Petits pas vers une communauté sûre', es: 'Pequeños pasos hacia una comunidad segura', pt: 'Pequenos passos rumo a uma comunidade segura', de: 'Kleine Schritte zu sicherer Gemeinschaft', ru: 'Маленькие шаги к безопасной общине', zh: '一步步走向安全的团契', ja: '安全な交わりへの小さな一歩', ko: '안전한 공동체를 향한 작은 걸음', ar: 'خطوات صغيرة نحو جماعة آمنة', fa: 'گام‌های کوچک به‌سوی جمعی امن', hi: 'सुरक्षित संगति की ओर छोटे कदम', id: 'Langkah kecil menuju persekutuan yang aman', sw: 'Hatua ndogo kuelekea ushirika salama', tl: 'Maliliit na hakbang tungo sa ligtas na komunidad', am: 'ወደ አስተማማኝ ኅብረት ትንንሽ እርምጃዎች' },
    ref: 'Romans 12:9-16',
    related: ['Hebrews 10:24-25'],
    reflection: L('Romans 12 pictures a community where love is sincere, evil is hated, honour is shared and people weep with those who weep. Hebrews 10:24-25 speaks of meeting together so that believers can spur one another on toward love; it is an invitation to encouragement, not a rule to be used against the wounded. You may take your time and choose a safe community. A first step might be one friend, a small group or a pastor outside the church that hurt you.', 'Romains 12 dépeint une communauté où l’amour est sincère, où l’on a le mal en horreur, où l’on s’honore les uns les autres et où l’on pleure avec ceux qui pleurent. Hébreux 10.24-25 parle de se réunir pour s’encourager mutuellement à l’amour ; c’est une invitation à l’encouragement, non une règle à retourner contre les personnes blessées. Tu peux prendre ton temps et choisir une communauté sûre. Un premier pas peut être un ami, un petit groupe ou un pasteur extérieur à l’Église qui t’a blessé.'),
    prompts: [
      L('Tell God what you miss about Christian fellowship, and what still makes it hard.', 'Dis à Dieu ce qui te manque dans la communion fraternelle, et ce qui la rend encore difficile.'),
      L('Ask Him to lead you, at a pace you can bear, to people who weep with you rather than correct you.', 'Demande-Lui de te conduire, à un rythme que tu peux supporter, vers des personnes qui pleurent avec toi au lieu de te reprendre.'),
      L('Pray for churches that are learning to welcome people carrying wounds from other churches.', 'Prie pour les Églises qui apprennent à accueillir des personnes blessées par d’autres Églises.'),
    ],
    practice: L('If you feel ready, choose one low-pressure step this week, such as coffee with a believer you trust or an online service; if not, simply ask God for the courage to take one later.', 'Si tu te sens prêt, choisis cette semaine un petit pas sans pression, comme un café avec un croyant de confiance ou un culte en ligne ; sinon, demande simplement à Dieu le courage d’en faire un plus tard.'),
    safetyNote: L('You are never required to return to a church where you were abused, where the person who harmed you still has influence, or where concerns were covered up. When you consider a new community, you may ask about its safeguarding policy and take a trusted friend with you. A counsellor familiar with spiritual abuse or trauma can help you find your pace.', 'Tu n’es jamais obligé de retourner dans une Église où tu as subi des abus, où la personne qui t’a fait du mal garde de l’influence, ou dans laquelle des alertes ont été étouffées. Quand tu envisages une nouvelle communauté, tu peux te renseigner sur sa politique de protection des personnes et te faire accompagner d’un ami de confiance. Un conseiller qui connaît les abus spirituels ou les traumatismes peut t’aider à trouver ton rythme.'),
    resourceTopics: ['community', 'church', 'church-hurt'],
  },
  {
    movement: 'hope',
    theme: { en: 'The God of all comfort', fr: 'Le Dieu de toute consolation', es: 'El Dios de toda consolación', pt: 'O Deus de toda consolação', de: 'Der Gott allen Trostes', ru: 'Бог всякого утешения', zh: '赐各样安慰的神', ja: 'あらゆる慰めの神', ko: '모든 위로의 하나님', ar: 'إله كل تعزية', fa: 'خدای همهٔ تسلی‌ها', hi: 'सब प्रकार की शान्ति का परमेश्वर', id: 'Allah sumber segala penghiburan', sw: 'Mungu wa faraja yote', tl: 'Ang Diyos ng lahat ng kaaliwan', am: 'የመጽናናት ሁሉ አምላክ' },
    ref: '2 Corinthians 1:3-7',
    related: ['Psalm 147:3'],
    reflection: L('Paul blesses the God of all comfort while he is still in the middle of affliction, not after it has passed. The comfort he receives flows outward, so that others in trouble can be comforted too. That does not mean your pain must quickly become a ministry, or that your story belongs to anyone else. It means comfort is shared among God’s people: first you may simply receive it, and later, if you choose, you may pass it on.', 'Paul bénit le Dieu de toute consolation alors qu’il est encore dans l’épreuve, et non une fois qu’elle est passée. La consolation qu’il reçoit se transmet, pour que d’autres personnes éprouvées soient consolées à leur tour. Cela ne veut pas dire que ta souffrance doit vite devenir un ministère, ni que ton histoire appartient à quelqu’un d’autre. Cela veut dire que la consolation circule dans le peuple de Dieu : d’abord, tu peux simplement la recevoir ; plus tard, si tu le choisis, tu pourras la transmettre.'),
    prompts: [
      L('Thank God for one way you have received comfort during this journey, however small.', 'Remercie Dieu pour une consolation reçue pendant ce parcours, même petite.'),
      L('Ask Him to keep comforting you where the pain is still fresh.', 'Demande-Lui de continuer à te consoler là où la douleur est encore vive.'),
      L('Pray for someone else who is hurting after a church experience, by name if you know one.', 'Prie pour une autre personne blessée par une expérience d’Église, en la nommant si tu en connais une.'),
    ],
    practice: L('Thank one person who has comforted you during this season, with a message, a call or a handwritten note.', 'Remercie une personne qui t’a consolé en cette période, par un message, un appel ou un mot écrit à la main.'),
    resourceTopics: ['healing', 'suffering', 'pastoral-care'],
  },
  {
    movement: 'hope',
    theme: { en: 'The Lamb who will be our Shepherd', fr: 'L’Agneau qui sera notre Berger', es: 'El Cordero que será nuestro Pastor', pt: 'O Cordeiro que será o nosso Pastor', de: 'Das Lamm wird unser Hirte sein', ru: 'Агнец, который будет нашим Пастырем', zh: '羔羊必作我们的牧者', ja: '小羊が私たちの羊飼いとなる', ko: '우리의 목자가 되실 어린양', ar: 'الحمل الذي سيكون راعينا', fa: 'بره‌ای که شبان ما خواهد بود', hi: 'मेम्ना जो हमारा चरवाहा होगा', id: 'Anak Domba yang akan menjadi Gembala kita', sw: 'Mwana-Kondoo atakayekuwa Mchungaji wetu', tl: 'Ang Korderong magiging aming Pastol', am: 'እረኛችን የሚሆነው በግ' },
    ref: 'Revelation 7:13-17',
    related: ['1 Peter 2:25'],
    reflection: L('John sees a great multitude who have come out of great tribulation. The Lamb at the centre of the throne becomes their shepherd and leads them to springs of life-giving water, and God wipes away their tears. The final Shepherd of God’s people is the Lamb who was slain, who knows suffering from the inside. This hope does not erase what happened or hurry you now. It shows where the story of His flock is heading, and who will be tending it.', 'Jean voit une foule immense sortie de la grande épreuve. L’Agneau qui est au centre du trône devient son berger, la conduit vers des sources d’eau qui donnent la vie, et Dieu essuie ses larmes. Le Berger ultime du peuple de Dieu est l’Agneau immolé, qui connaît la souffrance de l’intérieur. Cette espérance n’efface pas ce qui s’est passé et ne te presse pas aujourd’hui. Elle montre vers quoi se dirige l’histoire de Son troupeau, et qui en prendra soin.'),
    prompts: [
      L('Thank Jesus, the Lamb and the Shepherd, for walking with you through these twenty-one days.', 'Remercie Jésus, l’Agneau et le Berger, d’avoir marché avec toi durant ces vingt et un jours.'),
      L('Tell Him what you still carry, and entrust it to His care beyond this plan.', 'Dis-Lui ce que tu portes encore, et confie-le à Ses soins au-delà de ce parcours.'),
      L('Pray for everyone wounded in His name, that they would find safety and true shepherding.', 'Prie pour tous ceux qui ont été blessés en Son nom, afin qu’ils trouvent la sécurité et de vrais bergers.'),
    ],
    practice: L('Choose one next step for the coming month, such as continuing with a counsellor, meeting a trusted believer or praying Psalm 23 each week, and write it down.', 'Choisis une prochaine étape pour le mois à venir, comme poursuivre un accompagnement, rencontrer un croyant de confiance ou prier le Psaume 23 chaque semaine, et note-la.'),
    safetyNote: L('Recovering from church hurt, and especially from abuse, often takes longer than a plan. If you still feel overwhelmed, unsafe or unable to cope, keep seeking support from a counsellor, a doctor or a safeguarding service; in an emergency, contact emergency services.', 'Se relever d’une blessure vécue dans l’Église, et plus encore d’abus, prend souvent plus de temps qu’un parcours. Si tu te sens encore submergé, en danger ou incapable de faire face, continue à chercher du soutien auprès d’un conseiller, d’un médecin ou d’un service de protection ; en cas d’urgence, contacte les services d’urgence.'),
    resourceTopics: ['healing', 'church-hurt', 'suffering'],
  },
];
