// 30-day marriage curriculum using the same rich-day shape as the
// singles plan. English/French prose is authored here; 14 lazy overlays live in
// translations/marriage30/. Day titles are present in every supported language.
// The no-children day is always complete; `withChildren` is only an additive
// presentation layer and never changes the schedule or day numbering.

import { PAUL_PLAN_SIGNOFF } from '../reviews/paul20260903';

const l = (en, fr) => ({ en, fr });
const title = (en, fr, es, pt, de, ru, zh, ja, ko, ar, fa, hi, id, sw, tl, am) => ({
  en, fr, es, pt, de, ru, zh, ja, ko, ar, fa, hi, id, sw, tl, am,
});

function day({
  theme, ref, related = [], reflection, prompt, spouse, self, marriage,
  practice, conversation, together, topics = [], safety, roles,
  roleReviewStatus, withChildren,
}) {
  return {
    theme,
    ref,
    related,
    reflection: l(...reflection),
    prompts: [l(...prompt)],
    spousePrompt: l(...spouse),
    selfPrompt: l(...self),
    marriagePrompt: l(...marriage),
    ...(practice ? { practice: l(...practice) } : {}),
    ...(conversation ? { conversationPrompt: l(...conversation) } : {}),
    ...(together ? { prayTogether: l(...together) } : {}),
    ...(safety ? { safetyNote: l(...safety) } : {}),
    ...(roles ? {
      roles: { husband: l(...roles.husband), wife: l(...roles.wife) },
      roleReviewStatus: roleReviewStatus || { status: 'needs_review' },
    } : {}),
    resourceTopics: topics,
    ...(withChildren ? { withChildren } : {}),
  };
}

const TOGETHER = [
  'If you both wish and feel safe, pray one sentence each from today’s prompts. Nothing is recorded or shared.',
  'Si vous le souhaitez tous les deux et vous sentez en sécurité, priez chacun une phrase à partir des pistes du jour. Rien n’est enregistré ni partagé.',
];

export const DAYS = [
  day({
    theme: title('Christ at the center', 'Christ au centre', 'Cristo en el centro', 'Cristo no centro', 'Christus im Mittelpunkt', 'Христос в центре', '以基督为中心', 'キリストを中心に', '그리스도를 중심에', 'المسيح في المركز', 'مسیح در مرکز', 'मसीह को केंद्र में', 'Kristus sebagai pusat', 'Kristo awe kiini', 'Si Cristo ang sentro', 'ክርስቶስ በማዕከል'),
    ref: 'Matthew 6:33', related: ['Colossians 1:17-18'],
    reflection: ['Marriage can serve God’s kingdom, but it cannot take Christ’s place. Begin this rhythm by receiving your life and your marriage from Him.', 'Le mariage peut servir le royaume de Dieu, mais il ne peut pas prendre la place de Christ. Commence ce rythme en recevant de Lui ta vie et ton mariage.'],
    prompt: ['Keep our love ordered beneath our love for You.', 'Garde notre amour à sa juste place, sous notre amour pour Toi.'],
    spouse: ['Draw {partner} nearer to Christ and sustain faith today.', 'Attire {partner} plus près de Christ et soutiens sa foi aujourd’hui.'],
    self: ['Show me where I expect marriage to carry what only You can carry.', 'Montre-moi où j’attends du mariage ce que Toi seul peux porter.'],
    marriage: ['Let our life together point beyond itself to Your goodness.', 'Que notre vie commune renvoie au-delà d’elle-même vers Ta bonté.'],
    practice: ['Begin with gratitude for Christ before asking for change.', 'Commence par remercier pour Christ avant de demander un changement.'],
    together: TOGETHER, topics: ['marriage', 'spiritual-rhythms', 'prayer-together'],
  }),
  day({
    theme: title('Gratitude for my spouse', 'Reconnaissance pour mon conjoint', 'Gratitud por mi cónyuge', 'Gratidão pelo meu cônjuge', 'Dankbarkeit für meinen Ehepartner', 'Благодарность за супруга', '为配偶感恩', '配偶への感謝', '배우자를 향한 감사', 'الامتنان لشريك حياتي', 'شکرگزاری برای همسرم', 'जीवनसाथी के लिए कृतज्ञता', 'Bersyukur atas pasangan', 'Shukrani kwa mwenzi wangu', 'Pasasalamat para sa asawa ko', 'ለትዳር አጋሬ ምስጋና'),
    ref: 'Philippians 1:3-6',
    reflection: ['Gratitude notices grace without pretending that either spouse is perfect. Thank God for the real person beside you.', 'La reconnaissance remarque la grâce sans prétendre qu’aucun conjoint est parfait. Remercie Dieu pour la personne réelle à tes côtés.'],
    prompt: ['Open my eyes to gifts I have started to overlook.', 'Ouvre mes yeux aux dons que j’ai commencé à ne plus voir.'],
    spouse: ['Thank You for {partner}; continue the good work You have begun.', 'Merci pour {partner} ; poursuis l’œuvre bonne que Tu as commencée.'],
    self: ['Free me from entitlement and train me to express thanks.', 'Libère-moi de l’exigence et apprends-moi à exprimer ma gratitude.'],
    marriage: ['Make gratitude a steady language in our marriage.', 'Fais de la reconnaissance un langage constant dans notre couple.'],
    practice: ['Name one specific thing you appreciate, without adding a request.', 'Nomme une chose précise que tu apprécies, sans ajouter de demande.'],
    conversation: ['What kindness from this week are you thankful for?', 'Pour quel geste de bonté de cette semaine es-tu reconnaissant ?'],
    topics: ['marriage', 'friendship', 'contentment'],
  }),
  day({
    theme: title('Friendship in marriage', 'L’amitié dans le mariage', 'Amistad en el matrimonio', 'Amizade no casamento', 'Freundschaft in der Ehe', 'Дружба в браке', '婚姻中的友谊', '結婚生活の友情', '결혼 안의 우정', 'الصداقة في الزواج', 'دوستی در ازدواج', 'विवाह में मित्रता', 'Persahabatan dalam pernikahan', 'Urafiki katika ndoa', 'Pagkakaibigan sa pag-aasawa', 'ወዳጅነት በትዳር'),
    ref: 'Ecclesiastes 4:9-10',
    reflection: ['Companionship grows through shared attention, ordinary delight, and help when one person is tired or discouraged.', 'La complicité grandit par l’attention partagée, la joie ordinaire et l’aide offerte lorsque l’un est fatigué ou découragé.'],
    prompt: ['Renew delight and simple companionship between us.', 'Renouvelle entre nous la joie et une simple complicité.'],
    spouse: ['Give {partner} trustworthy friendship in me and in our community.', 'Donne à {partner} une amitié fiable en moi et dans notre communauté.'],
    self: ['Make me curious, present, and willing to enjoy what matters to my spouse.', 'Rends-moi curieux, présent et prêt à apprécier ce qui compte pour mon conjoint.'],
    marriage: ['Help us carry burdens and also make room for joy.', 'Aide-nous à porter les fardeaux et à faire aussi place à la joie.'],
    practice: ['Choose ten unhurried minutes to enjoy something simple together.', 'Choisissez dix minutes sans hâte pour apprécier ensemble quelque chose de simple.'],
    conversation: ['When have we felt most like friends lately?', 'Quand nous sommes-nous sentis le plus amis récemment ?'],
    topics: ['friendship', 'marriage'],
  }),
  day({
    theme: title('Character at home', 'Le caractère à la maison', 'Carácter en el hogar', 'Caráter em casa', 'Charakter zu Hause', 'Характер дома', '家中的品格', '家庭で表れる品性', '가정에서 드러나는 성품', 'الشخصية في البيت', 'شخصیت در خانه', 'घर में चरित्र', 'Karakter di rumah', 'Tabia nyumbani', 'Ugali sa tahanan', 'ባህርይ በቤት'),
    ref: 'Galatians 5:22-23',
    reflection: ['The Spirit’s fruit matters in the unobserved moments of marriage. Public warmth cannot replace private patience, gentleness, and self-control.', 'Le fruit de l’Esprit compte dans les moments invisibles du mariage. La chaleur publique ne remplace pas la patience, la douceur et la maîtrise de soi en privé.'],
    prompt: ['Grow the fruit of Your Spirit in the ordinary rooms of our home.', 'Fais grandir le fruit de Ton Esprit dans les pièces ordinaires de notre foyer.'],
    spouse: ['Strengthen {partner} with patience, kindness, and peace.', 'Fortifie {partner} par la patience, la bonté et la paix.'],
    self: ['Expose the gap between how I appear and how I act at home.', 'Révèle l’écart entre l’image que je donne et ma conduite à la maison.'],
    marriage: ['Make our closest relationship a place where Christlike character grows.', 'Fais de notre relation la plus proche un lieu où grandit le caractère de Christ.'],
    practice: ['Respond gently to one interruption today.', 'Réponds avec douceur à une interruption aujourd’hui.'],
    roleReviewStatus: { ...PAUL_PLAN_SIGNOFF },
    roles: {
      husband: ['As a husband, ask for self-giving love, humble responsibility, and gentleness; do not use a role to control.', 'Comme mari, demande un amour qui se donne, une responsabilité humble et de la douceur ; n’utilise pas un rôle pour contrôler.'],
      wife: ['As a wife, ask for self-giving love, courageous wisdom, and gentleness; do not let a role silence truth or safety.', 'Comme épouse, demande un amour qui se donne, une sagesse courageuse et de la douceur ; ne laisse pas un rôle faire taire la vérité ou la sécurité.'],
    },
    topics: ['character', 'marriage-roles'],
  }),
  day({
    theme: title('Words that build up', 'Des paroles qui édifient', 'Palabras que edifican', 'Palavras que edificam', 'Worte, die aufbauen', 'Слова, которые созидают', '造就人的言语', '人を育てる言葉', '서로를 세우는 말', 'كلام يبني', 'سخنانی که بنا می‌کنند', 'हौसला बढ़ाने वाले शब्द', 'Perkataan yang membangun', 'Maneno yanayojenga', 'Mga salitang nagpapatibay', 'የሚያንጹ ቃላት'),
    ref: 'Ephesians 4:29',
    reflection: ['Truth and kindness belong together. The goal of communication is not merely to be heard, but to serve the other person’s good.', 'La vérité et la bonté vont ensemble. Le but de la communication n’est pas seulement d’être entendu, mais de servir le bien de l’autre.'],
    prompt: ['Guard our words from contempt, exaggeration, and needless harm.', 'Garde nos paroles du mépris, de l’exagération et des blessures inutiles.'],
    spouse: ['Give {partner} freedom to speak honestly and be received with care.', 'Donne à {partner} la liberté de parler avec sincérité et d’être accueilli avec soin.'],
    self: ['Show me how pride, distraction, or defensiveness shapes my speech.', 'Montre-moi comment l’orgueil, la distraction ou la défensive façonnent mes paroles.'],
    marriage: ['Make our communication truthful, gracious, and safe.', 'Rends notre communication vraie, pleine de grâce et sûre.'],
    practice: ['Replace one sharp or vague sentence with a clear, kind one.', 'Remplace une phrase dure ou vague par une parole claire et bienveillante.'],
    conversation: ['What helps you feel safe enough to say something difficult?', 'Qu’est-ce qui t’aide à te sentir assez en sécurité pour dire quelque chose de difficile ?'],
    together: TOGETHER, topics: ['communication', 'marriage'],
  }),
  day({
    theme: title('Listening before answering', 'Écouter avant de répondre', 'Escuchar antes de responder', 'Ouvir antes de responder', 'Zuhören vor dem Antworten', 'Слушать прежде чем отвечать', '先听后答', '答える前に聴く', '대답하기 전에 듣기', 'الاستماع قبل الإجابة', 'شنیدن پیش از پاسخ', 'उत्तर देने से पहले सुनना', 'Mendengar sebelum menjawab', 'Kusikiliza kabla ya kujibu', 'Makinig bago sumagot', 'ከመመለስ በፊት ማዳመጥ'),
    ref: 'James 1:19',
    reflection: ['Listening is a form of love. It slows the impulse to defend, solve, correct, or turn another person’s experience back toward ourselves.', 'Écouter est une forme d’amour. Cela ralentit l’envie de se défendre, de résoudre, de corriger ou de ramener l’expérience de l’autre à soi.'],
    prompt: ['Make us quick to listen and slow to assume.', 'Rends-nous prompts à écouter et lents à présumer.'],
    spouse: ['Let {partner} feel heard, valued, and free to finish a thought.', 'Que {partner} se sente écouté, estimé et libre d’aller au bout de sa pensée.'],
    self: ['Quiet the answer I am rehearsing while my spouse is speaking.', 'Fais taire la réponse que je prépare pendant que mon conjoint parle.'],
    marriage: ['Teach us to understand before seeking agreement.', 'Apprends-nous à comprendre avant de chercher l’accord.'],
    practice: ['Ask one open question, then summarize what you heard.', 'Pose une question ouverte, puis résume ce que tu as entendu.'],
    topics: ['listening', 'communication'],
  }),
  day({
    theme: title('Conflict without contempt', 'Le conflit sans mépris', 'Conflicto sin desprecio', 'Conflito sem desprezo', 'Konflikt ohne Verachtung', 'Конфликт без презрения', '不带蔑视地面对冲突', '軽蔑せずに対立と向き合う', '멸시 없이 갈등 다루기', 'خلاف بلا احتقار', 'اختلاف بدون تحقیر', 'तिरस्कार के बिना मतभेद', 'Konflik tanpa merendahkan', 'Migogoro bila dharau', 'Alitan na walang paghamak', 'ያለ ንቀት ግጭት'),
    ref: 'James 1:19-20', related: ['Proverbs 15:1'],
    reflection: ['Disagreement is ordinary; contempt, intimidation, manipulation, and fear must not become normal. Prayer can accompany a pause, repair, and wise outside help.', 'Le désaccord est ordinaire ; le mépris, l’intimidation, la manipulation et la peur ne doivent pas devenir normaux. La prière peut accompagner une pause, une réparation et une aide extérieure avisée.'],
    prompt: ['Slow anger and keep disagreement from becoming harm.', 'Ralentis la colère et empêche le désaccord de devenir une blessure.'],
    spouse: ['Give {partner} dignity, clarity, and safe support.', 'Donne à {partner} dignité, clarté et un soutien sûr.'],
    self: ['Show me my part without making me responsible for another person’s harmful choices.', 'Montre-moi ma part sans me rendre responsable des choix nuisibles d’une autre personne.'],
    marriage: ['Teach us repair, honest limits, and peacemaking rooted in truth.', 'Apprends-nous la réparation, des limites honnêtes et une paix enracinée dans la vérité.'],
    practice: ['If tension rises, choose a calm pause with a clear time to return.', 'Si la tension monte, choisis une pause calme avec un moment précis pour reprendre.'],
    conversation: ['What helps a hard conversation remain respectful and safe?', 'Qu’est-ce qui aide une conversation difficile à rester respectueuse et sûre ?'],
    safety: ['If conflict includes threats, coercion, violence, sexual pressure, stalking, or fear, prioritize safety and seek trusted professional, pastoral, medical, legal, or safeguarding help as appropriate. This plan cannot assess danger.', 'Si le conflit comprend menaces, contrainte, violence, pression sexuelle, harcèlement ou peur, donne la priorité à la sécurité et cherche, selon le besoin, une aide professionnelle, pastorale, médicale, juridique ou de protection digne de confiance. Ce parcours ne peut pas évaluer le danger.'],
    topics: ['conflict', 'abuse-safety', 'marriage-crisis'],
  }),
  day({
    theme: title('Forgiveness and repair', 'Pardon et réparation', 'Perdón y reparación', 'Perdão e reparação', 'Vergebung und Wiedergutmachung', 'Прощение и восстановление', '饶恕与修复', '赦しと関係の修復', '용서와 회복', 'الغفران والإصلاح', 'بخشش و جبران', 'क्षमा और सुधार', 'Pengampunan dan pemulihan', 'Msamaha na kurekebisha', 'Pagpapatawad at pag-aayos', 'ይቅርታና እርማት'),
    ref: 'Colossians 3:12-14', related: ['Ephesians 4:31-32'],
    reflection: ['Christian forgiveness rejects revenge and moves toward truth and mercy. It does not erase consequences, require immediate trust, or demand silence about abuse.', 'Le pardon chrétien renonce à la vengeance et avance vers la vérité et la miséricorde. Il n’efface pas les conséquences, n’exige pas une confiance immédiate et n’impose pas le silence face aux abus.'],
    prompt: ['Make confession honest and forgiveness free from denial.', 'Rends la confession honnête et le pardon libre de tout déni.'],
    spouse: ['Give {partner} grace to receive mercy and courage to name harm truthfully.', 'Donne à {partner} la grâce de recevoir la miséricorde et le courage de nommer le mal avec vérité.'],
    self: ['Teach me to apologize without excuse and to change where repentance requires action.', 'Apprends-moi à demander pardon sans excuse et à changer lorsque la repentance exige des actes.'],
    marriage: ['Build patterns of confession, wise boundaries, repair, and renewed trust where possible.', 'Établis des habitudes de confession, de limites sages, de réparation et, lorsque c’est possible, de confiance renouvelée.'],
    practice: ['Use a simple apology: name the action, its impact, and one change.', 'Présente une excuse simple : nomme l’acte, son impact et un changement.'],
    together: TOGETHER,
    safety: ['Forgiveness never requires remaining in immediate danger or refusing outside help. Safety, accountability, and lawful protection can be part of faithful action.', 'Le pardon n’exige jamais de rester dans un danger immédiat ni de refuser une aide extérieure. La sécurité, la responsabilité et la protection légale peuvent faire partie d’une action fidèle.'],
    topics: ['forgiveness', 'conflict', 'abuse-safety'],
  }),
  day({
    theme: title('Trust through honesty', 'La confiance par l’honnêteté', 'Confianza mediante la honestidad', 'Confiança pela honestidade', 'Vertrauen durch Ehrlichkeit', 'Доверие через честность', '以诚实建立信任', '誠実さによる信頼', '정직함으로 쌓는 신뢰', 'الثقة من خلال الصدق', 'اعتماد از راه صداقت', 'ईमानदारी से भरोसा', 'Kepercayaan melalui kejujuran', 'Uaminifu kupitia ukweli', 'Tiwala sa pamamagitan ng katapatan', 'እምነት በታማኝነት'),
    ref: 'Ephesians 4:25',
    reflection: ['Trust grows through truthful patterns, kept commitments, and humility when something has been hidden or broken.', 'La confiance grandit par des habitudes vraies, des engagements tenus et de l’humilité lorsqu’une chose a été cachée ou brisée.'],
    prompt: ['Bring our words, promises, and private choices into the light.', 'Amène à la lumière nos paroles, nos promesses et nos choix privés.'],
    spouse: ['Protect {partner} from deceit and give wise discernment.', 'Protège {partner} de la tromperie et donne un discernement sage.'],
    self: ['Show me where partial truth or avoidance weakens trust.', 'Montre-moi où une vérité partielle ou l’évitement affaiblit la confiance.'],
    marriage: ['Make reliability and truth normal between us.', 'Rends la fiabilité et la vérité habituelles entre nous.'],
    practice: ['Keep one small promise promptly today.', 'Tiens rapidement une petite promesse aujourd’hui.'],
    topics: ['trust', 'marriage'],
  }),
  day({
    theme: title('Emotional closeness', 'La proximité émotionnelle', 'Cercanía emocional', 'Proximidade emocional', 'Emotionale Nähe', 'Эмоциональная близость', '情感亲密', '心の親密さ', '정서적 친밀감', 'القرب العاطفي', 'صمیمیت عاطفی', 'भावनात्मक निकटता', 'Kedekatan emosional', 'Ukaribu wa kihisia', 'Emosyonal na pagiging malapit', 'ስሜታዊ ቅርበት'),
    ref: 'Romans 12:15',
    reflection: ['Closeness includes rejoicing, grieving, and making room for feelings without demanding that both spouses process them in the same way.', 'La proximité consiste à se réjouir, à pleurer et à faire place aux émotions sans exiger que les deux conjoints les vivent de la même manière.'],
    prompt: ['Give us compassion that does not rush another person’s emotions.', 'Donne-nous une compassion qui ne précipite pas les émotions de l’autre.'],
    spouse: ['Help {partner} feel known without being examined or managed.', 'Aide {partner} à se sentir connu sans être interrogé ni dirigé.'],
    self: ['Teach me to name my feelings honestly and receive my spouse’s experience with care.', 'Apprends-moi à nommer honnêtement mes émotions et à accueillir avec soin l’expérience de mon conjoint.'],
    marriage: ['Deepen tenderness, empathy, and freedom to be truthful.', 'Approfondis la tendresse, l’empathie et la liberté d’être vrai.'],
    conversation: ['What emotion has been hardest to share lately?', 'Quelle émotion a été la plus difficile à partager récemment ?'],
    topics: ['marriage', 'listening', 'friendship'],
  }),
  day({
    theme: title('Mutual and faithful intimacy', 'Une intimité mutuelle et fidèle', 'Intimidad mutua y fiel', 'Intimidade mútua e fiel', 'Gegenseitige und treue Intimität', 'Взаимная и верная близость', '彼此忠诚的亲密关系', '互いを尊ぶ誠実な親密さ', '상호적이고 신실한 친밀감', 'حميمية متبادلة وأمينة', 'صمیمیت متقابل و وفادارانه', 'परस्पर और विश्वासयोग्य अंतरंगता', 'Keintiman yang timbal balik dan setia', 'Ukaribu wa kuheshimiana na uaminifu', 'Tapat at kapwa-loob na pagiging malapit', 'የጋራና ታማኝ ቅርበት'),
    ref: '1 Corinthians 7:3-5', related: ['Hebrews 13:4'],
    reflection: ['Marital sexual intimacy belongs with mutuality, tenderness, honesty, and willing consent. Scripture must never be used to pressure, shame, or coerce a spouse.', 'L’intimité sexuelle conjugale va avec la réciprocité, la tendresse, l’honnêteté et un consentement libre. La Bible ne doit jamais servir à faire pression, à humilier ou à contraindre un conjoint.'],
    prompt: ['Form faithful intimacy marked by honor, patience, and mutual care.', 'Forme une intimité fidèle marquée par l’honneur, la patience et l’attention mutuelle.'],
    spouse: ['Guard {partner}’s dignity, body, history, and freedom from shame.', 'Garde la dignité, le corps, l’histoire et la liberté de {partner} face à la honte.'],
    self: ['Remove entitlement and teach me to communicate, listen, and honor boundaries.', 'Ôte tout sentiment de droit et apprends-moi à communiquer, écouter et respecter les limites.'],
    marriage: ['Let sexual faithfulness serve safety, affection, and covenant love.', 'Que la fidélité sexuelle serve la sécurité, l’affection et l’amour d’alliance.'],
    conversation: ['Only if both wish: what helps affection feel safe, mutual, and unhurried?', 'Seulement si vous le souhaitez tous les deux : qu’est-ce qui rend l’affection sûre, mutuelle et sans hâte ?'],
    safety: ['Sexual coercion is harm, including within marriage. If you feel pressured or unsafe, prioritize safety and seek qualified medical, counseling, pastoral, legal, or safeguarding support as appropriate.', 'La contrainte sexuelle est une violence, y compris dans le mariage. Si tu subis une pression ou ne te sens pas en sécurité, donne la priorité à ta sécurité et cherche, selon le besoin, une aide médicale, thérapeutique, pastorale, juridique ou de protection qualifiée.'],
    topics: ['sexual-intimacy', 'trust', 'abuse-safety'],
  }),
  day({
    theme: title('Faithfulness in every choice', 'La fidélité dans chaque choix', 'Fidelidad en cada decisión', 'Fidelidade em cada escolha', 'Treue in jeder Entscheidung', 'Верность в каждом выборе', '在每个选择中忠诚', '一つ一つの選択に表れる誠実さ', '모든 선택에서의 신실함', 'الأمانة في كل اختيار', 'وفاداری در هر انتخاب', 'हर चुनाव में विश्वासयोग्यता', 'Kesetiaan dalam setiap pilihan', 'Uaminifu katika kila uamuzi', 'Katapatan sa bawat pasya', 'በየምርጫው ታማኝነት'),
    ref: 'Hebrews 13:4',
    reflection: ['Faithfulness is formed in repeated choices: attention, honesty, boundaries, and turning away from secrecy that feeds betrayal.', 'La fidélité se forme dans des choix répétés : l’attention, l’honnêteté, les limites et le refus du secret qui nourrit la trahison.'],
    prompt: ['Guard our covenant in public, online, at work, and in private.', 'Garde notre alliance en public, en ligne, au travail et en privé.'],
    spouse: ['Protect {partner} from temptation and isolation; provide trustworthy support.', 'Protège {partner} de la tentation et de l’isolement ; donne un soutien fiable.'],
    self: ['Expose any secrecy I am protecting and lead me toward accountable truth.', 'Révèle tout secret que je protège et conduis-moi vers une vérité responsable.'],
    marriage: ['Strengthen loyalty without replacing wise accountability or help.', 'Fortifie la loyauté sans remplacer une responsabilité sage ni l’aide nécessaire.'],
    practice: ['Review one boundary that protects trust and make it clear.', 'Réexamine une limite qui protège la confiance et rends-la claire.'],
    safety: ['Betrayal, compulsive sexual behavior, or hidden addiction may require specialized counseling, medical care, pastoral accountability, safeguarding, or legal help. A harmed spouse is not responsible for another person’s choices.', 'La trahison, un comportement sexuel compulsif ou une dépendance cachée peuvent demander une thérapie spécialisée, des soins médicaux, une responsabilité pastorale, une protection ou une aide juridique. Le conjoint blessé n’est pas responsable des choix de l’autre.'],
    topics: ['marriage', 'trust', 'pornography', 'infidelity'],
  }),
  day({
    theme: title('Money as stewardship', 'L’argent comme intendance', 'El dinero como mayordomía', 'Dinheiro como mordomia', 'Geld als anvertrautes Gut', 'Деньги как доверенное управление', '以管家身份看待金钱', '委ねられたものとしてのお金', '청지기직으로서의 돈', 'المال كأمانة', 'پول به‌عنوان امانت', 'धन का भंडारीपन', 'Uang sebagai tanggung jawab', 'Fedha kama dhamana', 'Pera bilang katiwala', 'ገንዘብ እንደ አደራ'),
    ref: 'Matthew 6:19-21', related: ['1 Timothy 6:6-10'],
    reflection: ['Money can reveal fear, desire, and competing definitions of security. Prayer creates room for honest decisions; this plan does not provide financial advice.', 'L’argent peut révéler la peur, le désir et des définitions concurrentes de la sécurité. La prière ouvre un espace pour des décisions honnêtes ; ce parcours ne donne pas de conseil financier.'],
    prompt: ['Make our spending, saving, giving, and planning honest and generous.', 'Rends honnêtes et généreuses nos dépenses, notre épargne, nos dons et nos projets.'],
    spouse: ['Give {partner} wisdom and freedom from shame or control around money.', 'Donne à {partner} sagesse et liberté face à la honte ou au contrôle liés à l’argent.'],
    self: ['Show me where fear, status, secrecy, or entitlement shapes my choices.', 'Montre-moi où la peur, le statut, le secret ou l’exigence façonnent mes choix.'],
    marriage: ['Help us make financial decisions as one team with truthful limits.', 'Aide-nous à prendre les décisions financières comme une équipe, avec des limites vraies.'],
    conversation: ['What did money represent in each of our families growing up?', 'Que représentait l’argent dans chacune de nos familles pendant notre enfance ?'],
    topics: ['finances', 'marriage'],
  }),
  day({
    theme: title('Work and rest', 'Travail et repos', 'Trabajo y descanso', 'Trabalho e descanso', 'Arbeit und Ruhe', 'Труд и отдых', '工作与安息', '仕事と休息', '일과 쉼', 'العمل والراحة', 'کار و استراحت', 'काम और विश्राम', 'Kerja dan istirahat', 'Kazi na pumziko', 'Trabaho at pahinga', 'ሥራና ዕረፍት'),
    ref: 'Mark 6:31', related: ['Colossians 3:23-24'],
    reflection: ['Work matters, and human limits matter. A marriage needs honest rhythms for vocation, unpaid labor, caregiving, recreation, and rest.', 'Le travail compte, et les limites humaines aussi. Un couple a besoin de rythmes honnêtes pour la vocation, le travail non rémunéré, le soin, les loisirs et le repos.'],
    prompt: ['Order our work and rest without making either one an idol.', 'Ordonne notre travail et notre repos sans faire de l’un ou l’autre une idole.'],
    spouse: ['Sustain {partner} in work, hidden labor, and needed rest.', 'Soutiens {partner} dans le travail, les tâches invisibles et le repos nécessaire.'],
    self: ['Show me where I ignore my spouse’s labor or resist healthy limits.', 'Montre-moi où j’ignore le travail de mon conjoint ou refuse des limites saines.'],
    marriage: ['Give us fair, flexible rhythms that respect both people.', 'Donne-nous des rythmes justes et souples qui respectent chacun.'],
    conversation: ['Which responsibility feels unseen or too heavy right now?', 'Quelle responsabilité semble invisible ou trop lourde en ce moment ?'],
    topics: ['work', 'marriage'],
  }),
  day({
    theme: title('Spiritual rhythms together', 'Des rythmes spirituels à deux', 'Ritmos espirituales juntos', 'Ritmos espirituais juntos', 'Gemeinsame geistliche Rhythmen', 'Совместные духовные ритмы', '共同的属灵节奏', '共に育む霊的な習慣', '함께하는 영적 리듬', 'إيقاعات روحية معًا', 'ریتم‌های روحانی مشترک', 'साथ मिलकर आत्मिक लय', 'Irama rohani bersama', 'Mizani ya kiroho pamoja', 'Sabay na espirituwal na ritmo', 'የጋራ መንፈሳዊ ልምዶች'),
    ref: 'Colossians 3:16',
    reflection: ['Couples may pray, read, worship, and reflect differently. Shared faith does not require identical personalities or matching spiritual routines.', 'Les conjoints peuvent prier, lire, adorer et réfléchir différemment. Une foi partagée n’exige pas des personnalités identiques ni des habitudes spirituelles identiques.'],
    prompt: ['Give us rhythms that nourish faith without comparison or pressure.', 'Donne-nous des rythmes qui nourrissent la foi sans comparaison ni pression.'],
    spouse: ['Meet {partner} personally in Scripture, prayer, worship, and community.', 'Rencontre personnellement {partner} dans la Bible, la prière, l’adoration et la communauté.'],
    self: ['Keep me from judging my spouse’s spiritual life by my preferences.', 'Garde-moi de juger la vie spirituelle de mon conjoint selon mes préférences.'],
    marriage: ['Let faith be spoken, practiced, and received with grace in our home.', 'Que la foi soit dite, vécue et reçue avec grâce dans notre foyer.'],
    practice: ['Choose one small shared rhythm that leaves room for both people.', 'Choisissez un petit rythme commun qui laisse place à chacun.'],
    together: TOGETHER, topics: ['spiritual-rhythms', 'prayer-together', 'marriage'],
  }),
  day({
    theme: title('Prayer together', 'Prier ensemble', 'Orar juntos', 'Orar juntos', 'Gemeinsam beten', 'Молиться вместе', '一起祷告', '共に祈る', '함께 기도하기', 'الصلاة معًا', 'دعای مشترک', 'साथ प्रार्थना करना', 'Berdoa bersama', 'Kuomba pamoja', 'Manalangin nang magkasama', 'አብሮ መጸለይ'),
    ref: 'Philippians 4:6-7',
    reflection: ['Prayer together can be brief and ordinary. It is an invitation, not a performance test and never a tool for monitoring another person’s faith.', 'La prière à deux peut être brève et ordinaire. C’est une invitation, pas un test de performance ni un moyen de surveiller la foi de l’autre.'],
    prompt: ['Receive our gratitude, needs, and silence without performance.', 'Reçois notre gratitude, nos besoins et notre silence sans performance.'],
    spouse: ['Give {partner} freedom to pray in an honest and natural way.', 'Donne à {partner} la liberté de prier avec honnêteté et naturel.'],
    self: ['Make me patient and free from correcting how my spouse prays.', 'Rends-moi patient et libre du besoin de corriger la manière de prier de mon conjoint.'],
    marriage: ['Make prayer a place of peace rather than pressure.', 'Fais de la prière un lieu de paix plutôt que de pression.'],
    practice: ['If you both wish, pray one sentence of thanks and one request.', 'Si vous le souhaitez tous les deux, priez une phrase de gratitude et une demande.'],
    together: TOGETHER, topics: ['prayer-together', 'spiritual-rhythms'],
  }),
  day({
    theme: title('Rooted in church and community', 'Enracinés dans l’Église et la communauté', 'Arraigados en la iglesia y la comunidad', 'Enraizados na igreja e na comunidade', 'In Kirche und Gemeinschaft verwurzelt', 'Укоренённость в церкви и общине', '扎根于教会与群体', '教会と共同体に根ざす', '교회와 공동체에 뿌리내리기', 'متجذّران في الكنيسة والجماعة', 'ریشه‌دار در کلیسا و اجتماع', 'कलीसिया और समुदाय में जड़ें', 'Berakar dalam gereja dan komunitas', 'Kukita mizizi kanisani na katika jumuiya', 'Nakaugat sa iglesya at komunidad', 'በቤተ ክርስቲያንና ማህበረሰብ መሠረት መያዝ'),
    ref: 'Hebrews 10:24-25',
    reflection: ['Marriage should not become an isolated world. Christian community offers worship, friendship, service, perspective, encouragement, and sometimes needed help.', 'Le mariage ne doit pas devenir un monde isolé. La communauté chrétienne offre adoration, amitié, service, recul, encouragement et parfois l’aide nécessaire.'],
    prompt: ['Connect our marriage to a community where truth and care can grow.', 'Relie notre mariage à une communauté où la vérité et le soin peuvent grandir.'],
    spouse: ['Give {partner} faithful friendships beyond our marriage.', 'Donne à {partner} des amitiés fidèles au-delà de notre couple.'],
    self: ['Show me where possessiveness or busyness has narrowed our relationships.', 'Montre-moi où la possessivité ou l’activisme ont rétréci nos relations.'],
    marriage: ['Let our life together receive from and contribute to Your people.', 'Que notre vie commune reçoive de Ton peuple et y contribue.'],
    practice: ['Encourage or contact one trustworthy person outside your household.', 'Encourage ou contacte une personne de confiance hors de ton foyer.'],
    topics: ['church', 'community', 'marriage'],
  }),
  day({
    theme: title('Family boundaries with wisdom', 'Des limites familiales avec sagesse', 'Límites familiares con sabiduría', 'Limites familiares com sabedoria', 'Weise Grenzen in der Familie', 'Мудрые семейные границы', '有智慧的家庭界限', '知恵ある家族との境界', '지혜로운 가족 경계', 'حدود عائلية بحكمة', 'مرزهای خانوادگی حکیمانه', 'परिवार में बुद्धिमान सीमाएँ', 'Batas keluarga yang bijaksana', 'Mipaka ya kifamilia yenye hekima', 'Matalinong hangganan sa pamilya', 'ጥበባዊ የቤተሰብ ድንበሮች'),
    ref: 'Genesis 2:24',
    reflection: ['Forming a household changes family relationships without erasing honor or care. Boundaries may need flexibility, clarity, and stronger protection where relationships are unsafe.', 'Former un foyer transforme les relations familiales sans effacer l’honneur ni le soin. Les limites peuvent demander souplesse, clarté et une protection plus forte lorsque des relations sont dangereuses.'],
    prompt: ['Give us wisdom to honor relatives without surrendering the health of our household.', 'Donne-nous la sagesse d’honorer nos proches sans abandonner la santé de notre foyer.'],
    spouse: ['Give {partner} courage and peace in complicated family relationships.', 'Donne à {partner} courage et paix dans les relations familiales compliquées.'],
    self: ['Show me where loyalty, fear, or habit keeps me from hearing my spouse.', 'Montre-moi où la loyauté, la peur ou l’habitude m’empêchent d’écouter mon conjoint.'],
    marriage: ['Help us agree on privacy, caregiving, visits, holidays, and safe limits.', 'Aide-nous à nous accorder sur la vie privée, le soin, les visites, les fêtes et des limites sûres.'],
    conversation: ['Which family expectation needs a clearer and kinder boundary?', 'Quelle attente familiale demande une limite plus claire et plus bienveillante ?'],
    safety: ['A simple boundary is not always enough in abusive or coercive relationships. Seek qualified safeguarding, counseling, pastoral, medical, or legal support when needed.', 'Une simple limite ne suffit pas toujours dans une relation abusive ou coercitive. Cherche, si nécessaire, une aide qualifiée en protection, thérapie, pastorale, médecine ou droit.'],
    topics: ['family-of-origin', 'boundaries', 'abuse-safety'],
  }),
  day({
    theme: title('A hospitable home', 'Un foyer accueillant', 'Un hogar hospitalario', 'Um lar acolhedor', 'Ein gastfreundliches Zuhause', 'Гостеприимный дом', '好客的家', '人を迎える家庭', '환대하는 가정', 'بيت مضياف', 'خانه‌ای مهمان‌نواز', 'अतिथि-सत्कार वाला घर', 'Rumah yang ramah', 'Nyumba yenye ukarimu', 'Mapagpatuloy na tahanan', 'እንግዳ ተቀባይ ቤት'),
    ref: '1 Peter 4:9-10',
    reflection: ['Hospitality is generous attention, not a perfect home or constant availability. It can be practiced within real capacity and healthy limits.', 'L’hospitalité est une attention généreuse, pas une maison parfaite ni une disponibilité constante. Elle peut se vivre selon nos capacités réelles et avec des limites saines.'],
    prompt: ['Make our home and time available to others without pretense.', 'Rends notre foyer et notre temps disponibles aux autres sans prétention.'],
    spouse: ['Give {partner} joy, wisdom, and freedom to name limits.', 'Donne à {partner} joie, sagesse et liberté de nommer ses limites.'],
    self: ['Free me from impressing people or volunteering my spouse without consent.', 'Libère-moi du besoin d’impressionner ou d’engager mon conjoint sans son accord.'],
    marriage: ['Let welcome and rest coexist in our household.', 'Que l’accueil et le repos coexistent dans notre foyer.'],
    practice: ['Offer one manageable act of welcome or encouragement.', 'Offre un geste d’accueil ou d’encouragement à ta mesure.'],
    topics: ['hospitality', 'family', 'marriage'],
  }),
  day({
    theme: title('Serving side by side', 'Servir côte à côte', 'Servir lado a lado', 'Servir lado a lado', 'Seite an Seite dienen', 'Служить рядом', '并肩服侍', '共に仕える', '나란히 섬기기', 'الخدمة جنبًا إلى جنب', 'خدمت در کنار هم', 'कंधे से कंधा मिलाकर सेवा', 'Melayani berdampingan', 'Kutumikia pamoja', 'Magkatabing maglingkod', 'ጎን ለጎን ማገልገል'),
    ref: 'Galatians 5:13',
    reflection: ['Shared service can turn a household outward, but it should not become image management, exhaustion, or a fixed hierarchy of worth.', 'Le service commun peut ouvrir le foyer vers l’extérieur, mais il ne doit pas devenir une gestion d’image, un épuisement ou une hiérarchie fixe de valeur.'],
    prompt: ['Show us where our gifts can serve love rather than status.', 'Montre-nous où nos dons peuvent servir l’amour plutôt que le statut.'],
    spouse: ['Strengthen {partner}’s gifts without pressure to copy mine.', 'Fortifie les dons de {partner} sans pression pour qu’ils ressemblent aux miens.'],
    self: ['Make me willing to take unnoticed responsibility and to receive help.', 'Rends-moi prêt à prendre une responsabilité invisible et à recevoir de l’aide.'],
    marriage: ['Teach us partnership shaped by humility, consent, and shared responsibility.', 'Apprends-nous un partenariat marqué par l’humilité, le consentement et une responsabilité partagée.'],
    practice: ['Choose one task to carry together or redistribute fairly.', 'Choisissez une tâche à porter ensemble ou à redistribuer équitablement.'],
    roleReviewStatus: { ...PAUL_PLAN_SIGNOFF },
    roles: {
      husband: ['As a husband, practice leadership only as accountable, self-giving service; never as entitlement, control, or immunity from correction.', 'Comme mari, ne vis la conduite que comme un service responsable qui se donne ; jamais comme un droit, un contrôle ou une immunité face à la correction.'],
      wife: ['As a wife, practice courageous, self-giving service without surrendering voice, wisdom, safety, or equal dignity before God.', 'Comme épouse, vis un service courageux qui se donne sans abandonner ta voix, ta sagesse, ta sécurité ni ton égale dignité devant Dieu.'],
    },
    topics: ['mission', 'marriage-roles', 'character'],
  }),
  day({
    theme: title('Faithful in difficult seasons', 'Fidèles dans les saisons difficiles', 'Fieles en tiempos difíciles', 'Fiéis em tempos difíceis', 'Treu in schweren Zeiten', 'Верность в трудные времена', '在艰难季节中忠诚', '困難な時期にも誠実に', '어려운 계절에도 신실하게', 'الأمانة في المواسم الصعبة', 'وفاداری در فصل‌های دشوار', 'कठिन समय में विश्वासयोग्य', 'Setia dalam masa sulit', 'Uaminifu katika nyakati ngumu', 'Tapat sa mahihirap na panahon', 'በአስቸጋሪ ወቅቶች ታማኝ'),
    ref: 'Romans 12:12', related: ['Galatians 6:2'],
    reflection: ['Marriage includes pressures neither spouse can predict. Hope does not require pretending that grief, illness, loss, mental distress, or crisis is small.', 'Le mariage traverse des pressions qu’aucun conjoint ne peut prévoir. L’espérance n’exige pas de prétendre que le deuil, la maladie, la perte, la détresse psychique ou la crise sont insignifiants.'],
    prompt: ['Keep hope alive without asking us to deny pain.', 'Garde l’espérance vivante sans nous demander de nier la douleur.'],
    spouse: ['Carry {partner} with mercy in burdens I can and cannot see.', 'Porte {partner} avec miséricorde dans les fardeaux que je vois et ceux que je ne vois pas.'],
    self: ['Give me courage to be honest, ask for help, and respect my limits.', 'Donne-moi le courage d’être honnête, de demander de l’aide et de respecter mes limites.'],
    marriage: ['Sustain us through change and surround us with trustworthy care.', 'Soutiens-nous dans le changement et entoure-nous d’un soutien fiable.'],
    together: TOGETHER,
    safety: ['Prayer can accompany pastoral care, counseling, medical treatment, crisis services, and legal or safeguarding help. This plan does not diagnose or replace qualified support.', 'La prière peut accompagner l’accompagnement pastoral, la thérapie, les soins médicaux, les services de crise et l’aide juridique ou de protection. Ce parcours ne diagnostique pas et ne remplace pas un soutien qualifié.'],
    topics: ['suffering', 'grief', 'illness', 'marriage-crisis'],
  }),
  day({
    theme: title('Health and strength with humility', 'Santé et force avec humilité', 'Salud y fortaleza con humildad', 'Saúde e força com humildade', 'Gesundheit und Kraft in Demut', 'Здоровье и силы со смирением', '谦卑地面对健康与力量', '健康と力を謙虚に願う', '겸손히 구하는 건강과 힘', 'الصحة والقوة بتواضع', 'سلامتی و نیرو با فروتنی', 'नम्रता के साथ स्वास्थ्य और शक्ति', 'Kesehatan dan kekuatan dengan rendah hati', 'Afya na nguvu kwa unyenyekevu', 'Kalusugan at lakas na may pagpapakumbaba', 'ጤናና ኃይል በትሕትና'),
    ref: 'Psalm 73:26',
    reflection: ['Bodies have limits and health is not guaranteed. Pray for strength without treating sickness or disability as spiritual failure.', 'Les corps ont des limites et la santé n’est pas garantie. Prie pour la force sans traiter la maladie ou le handicap comme un échec spirituel.'],
    prompt: ['Meet us in strength and weakness; guide us toward wise care.', 'Rencontre-nous dans la force et la faiblesse ; conduis-nous vers des soins sages.'],
    spouse: ['Give {partner} the care, rest, access, treatment, and companionship needed today.', 'Donne à {partner} les soins, le repos, l’accès, le traitement et la présence nécessaires aujourd’hui.'],
    self: ['Teach me to care without controlling and to receive care without shame.', 'Apprends-moi à prendre soin sans contrôler et à recevoir de l’aide sans honte.'],
    marriage: ['Help us adapt faithfully to changing capacity.', 'Aide-nous à nous adapter fidèlement à des capacités changeantes.'],
    practice: ['Ask one practical question about rest, access, or support.', 'Pose une question concrète sur le repos, l’accès ou le soutien.'],
    topics: ['illness', 'suffering', 'marriage'],
  }),
  day({
    theme: title('Dreams and decisions', 'Rêves et décisions', 'Sueños y decisiones', 'Sonhos e decisões', 'Träume und Entscheidungen', 'Мечты и решения', '梦想与决定', '夢と決断', '꿈과 결정', 'الأحلام والقرارات', 'رویاها و تصمیم‌ها', 'सपने और निर्णय', 'Impian dan keputusan', 'Ndoto na maamuzi', 'Mga pangarap at pasya', 'ሕልሞችና ውሳኔዎች'),
    ref: 'James 1:5',
    reflection: ['Shared decisions need wisdom, time, truthful information, and freedom to name different hopes. Prayer is not a shortcut around consent or careful thought.', 'Les décisions communes demandent sagesse, temps, informations vraies et liberté de nommer des espoirs différents. La prière ne contourne ni le consentement ni une réflexion attentive.'],
    prompt: ['Give wisdom for choices before us and patience where clarity takes time.', 'Donne la sagesse pour les choix devant nous et la patience lorsque la clarté demande du temps.'],
    spouse: ['Guide {partner} without making me the interpreter of Your will.', 'Guide {partner} sans faire de moi l’interprète de Ta volonté.'],
    self: ['Expose where fear or control makes my preference sound absolute.', 'Révèle où la peur ou le contrôle rendent ma préférence absolue.'],
    marriage: ['Teach us to decide with honesty, shared agency, counsel, and peace.', 'Apprends-nous à décider avec honnêteté, responsabilité partagée, conseil et paix.'],
    conversation: ['Which decision needs more information, counsel, or time?', 'Quelle décision demande davantage d’information, de conseil ou de temps ?'],
    together: TOGETHER, topics: ['discernment', 'trust', 'marriage'],
  }),
  day({
    theme: title('Contentment in ordinary life', 'Le contentement dans la vie ordinaire', 'Contentamiento en la vida cotidiana', 'Contentamento na vida comum', 'Zufriedenheit im Alltag', 'Довольство в обычной жизни', '平凡生活中的知足', '日常にある満足', '평범한 삶 속의 자족', 'القناعة في الحياة العادية', 'قناعت در زندگی روزمره', 'साधारण जीवन में संतोष', 'Rasa cukup dalam keseharian', 'Kuridhika katika maisha ya kawaida', 'Pagiging kontento sa karaniwang buhay', 'በመደበኛ ሕይወት እርካታ'),
    ref: 'Philippians 4:11-13',
    reflection: ['Contentment receives today without denying real needs or refusing healthy change. Comparison can make an ordinary marriage feel perpetually deficient.', 'Le contentement reçoit aujourd’hui sans nier les besoins réels ni refuser un changement sain. La comparaison peut faire paraître un mariage ordinaire toujours insuffisant.'],
    prompt: ['Free us from measuring our marriage against curated images or imagined lives.', 'Libère-nous de mesurer notre couple aux images choisies ou aux vies imaginées.'],
    spouse: ['Give {partner} joy that is not dependent on matching another household.', 'Donne à {partner} une joie qui ne dépend pas de ressembler à un autre foyer.'],
    self: ['Show me what I can gratefully receive and what I should responsibly address.', 'Montre-moi ce que je peux recevoir avec gratitude et ce que je dois traiter avec responsabilité.'],
    marriage: ['Root our peace in Christ while keeping us open to growth.', 'Enracine notre paix en Christ tout en nous gardant ouverts à la croissance.'],
    practice: ['Name one ordinary gift from today.', 'Nomme un don ordinaire reçu aujourd’hui.'],
    topics: ['contentment', 'marriage'],
  }),
  day({
    theme: title('Protecting time together', 'Protéger le temps à deux', 'Proteger el tiempo juntos', 'Proteger o tempo juntos', 'Gemeinsame Zeit schützen', 'Беречь время вдвоём', '守护相处的时间', '二人の時間を守る', '함께하는 시간 지키기', 'حماية الوقت معًا', 'حفظ زمان باهم بودن', 'साथ के समय की रक्षा', 'Menjaga waktu bersama', 'Kulinda wakati wa pamoja', 'Pangalagaan ang oras na magkasama', 'የጋራ ጊዜን መጠበቅ'),
    ref: 'Ephesians 5:15-16',
    reflection: ['Attention is finite. Protecting connection may require boundaries around work, screens, commitments, and even good activities.', 'L’attention est limitée. Protéger le lien peut demander des limites autour du travail, des écrans, des engagements et même de bonnes activités.'],
    prompt: ['Teach us to use time wisely without turning closeness into another task.', 'Apprends-nous à bien employer le temps sans transformer la proximité en tâche supplémentaire.'],
    spouse: ['Help {partner} feel chosen without being isolated from needed rest or relationships.', 'Aide {partner} à se sentir choisi sans être isolé du repos ni des relations nécessaires.'],
    self: ['Show me what repeatedly receives my best attention while my spouse receives what remains.', 'Montre-moi ce qui reçoit constamment ma meilleure attention tandis que mon conjoint reçoit ce qui reste.'],
    marriage: ['Give us realistic rhythms of attention, play, conversation, and rest.', 'Donne-nous des rythmes réalistes d’attention, de jeu, de conversation et de repos.'],
    practice: ['Protect one short block of undistracted time this week.', 'Protège un court moment sans distraction cette semaine.'],
    conversation: ['What kind of time together restores rather than drains us?', 'Quel type de temps à deux nous restaure au lieu de nous épuiser ?'],
    topics: ['friendship', 'work', 'marriage'],
  }),
  day({
    theme: title('Wisdom for those in our care', 'La sagesse pour ceux qui nous sont confiés', 'Sabiduría para quienes cuidamos', 'Sabedoria para quem cuidamos', 'Weisheit für Menschen in unserer Obhut', 'Мудрость для тех, о ком мы заботимся', '为所照顾的人求智慧', '委ねられた人を支える知恵', '우리에게 맡겨진 이들을 위한 지혜', 'الحكمة لمن نرعاهم', 'حکمت برای کسانی که از آنان مراقبت می‌کنیم', 'हमारी देखभाल में लोगों के लिए बुद्धि', 'Hikmat bagi mereka yang kami rawat', 'Hekima kwa walio chini ya uangalizi wetu', 'Karunungan para sa mga inaalagaan namin', 'በእንክብካቤያችን ላሉት ጥበብ'),
    ref: 'James 1:5',
    reflection: ['Every household has people to love and responsibilities to carry. Parenting, when present, is one calling within the family and not the condition that makes a marriage complete.', 'Chaque foyer a des personnes à aimer et des responsabilités à porter. La parentalité, lorsqu’elle est présente, est un appel au sein de la famille et non la condition qui rend un mariage complet.'],
    prompt: ['Give us wisdom to care without trying to control outcomes.', 'Donne-nous la sagesse de prendre soin sans chercher à contrôler les résultats.'],
    spouse: ['Strengthen {partner} in each responsibility carried today.', 'Fortifie {partner} dans chaque responsabilité portée aujourd’hui.'],
    self: ['Make me patient, teachable, and willing to repair when my care causes harm.', 'Rends-moi patient, disposé à apprendre et prêt à réparer lorsque ma manière de prendre soin blesse.'],
    marriage: ['Keep our partnership whole and loving as responsibilities change.', 'Garde notre partenariat entier et aimant lorsque les responsabilités changent.'],
    practice: ['Offer one concrete act of patient care without expecting recognition.', 'Offre un geste concret de soin patient sans attendre de reconnaissance.'],
    topics: ['family', 'marriage'],
    withChildren: {
      reflection: l('Parenting calls for wisdom, humility, repair, and respect for each child as a person before God. Prayer does not guarantee a child’s choices.', 'Être parent demande sagesse, humilité, réparation et respect de chaque enfant comme personne devant Dieu. La prière ne garantit pas les choix d’un enfant.'),
      childPrompt: l('Give {child} wise care, courage, trustworthy relationships, and room to grow; make us humble and attentive as parents.', 'Donne à {child} des soins sages, du courage, des relations fiables et de l’espace pour grandir ; rends-nous humbles et attentifs comme parents.'),
      practice: l('Give each child a moment of unhurried attention, without interrogation.', 'Accorde à chaque enfant un moment d’attention sans hâte ni interrogatoire.'),
      resourceTopics: ['parenting', 'children', 'family-discipleship'],
    },
  }),
  day({
    theme: title('Each person known by God', 'Chaque personne connue de Dieu', 'Cada persona conocida por Dios', 'Cada pessoa conhecida por Deus', 'Jeder Mensch von Gott gekannt', 'Каждый человек известен Богу', '每个人都被上帝认识', '一人ひとりを知る神', '각 사람을 아시는 하나님', 'كل شخص معروف لدى الله', 'هر شخص نزد خدا شناخته‌شده است', 'हर व्यक्ति परमेश्वर को ज्ञात', 'Setiap pribadi dikenal Allah', 'Kila mtu anajulikana na Mungu', 'Bawat tao ay kilala ng Diyos', 'እያንዳንዱ ሰው በእግዚአብሔር የታወቀ'),
    ref: 'Psalm 139:1-6', related: ['Proverbs 13:20'],
    reflection: ['The people around us belong first to God, not to our plans. Love can guide, listen, protect, and pray without claiming control over another person’s future.', 'Les personnes autour de nous appartiennent d’abord à Dieu, pas à nos projets. L’amour peut guider, écouter, protéger et prier sans prétendre contrôler l’avenir d’autrui.'],
    prompt: ['Help us love people as persons, not projects.', 'Aide-nous à aimer les personnes comme des personnes, pas comme des projets.'],
    spouse: ['Remind {partner} of being fully known and held by You.', 'Rappelle à {partner} qu’il est pleinement connu et porté par Toi.'],
    self: ['Free me from anxiety that becomes control or from distance that avoids responsibility.', 'Libère-moi de l’anxiété qui devient contrôle ou de la distance qui évite la responsabilité.'],
    marriage: ['Make our household a place of attentive love and appropriate freedom.', 'Fais de notre foyer un lieu d’amour attentif et de liberté adaptée.'],
    conversation: ['Who needs listening, guidance, or encouragement from us this week?', 'Qui a besoin de notre écoute, de nos conseils ou de nos encouragements cette semaine ?'],
    topics: ['family', 'friendship'],
    withChildren: {
      reflection: l('Each child is known by God and has a life that cannot be scripted by parental fear. Pray with hope and open hands.', 'Chaque enfant est connu de Dieu et possède une vie que la peur parentale ne peut pas écrire. Prie avec espérance et les mains ouvertes.'),
      childPrompt: l('Give {child} wise and faithful friends, courage before unhealthy influence, compassion as a friend, and parents who guide without controlling.', 'Donne à {child} des amis sages et fidèles, du courage face aux mauvaises influences, de la compassion dans l’amitié et des parents qui guident sans contrôler.'),
      practice: l('Ask each child one open question about a friend and simply listen.', 'Pose à chaque enfant une question ouverte sur un ami et écoute simplement.'),
      resourceTopics: ['children', 'parenting', 'friendship'],
    },
  }),
  day({
    theme: title('The culture of our home', 'La culture de notre foyer', 'La cultura de nuestro hogar', 'A cultura do nosso lar', 'Die Kultur unseres Zuhauses', 'Культура нашего дома', '我们家的文化', 'わが家の文化', '우리 가정의 문화', 'ثقافة بيتنا', 'فرهنگ خانه ما', 'हमारे घर की संस्कृति', 'Budaya rumah kami', 'Utamaduni wa nyumba yetu', 'Kultura ng aming tahanan', 'የቤታችን ባህል'),
    ref: 'Colossians 3:12-15',
    reflection: ['A household culture forms through repeated words, habits, celebrations, repairs, and ways of using power. It is meaningful with or without children.', 'La culture d’un foyer se forme par des paroles, des habitudes, des fêtes, des réparations et des manières d’exercer le pouvoir. Elle a du sens avec ou sans enfants.'],
    prompt: ['Clothe our home with compassion, humility, patience, love, and peace.', 'Revêts notre foyer de compassion, d’humilité, de patience, d’amour et de paix.'],
    spouse: ['Give {partner} voice and belonging in shaping our shared life.', 'Donne à {partner} une voix et une vraie place dans la construction de notre vie commune.'],
    self: ['Show me which repeated habit creates welcome and which creates fear or distance.', 'Montre-moi quelle habitude répétée crée l’accueil et laquelle crée la peur ou la distance.'],
    marriage: ['Help us build a home marked by truth, kindness, repair, rest, and joy.', 'Aide-nous à bâtir un foyer marqué par la vérité, la bonté, la réparation, le repos et la joie.'],
    practice: ['Choose one small household habit to strengthen or change.', 'Choisissez une petite habitude du foyer à fortifier ou à changer.'],
    conversation: ['What do we want people to experience in our home?', 'Que voulons-nous que les personnes vivent dans notre foyer ?'],
    topics: ['family', 'marriage'],
  }),
  day({
    theme: title('Generosity and mission', 'Générosité et mission', 'Generosidad y misión', 'Generosidade e missão', 'Großzügigkeit und Mission', 'Щедрость и миссия', '慷慨与使命', '惜しみない心と使命', '관대함과 사명', 'الكرم والرسالة', 'سخاوت و رسالت', 'उदारता और मिशन', 'Kemurahan hati dan misi', 'Ukarimu na utume', 'Pagkamapagbigay at misyon', 'ልግስናና ተልዕኮ'),
    ref: '2 Corinthians 9:7-8', related: ['1 Peter 4:10'],
    reflection: ['Generosity is willing and wise, not coerced. A marriage can share time, attention, skills, money, and welcome without seeking status or neglecting real limits.', 'La générosité est volontaire et sage, non forcée. Un couple peut partager temps, attention, compétences, argent et accueil sans chercher le statut ni négliger ses limites réelles.'],
    prompt: ['Make us generous from grace rather than guilt or appearance.', 'Rends-nous généreux par grâce plutôt que par culpabilité ou apparence.'],
    spouse: ['Guide {partner}’s gifts toward life-giving service.', 'Guide les dons de {partner} vers un service qui donne la vie.'],
    self: ['Show me where I cling tightly or give away what is not mine to promise.', 'Montre-moi où je m’accroche trop ou promets ce qui ne m’appartient pas.'],
    marriage: ['Turn our household outward in ways that are faithful and sustainable.', 'Tourne notre foyer vers les autres d’une manière fidèle et durable.'],
    practice: ['Choose one shared act of generosity that both spouses can freely support.', 'Choisissez un geste commun de générosité que chacun peut librement soutenir.'],
    together: TOGETHER, topics: ['generosity', 'mission', 'hospitality'],
  }),
  day({
    theme: title('Our marriage in open hands', 'Notre mariage entre des mains ouvertes', 'Nuestro matrimonio en manos abiertas', 'Nosso casamento de mãos abertas', 'Unsere Ehe in offenen Händen', 'Наш брак в открытых руках', '张开双手交托婚姻', '開いた手で結婚を委ねる', '열린 손으로 맡기는 결혼', 'زواجنا بأيدٍ مفتوحة', 'ازدواجمان با دستان باز', 'खुले हाथों में हमारा विवाह', 'Pernikahan kami dalam tangan terbuka', 'Ndoa yetu mikononi mwako', 'Ang aming pagsasama sa bukas na mga kamay', 'ትዳራችንን በተከፈተ እጅ መስጠት'),
    ref: 'Psalm 127:1',
    reflection: ['A prayer plan cannot secure a marriage or measure its worth. End by thanking God, receiving responsibility for today, and surrendering what neither spouse can control.', 'Un parcours de prière ne peut ni garantir un mariage ni en mesurer la valeur. Termine en remerciant Dieu, en assumant la responsabilité d’aujourd’hui et en Lui remettant ce qu’aucun conjoint ne peut contrôler.'],
    prompt: ['Build what is good in our marriage and correct what is not.', 'Bâtis ce qui est bon dans notre mariage et corrige ce qui ne l’est pas.'],
    spouse: ['Hold {partner} with mercy, freedom, wisdom, and enduring love.', 'Porte {partner} avec miséricorde, liberté, sagesse et un amour durable.'],
    self: ['Keep forming humility, courage, faithfulness, and repentance in me.', 'Continue à former en moi l’humilité, le courage, la fidélité et la repentance.'],
    marriage: ['Receive our gratitude and keep our marriage open to Your guidance and the help we need.', 'Reçois notre reconnaissance et garde notre couple ouvert à Ta direction et à l’aide dont nous avons besoin.'],
    practice: ['Thank God for one grace, name one responsibility, and release one fear.', 'Remercie Dieu pour une grâce, nomme une responsabilité et dépose une peur.'],
    together: TOGETHER, topics: ['marriage', 'covenant', 'prayer-together'],
  }),
];

export default DAYS;
