// Prayer plan templates: guided journeys with a theme + Scripture for each day.
// Starting a plan creates ONE recurring prayer (freq daily, end after N times,
// schedule.plan = { id, version?, startDate }); the engine numbers the days and this file
// supplies each day's content. Themes are AUTHORED (not generated) in all 16
// supported languages and resolved via pick(); pick() still falls back to
// English if a key is ever missing. Verse references are language-neutral and
// resolve through the localized verse pipeline.
//
// Each plan also carries teaching content the detail view shows before a user
// commits: `intro` (what the journey is) and `biblical` (the Scripture story it
// follows — when and how it was prayed/fasted in the Bible, with a reference).
// Following the teaching-content convention, intro/biblical are authored in
// English + French only and fall back to English via pick() in other languages;
// the per-day themes remain authored in all 16 languages.

import { PREPARING_IN_PRAYER } from './plans/preparingInPrayer';
import { PREPARING_FOR_COVENANT } from './plans/preparingForCovenant';
import { PRAYING_FOR_OUR_MARRIAGE } from './plans/prayingForOurMarriage';
import { canUsePlan } from '../lib/planReview';

// Plans are grouped in the UI by CATEGORY so the list stays browsable as it
// grows. `id` is stable; the label is an i18n key resolved at render.
export const PLAN_CATEGORIES = [
  { id: 'seeking', labelKey: 'planCategorySeeking' },
  { id: 'others', labelKey: 'planCategoryOthers' },
  { id: 'relationships', labelKey: 'planCategoryRelationships' },
];

// Plans with no category of their own fall in here, so an older plan never
// disappears from the list just because categories were introduced.
export const DEFAULT_PLAN_CATEGORY = 'seeking';

export const PLANS = [

  {
    id: 'fast3',
    category: 'seeking',
    emoji: '🕯️',
    count: 3,
    titleKey: 'planFast3Title',
    subKey: 'planFast3Sub',
    intro: {
      en: "A short, focused fast in the pattern of Scripture: three days set apart to humble yourself, seek God's face, and pray for a breakthrough only He can give. Fast in a way that is wise for your health — a meal, a whole day, or the Daniel fast (giving up rich food) — and offer the hunger back to God as prayer. The point was never the food; it was turning wholly to Him.",
      fr: "Un jeûne court et ciblé, à la manière de l'Écriture : trois jours mis à part pour t'humilier, chercher la face de Dieu et prier pour une percée que Lui seul peut donner. Jeûne d'une façon sage pour ta santé — un repas, une journée entière ou le jeûne de Daniel (renoncer aux mets délicats) — et offre cette faim à Dieu comme une prière. Le jeûne n'a jamais concerné la nourriture, mais le fait de se tourner entièrement vers Lui.",
    },
    biblical: {
      ref: 'Esther 4:15-16',
      text: {
        en: "Facing an impossible situation, Esther called her people to a three-day fast — neither eating nor drinking, night or day — before she dared approach the king: 'If I perish, I perish' (Esther 4:16). Scripture is full of three-day fasts sought before God: Nineveh turned from ruin (Jonah 3), Ezra fasted for protection on a dangerous road (Ezra 8:21-23), and after meeting the risen Jesus, Saul spent three days without food or drink (Acts 9:9). Three days, set apart, to trust God for deliverance.",
        fr: "Face à une situation impossible, Esther appela son peuple à un jeûne de trois jours — sans manger ni boire, ni jour ni nuit — avant d'oser s'approcher du roi : « Si je péris, je péris » (Esther 4:16). L'Écriture est remplie de jeûnes de trois jours devant Dieu : Ninive se détourna de sa ruine (Jonas 3), Esdras jeûna pour être protégé sur une route dangereuse (Esdras 8:21-23), et après sa rencontre avec Jésus ressuscité, Saul resta trois jours sans manger ni boire (Actes 9:9). Trois jours, mis à part, pour se confier en Dieu pour la délivrance.",
      },
    },
    days: [
      { theme: { en: 'Consecrate the fast — turn your whole heart to God', fr: 'Consacre le jeûne — tourne tout ton cœur vers Dieu', es: 'Consagra el ayuno — vuelve todo tu corazón a Dios', pt: 'Consagre o jejum — volte todo o seu coração para Deus', de: 'Weihe das Fasten — wende dein ganzes Herz Gott zu', ru: 'Освяти пост — обрати всё сердце к Богу', zh: '分别这禁食——全心归向神', ja: '断食を聖別しよう——心を尽くして神様に向かおう', ko: '금식을 구별하라 — 온 마음을 하나님께 돌이키라', ar: 'كرِّس الصوم — ارجع بكل قلبك إلى الله', fa: 'روزه را تقدیس کن — با تمام دل به‌سوی خدا بازگرد', hi: 'उपवास को समर्पित करें — अपना सारा मन परमेश्वर की ओर लगाएं', id: 'Kuduskan puasa ini — berbaliklah dengan segenap hati kepada Allah', sw: 'Weka wakfu mfungo huu — mgeukie Mungu kwa moyo wako wote', tl: 'Italaga ang pag-aayuno — ibaling ang buong puso mo sa Diyos', am: 'ጾሙን ቀድስ — ልብህን ሙሉ በሙሉ ወደ እግዚአብሔር መልስ' }, ref: 'Joel 2:12' },
      { theme: { en: 'Choose the fast God loves — humble yourself and loosen every chain', fr: "Choisis le jeûne que Dieu aime — humilie-toi et brise toute chaîne", es: 'Escoge el ayuno que Dios ama — humíllate y rompe toda cadena', pt: 'Escolha o jejum que Deus ama — humilhe-se e quebre toda corrente', de: 'Wähle das Fasten, das Gott gefällt — demütige dich und löse jede Kette', ru: 'Избери пост, угодный Богу — смирись и разорви всякую цепь', zh: '选择神所喜悦的禁食——谦卑自己，松开一切锁链', ja: '神様が喜ばれる断食を選ぼう——へりくだり、すべての鎖を解こう', ko: '하나님이 기뻐하시는 금식을 택하라 — 자신을 낮추고 모든 결박을 풀라', ar: 'اختَر الصوم الذي يحبه الله — اتّضع وفُكَّ كل قيد', fa: 'روزه‌ای را برگزین که خدا می‌پسندد — فروتن شو و هر زنجیر را بگسل', hi: 'वह उपवास चुनें जिससे परमेश्वर प्रेम करता है — नम्र बनें और हर बंधन तोड़ें', id: 'Pilih puasa yang Allah kehendaki — rendahkan dirimu dan lepaskan setiap belenggu', sw: 'Chagua mfungo ampendao Mungu — jinyenyekeze na ufungue kila mnyororo', tl: 'Piliin ang pag-aayunong minamahal ng Diyos — magpakumbaba at kalagin ang bawat tanikala', am: 'እግዚአብሔር የሚወደውን ጾም ምረጥ — ራስህን አዋርድ፤ ሁሉንም ሰንሰለት ፍታ' }, ref: 'Isaiah 58:6' },
      { theme: { en: "Stand in the gap with bold faith — 'If I perish, I perish'", fr: "Tiens-toi sur la brèche avec une foi audacieuse — « Si je péris, je péris »", es: 'Ponte en la brecha con fe audaz — «Si perezco, que perezca»', pt: 'Ponha-se na brecha com fé ousada — “Se perecer, perecerei”', de: 'Tritt mit kühnem Glauben in den Riss — „Komme ich um, so komme ich um“', ru: 'Встань в проломе с дерзновенной верой — «Если погибнуть — погибну»', zh: '以刚强的信心站在破口——「我若死就死吧」', ja: '大胆な信仰で破れ口に立とう——「死ななければならないなら、死にます」', ko: "담대한 믿음으로 무너진 곳에 서라 — '죽으면 죽으리이다'", ar: 'قِف في الثغرة بإيمان جريء — «إن هلكتُ هلكتُ»', fa: 'با ایمانی دلیر در شکاف بایست — «اگر هلاک شوم، هلاک شوم»', hi: "साहसिक विश्वास के साथ नाके में खड़े हों — 'यदि मैं नष्ट हो जाऊं, तो हो जाऊं'", id: "Berdirilah di celah dengan iman yang berani — 'Kalau terpaksa mati, biarlah aku mati'", sw: "Simama katika lengo kwa imani thabiti — 'Nikiangamia, na niangamie'", tl: "Tumayo sa puwang nang may matapang na pananampalataya — 'Kung ako'y mamatay, mamatay'", am: "በድፍረት እምነት በተሰበረው ስፍራ ቁም — 'ብጠፋም ልጥፋ'" }, ref: 'Esther 4:16' },
    ],
  },
  {
    id: 'altar7',
    category: 'seeking',
    emoji: '🕊️',
    count: 7,
    titleKey: 'planAltar7Title',
    subKey: 'planAltar7Sub',
    intro: {
      en: "Seven days to come home to God and rebuild the altar of prayer that has grown cold. Like Elijah repairing the broken-down altar before the fire fell, you'll clear away what crowded God out, draw near again, and let hunger and thirst for His presence and His Word be rekindled — until meeting with God is the joy of your day, not a duty.",
      fr: "Sept jours pour revenir à Dieu et rebâtir l'autel de la prière qui s'est refroidi. Comme Élie réparant l'autel démoli avant que le feu ne tombe, tu ôteras ce qui a pris Sa place, tu t'approcheras de nouveau, et tu laisseras se raviver la faim et la soif de Sa présence et de Sa Parole — jusqu'à ce que la rencontre avec Dieu devienne la joie de ta journée, et non un devoir.",
    },
    biblical: {
      ref: '1 Kings 18:30-39',
      text: {
        en: "When Israel's altars lay in ruins, Elijah said to the people, 'Come near to me,' and he repaired the altar of the LORD that had been thrown down (1 Kings 18:30). He rebuilt it stone by stone, laid the sacrifice, and prayed — and the fire of the LORD fell (1 Kings 18:38). Scripture calls us again and again to return: 'Come, let us return to the LORD' (Hosea 6:1), 'Draw near to God, and he will draw near to you' (James 4:8). This week you repair your own altar and wait for the fire to fall again.",
        fr: "Alors que les autels d'Israël étaient en ruine, Élie dit au peuple : « Approchez-vous de moi », et il rétablit l'autel de l'Éternel qui avait été renversé (1 Rois 18:30). Il le rebâtit pierre après pierre, disposa le sacrifice et pria — et le feu de l'Éternel tomba (1 Rois 18:38). L'Écriture nous appelle sans cesse à revenir : « Venez, retournons à l'Éternel » (Osée 6:1), « Approchez-vous de Dieu, et il s'approchera de vous » (Jacques 4:8). Cette semaine, tu répares ton propre autel et tu attends que le feu tombe de nouveau.",
      },
    },
    days: [
      { theme: { en: 'Return to the LORD with all your heart', fr: "Reviens à l'Éternel de tout ton cœur", es: 'Vuelve al SEÑOR con todo tu corazón', pt: 'Volte ao SENHOR de todo o seu coração', de: 'Kehre zum HERRN um mit deinem ganzen Herzen', ru: 'Обратись к Господу всем сердцем', zh: '全心回转归向耶和华', ja: '心を尽くして主に立ち返ろう', ko: '마음을 다해 여호와께로 돌아오라', ar: 'ارجع إلى الرب بكل قلبك', fa: 'با تمام دل به‌سوی خداوند بازگرد', hi: 'अपने पूरे मन से यहोवा की ओर लौट आएं', id: 'Kembalilah kepada TUHAN dengan segenap hatimu', sw: 'Mrudie BWANA kwa moyo wako wote', tl: 'Manumbalik sa PANGINOON nang buong puso', am: 'በፍጹም ልብህ ወደ እግዚአብሔር ተመለስ' }, ref: 'Joel 2:12-13' },
      { theme: { en: 'Repair the altar that has broken down', fr: "Répare l'autel qui s'est écroulé", es: 'Repara el altar que se ha derrumbado', pt: 'Repare o altar que foi derrubado', de: 'Baue den zerfallenen Altar wieder auf', ru: 'Восстанови разрушенный жертвенник', zh: '重修那已倒塌的祭坛', ja: '崩れた祭壇を築き直そう', ko: '무너진 제단을 다시 쌓으라', ar: 'أصلِح المذبح الذي تهدَّم', fa: 'مذبحِ فروریخته را بازسازی کن', hi: 'टूटी हुई वेदी की मरम्मत करें', id: 'Perbaiki mezbah yang telah runtuh', sw: 'Karabati madhabahu iliyobomoka', tl: 'Ayusin ang dambanang naguho', am: 'የፈረሰውን መሠዊያ ጠግን' }, ref: '1 Kings 18:30' },
      { theme: { en: 'Thirst for God like the deer for water', fr: "Aie soif de Dieu comme le cerf de l'eau", es: 'Ten sed de Dios como el ciervo del agua', pt: 'Tenha sede de Deus como o cervo da água', de: 'Dürste nach Gott wie der Hirsch nach Wasser', ru: 'Жаждай Бога, как олень воды', zh: '渴慕神，如鹿切慕溪水', ja: '鹿が谷川を慕うように神様を慕い求めよう', ko: '사슴이 물을 찾듯 하나님을 갈망하라', ar: 'اعطش إلى الله كما يعطش الأيل إلى الماء', fa: 'مانند آهو که تشنهٔ آب است، تشنهٔ خدا باش', hi: 'जैसे हिरणी जल के लिए, वैसे परमेश्वर के लिए प्यासे हों', id: 'Hauslah akan Allah seperti rusa akan air', sw: 'Mwonee Mungu kiu kama ayala aionavyo maji', tl: 'Mauhaw sa Diyos gaya ng usa sa tubig', am: 'ዋላ ውሃ እንደሚናፍቅ እግዚአብሔርን ተጠማ' }, ref: 'Psalm 42:1-2' },
      { theme: { en: 'Feast on His Word — eat and be filled', fr: 'Nourris-toi de Sa Parole — mange et sois rassasié', es: 'Deléitate en Su Palabra — come y sáciate', pt: 'Banqueteie-se na Sua Palavra — coma e sacie-se', de: 'Nähre dich an Seinem Wort — iss und werde satt', ru: 'Насыщайся Его Словом — вкуси и насыться', zh: '以祂的话为食——吃了就饱足', ja: 'み言葉をごちそうにしよう——食べて満たされよう', ko: '그분의 말씀을 양식으로 삼아 먹고 배부르라', ar: 'تلذَّذ بكلمته — كُل واشبع', fa: 'از کلام او سیر شو — بخور و سیر شو', hi: 'उसके वचन का भोजन करें — खाएं और तृप्त हों', id: 'Nikmatilah Firman-Nya — makan dan menjadi kenyang', sw: 'Jifurahishe kwa Neno lake — kula ushibe', tl: 'Magpakabusog sa Kanyang Salita — kumain at mabusog', am: 'በቃሉ ተመገብ — ብላና ጥገብ' }, ref: 'Jeremiah 15:16' },
      { theme: { en: 'Draw near, and He will draw near to you', fr: "Approche-toi, et Il s'approchera de toi", es: 'Acércate, y Él se acercará a ti', pt: 'Aproxime-se, e Ele se aproximará de você', de: 'Nahe dich Ihm, und Er wird sich dir nahen', ru: 'Приблизься, и Он приблизится к тебе', zh: '你亲近神，神就亲近你', ja: '神様に近づこう、そうすれば神様も近づいてくださる', ko: '하나님께 가까이 가라, 그리하면 그분이 가까이 오시리라', ar: 'اقترِب إليه، فيقترب إليك', fa: 'به او نزدیک شو، و او به تو نزدیک خواهد شد', hi: 'परमेश्वर के निकट आएं, और वह आपके निकट आएगा', id: 'Mendekatlah kepada-Nya, maka Ia akan mendekat kepadamu', sw: 'Mkaribie Mungu, naye atakukaribia', tl: "Lumapit sa Kanya, at Siya'y lalapit sa iyo", am: 'ወደ እግዚአብሔር ቅረብ፣ እርሱም ወደ አንተ ይቀርባል' }, ref: 'James 4:8' },
      { theme: { en: 'Be still and gaze on His beauty', fr: 'Fais silence et contemple Sa beauté', es: 'Aquiétate y contempla Su hermosura', pt: 'Aquiete-se e contemple a Sua beleza', de: 'Werde still und schau auf Seine Schönheit', ru: 'Умолкни и созерцай Его красоту', zh: '安静下来，仰望祂的荣美', ja: '静まって、神様の麗しさを仰ぎ見よう', ko: '잠잠히 그분의 아름다움을 바라보라', ar: 'اسكُن وتأمّل جماله', fa: 'آرام باش و جمال او را بنگر', hi: 'शांत होकर उसकी सुंदरता पर दृष्टि लगाएं', id: 'Berdiam dirilah dan pandanglah keindahan-Nya', sw: 'Tulia na uutazame uzuri wake', tl: 'Manahimik at pagmasdan ang Kanyang kagandahan', am: 'ጸጥ ብለህ ውበቱን ተመልከት' }, ref: 'Psalm 27:4' },
      { theme: { en: 'Keep the fire on the altar burning', fr: "Entretiens le feu sur l'autel", es: 'Mantén encendido el fuego del altar', pt: 'Mantenha aceso o fogo do altar', de: 'Halte das Feuer auf dem Altar am Brennen', ru: 'Пусть огонь на жертвеннике горит непрестанно', zh: '让坛上的火常常烧着', ja: '祭壇の火を絶やさず燃やし続けよう', ko: '제단의 불을 꺼지지 않게 지키라', ar: 'أبقِ النار متّقدة على المذبح', fa: 'آتش را بر مذبح فروزان نگاه دار', hi: 'वेदी की आग को जलती हुई बनाए रखें', id: 'Jagalah api di atas mezbah tetap menyala', sw: 'Uidumishe moto uwakao juu ya madhabahu', tl: 'Panatilihing nagniningas ang apoy sa dambana', am: 'በመሠዊያው ላይ ያለው እሳት ሳይጠፋ ይንደድ' }, ref: 'Leviticus 6:13' },
    ],
  },
  {
    id: 'gratitude7',
    category: 'seeking',
    emoji: '🌅',
    count: 7,
    titleKey: 'planWeek7Title',
    subKey: 'planWeek7Sub',
    intro: {
      en: 'Seven days to retrain your heart toward thankfulness. Each day takes one reason to give thanks — for who God is, for salvation, for the people around you, for His provision, even in the trial — until gratitude becomes your first response instead of your last.',
      fr: "Sept jours pour rééduquer ton cœur à la reconnaissance. Chaque jour prend une raison de rendre grâce — pour qui est Dieu, pour le salut, pour ceux qui t'entourent, pour Sa provision, même dans l'épreuve — jusqu'à ce que la gratitude devienne ta première réaction plutôt que la dernière.",
    },
    biblical: {
      ref: 'Luke 17:11-19',
      text: {
        en: "Jesus healed ten lepers, but only one — a Samaritan — turned back, praising God with a loud voice, and fell at His feet to thank Him. 'Were not ten cleansed? Where are the nine?' (Luke 17:17). Thanksgiving runs all through Scripture, from David inviting us to 'enter His gates with thanksgiving' (Psalm 100:4) to Paul's charge to 'give thanks in all circumstances' (1 Thessalonians 5:18). This week is a call to be the one who comes back.",
        fr: "Jésus guérit dix lépreux, mais un seul — un Samaritain — revint, glorifiant Dieu à haute voix, et se jeta à Ses pieds pour Le remercier. « Les dix n'ont-ils pas été guéris ? Où sont les neuf autres ? » (Luc 17:17). L'action de grâce traverse toute l'Écriture, de David qui nous invite à « entrer dans Ses portes avec des louanges » (Psaume 100:4) jusqu'à l'appel de Paul à « rendre grâces en toutes choses » (1 Thessaloniciens 5:18). Cette semaine est un appel à être celui qui revient.",
      },
    },
    days: [
      { theme: { en: 'Thank God for who He is', fr: 'Remercie Dieu pour qui Il est', es: 'Agradece a Dios por quién es Él', pt: 'Agradeça a Deus por quem Ele é', de: 'Danke Gott für das, was Er ist', ru: 'Благодари Бога за то, каков Он', zh: '为神的本相感谢祂', ja: '神様がどのような方かを感謝しよう', ko: '하나님이 어떤 분이신지 감사하라', ar: 'اشكر الله على ما هو عليه', fa: 'خدا را برای آنچه هست شکر کن', hi: 'परमेश्वर जैसा है, उसके लिए धन्यवाद दें', id: 'Bersyukurlah kepada Allah atas siapa Dia', sw: 'Mshukuru Mungu kwa vile alivyo', tl: 'Pasalamatan ang Diyos sa kung sino Siya', am: 'እግዚአብሔርን ስለ ማንነቱ አመስግኑ' }, ref: 'Psalm 100:4-5' },
      { theme: { en: 'Thank Him for salvation', fr: 'Remercie-Le pour le salut', es: 'Agradécele por la salvación', pt: 'Agradeça-Lhe pela salvação', de: 'Danke Ihm für die Erlösung', ru: 'Благодари Его за спасение', zh: '为救恩感谢祂', ja: '救いを感謝しよう', ko: '구원을 주심에 감사하라', ar: 'اشكره على الخلاص', fa: 'او را برای نجات شکر کن', hi: 'उद्धार के लिए उसका धन्यवाद करें', id: 'Bersyukurlah kepada-Nya atas keselamatan', sw: 'Mshukuru kwa wokovu', tl: 'Pasalamatan Siya sa kaligtasan', am: 'ስለ መዳን አመስግኑት' }, ref: 'Ephesians 2:8-9' },
      { theme: { en: 'Thank Him for your family and friends', fr: 'Remercie-Le pour ta famille et tes amis', es: 'Agradécele por tu familia y amigos', pt: 'Agradeça-Lhe pela sua família e amigos', de: 'Danke Ihm für deine Familie und Freunde', ru: 'Благодари Его за твою семью и друзей', zh: '为你的家人和朋友感谢祂', ja: 'あなたの家族と友を感謝しよう', ko: '가족과 친구들로 인해 감사하라', ar: 'اشكره على عائلتك وأصدقائك', fa: 'او را برای خانواده و دوستانت شکر کن', hi: 'अपने परिवार और मित्रों के लिए उसका धन्यवाद करें', id: 'Bersyukurlah kepada-Nya atas keluarga dan sahabatmu', sw: 'Mshukuru kwa familia na marafiki zako', tl: 'Pasalamatan Siya sa iyong pamilya at mga kaibigan', am: 'ስለ ቤተሰብህና ጓደኞችህ አመስግኑት' }, ref: 'Philippians 1:3' },
      { theme: { en: 'Thank Him for provision', fr: 'Remercie-Le pour Sa provision', es: 'Agradécele por Su provisión', pt: 'Agradeça-Lhe pela Sua provisão', de: 'Danke Ihm für Seine Versorgung', ru: 'Благодари Его за Его обеспечение', zh: '为祂的供应感谢祂', ja: '神様の備えを感謝しよう', ko: '그분의 공급하심에 감사하라', ar: 'اشكره على إعالته', fa: 'او را برای تدارکش شکر کن', hi: 'उसके भरण-पोषण के लिए उसका धन्यवाद करें', id: 'Bersyukurlah kepada-Nya atas pemeliharaan-Nya', sw: 'Mshukuru kwa maandalizi yake', tl: 'Pasalamatan Siya sa Kanyang panustos', am: 'ስለ አቅርቦቱ አመስግኑት' }, ref: 'Philippians 4:19' },
      { theme: { en: 'Thank Him in the trial', fr: 'Remercie-Le dans l\'épreuve', es: 'Agradécele en la prueba', pt: 'Agradeça-Lhe na provação', de: 'Danke Ihm in der Prüfung', ru: 'Благодари Его в испытании', zh: '在试炼中感谢祂', ja: '試練の中で感謝しよう', ko: '시련 가운데 감사하라', ar: 'اشكره في التجربة', fa: 'او را در آزمایش شکر کن', hi: 'परीक्षा में उसका धन्यवाद करें', id: 'Bersyukurlah kepada-Nya dalam pencobaan', sw: 'Mshukuru katika jaribu', tl: 'Pasalamatan Siya sa gitna ng pagsubok', am: 'በፈተና ውስጥ አመስግኑት' }, ref: '1 Thessalonians 5:18' },
      { theme: { en: 'Thank Him for answered prayers', fr: 'Remercie-Le pour les prières exaucées', es: 'Agradécele por las oraciones contestadas', pt: 'Agradeça-Lhe pelas orações respondidas', de: 'Danke Ihm für erhörte Gebete', ru: 'Благодари Его за отвеченные молитвы', zh: '为蒙应允的祷告感谢祂', ja: '答えられた祈りを感謝しよう', ko: '응답된 기도로 인해 감사하라', ar: 'اشكره على الصلوات المستجابة', fa: 'او را برای دعاهای مستجاب‌شده شکر کن', hi: 'उत्तर दी गई प्रार्थनाओं के लिए उसका धन्यवाद करें', id: 'Bersyukurlah kepada-Nya atas doa yang terjawab', sw: 'Mshukuru kwa maombi yaliyojibiwa', tl: 'Pasalamatan Siya sa mga panalanging sinagot', am: 'ስለ ተመለሱ ጸሎቶች አመስግኑት' }, ref: 'Psalm 116:1-2' },
      { theme: { en: 'Overflow: tell someone what God did', fr: 'Déborde : raconte à quelqu\'un ce que Dieu a fait', es: 'Desborda: cuéntale a alguien lo que Dios hizo', pt: 'Transborde: conte a alguém o que Deus fez', de: 'Lauf über: erzähle jemandem, was Gott getan hat', ru: 'Пусть переполнит: расскажи кому-нибудь, что сделал Бог', zh: '满溢而出：把神的作为告诉一个人', ja: 'あふれ出そう：神様がなさったことを誰かに伝えよう', ko: '넘치게 하라: 하나님이 하신 일을 누군가에게 전하라', ar: 'فِض: أخبر أحدًا بما فعله الله', fa: 'سرریز شو: به کسی بگو خدا چه کرد', hi: 'उमड़ पड़ें: किसी को बताएं कि परमेश्वर ने क्या किया', id: 'Meluaplah: ceritakan kepada seseorang apa yang Allah lakukan', sw: 'Furika: mwambie mtu jambo Mungu alilofanya', tl: 'Umapaw: sabihin sa isang tao ang ginawa ng Diyos', am: 'ተትረፍርፍ፦ እግዚአብሔር ያደረገውን ለአንድ ሰው ንገር' }, ref: 'Psalm 107:1-2' },
    ],
  },
  {
    id: 'upperRoom10',
    category: 'seeking',
    emoji: '🔥',
    count: 10,
    titleKey: 'planUpperRoomTitle',
    subKey: 'planUpperRoomSub',
    intro: {
      en: "Ten days of united, waiting prayer — the same stretch the first disciples spent between Jesus' ascension and Pentecost. You're not striving to earn the Spirit; you're making room, asking the Father, and expecting Him to pour out what He promised.",
      fr: "Dix jours de prière commune et d'attente — le même intervalle que les premiers disciples ont passé entre l'ascension de Jésus et la Pentecôte. Tu ne t'efforces pas de mériter l'Esprit ; tu fais de la place, tu demandes au Père, et tu t'attends à ce qu'Il répande ce qu'Il a promis.",
    },
    biblical: {
      ref: 'Acts 1:12-14',
      text: {
        en: "After Jesus ascended, the disciples returned to an upper room in Jerusalem and 'with one accord were devoting themselves to prayer' (Acts 1:14). For about ten days they waited together for what the Father had promised (Acts 1:4). Then, on the day of Pentecost, the Holy Spirit fell on them and the church was born (Acts 2:1-4). This plan walks those ten days with them — waiting, united, and expectant.",
        fr: "Après l'ascension de Jésus, les disciples regagnèrent une chambre haute à Jérusalem et « persévéraient d'un commun accord dans la prière » (Actes 1:14). Pendant une dizaine de jours, ils attendirent ensemble ce que le Père avait promis (Actes 1:4). Puis, le jour de la Pentecôte, le Saint-Esprit descendit sur eux et l'Église naquit (Actes 2:1-4). Ce plan traverse ces dix jours avec eux — dans l'attente, l'unité et l'espérance.",
      },
    },
    days: [
      { theme: { en: 'Wait for what the Father promised', fr: 'Attends ce que le Père a promis', es: 'Espera lo que el Padre prometió', pt: 'Aguarde o que o Pai prometeu', de: 'Warte auf das, was der Vater verheißen hat', ru: 'Жди того, что обещал Отец', zh: '等候父所应许的', ja: '父が約束されたものを待とう', ko: '아버지께서 약속하신 것을 기다리라', ar: 'انتظر ما وعد به الآب', fa: 'منتظر آنچه پدر وعده داد باش', hi: 'पिता की प्रतिज्ञा की प्रतीक्षा करें', id: 'Nantikanlah apa yang Bapa janjikan', sw: 'Ngoja kile Baba alichoahidi', tl: 'Hintayin ang ipinangako ng Ama', am: 'አብ ቃል የገባውን ጠብቅ' }, ref: 'Acts 1:4' },
      { theme: { en: 'You will receive power', fr: 'Tu recevras la puissance', es: 'Recibirás poder', pt: 'Você receberá poder', de: 'Du wirst Kraft empfangen', ru: 'Ты примешь силу', zh: '你必得着能力', ja: 'あなたは力を受ける', ko: '너는 권능을 받으리라', ar: 'ستنال قوة', fa: 'قوت خواهی یافت', hi: 'तुम सामर्थ्य पाओगे', id: 'Kamu akan menerima kuasa', sw: 'Utapokea nguvu', tl: 'Tatanggap ka ng kapangyarihan', am: 'ኃይል ትቀበላለህ' }, ref: 'Acts 1:8' },
      { theme: { en: 'Gather with one accord', fr: 'Rassemble-toi d\'un même cœur', es: 'Reúnete unánime', pt: 'Reúna-se em unânime acordo', de: 'Versammelt euch einmütig', ru: 'Собирайся в единодушии', zh: '同心合意地聚集', ja: '心を合わせて集まろう', ko: '한마음으로 모이라', ar: 'اجتمعوا بنفس واحدة', fa: 'با یک‌دلی گرد هم آیید', hi: 'एकचित्त होकर इकट्ठे हों', id: 'Berkumpullah dengan sehati', sw: 'Kusanyikeni kwa nia moja', tl: 'Magtipon nang nagkakaisang loob', am: 'በአንድ ልብ ተሰብሰቡ' }, ref: 'Acts 1:14' },
      { theme: { en: 'Devote yourselves to prayer', fr: 'Persévère dans la prière', es: 'Persevera en la oración', pt: 'Perseverem na oração', de: 'Haltet fest am Gebet', ru: 'Постоянно пребывай в молитве', zh: '恒切祷告', ja: '祈りに専念しよう', ko: '기도에 힘쓰라', ar: 'واظبوا على الصلاة', fa: 'در دعا مواظبت کنید', hi: 'प्रार्थना में लगे रहें', id: 'Bertekunlah dalam doa', sw: 'Dumuni katika maombi', tl: 'Manatili sa panalangin', am: 'በጸሎት ጽኑ' }, ref: 'Acts 2:42' },
      { theme: { en: 'Ask the Father for the Spirit', fr: 'Demande l\'Esprit au Père', es: 'Pide al Padre el Espíritu', pt: 'Peça ao Pai o Espírito', de: 'Bitte den Vater um den Geist', ru: 'Проси у Отца Духа', zh: '向父求圣灵', ja: '父に御霊を求めよう', ko: '아버지께 성령을 구하라', ar: 'اطلب الروح من الآب', fa: 'روح را از پدر بخواه', hi: 'पिता से आत्मा मांगें', id: 'Mintalah Roh kepada Bapa', sw: 'Mwombe Baba Roho', tl: 'Hingin sa Ama ang Espiritu', am: 'መንፈስን ከአብ ለምን' }, ref: 'Luke 11:13' },
      { theme: { en: 'Be of one heart and mind', fr: 'Sois d\'un seul cœur et d\'un seul esprit', es: 'Sé de un solo corazón y mente', pt: 'Seja de um só coração e mente', de: 'Sei ein Herz und eine Seele', ru: 'Будь един сердцем и разумом', zh: '同心合意，合而为一', ja: '心と思いを一つにしよう', ko: '한마음 한뜻이 되라', ar: 'كن قلبًا واحدًا وفكرًا واحدًا', fa: 'یک‌دل و یک‌رأی باش', hi: 'एक मन और एक चित्त हों', id: 'Sehati dan sepikirlah', sw: 'Uwe na moyo mmoja na nia moja', tl: 'Magkaisa sa puso at isip', am: 'በአንድ ልብና በአንድ ሐሳብ ሁን' }, ref: 'John 17:21' },
      { theme: { en: 'Repent and make room for Him', fr: 'Repens-toi et fais-Lui de la place', es: 'Arrepiéntete y hazle lugar', pt: 'Arrependa-se e abra espaço para Ele', de: 'Kehr um und mach Ihm Raum', ru: 'Покайся и освободи Ему место', zh: '悔改，为祂腾出空间', ja: '悔い改めて、神様に場所を空けよう', ko: '회개하고 그분께 자리를 내어 드리라', ar: 'توبوا وافسحوا له مكانًا', fa: 'توبه کن و برای او جا باز کن', hi: 'मन फिराएं और उसके लिए स्थान बनाएं', id: 'Bertobatlah dan berilah tempat bagi-Nya', sw: 'Tubu na umpishe nafasi', tl: 'Magsisi at bigyang-daan Siya', am: 'ንስሐ ግባ፤ ለእርሱም ስፍራ አዘጋጅ' }, ref: 'Acts 2:38' },
      { theme: { en: 'Expect the outpouring', fr: 'Attends-toi à l\'effusion', es: 'Espera el derramamiento', pt: 'Espere o derramamento', de: 'Erwarte die Ausgießung', ru: 'Ожидай излияния', zh: '期待圣灵的浇灌', ja: '御霊の注ぎを待ち望もう', ko: '부어 주심을 기대하라', ar: 'ترقّبوا الفيض', fa: 'منتظر ریخته‌شدن روح باش', hi: 'उंडेले जाने की आशा रखें', id: 'Nantikanlah pencurahan-Nya', sw: 'Tarajia kumwagwa kwa Roho', tl: 'Asahan ang pagbubuhos ng Espiritu', am: 'መንፈሱ መፍሰሱን ተጠባበቅ' }, ref: 'Acts 2:17' },
      { theme: { en: 'Keep watch in steadfast prayer', fr: 'Veille dans une prière persévérante', es: 'Vela en oración perseverante', pt: 'Vigie em oração perseverante', de: 'Wache in beharrlichem Gebet', ru: 'Бодрствуй в постоянной молитве', zh: '在恒切的祷告中警醒', ja: '絶えず祈りつつ目を覚まそう', ko: '깨어 기도에 항상 힘쓰라', ar: 'اسهروا في صلاة دائمة', fa: 'در دعای پیوسته بیدار بمان', hi: 'निरंतर प्रार्थना में जागते रहें', id: 'Berjaga-jagalah dalam doa yang tekun', sw: 'Kesha katika maombi ya kudumu', tl: 'Magbantay sa masikap na panalangin', am: 'በጽኑ ጸሎት ንቁ' }, ref: 'Colossians 4:2' },
      { theme: { en: 'Receive power, then go', fr: 'Reçois la puissance, puis va', es: 'Recibe poder, y luego ve', pt: 'Receba poder, e então vá', de: 'Empfange Kraft, dann geh', ru: 'Прими силу и иди', zh: '领受能力，然后出去', ja: '力を受けて、そして出て行こう', ko: '권능을 받고 나아가라', ar: 'انل القوة ثم اذهب', fa: 'قوت را بگیر و برو', hi: 'सामर्थ्य पाएं, फिर जाएं', id: 'Terimalah kuasa, lalu pergilah', sw: 'Pokea nguvu, kisha nenda', tl: 'Tumanggap ng kapangyarihan, at humayo', am: 'ኃይል ተቀበል፤ ከዚያም ሂድ' }, ref: 'Acts 2:1-4' },
    ],
  },
  {
    id: 'breakthrough21',
    category: 'seeking',
    emoji: '⚡',
    count: 21,
    titleKey: 'planTheme21Title',
    subKey: 'planTheme21Sub',
    intro: {
      en: "Three weeks of persistent, daily prayer for one thing you're believing God for. It rests on a truth Daniel discovered: heaven can move from day one even when the answer takes time to arrive — so you keep praying, in faith, refusing to give up before the breakthrough comes.",
      fr: "Trois semaines de prière quotidienne et persévérante pour une chose que tu attends de Dieu. Ce plan repose sur une vérité que Daniel a découverte : le ciel peut se mettre en mouvement dès le premier jour, même si la réponse tarde à venir — alors tu continues de prier, dans la foi, sans lâcher avant la percée.",
    },
    biblical: {
      ref: 'Daniel 10:12-13',
      text: {
        en: "Daniel set his heart to understand and humbled himself before God, mourning and praying for three full weeks (Daniel 10:2-3). When the answer finally came, the angel explained: 'From the first day... your words were heard, and I have come because of your words' — but he had been withstood twenty-one days until help arrived (Daniel 10:12-13). The delay was never God's silence. This plan is twenty-one days of not giving up.",
        fr: "Daniel disposa son cœur à comprendre et s'humilia devant Dieu, dans le deuil et la prière pendant trois semaines entières (Daniel 10:2-3). Quand la réponse vint enfin, l'ange expliqua : « Dès le premier jour... tes paroles ont été entendues, et je viens à cause de tes paroles » — mais il avait été retenu vingt et un jours avant que le secours n'arrive (Daniel 10:12-13). Le retard n'a jamais été le silence de Dieu. Ce plan, c'est vingt et un jours pour ne pas lâcher.",
      },
    },
    days: [
      { theme: { en: 'Set your heart to seek God', fr: 'Dispose ton cœur à chercher Dieu', es: 'Dispón tu corazón para buscar a Dios', pt: 'Disponha seu coração para buscar a Deus', de: 'Richte dein Herz darauf aus, Gott zu suchen', ru: 'Расположи сердце искать Бога', zh: '定意寻求神', ja: '心を定めて神様を求めよう', ko: '하나님을 찾기로 마음을 정하라', ar: 'وطِّن قلبك على طلب الله', fa: 'دلت را برای طلبیدن خدا آماده کن', hi: 'परमेश्वर को खोजने के लिए अपना मन लगाएं', id: 'Arahkan hatimu untuk mencari Allah', sw: 'Kaza moyo wako kumtafuta Mungu', tl: 'Ihanda ang iyong puso na hanapin ang Diyos', am: 'እግዚአብሔርን ለመፈለግ ልብህን አዘጋጅ' }, ref: 'Jeremiah 29:12-13' },
      { theme: { en: 'Come boldly to the throne', fr: 'Approche-toi avec assurance du trône', es: 'Acércate con confianza al trono', pt: 'Aproxime-se com confiança do trono', de: 'Tritt freimütig vor den Thron', ru: 'Приступай с дерзновением к престолу', zh: '坦然无惧地来到宝座前', ja: '大胆に御座に近づこう', ko: '담대히 보좌 앞에 나아가라', ar: 'تقدَّم بثقة إلى العرش', fa: 'با دلیری به تخت فیض نزدیک شو', hi: 'साहस के साथ सिंहासन के पास आएं', id: 'Datanglah dengan berani ke takhta', sw: 'Njoo kwa ujasiri kwenye kiti cha enzi', tl: 'Lumapit nang may lakas ng loob sa trono', am: 'በድፍረት ወደ ዙፋኑ ቅረብ' }, ref: 'Hebrews 4:16' },
      { theme: { en: 'Pray the promises, not the problem', fr: 'Prie les promesses, pas le problème', es: 'Ora las promesas, no el problema', pt: 'Ore as promessas, não o problema', de: 'Bete die Verheißungen, nicht das Problem', ru: 'Молись обещаниями, а не проблемой', zh: '祷告神的应许，而非难题', ja: '問題ではなく約束を祈ろう', ko: '문제가 아니라 약속을 기도하라', ar: 'صلِّ الوعود لا المشكلة', fa: 'وعده‌ها را دعا کن، نه مشکل را', hi: 'समस्या नहीं, प्रतिज्ञाओं की प्रार्थना करें', id: 'Doakan janji-janji-Nya, bukan masalahnya', sw: 'Omba ahadi, siyo tatizo', tl: 'Ipanalangin ang mga pangako, hindi ang problema', am: 'ችግሩን ሳይሆን ተስፋዎቹን ጸልይ' }, ref: '2 Corinthians 1:20' },
      { theme: { en: 'Humble yourself before Him', fr: 'Humilie-toi devant Lui', es: 'Humíllate delante de Él', pt: 'Humilhe-se diante d\'Ele', de: 'Demütige dich vor Ihm', ru: 'Смирись перед Ним', zh: '在祂面前谦卑', ja: '神様の前にへりくだろう', ko: '그분 앞에 자신을 낮추라', ar: 'اتّضع أمامه', fa: 'در حضور او فروتن شو', hi: 'उसके सामने खुद को नम्र करें', id: 'Rendahkan dirimu di hadapan-Nya', sw: 'Jinyenyekeze mbele zake', tl: 'Magpakumbaba sa harap Niya', am: 'በፊቱ ራስህን አዋርድ' }, ref: '2 Chronicles 7:14' },
      { theme: { en: 'Forgive as you pray', fr: 'Pardonne en priant', es: 'Perdona mientras oras', pt: 'Perdoe enquanto ora', de: 'Vergib, während du betest', ru: 'Прощай, когда молишься', zh: '祷告时也要饶恕', ja: '祈りながら赦そう', ko: '기도하며 용서하라', ar: 'اغفر وأنت تصلي', fa: 'در حین دعا ببخش', hi: 'प्रार्थना करते समय क्षमा करें', id: 'Ampunilah saat kamu berdoa', sw: 'Samehe unapoomba', tl: 'Magpatawad habang nananalangin', am: 'ስትጸልይ ይቅር በል' }, ref: 'Mark 11:25' },
      { theme: { en: 'Fast something; hunger for Him', fr: 'Jeûne de quelque chose ; aie faim de Lui', es: 'Ayuna de algo; ten hambre de Él', pt: 'Jejue de algo; tenha fome d\'Ele', de: 'Faste von etwas; hungere nach Ihm', ru: 'Постись от чего-то; жаждай Его', zh: '禁戒一样东西，渴慕祂', ja: '何かを断ち、神様を慕い求めよう', ko: '무언가를 금식하며 그분을 갈망하라', ar: 'صُم عن شيء؛ واجُع إليه', fa: 'از چیزی روزه بگیر؛ گرسنهٔ او باش', hi: 'किसी चीज़ का उपवास करें; उसके लिए भूखे रहें', id: 'Berpuasalah dari sesuatu; laparlah akan Dia', sw: 'Funga kitu fulani; mtamani Yeye', tl: 'Mag-ayuno sa isang bagay; magutom para sa Kanya', am: 'ከአንድ ነገር ጹም፤ ለእርሱ ራብ' }, ref: 'Matthew 6:17-18' },
      { theme: { en: 'Pray with the Word open', fr: 'Prie la Bible ouverte', es: 'Ora con la Palabra abierta', pt: 'Ore com a Palavra aberta', de: 'Bete mit aufgeschlagenem Wort', ru: 'Молись с открытым Словом', zh: '打开圣经祷告', ja: 'みことばを開いて祈ろう', ko: '말씀을 펴 놓고 기도하라', ar: 'صلِّ والكلمة مفتوحة', fa: 'با کلام باز دعا کن', hi: 'वचन खोलकर प्रार्थना करें', id: 'Berdoalah dengan Firman terbuka', sw: 'Omba huku Neno likiwa wazi', tl: 'Manalangin nang bukas ang Salita', am: 'ቃሉን ከፍተህ ጸልይ' }, ref: 'John 15:7' },
      { theme: { en: 'Resist discouragement', fr: 'Résiste au découragement', es: 'Resiste el desánimo', pt: 'Resista ao desânimo', de: 'Widerstehe der Entmutigung', ru: 'Противостой унынию', zh: '抵挡灰心', ja: '落胆に抵抗しよう', ko: '낙심을 물리치라', ar: 'قاوِم اليأس', fa: 'در برابر دلسردی بایست', hi: 'निराशा का सामना करें', id: 'Lawanlah keputusasaan', sw: 'Pinga kukata tamaa', tl: 'Labanan ang pagkapanghina ng loob', am: 'ተስፋ መቁረጥን ተቃወም' }, ref: 'Galatians 6:9' },
      { theme: { en: 'Like Daniel: keep your rhythm', fr: 'Comme Daniel : garde ton rythme', es: 'Como Daniel: mantén tu ritmo', pt: 'Como Daniel: mantenha o seu ritmo', de: 'Wie Daniel: bewahre deinen Rhythmus', ru: 'Как Даниил: держи свой ритм', zh: '像但以理：保持你的规律', ja: 'ダニエルのように、リズムを保とう', ko: '다니엘처럼 네 리듬을 지키라', ar: 'مثل دانيال: حافظ على إيقاعك', fa: 'مانند دانیال: نظم خود را حفظ کن', hi: 'दानिय्येल की तरह: अपनी नियमितता बनाए रखें', id: 'Seperti Daniel: jagalah iramamu', sw: 'Kama Danieli: dumisha mpangilio wako', tl: 'Tulad ni Daniel: panatilihin ang iyong ritmo', am: 'እንደ ዳንኤል፦ ልማድህን ጠብቅ' }, ref: 'Daniel 6:10' },
      { theme: { en: 'Praise before the answer', fr: 'Loue avant la réponse', es: 'Alaba antes de la respuesta', pt: 'Louve antes da resposta', de: 'Lobe vor der Antwort', ru: 'Хвали до ответа', zh: '在答案之前先赞美', ja: '答えの前に賛美しよう', ko: '응답 전에 찬양하라', ar: 'سبِّح قبل الإجابة', fa: 'پیش از پاسخ، ستایش کن', hi: 'उत्तर मिलने से पहले स्तुति करें', id: 'Pujilah sebelum jawaban datang', sw: 'Sifu kabla ya jibu', tl: 'Magpuri bago ang sagot', am: 'ከመልሱ በፊት አመስግን' }, ref: 'Acts 16:25-26' },
      { theme: { en: 'Ask largely — He is able', fr: 'Demande largement — Il est puissant', es: 'Pide en grande — Él es poderoso', pt: 'Peça grandemente — Ele é poderoso', de: 'Bitte groß — Er ist mächtig', ru: 'Проси щедро — Он силён', zh: '放胆大求——祂能成就', ja: '大きく求めよう——神様にはできる', ko: '크게 구하라 — 그분은 능하시다', ar: 'اطلب بسخاء — فهو قادر', fa: 'بزرگ بخواه — او تواناست', hi: 'बड़ा मांगें — वह सामर्थी है', id: 'Mintalah dengan besar — Dia sanggup', sw: 'Omba kwa wingi — Yeye anaweza', tl: 'Humingi nang malaki — kaya Niya', am: 'በስፋት ለምን — እርሱ ይችላል' }, ref: 'Ephesians 3:20' },
      { theme: { en: 'Pray for those in the same battle', fr: 'Prie pour ceux qui vivent le même combat', es: 'Ora por quienes libran la misma batalla', pt: 'Ore por quem enfrenta a mesma batalha', de: 'Bete für die, die denselben Kampf kämpfen', ru: 'Молись о тех, кто в той же битве', zh: '为身处相同争战的人祷告', ja: '同じ戦いにある人のために祈ろう', ko: '같은 싸움을 하는 이들을 위해 기도하라', ar: 'صلِّ لأجل من يخوضون المعركة نفسها', fa: 'برای کسانی که در همان نبردند دعا کن', hi: 'उसी संघर्ष में जूझ रहे लोगों के लिए प्रार्थना करें', id: 'Doakan mereka yang berjuang dalam pergumulan yang sama', sw: 'Waombee walio katika vita vilevile', tl: 'Ipanalangin ang mga nasa parehong laban', am: 'በዚያው ውጊያ ውስጥ ላሉት ጸልይ' }, ref: 'Job 42:10' },
      { theme: { en: 'Watch and pray', fr: 'Veille et prie', es: 'Vela y ora', pt: 'Vigie e ore', de: 'Wache und bete', ru: 'Бодрствуй и молись', zh: '警醒祷告', ja: '目を覚まして祈ろう', ko: '깨어 기도하라', ar: 'اسهر وصلِّ', fa: 'بیدار باش و دعا کن', hi: 'जागते रहें और प्रार्थना करें', id: 'Berjaga-jagalah dan berdoalah', sw: 'Kesha na uombe', tl: 'Magbantay at manalangin', am: 'ንቁ ሆነህ ጸልይ' }, ref: 'Matthew 26:41' },
      { theme: { en: 'Wrestle like Jacob: do not let go', fr: 'Lutte comme Jacob : ne Le lâche pas', es: 'Lucha como Jacob: no lo sueltes', pt: 'Lute como Jacó: não O solte', de: 'Ringe wie Jakob: lass Ihn nicht los', ru: 'Борись, как Иаков: не отпускай Его', zh: '像雅各一样摔跤：不要放手', ja: 'ヤコブのように格闘しよう——神様を離すな', ko: '야곱처럼 씨름하라: 놓지 말라', ar: 'صارِع مثل يعقوب: لا تتركه', fa: 'مانند یعقوب کشتی بگیر: او را رها نکن', hi: 'याकूब की तरह मल्लयुद्ध करें: उसे न छोड़ें', id: 'Bergumullah seperti Yakub: jangan lepaskan Dia', sw: 'Shindana kama Yakobo: usimwache', tl: 'Makipagbuno tulad ni Jacob: huwag bibitaw', am: 'እንደ ያዕቆብ ታገል፦ አትልቀቀው' }, ref: 'Genesis 32:26' },
      { theme: { en: 'Speak to the mountain', fr: 'Parle à la montagne', es: 'Habla a la montaña', pt: 'Fale à montanha', de: 'Sprich zu dem Berg', ru: 'Скажи горе', zh: '向这座山说话', ja: '山に向かって語ろう', ko: '산을 향해 말하라', ar: 'خاطِب الجبل', fa: 'با کوه سخن بگو', hi: 'पहाड़ से कहें', id: 'Berkatalah kepada gunung itu', sw: 'Uambie mlima', tl: 'Magsalita sa bundok', am: 'ተራራውን ተናገር' }, ref: 'Mark 11:23' },
      { theme: { en: 'Stand on His faithfulness', fr: 'Tiens ferme sur Sa fidélité', es: 'Afírmate en Su fidelidad', pt: 'Firme-se na Sua fidelidade', de: 'Steh fest auf Seiner Treue', ru: 'Стой на Его верности', zh: '站立在祂的信实上', ja: '神様の真実に立とう', ko: '그분의 신실하심 위에 서라', ar: 'اثبت على أمانته', fa: 'بر وفاداری او بایست', hi: 'उसकी विश्वासयोग्यता पर दृढ़ रहें', id: 'Berdirilah di atas kesetiaan-Nya', sw: 'Simama juu ya uaminifu wake', tl: 'Tumayo sa Kanyang katapatan', am: 'በታማኝነቱ ላይ ቁም' }, ref: 'Numbers 23:19' },
      { theme: { en: 'Pray in the Spirit', fr: 'Prie par l\'Esprit', es: 'Ora en el Espíritu', pt: 'Ore no Espírito', de: 'Bete im Geist', ru: 'Молись в Духе', zh: '在圣灵里祷告', ja: '御霊によって祈ろう', ko: '성령 안에서 기도하라', ar: 'صلِّ في الروح', fa: 'در روح دعا کن', hi: 'आत्मा में प्रार्थना करें', id: 'Berdoalah dalam Roh', sw: 'Omba katika Roho', tl: 'Manalangin sa Espiritu', am: 'በመንፈስ ጸልይ' }, ref: 'Romans 8:26-27' },
      { theme: { en: 'Cast every care on Him', fr: 'Décharge-toi de tout souci sur Lui', es: 'Echa toda ansiedad sobre Él', pt: 'Lance toda ansiedade sobre Ele', de: 'Wirf alle Sorge auf Ihn', ru: 'Возложи всякую заботу на Него', zh: '将一切忧虑卸给祂', ja: 'すべての思い煩いを神様にゆだねよう', ko: '모든 염려를 그분께 맡기라', ar: 'ألقِ كل همّك عليه', fa: 'هر نگرانی را به او واگذار', hi: 'अपनी सारी चिंता उस पर डाल दें', id: 'Serahkanlah segala kekhawatiran kepada-Nya', sw: 'Mtwike kila wasiwasi wako', tl: 'Ilagak sa Kanya ang lahat ng alalahanin', am: 'ጭንቀትህን ሁሉ በእርሱ ላይ ጣል' }, ref: '1 Peter 5:7' },
      { theme: { en: 'Expect: set a watch for the answer', fr: 'Attends-toi à Lui : guette la réponse', es: 'Espera: ponte en vela por la respuesta', pt: 'Espere: fique de atalaia pela resposta', de: 'Erwarte es: halte Ausschau nach der Antwort', ru: 'Ожидай: встань на страже ответа', zh: '存着期待：守望神的答案', ja: '期待しよう——答えを見張ろう', ko: '기대하라: 응답을 파수하라', ar: 'ترقَّب: قِف تنتظر الجواب', fa: 'منتظر باش: برای پاسخ دیده‌بانی کن', hi: 'आशा रखें: उत्तर के लिए पहरा दें', id: 'Berharaplah: berjaga menanti jawaban', sw: 'Tarajia: kesha ukisubiri jibu', tl: 'Umasa: magbantay para sa sagot', am: 'ተጠባበቅ፦ መልሱን ለመጠበቅ ተጠንቀቅ' }, ref: 'Habakkuk 2:1-3' },
      { theme: { en: 'Thank Him for what is already moving', fr: 'Remercie-Le pour ce qui bouge déjà', es: 'Agradécele por lo que ya se mueve', pt: 'Agradeça-Lhe pelo que já está se movendo', de: 'Danke Ihm für das, was sich schon bewegt', ru: 'Благодари Его за то, что уже движется', zh: '为已经开始动工的事感谢祂', ja: 'すでに動き始めていることを感謝しよう', ko: '이미 움직이고 있는 것으로 인해 감사하라', ar: 'اشكره على ما بدأ يتحرك بالفعل', fa: 'او را برای آنچه از پیش در حرکت است شکر کن', hi: 'जो पहले से हो रहा है, उसके लिए उसका धन्यवाद करें', id: 'Bersyukurlah atas apa yang sudah mulai bergerak', sw: 'Mshukuru kwa kile ambacho tayari kinaendelea', tl: 'Pasalamatan Siya sa kung ano ang gumagalaw na', am: 'አስቀድሞ ለተጀመረው አመስግን' }, ref: 'John 11:41' },
      { theme: { en: 'Seal it: faith over feelings', fr: 'Scelle tout : la foi au-dessus des émotions', es: 'Séllalo: fe por encima de los sentimientos', pt: 'Sele tudo: fé acima dos sentimentos', de: 'Besiegle es: Glaube über Gefühle', ru: 'Запечатай это: вера выше чувств', zh: '封住这一切：信心胜过感觉', ja: '封印しよう——感情より信仰を', ko: '봉인하라: 감정보다 믿음을', ar: 'اختمها: الإيمان فوق المشاعر', fa: 'مهرش کن: ایمان برتر از احساسات', hi: 'इसे मुहरबंद करें: भावनाओं से ऊपर विश्वास', id: 'Meteraikan: iman di atas perasaan', sw: 'Itie muhuri: imani juu ya hisia', tl: 'Tatakan ito: pananampalataya higit sa damdamin', am: 'አትም፦ እምነት ከስሜት በላይ' }, ref: '2 Timothy 4:7' },
    ],
  },
  {
    id: 'others30',
    category: 'others',
    emoji: '🤝',
    count: 30,
    titleKey: 'plan30Title',
    subKey: 'plan30Sub',
    intro: {
      en: 'A month of looking outward — one person or group to lift up each day, from those closest to you to strangers, the hurting, the lost, and your nation. It trains you to carry others to God the way Christ carries us.',
      fr: "Un mois tourné vers les autres — une personne ou un groupe à porter chaque jour, de tes proches aux inconnus, des personnes qui souffrent aux perdus, jusqu'à ta nation. Il t'exerce à porter les autres devant Dieu comme Christ nous porte.",
    },
    biblical: {
      ref: 'Colossians 4:12',
      text: {
        en: "Paul described Epaphras as one 'always struggling on your behalf in his prayers, that you may stand mature and fully assured in all the will of God' (Colossians 4:12). Scripture honours the intercessor: Job's own fortunes turned when he prayed for his friends (Job 42:10), and Samuel called it sin to stop — 'far be it from me that I should sin against the LORD by ceasing to pray for you' (1 Samuel 12:23). This plan is thirty days of that kind of love.",
        fr: "Paul disait d'Épaphras qu'il « combat toujours pour vous dans ses prières, afin que vous demeuriez parfaits et pleinement convaincus de toute la volonté de Dieu » (Colossiens 4:12). L'Écriture honore l'intercesseur : le sort de Job changea lorsqu'il pria pour ses amis (Job 42:10), et Samuel tenait pour un péché de cesser — « loin de moi de pécher contre l'Éternel en cessant de prier pour vous » (1 Samuel 12:23). Ce plan, c'est trente jours de cet amour-là.",
      },
    },
    days: [
      { theme: { en: 'Your spouse or closest person', fr: 'Ton conjoint ou la personne la plus proche', es: 'Tu cónyuge o la persona más cercana', pt: 'Seu cônjuge ou a pessoa mais próxima', de: 'Dein Ehepartner oder der nächste Mensch', ru: 'Твой супруг или самый близкий человек', zh: '你的配偶或最亲近的人', ja: 'あなたの配偶者、または最も近しい人', ko: '당신의 배우자나 가장 가까운 사람', ar: 'زوجك أو أقرب الناس إليك', fa: 'همسرت یا نزدیک‌ترین فرد', hi: 'आपका जीवनसाथी या सबसे करीबी व्यक्ति', id: 'Pasanganmu atau orang terdekat', sw: 'Mwenzi wako au mtu wa karibu zaidi', tl: 'Ang iyong asawa o pinakamalapit na tao', am: 'የትዳር አጋርህ ወይም በጣም ቅርብ የሆነው ሰው' }, ref: 'Philippians 1:9-11' },
      { theme: { en: 'Your children or the next generation', fr: 'Tes enfants ou la génération suivante', es: 'Tus hijos o la próxima generación', pt: 'Seus filhos ou a próxima geração', de: 'Deine Kinder oder die nächste Generation', ru: 'Твои дети или следующее поколение', zh: '你的儿女或下一代', ja: 'あなたの子ども、または次の世代', ko: '당신의 자녀나 다음 세대', ar: 'أولادك أو الجيل القادم', fa: 'فرزندانت یا نسل بعد', hi: 'आपके बच्चे या अगली पीढ़ी', id: 'Anak-anakmu atau generasi berikutnya', sw: 'Watoto wako au kizazi kijacho', tl: 'Ang iyong mga anak o susunod na henerasyon', am: 'ልጆችህ ወይም ቀጣዩ ትውልድ' }, ref: 'Isaiah 54:13' },
      { theme: { en: 'Your parents', fr: 'Tes parents', es: 'Tus padres', pt: 'Seus pais', de: 'Deine Eltern', ru: 'Твои родители', zh: '你的父母', ja: 'あなたの両親', ko: '당신의 부모님', ar: 'والداك', fa: 'والدینت', hi: 'आपके माता-पिता', id: 'Orang tuamu', sw: 'Wazazi wako', tl: 'Ang iyong mga magulang', am: 'ወላጆችህ' }, ref: 'Exodus 20:12' },
      { theme: { en: 'Your siblings', fr: 'Tes frères et sœurs', es: 'Tus hermanos', pt: 'Seus irmãos', de: 'Deine Geschwister', ru: 'Твои братья и сёстры', zh: '你的兄弟姐妹', ja: 'あなたの兄弟姉妹', ko: '당신의 형제자매', ar: 'إخوتك', fa: 'خواهران و برادرانت', hi: 'आपके भाई-बहन', id: 'Saudara-saudaramu', sw: 'Ndugu zako', tl: 'Ang iyong mga kapatid', am: 'ወንድሞችህና እህቶችህ' }, ref: 'Psalm 133:1' },
      { theme: { en: 'A friend in need', fr: 'Un ami dans le besoin', es: 'Un amigo en necesidad', pt: 'Um amigo em necessidade', de: 'Ein Freund in Not', ru: 'Друг в нужде', zh: '有需要的朋友', ja: '困っている友', ko: '어려움에 처한 친구', ar: 'صديق في ضيق', fa: 'دوستی که در نیاز است', hi: 'ज़रूरत में पड़ा एक मित्र', id: 'Seorang teman yang membutuhkan', sw: 'Rafiki aliye na shida', tl: 'Isang kaibigang nangangailangan', am: 'በችግር ውስጥ ያለ ወዳጅ' }, ref: 'Job 42:10' },
      { theme: { en: 'Someone who is sick', fr: 'Une personne malade', es: 'Alguien que está enfermo', pt: 'Alguém que está doente', de: 'Jemand, der krank ist', ru: 'Кто-то, кто болен', zh: '一位患病的人', ja: '病んでいる人', ko: '병든 누군가', ar: 'شخص مريض', fa: 'کسی که بیمار است', hi: 'कोई जो बीमार है', id: 'Seseorang yang sakit', sw: 'Mtu aliye mgonjwa', tl: 'Isang taong may sakit', am: 'የታመመ ሰው' }, ref: 'James 5:14-15' },
      { theme: { en: 'Someone grieving', fr: 'Une personne en deuil', es: 'Alguien que está de duelo', pt: 'Alguém que está de luto', de: 'Jemand, der trauert', ru: 'Кто-то скорбящий', zh: '一位正在哀伤的人', ja: '悲しみの中にある人', ko: '슬픔에 잠긴 누군가', ar: 'شخص يحزن', fa: 'کسی که سوگوار است', hi: 'कोई जो शोक में है', id: 'Seseorang yang berdukacita', sw: 'Mtu aliye na huzuni', tl: 'Isang taong nagdadalamhati', am: 'የሚያዝን ሰው' }, ref: 'Psalm 34:18' },
      { theme: { en: 'Someone far from God', fr: 'Une personne loin de Dieu', es: 'Alguien lejos de Dios', pt: 'Alguém longe de Deus', de: 'Jemand, der fern von Gott ist', ru: 'Кто-то далёкий от Бога', zh: '一位远离神的人', ja: '神様から遠く離れている人', ko: '하나님에게서 멀리 있는 누군가', ar: 'شخص بعيد عن الله', fa: 'کسی که از خدا دور است', hi: 'कोई जो परमेश्वर से दूर है', id: 'Seseorang yang jauh dari Allah', sw: 'Mtu aliye mbali na Mungu', tl: 'Isang taong malayo sa Diyos', am: 'ከእግዚአብሔር የራቀ ሰው' }, ref: '2 Peter 3:9' },
      { theme: { en: 'Your pastor and church leaders', fr: 'Ton pasteur et les responsables d\'église', es: 'Tu pastor y los líderes de la iglesia', pt: 'Seu pastor e os líderes da igreja', de: 'Dein Pastor und die Gemeindeleiter', ru: 'Твой пастор и церковные служители', zh: '你的牧师和教会领袖', ja: 'あなたの牧師と教会の指導者', ko: '당신의 목사님과 교회 지도자들', ar: 'راعيك وقادة الكنيسة', fa: 'شبان و رهبران کلیسایت', hi: 'आपके पास्टर और कलीसिया के अगुवे', id: 'Gembala dan para pemimpin gerejamu', sw: 'Mchungaji wako na viongozi wa kanisa', tl: 'Ang iyong pastor at mga pinuno ng iglesia', am: 'እረኛህና የቤተ ክርስቲያን መሪዎች' }, ref: '1 Thessalonians 5:12-13' },
      { theme: { en: 'Your church family', fr: 'Ta famille d\'église', es: 'Tu familia de la iglesia', pt: 'Sua família da igreja', de: 'Deine Gemeindefamilie', ru: 'Твоя церковная семья', zh: '你的教会大家庭', ja: 'あなたの教会家族', ko: '당신의 교회 가족', ar: 'عائلتك الكنسية', fa: 'خانوادهٔ کلیسایت', hi: 'आपका कलीसिया परिवार', id: 'Keluarga gerejamu', sw: 'Familia yako ya kanisa', tl: 'Ang iyong pamilya sa iglesia', am: 'የቤተ ክርስቲያን ቤተሰብህ' }, ref: 'John 17:20-21' },
      { theme: { en: 'A neighbour', fr: 'Un voisin', es: 'Un vecino', pt: 'Um vizinho', de: 'Ein Nachbar', ru: 'Сосед', zh: '一位邻舍', ja: '隣人', ko: '이웃 한 사람', ar: 'جار', fa: 'یک همسایه', hi: 'एक पड़ोसी', id: 'Seorang tetangga', sw: 'Jirani', tl: 'Isang kapitbahay', am: 'ጎረቤት' }, ref: 'Luke 10:27' },
      { theme: { en: 'Your colleagues or classmates', fr: 'Tes collègues ou camarades', es: 'Tus colegas o compañeros de clase', pt: 'Seus colegas de trabalho ou de classe', de: 'Deine Kollegen oder Mitschüler', ru: 'Твои коллеги или одноклассники', zh: '你的同事或同学', ja: 'あなたの同僚や同級生', ko: '당신의 동료나 급우들', ar: 'زملاؤك في العمل أو الدراسة', fa: 'همکاران یا هم‌کلاسی‌هایت', hi: 'आपके सहकर्मी या सहपाठी', id: 'Rekan kerja atau teman sekelasmu', sw: 'Wenzako kazini au shuleni', tl: 'Ang iyong mga katrabaho o kaklase', am: 'የስራ ባልደረቦችህ ወይም የክፍል ጓደኞችህ' }, ref: 'Matthew 5:16' },
      { theme: { en: 'Someone who hurt you', fr: 'Une personne qui t\'a blessé', es: 'Alguien que te hirió', pt: 'Alguém que o feriu', de: 'Jemand, der dich verletzt hat', ru: 'Тот, кто причинил тебе боль', zh: '一位曾伤害你的人', ja: 'あなたを傷つけた人', ko: '당신에게 상처 준 누군가', ar: 'شخص جرحك', fa: 'کسی که به تو آسیب زده', hi: 'कोई जिसने आपको चोट पहुंचाई', id: 'Seseorang yang menyakitimu', sw: 'Mtu aliyekuumiza', tl: 'Isang taong nanakit sa iyo', am: 'ያሳመመህ ሰው' }, ref: 'Matthew 5:44' },
      { theme: { en: 'The poor and the hungry', fr: 'Les pauvres et ceux qui ont faim', es: 'Los pobres y los hambrientos', pt: 'Os pobres e os famintos', de: 'Die Armen und die Hungernden', ru: 'Бедные и голодные', zh: '贫穷人和饥饿的人', ja: '貧しい人と飢えている人', ko: '가난한 자들과 굶주린 자들', ar: 'الفقراء والجياع', fa: 'فقیران و گرسنگان', hi: 'गरीब और भूखे लोग', id: 'Orang miskin dan yang lapar', sw: 'Maskini na wenye njaa', tl: 'Ang mga mahihirap at nagugutom', am: 'ድሆችና የተራቡ' }, ref: 'Proverbs 19:17' },
      { theme: { en: 'Refugees and displaced people', fr: 'Les réfugiés et les déplacés', es: 'Los refugiados y desplazados', pt: 'Os refugiados e deslocados', de: 'Flüchtlinge und Vertriebene', ru: 'Беженцы и переселенцы', zh: '难民和流离失所的人', ja: '難民と避難を強いられた人々', ko: '난민과 실향민들', ar: 'اللاجئون والنازحون', fa: 'پناهندگان و آوارگان', hi: 'शरणार्थी और विस्थापित लोग', id: 'Para pengungsi dan orang terlantar', sw: 'Wakimbizi na waliohamishwa makazi', tl: 'Ang mga refugee at napalayas na tao', am: 'ስደተኞችና ተፈናቃዮች' }, ref: 'Deuteronomy 10:18-19' },
      { theme: { en: 'Orphans and widows', fr: 'Les orphelins et les veuves', es: 'Los huérfanos y las viudas', pt: 'Os órfãos e as viúvas', de: 'Waisen und Witwen', ru: 'Сироты и вдовы', zh: '孤儿和寡妇', ja: '孤児とやもめ', ko: '고아와 과부들', ar: 'الأيتام والأرامل', fa: 'یتیمان و بیوه‌زنان', hi: 'अनाथ और विधवाएं', id: 'Anak yatim dan para janda', sw: 'Yatima na wajane', tl: 'Ang mga ulila at balo', am: 'ወላጅ አልባዎችና መበለቶች' }, ref: 'James 1:27' },
      { theme: { en: 'The persecuted church', fr: 'L\'Église persécutée', es: 'La iglesia perseguida', pt: 'A igreja perseguida', de: 'Die verfolgte Gemeinde', ru: 'Гонимая церковь', zh: '受逼迫的教会', ja: '迫害されている教会', ko: '핍박받는 교회', ar: 'الكنيسة المضطهَدة', fa: 'کلیسای جفادیده', hi: 'सताई गई कलीसिया', id: 'Gereja yang teraniaya', sw: 'Kanisa linaloteswa', tl: 'Ang iglesiang inuusig', am: 'የተሰደደችው ቤተ ክርስቲያን' }, ref: 'Hebrews 13:3' },
      { theme: { en: 'Missionaries and evangelists', fr: 'Les missionnaires et évangélistes', es: 'Los misioneros y evangelistas', pt: 'Os missionários e evangelistas', de: 'Missionare und Evangelisten', ru: 'Миссионеры и благовестники', zh: '宣教士和传福音的人', ja: '宣教師と伝道者', ko: '선교사들과 전도자들', ar: 'المرسلون والمبشرون', fa: 'مبشران و بشارت‌دهندگان', hi: 'मिशनरी और सुसमाचार प्रचारक', id: 'Para misionaris dan penginjil', sw: 'Wamisionari na wainjilisti', tl: 'Ang mga misyonero at ebanghelista', am: 'ሚስዮናውያንና ወንጌላውያን' }, ref: 'Matthew 9:37-38' },
      { theme: { en: 'Your city', fr: 'Ta ville', es: 'Tu ciudad', pt: 'Sua cidade', de: 'Deine Stadt', ru: 'Твой город', zh: '你的城市', ja: 'あなたの町', ko: '당신의 도시', ar: 'مدينتك', fa: 'شهرت', hi: 'आपका शहर', id: 'Kotamu', sw: 'Jiji lako', tl: 'Ang iyong lungsod', am: 'ከተማህ' }, ref: 'Jeremiah 29:7' },
      { theme: { en: 'Your nation and its leaders', fr: 'Ta nation et ses dirigeants', es: 'Tu nación y sus líderes', pt: 'Sua nação e seus líderes', de: 'Deine Nation und ihre Führung', ru: 'Твой народ и его руководители', zh: '你的国家和领袖', ja: 'あなたの国とその指導者', ko: '당신의 나라와 지도자들', ar: 'أمّتك وقادتها', fa: 'ملت تو و رهبرانش', hi: 'आपका राष्ट्र और उसके नेता', id: 'Bangsamu dan para pemimpinnya', sw: 'Taifa lako na viongozi wake', tl: 'Ang iyong bansa at mga pinuno nito', am: 'ሀገርህና መሪዎቿ' }, ref: '1 Timothy 2:1-2' },
      { theme: { en: 'Teachers and schools', fr: 'Les enseignants et les écoles', es: 'Los maestros y las escuelas', pt: 'Os professores e as escolas', de: 'Lehrer und Schulen', ru: 'Учителя и школы', zh: '教师和学校', ja: '教師と学校', ko: '교사들과 학교들', ar: 'المعلمون والمدارس', fa: 'معلمان و مدارس', hi: 'शिक्षक और स्कूल', id: 'Para guru dan sekolah', sw: 'Walimu na shule', tl: 'Ang mga guro at paaralan', am: 'መምህራንና ትምህርት ቤቶች' }, ref: 'Proverbs 22:6' },
      { theme: { en: 'Doctors and caregivers', fr: 'Les médecins et soignants', es: 'Los médicos y cuidadores', pt: 'Os médicos e cuidadores', de: 'Ärzte und Pflegende', ru: 'Врачи и те, кто ухаживает за больными', zh: '医生和照护者', ja: '医師と介護者', ko: '의사들과 돌보는 이들', ar: 'الأطباء ومقدّمو الرعاية', fa: 'پزشکان و پرستاران', hi: 'डॉक्टर और देखभाल करने वाले', id: 'Para dokter dan perawat', sw: 'Madaktari na watunzaji', tl: 'Ang mga doktor at tagapag-alaga', am: 'ዶክተሮችና ተንከባካቢዎች' }, ref: 'Colossians 3:23' },
      { theme: { en: 'The lonely and the elderly', fr: 'Les personnes seules et âgées', es: 'Los solitarios y los ancianos', pt: 'Os solitários e os idosos', de: 'Die Einsamen und die Alten', ru: 'Одинокие и пожилые', zh: '孤单的人和年长的人', ja: '孤独な人と高齢の人', ko: '외로운 이들과 노인들', ar: 'الوحيدون وكبار السن', fa: 'تنهایان و سالمندان', hi: 'अकेले और बुज़ुर्ग लोग', id: 'Orang yang kesepian dan lanjut usia', sw: 'Wapweke na wazee', tl: 'Ang mga nag-iisa at matatanda', am: 'ብቸኞችና አረጋውያን' }, ref: 'Psalm 68:5-6' },
      { theme: { en: 'Prodigals — those who walked away', fr: 'Les prodigues — ceux qui se sont éloignés', es: 'Los pródigos: los que se alejaron', pt: 'Os pródigos — os que se afastaram', de: 'Die verlorenen Söhne — die sich abgewandt haben', ru: 'Блудные — те, кто отошёл', zh: '浪子——那些离开的人', ja: '放蕩の者——離れ去った人々', ko: '탕자들 — 떠나간 이들', ar: 'الضالّون — الذين ابتعدوا', fa: 'گمشدگان — کسانی که دور شده‌اند', hi: 'उड़ाऊ लोग — जो दूर चले गए', id: 'Mereka yang hilang — yang telah menjauh', sw: 'Wapotevu — wale walioondoka', tl: 'Ang mga alibughang anak — silang lumayo', am: 'አባካኞች — የራቁት' }, ref: 'Luke 15:20' },
      { theme: { en: 'Marriages under strain', fr: 'Les couples en difficulté', es: 'Los matrimonios en dificultad', pt: 'Os casamentos em dificuldade', de: 'Ehen unter Belastung', ru: 'Браки в трудностях', zh: '陷入困境的婚姻', ja: '緊張の中にある夫婦', ko: '어려움 가운데 있는 부부들', ar: 'الزيجات المتعثّرة', fa: 'ازدواج‌های زیر فشار', hi: 'तनाव में पड़े वैवाहिक जीवन', id: 'Pernikahan yang sedang goyah', sw: 'Ndoa zilizo katika shida', tl: 'Ang mga pagsasamang nasa gitna ng pagsubok', am: 'በችግር ውስጥ ያሉ ትዳሮች' }, ref: 'Ecclesiastes 4:12' },
      { theme: { en: 'The unemployed and discouraged', fr: 'Les sans-emploi et découragés', es: 'Los desempleados y desanimados', pt: 'Os desempregados e desanimados', de: 'Die Arbeitslosen und Entmutigten', ru: 'Безработные и унывающие', zh: '失业和灰心的人', ja: '職を失い落胆している人', ko: '실직하고 낙심한 이들', ar: 'العاطلون والمحبَطون', fa: 'بیکاران و دلسردشدگان', hi: 'बेरोज़गार और निराश लोग', id: 'Para penganggur dan yang putus asa', sw: 'Wasio na ajira na waliokata tamaa', tl: 'Ang mga walang trabaho at nanghihina ng loob', am: 'ስራ አጦችና ተስፋ የቆረጡ' }, ref: 'Isaiah 41:10' },
      { theme: { en: 'Those battling addiction', fr: 'Ceux qui luttent contre une dépendance', es: 'Los que luchan contra una adicción', pt: 'Os que lutam contra o vício', de: 'Die gegen Sucht kämpfen', ru: 'Те, кто борется с зависимостью', zh: '与瘾癖争战的人', ja: '依存症と闘っている人', ko: '중독과 싸우는 이들', ar: 'المكافحون للإدمان', fa: 'کسانی که با اعتیاد مبارزه می‌کنند', hi: 'व्यसन से जूझ रहे लोग', id: 'Mereka yang berjuang melawan kecanduan', sw: 'Wale wanaopambana na uraibu', tl: 'Ang mga nakikipaglaban sa adiksyon', am: 'ከሱስ ጋር የሚታገሉ' }, ref: 'John 8:36' },
      { theme: { en: 'New believers', fr: 'Les nouveaux croyants', es: 'Los nuevos creyentes', pt: 'Os novos convertidos', de: 'Neue Gläubige', ru: 'Новообращённые', zh: '初信的人', ja: '新しい信者', ko: '새신자들', ar: 'المؤمنون الجدد', fa: 'ایمانداران تازه', hi: 'नए विश्वासी', id: 'Orang-orang percaya yang baru', sw: 'Waamini wapya', tl: 'Ang mga bagong mananampalataya', am: 'አዲስ አማኞች' }, ref: 'Colossians 2:6-7' },
      { theme: { en: 'Peace where there is conflict', fr: 'La paix là où il y a conflit', es: 'Paz donde hay conflicto', pt: 'Paz onde há conflito', de: 'Frieden, wo Konflikt herrscht', ru: 'Мир там, где конфликт', zh: '在冲突之处求平安', ja: '争いのあるところに平和を', ko: '갈등이 있는 곳에 평화를', ar: 'سلام حيث يوجد نزاع', fa: 'صلح در جایی که درگیری هست', hi: 'जहां संघर्ष है वहां शांति', id: 'Damai di tempat yang penuh konflik', sw: 'Amani mahali penye migogoro', tl: 'Kapayapaan kung saan may alitan', am: 'ግጭት ባለበት ሰላም' }, ref: 'Matthew 5:9' },
      { theme: { en: 'One more: whoever God brings to mind', fr: 'Encore un : celui que Dieu met sur ton cœur', es: 'Uno más: aquel que Dios traiga a tu mente', pt: 'Mais um: aquele que Deus trouxer à mente', de: 'Noch einer: wen Gott dir ins Herz legt', ru: 'Ещё один: тот, кого напомнит Бог', zh: '再多一个：神让你想起的那个人', ja: 'もう一人——神様が心に思い起こさせる人', ko: '한 사람 더: 하나님이 마음에 떠올려 주시는 이', ar: 'واحد آخر: من يضعه الله في قلبك', fa: 'یکی دیگر: هر که خدا به یادت می‌آورد', hi: 'एक और: जिसे परमेश्वर आपके मन में लाए', id: 'Satu lagi: siapa pun yang Allah ingatkan', sw: 'Mmoja zaidi: yeyote Mungu akuletaye moyoni', tl: 'Isa pa: sinumang ipaalala ng Diyos sa iyo', am: 'አንድ ተጨማሪ፦ እግዚአብሔር ወደ ልብህ የሚያመጣው ማንኛውም ሰው' }, ref: 'Romans 10:1' },
    ],
  },
  PREPARING_IN_PRAYER,
  PREPARING_FOR_COVENANT,
  PRAYING_FOR_OUR_MARRIAGE,
];

export function getPlan(id, version = null) {
  const plan = PLANS.find((p) => p.id === id) || null;
  if (!plan || version == null || version === plan.version) return plan;
  // Meaningful revisions retain their prior content here. Unknown versions
  // fail closed instead of silently changing a completed prayer's history.
  return plan.versions?.[version] || null;
}

// Plans grouped for display, in PLAN_CATEGORIES order. Empty categories are
// dropped so the list only ever shows headings that have something under them.
export function plansByCategory(plans = PLANS) {
  return PLAN_CATEGORIES
    .map((c) => ({ ...c, plans: plans.filter((p) => (p.category || DEFAULT_PLAN_CATEGORY) === c.id) }))
    .filter((c) => c.plans.length > 0);
}

// Day content (1-based) for a plan, or null past the end. `resolved` lets a
// caller pass a plan that already has a language overlay folded in (see
// src/hooks/useLocalizedPlan.js) without this module knowing about translations.
export function planDayContent(planId, dayNumber, resolved = null, version = null) {
  const plan = resolved || getPlan(planId, version);
  if (!canUsePlan(plan) || !dayNumber || dayNumber < 1 || dayNumber > plan.days.length) return null;
  return plan.days[dayNumber - 1];
}
