// Prayer plan templates: guided journeys with a theme + Scripture for each day.
// Starting a plan creates ONE recurring prayer (freq daily, end after N times,
// schedule.plan = { id, startDate }); the engine numbers the days and this file
// supplies each day's content. Themes are AUTHORED (not generated) in all 16
// supported languages and resolved via pick(); pick() still falls back to
// English if a key is ever missing. Verse references are language-neutral and
// resolve through the localized verse pipeline.

export const PLANS = [
  {
    id: 'gratitude7',
    emoji: '🌅',
    count: 7,
    titleKey: 'planWeek7Title',
    subKey: 'planWeek7Sub',
    days: [
      { theme: { en: 'Thank God for who He is', fr: 'Remercie Dieu pour qui Il est', es: 'Agradece a Dios por quién es Él', pt: 'Agradeça a Deus por quem Ele é', de: 'Danke Gott für das, was Er ist', ru: 'Благодари Бога за то, каков Он', zh: '为神的本相感谢祂', ja: '神様がどのような方かを感謝しよう', ko: '하나님이 어떤 분이신지 감사하라', ar: 'اشكر الله على ما هو عليه', fa: 'خدا را برای آنچه هست شکر کن', hi: 'परमेश्वर जैसा है, उसके लिए धन्यवाद दें', id: 'Bersyukurlah kepada Allah atas siapa Dia', sw: 'Mshukuru Mungu kwa vile alivyo', tl: 'Pasalamatan ang Diyos sa kung sino Siya', am: 'እግዚአብሔርን ስለ ማንነቱ አመስግኑ' }, ref: 'Psalm 100:4-5' },
      { theme: { en: 'Thank Him for salvation', fr: 'Remercie-Le pour le salut', es: 'Agradécele por la salvación', pt: 'Agradeça-Lhe pela salvação', de: 'Danke Ihm für die Erlösung', ru: 'Благодари Его за спасение', zh: '为救恩感谢祂', ja: '救いを感謝しよう', ko: '구원을 주심에 감사하라', ar: 'اشكره على الخلاص', fa: 'او را برای نجات شکر کن', hi: 'उद्धार के लिए उसका धन्यवाद करें', id: 'Bersyukurlah kepada-Nya atas keselamatan', sw: 'Mshukuru kwa wokovu', tl: 'Pasalamatan Siya sa kaligtasan', am: 'ስለ መዳን አመስግኑት' }, ref: 'Ephesians 2:8-9' },
      { theme: { en: 'Thank Him for your family and friends', fr: 'Remercie-Le pour ta famille et tes amis', es: 'Agradécele por tu familia y amigos', pt: 'Agradeça-Lhe pela sua família e amigos', de: 'Danke Ihm für deine Familie und Freunde', ru: 'Благодари Его за твою семью и друзей', zh: '为你的家人和朋友感谢祂', ja: 'あなたの家族と友を感謝しよう', ko: '가족과 친구들로 인해 감사하라', ar: 'اشكره على عائلتك وأصدقائك', fa: 'او را برای خانواده و دوستانت شکر کن', hi: 'अपने परिवार और मित्रों के लिए उसका धन्यवाद करें', id: 'Bersyukurlah kepada-Nya atas keluarga dan sahabatmu', sw: 'Mshukuru kwa familia na marafiki zako', tl: 'Pasalamatan Siya sa iyong pamilya at mga kaibigan', am: 'ስለ ቤተሰብህና ጓደኞችህ አመስግኑት' }, ref: 'Philippians 1:3' },
      { theme: { en: 'Thank Him for provision', fr: 'Remercie-Le pour Sa provision', es: 'Agradécele por Su provisión', pt: 'Agradeça-Lhe pela Sua provisão', de: 'Danke Ihm für Seine Versorgung', ru: 'Благодари Его за Его обеспечение', zh: '为祂的供应感谢祂', ja: '神様の備えを感謝しよう', ko: '그분의 공급하심에 감사하라', ar: 'اشكره على إعالته', fa: 'او را برای تدارکش شکر کن', hi: 'उसके भरण-पोषण के लिए उसका धन्यवाद करें', id: 'Bersyukurlah kepada-Nya atas pemeliharaan-Nya', sw: 'Mshukuru kwa maandalizi yake', tl: 'Pasalamatan Siya sa Kanyang panustos', am: 'ስለ አቅርቦቱ አመስግኑት' }, ref: 'Philippians 4:19' },
      { theme: { en: 'Thank Him in the trial', fr: 'Remercie-Le dans l\'épreuve', es: 'Agradécele en la prueba', pt: 'Agradeça-Lhe na provação', de: 'Danke Ihm in der Prüfung', ru: 'Благодари Его в испытании', zh: '在试炼中感谢祂', ja: '試練の中で感謝しよう', ko: '시련 가운데 감사하라', ar: 'اشكره في التجربة', fa: 'او را در آزمایش شکر کن', hi: 'परीक्षा में उसका धन्यवाद करें', id: 'Bersyukurlah kepada-Nya dalam pencobaan', sw: 'Mshukuru katika jaribu', tl: 'Pasalamatan Siya sa gitna ng pagsubok', am: 'በፈተና ውስጥ አመስግኑት' }, ref: '1 Thessalonians 5:18' },
      { theme: { en: 'Thank Him for answered prayers', fr: 'Remercie-Le pour les prières exaucées', es: 'Agradécele por las oraciones contestadas', pt: 'Agradeça-Lhe pelas orações respondidas', de: 'Danke Ihm für erhörte Gebete', ru: 'Благодари Его за отвеченные молитвы', zh: '为蒙应允的祷告感谢祂', ja: '答えられた祈りを感謝しよう', ko: '응답된 기도로 인해 감사하라', ar: 'اشكره على الصلوات المستجابة', fa: 'او را برای دعاهای مستجاب‌شده شکر کن', hi: 'उत्तर दी गई प्रार्थनाओं के लिए उसका धन्यवाद करें', id: 'Bersyukurlah kepada-Nya atas doa yang terjawab', sw: 'Mshukuru kwa maombi yaliyojibiwa', tl: 'Pasalamatan Siya sa mga panalanging sinagot', am: 'ስለ ተመለሱ ጸሎቶች አመስግኑት' }, ref: 'Psalm 116:1-2' },
      { theme: { en: 'Overflow: tell someone what God did', fr: 'Déborde : raconte à quelqu\'un ce que Dieu a fait', es: 'Desborda: cuéntale a alguien lo que Dios hizo', pt: 'Transborde: conte a alguém o que Deus fez', de: 'Lauf über: erzähle jemandem, was Gott getan hat', ru: 'Пусть переполнит: расскажи кому-нибудь, что сделал Бог', zh: '满溢而出：把神的作为告诉一个人', ja: 'あふれ出そう：神様がなさったことを誰かに伝えよう', ko: '넘치게 하라: 하나님이 하신 일을 누군가에게 전하라', ar: 'فِض: أخبر أحدًا بما فعله الله', fa: 'سرریز شو: به کسی بگو خدا چه کرد', hi: 'उमड़ पड़ें: किसी को बताएं कि परमेश्वर ने क्या किया', id: 'Meluaplah: ceritakan kepada seseorang apa yang Allah lakukan', sw: 'Furika: mwambie mtu jambo Mungu alilofanya', tl: 'Umapaw: sabihin sa isang tao ang ginawa ng Diyos', am: 'ተትረፍርፍ፦ እግዚአብሔር ያደረገውን ለአንድ ሰው ንገር' }, ref: 'Psalm 107:1-2' },
    ],
  },
  {
    id: 'novena9',
    emoji: '🕊️',
    count: 9,
    titleKey: 'planNovenaTitle',
    subKey: 'planNovenaSub',
    days: [
      { theme: { en: 'Place your request before God', fr: 'Dépose ta requête devant Dieu', es: 'Presenta tu petición delante de Dios', pt: 'Apresente seu pedido diante de Deus', de: 'Bring dein Anliegen vor Gott', ru: 'Изложи свою просьбу перед Богом', zh: '将你的祈求呈到神面前', ja: 'あなたの願いを神様の前に置こう', ko: '너의 간구를 하나님 앞에 아뢰라', ar: 'ضع طلبك أمام الله', fa: 'درخواستت را به حضور خدا بگذار', hi: 'अपनी विनती परमेश्वर के सामने रखें', id: 'Sampaikan permohonanmu di hadapan Allah', sw: 'Weka ombi lako mbele za Mungu', tl: 'Ilagay ang iyong kahilingan sa harap ng Diyos', am: 'ልመናህን በእግዚአብሔር ፊት አቅርብ' }, ref: 'Philippians 4:6-7' },
      { theme: { en: 'Ask, seek, knock', fr: 'Demande, cherche, frappe', es: 'Pide, busca, llama', pt: 'Peça, busque, bata', de: 'Bitte, suche, klopfe an', ru: 'Проси, ищи, стучи', zh: '祈求，寻找，叩门', ja: '求めよ、探せ、たたけ', ko: '구하라, 찾으라, 두드리라', ar: 'اسأل، اطلب، اقرع', fa: 'بخواه، بجوی، در بزن', hi: 'मांगो, ढूंढो, खटखटाओ', id: 'Mintalah, carilah, ketuklah', sw: 'Omba, tafuta, bisha', tl: 'Humingi, maghanap, kumatok', am: 'ለምን፣ ፈልግ፣ አንኳኳ' }, ref: 'Matthew 7:7-8' },
      { theme: { en: 'Pray with faith', fr: 'Prie avec foi', es: 'Ora con fe', pt: 'Ore com fé', de: 'Bete im Glauben', ru: 'Молись с верой', zh: '凭信心祷告', ja: '信仰をもって祈ろう', ko: '믿음으로 기도하라', ar: 'صلِّ بإيمان', fa: 'با ایمان دعا کن', hi: 'विश्वास के साथ प्रार्थना करें', id: 'Berdoalah dengan iman', sw: 'Omba kwa imani', tl: 'Manalangin nang may pananampalataya', am: 'በእምነት ጸልይ' }, ref: 'Mark 11:24' },
      { theme: { en: 'Wait with hope', fr: 'Attends avec espérance', es: 'Espera con esperanza', pt: 'Aguarde com esperança', de: 'Warte mit Hoffnung', ru: 'Жди с надеждой', zh: '带着盼望等候', ja: '望みをもって待とう', ko: '소망으로 기다리라', ar: 'انتظر برجاء', fa: 'با امید منتظر بمان', hi: 'आशा के साथ प्रतीक्षा करें', id: 'Menantilah dengan pengharapan', sw: 'Ngoja kwa tumaini', tl: 'Maghintay nang may pag-asa', am: 'በተስፋ ጠብቅ' }, ref: 'Psalm 130:5-6' },
      { theme: { en: 'Surrender the outcome', fr: 'Remets l\'issue entre Ses mains', es: 'Entrega el resultado', pt: 'Entregue o resultado', de: 'Überlass Ihm das Ergebnis', ru: 'Вверь Ему исход', zh: '将结果交托给祂', ja: '結果を神様に委ねよう', ko: '결과를 그분께 맡기라', ar: 'سلِّم النتيجة له', fa: 'نتیجه را به او بسپار', hi: 'परिणाम उसे सौंप दें', id: 'Serahkan hasilnya kepada-Nya', sw: 'Mkabidhi matokeo', tl: 'Ipagkatiwala sa Kanya ang kalalabasan', am: 'ውጤቱን ለእርሱ አስረክብ' }, ref: 'Luke 22:42' },
      { theme: { en: 'Persist — do not lose heart', fr: 'Persévère — ne te décourage pas', es: 'Persiste — no desmayes', pt: 'Persista — não desanime', de: 'Halte durch — verzage nicht', ru: 'Не переставай — не унывай', zh: '坚持不懈——不要灰心', ja: '祈り続けよう——落胆してはならない', ko: '끈질기게 구하라 — 낙심하지 말라', ar: 'واظب — لا تفقد الرجاء', fa: 'پایداری کن — دلسرد نشو', hi: 'लगे रहें — हियाव न छोड़ें', id: 'Bertekunlah — jangan tawar hati', sw: 'Dumu — usikate tamaa', tl: 'Magpumilit — huwag panghinaan ng loob', am: 'ጽና — ተስፋ አትቁረጥ' }, ref: 'Luke 18:1' },
      { theme: { en: 'Remember His faithfulness', fr: 'Souviens-toi de Sa fidélité', es: 'Recuerda Su fidelidad', pt: 'Lembre-se da Sua fidelidade', de: 'Erinnere dich an Seine Treue', ru: 'Вспомни Его верность', zh: '记念祂的信实', ja: '神様の真実を思い起こそう', ko: '그분의 신실하심을 기억하라', ar: 'تذكّر أمانته', fa: 'وفاداری او را به یاد آور', hi: 'उसकी विश्वासयोग्यता को स्मरण करें', id: 'Ingatlah kesetiaan-Nya', sw: 'Kumbuka uaminifu wake', tl: 'Alalahanin ang Kanyang katapatan', am: 'ታማኝነቱን አስታውስ' }, ref: 'Lamentations 3:22-23' },
      { theme: { en: 'Pray in agreement with His will', fr: 'Prie en accord avec Sa volonté', es: 'Ora conforme a Su voluntad', pt: 'Ore em conformidade com a Sua vontade', de: 'Bete im Einklang mit Seinem Willen', ru: 'Молись в согласии с Его волей', zh: '照着祂的旨意祷告', ja: '神様の御心にかなって祈ろう', ko: '그분의 뜻에 따라 기도하라', ar: 'صلِّ وفق مشيئته', fa: 'مطابق ارادهٔ او دعا کن', hi: 'उसकी इच्छा के अनुसार प्रार्थना करें', id: 'Berdoalah sesuai dengan kehendak-Nya', sw: 'Omba kulingana na mapenzi yake', tl: 'Manalangin ayon sa Kanyang kalooban', am: 'እንደ ፈቃዱ ጸልይ' }, ref: '1 John 5:14-15' },
      { theme: { en: 'Entrust and give thanks', fr: 'Confie-Lui tout et rends grâce', es: 'Confía y da gracias', pt: 'Confie e dê graças', de: 'Vertraue an und danke', ru: 'Доверься и благодари', zh: '交托并感恩', ja: '委ねて感謝しよう', ko: '맡기고 감사하라', ar: 'استودعه واشكر', fa: 'بسپار و شکر کن', hi: 'सौंप दें और धन्यवाद दें', id: 'Percayakan dan bersyukurlah', sw: 'Mkabidhi na ushukuru', tl: 'Ipagkatiwala at magpasalamat', am: 'አደራ ስጥና አመስግን' }, ref: 'Psalm 37:5' },
    ],
  },
  {
    id: 'breakthrough21',
    emoji: '⚡',
    count: 21,
    titleKey: 'planTheme21Title',
    subKey: 'planTheme21Sub',
    days: [
      { theme: { en: 'Set your heart to seek God', fr: 'Dispose ton cœur à chercher Dieu', es: 'Dispón tu corazón para buscar a Dios', pt: 'Disponha seu coração para buscar a Deus', de: 'Richte dein Herz darauf aus, Gott zu suchen', ru: 'Расположи сердце искать Бога', zh: '定意寻求神', ja: '心を定めて神様を求めよう', ko: '하나님을 찾기로 마음을 정하라', ar: 'وطِّن قلبك على طلب الله', fa: 'دلت را برای طلبیدن خدا آماده کن', hi: 'परमेश्वर को खोजने के लिए अपना मन लगाएं', id: 'Arahkan hatimu untuk mencari Allah', sw: 'Kaza moyo wako kumtafuta Mungu', tl: 'Ihanda ang iyong puso na hanapin ang Diyos', am: 'እግዚአብሔርን ለመፈለግ ልብህን አዘጋጅ' }, ref: 'Jeremiah 29:12-13' },
      { theme: { en: 'Come boldly to the throne', fr: 'Approche-toi avec assurance du trône', es: 'Acércate con confianza al trono', pt: 'Aproxime-se com confiança do trono', de: 'Tritt freimütig vor den Thron', ru: 'Приступай с дерзновением к престолу', zh: '坦然无惧地来到宝座前', ja: '大胆に御座に近づこう', ko: '담대히 보좌 앞에 나아가라', ar: 'تقدَّم بثقة إلى العرش', fa: 'با دلیری به تخت فیض نزدیک شو', hi: 'साहस के साथ सिंहासन के पास आएं', id: 'Datanglah dengan berani ke takhta', sw: 'Njoo kwa ujasiri kwenye kiti cha enzi', tl: 'Lumapit nang may lakas ng loob sa trono', am: 'በድፍረት ወደ ዙፋኑ ቅረብ' }, ref: 'Hebrews 4:16' },
      { theme: { en: 'Pray the promises, not the problem', fr: 'Prie les promesses, pas le problème', es: 'Ora las promesas, no el problema', pt: 'Ore as promessas, não o problema', de: 'Bete die Verheißungen, nicht das Problem', ru: 'Молись обещаниями, а не проблемой', zh: '祷告神的应许，而非难题', ja: '問題ではなく約束を祈ろう', ko: '문제가 아니라 약속을 기도하라', ar: 'صلِّ الوعود لا المشكلة', fa: 'وعده‌ها را دعا کن، نه مشکل را', hi: 'समस्या नहीं, प्रतिज्ञाओं की प्रार्थना करें', id: 'Doakan janji-janji-Nya, bukan masalahnya', sw: 'Omba ahadi, siyo tatizo', tl: 'Ipanalangin ang mga pangako, hindi ang problema', am: 'ችግሩን ሳይሆን ተስፋዎቹን ጸልይ' }, ref: '2 Corinthians 1:20' },
      { theme: { en: 'Humble yourself before Him', fr: 'Humilie-toi devant Lui', es: 'Humíllate delante de Él', pt: 'Humilhe-se diante d\'Ele', de: 'Demütige dich vor Ihm', ru: 'Смирись перед Ним', zh: '在祂面前谦卑', ja: '神様の前にへりくだろう', ko: '그분 앞에 자신을 낮추라', ar: 'اتّضع أمامه', fa: 'در حضور او فروتن شو', hi: 'उसके सामने खुद को नम्र करें', id: 'Rendahkan dirimu di hadapan-Nya', sw: 'Jinyenyekeze mbele zake', tl: 'Magpakumbaba sa harap Niya', am: 'በፊቱ ራስህን አዋርድ' }, ref: '2 Chronicles 7:14' },
      { theme: { en: 'Forgive as you pray', fr: 'Pardonne en priant', es: 'Perdona mientras oras', pt: 'Perdoe enquanto ora', de: 'Vergib, während du betest', ru: 'Прощай, когда молишься', zh: '祷告时也要饶恕', ja: '祈りながら赦そう', ko: '기도하며 용서하라', ar: 'اغفر وأنت تصلي', fa: 'در حین دعا ببخش', hi: 'प्रार्थना करते समय क्षमा करें', id: 'Ampunilah saat kamu berdoa', sw: 'Samehe unapoomba', tl: 'Magpatawad habang nananalangin', am: 'ስትጸልይ ይቅር በል' }, ref: 'Mark 11:25' },
      { theme: { en: 'Fast something; hunger for Him', fr: 'Jeûne de quelque chose ; aie faim de Lui', es: 'Ayuna de algo; ten hambre de Él', pt: 'Jejue de algo; tenha fome d\'Ele', de: 'Faste von etwas; hungere nach Ihm', ru: 'Постись от чего-то; жаждай Его', zh: '禁戒一样东西，渴慕祂', ja: '何かを断ち、神様を慕い求めよう', ko: '무언가를 금식하며 그분을 갈망하라', ar: 'صُم عن شيء؛ واجُع إليه', fa: 'از چیزی روزه بگیر؛ گرسنهٔ او باش', hi: 'किसी चीज़ का उपवास करें; उसके लिए भूखे रहें', id: 'Berpuasalah dari sesuatu; laparlah akan Dia', sw: 'Funga kitu fulani; mtamani Yeye', tl: 'Mag-ayuno sa isang bagay; magutom para sa Kanya', am: 'ከአንድ ነገር ጹም፤ ለእርሱ ራብ' }, ref: 'Matthew 6:17-18' },
      { theme: { en: 'Pray with the Word open', fr: 'Prie la Bible ouverte', es: 'Ora con la Palabra abierta', pt: 'Ore com a Palavra aberta', de: 'Bete mit aufgeschlagenem Wort', ru: 'Молись с открытым Словом', zh: '打开圣经祷告', ja: 'みことばを開いて祈ろう', ko: '말씀을 펴 놓고 기도하라', ar: 'صلِّ والكلمة مفتوحة', fa: 'با کلام باز دعا کن', hi: 'वचन खोलकर प्रार्थना करें', id: 'Berdoalah dengan Firman terbuka', sw: 'Omba huku Neno likiwa wazi', tl: 'Manalangin nang bukas ang Salita', am: 'ቃሉን ከፍተህ ጸልይ' }, ref: 'John 15:7' },
      { theme: { en: 'Resist discouragement', fr: 'Résiste au découragement', es: 'Resiste el desánimo', pt: 'Resista ao desânimo', de: 'Widerstehe der Entmutigung', ru: 'Противостой унынию', zh: '抵挡灰心', ja: '落胆に抵抗しよう', ko: '낙심을 물리치라', ar: 'قاوِم اليأس', fa: 'در برابر دلسردی بایست', hi: 'निराशा का सामना करें', id: 'Lawanlah keputusasaan', sw: 'Pinga kukata tamaa', tl: 'Labanan ang pagkapanghina ng loob', am: 'ተስፋ መቁረጥን ተቃወም' }, ref: 'Galatians 6:9' },
      { theme: { en: 'Like Daniel: keep your rhythm', fr: 'Comme Daniel : garde ton rythme', es: 'Como Daniel: mantén tu ritmo', pt: 'Como Daniel: mantenha o seu ritmo', de: 'Wie Daniel: bewahre deinen Rhythmus', ru: 'Как Даниил: держи свой ритм', zh: '像但以理：保持你的规律', ja: 'ダニエルのように、リズムを保とう', ko: '다니엘처럼 네 리듬을 지키라', ar: 'مثل دانيال: حافظ على إيقاعك', fa: 'مانند دانیال: نظم خود را حفظ کن', hi: 'दानिय्येल की तरह: अपनी नियमितता बनाए रखें', id: 'Seperti Daniel: jagalah iramamu', sw: 'Kama Danieli: dumisha mpangilio wako', tl: 'Tulad ni Daniel: panatilihin ang iyong ritmo', am: 'እንደ ዳንኤል፦ ልማድህን ጠብቅ' }, ref: 'Daniel 6:10' },
      { theme: { en: 'Praise before the answer', fr: 'Loue avant la réponse', es: 'Alaba antes de la respuesta', pt: 'Louve antes da resposta', de: 'Lobe vor der Antwort', ru: 'Хвали до ответа', zh: '在答案之前先赞美', ja: '答えの前に賛美しよう', ko: '응답 전에 찬양하라', ar: 'سبِّح قبل الإجابة', fa: 'پیش از پاسخ، ستایش کن', hi: 'उत्तर मिलने से पहले स्तुति करें', id: 'Pujilah sebelum jawaban datang', sw: 'Sifu kabla ya jibu', tl: 'Magpuri bago ang sagot', am: 'ከመልሱ በፊት አመስግን' }, ref: 'Acts 16:25-26' },
      { theme: { en: 'Ask largely — He is able', fr: 'Demande largement — Il est puissant', es: 'Pide en grande — Él es poderoso', pt: 'Peça grandemente — Ele é poderoso', de: 'Bitte groß — Er ist mächtig', ru: 'Проси щедро — Он силён', zh: '放胆大求——祂能成就', ja: '大きく求めよう——神様にはできる', ko: '크게 구하라 — 그분은 능하시다', ar: 'اطلب بسخاء — فهو قادر', fa: 'بزرگ بخواه — او تواناست', hi: 'बड़ा मांगें — वह सामर्थी है', id: 'Mintalah dengan besar — Dia sanggup', sw: 'Omba kwa wingi — Yeye anaweza', tl: 'Humingi nang malaki — kaya Niya', am: 'በስፋት ለምን — እርሱ ይችላል' }, ref: 'Ephesians 3:20' },
      { theme: { en: 'Pray for those in the same battle', fr: 'Prie pour ceux qui vivent le même combat', es: 'Ora por quienes libran la misma batalla', pt: 'Ore por quem enfrenta a mesma batalha', de: 'Bete für die, die denselben Kampf kämpfen', ru: 'Молись о тех, кто в той же битве', zh: '为身处相同争战的人祷告', ja: '同じ戦いにある人のために祈ろう', ko: '같은 싸움을 하는 이들을 위해 기도하라', ar: 'صلِّ لأجل من يخوضون المعركة نفسها', fa: 'برای کسانی که در همان نبردند دعا کن', hi: 'उसी संघर्ष में जूझ रहे लोगों के लिए प्रार्थना करें', id: 'Doakan mereka yang berjuang dalam pergumulan yang sama', sw: 'Waombee walio katika vita vilevile', tl: 'Ipanalangin ang mga nasa parehong laban', am: 'በዚያው ውጊያ ውስጥ ላሉት ጸልይ' }, ref: 'Job 42:10' },
      { theme: { en: 'Watch and pray', fr: 'Veille et prie', es: 'Vela y ora', pt: 'Vigie e ore', de: 'Wache und bete', ru: 'Бодрствуй и молись', zh: '警醒祷告', ja: '目を覚まして祈ろう', ko: '깨어 기도하라', ar: 'اسهر وصلِّ', fa: 'بیدار باش و دعا کن', hi: 'जागते रहें और प्रार्थना करें', id: 'Berjaga-jagalah dan berdoalah', sw: 'Kesha na uombe', tl: 'Magbantay at manalangin', am: 'ንቁ ሆነህ ጸልይ' }, ref: 'Matthew 26:41' },
      { theme: { en: 'Wrestle like Jacob: do not let go', fr: 'Lutte comme Jacob : ne Le lâche pas', es: 'Lucha como Jacob: no lo sueltes', pt: 'Lute como Jacó: não O solte', de: 'Ringe wie Jakob: lass Ihn nicht los', ru: 'Борись, как Иаков: не отпускай Его', zh: '像雅各一样摔跤：不要放手', ja: 'ヤコブのように格闘しよう——神様を離すな', ko: '야곱처럼 씨름하라: 놓지 말라', ar: 'صارِع مثل يعقوب: لا تتركه', fa: 'مانند یعقوب کشتی بگیر: او را رها نکن', hi: 'याकूब की तरह मल्लयुद्ध करें: उसे न छोड़ें', id: 'Bergumullah seperti Yakub: jangan lepaskan Dia', sw: 'Shindana kama Yakobo: usimwache', tl: 'Makipagbuno tulad ni Jacob: huwag bibitaw', am: 'እንደ ያዕቆብ ታገል፦ አትልቀቀው' }, ref: 'Genesis 32:26' },
      { theme: { en: 'Speak to the mountain', fr: 'Parle à la montagne', es: 'Habla a la montaña', pt: 'Fale à montanha', de: 'Sprich zu dem Berg', ru: 'Скажи горе', zh: '向这座山说话', ja: '山に向かって語ろう', ko: '산을 향해 말하라', ar: 'خاطِب الجبل', fa: 'با کوه سخن بگو', hi: 'पहाड़ से कहें', id: 'Berkatalah kepada gunung itu', sw: 'Uambie mlima', tl: 'Magsalita sa bundok', am: 'ተራራውን ተናገር' }, ref: 'Mark 11:23' },
      { theme: { en: 'Stand on His faithfulness', fr: 'Tiens ferme sur Sa fidélité', es: 'Afírmate en Su fidelidad', pt: 'Firme-se na Sua fidelidade', de: 'Steh fest auf Seiner Treue', ru: 'Стой на Его верности', zh: '站立在祂的信实上', ja: '神様の真実に立とう', ko: '그분의 신실하심 위에 서라', ar: 'اثبت على أمانته', fa: 'بر وفاداری او بایست', hi: 'उसकी विश्वासयोग्यता पर दृढ़ रहें', id: 'Berdirilah di atas kesetiaan-Nya', sw: 'Simama juu ya uaminifu wake', tl: 'Tumayo sa Kanyang katapatan', am: 'በታማኝነቱ ላይ ቁም' }, ref: 'Numbers 23:19' },
      { theme: { en: 'Pray in the Spirit', fr: 'Prie par l\'Esprit', es: 'Ora en el Espíritu', pt: 'Ore no Espírito', de: 'Bete im Geist', ru: 'Молись в Духе', zh: '在圣灵里祷告', ja: '御霊によって祈ろう', ko: '성령 안에서 기도하라', ar: 'صلِّ في الروح', fa: 'در روح دعا کن', hi: 'आत्मा में प्रार्थना करें', id: 'Berdoalah dalam Roh', sw: 'Omba katika Roho', tl: 'Manalangin sa Espiritu', am: 'በመንፈስ ጸልይ' }, ref: 'Romans 8:26-27' },
      { theme: { en: 'Cast every care on Him', fr: 'Décharge-toi de tout souci sur Lui', es: 'Echa toda ansiedad sobre Él', pt: 'Lance toda ansiedade sobre Ele', de: 'Wirf alle Sorge auf Ihn', ru: 'Возложи всякую заботу на Него', zh: '将一切忧虑卸给祂', ja: 'すべての思い煩いを神様にゆだねよう', ko: '모든 염려를 그분께 맡기라', ar: 'ألقِ كل همّك عليه', fa: 'هر نگرانی را به او واگذار', hi: 'अपनी सारी चिंता उस पर डाल दें', id: 'Serahkanlah segala kekhawatiran kepada-Nya', sw: 'Mtwike kila wasiwasi wako', tl: 'Ilagak sa Kanya ang lahat ng alalahanin', am: 'ጭንቀትህን ሁሉ በእርሱ ላይ ጣል' }, ref: '1 Peter 5:7' },
      { theme: { en: 'Expect: set a watch for the answer', fr: 'Attends-toi à Lui : guette la réponse', es: 'Espera: ponte en vela por la respuesta', pt: 'Espere: fique de atalaia pela resposta', de: 'Erwarte es: halte Ausschau nach der Antwort', ru: 'Ожидай: встань на страже ответа', zh: '存着期待：守望神的答案', ja: '期待しよう——答えを見張ろう', ko: '기대하라: 응답을 파수하라', ar: 'ترقَّب: قِف تنتظر الجواب', fa: 'منتظر باش: برای پاسخ دیده‌بانی کن', hi: 'आशा रखें: उत्तर के लिए पहरा दें', id: 'Berharaplah: berjaga menanti jawaban', sw: 'Tarajia: kesha ukisubiri jibu', tl: 'Umasa: magbantay para sa sagot', am: 'ተጠባበቅ፦ መልሱን ለመጠበቅ ተጠንቀቅ' }, ref: 'Habakkuk 2:1-3' },
      { theme: { en: 'Thank Him for what is already moving', fr: 'Remercie-Le pour ce qui bouge déjà', es: 'Agradécele por lo que ya se mueve', pt: 'Agradeça-Lhe pelo que já está se movendo', de: 'Danke Ihm für das, was sich schon bewegt', ru: 'Благодари Его за то, что уже движется', zh: '为已经开始动工的事感谢祂', ja: 'すでに動き始めていることを感謝しよう', ko: '이미 움직이고 있는 것으로 인해 감사하라', ar: 'اشكره على ما بدأ يتحرك بالفعل', fa: 'او را برای آنچه از پیش در حرکت است شکر کن', hi: 'जो पहले से हो रहा है, उसके लिए उसका धन्यवाद करें', id: 'Bersyukurlah atas apa yang sudah mulai bergerak', sw: 'Mshukuru kwa kile ambacho tayari kinaendelea', tl: 'Pasalamatan Siya sa kung ano ang gumagalaw na', am: 'አስቀድሞ ለተጀመረው አመስግን' }, ref: 'John 11:41' },
      { theme: { en: 'Seal it: faith over feelings', fr: 'Scelle tout : la foi au-dessus des émotions', es: 'Séllalo: fe por encima de los sentimientos', pt: 'Sele tudo: fé acima dos sentimentos', de: 'Besiegle es: Glaube über Gefühle', ru: 'Запечатай это: вера выше чувств', zh: '封住这一切：信心胜过感觉', ja: '封印しよう——感情より信仰を', ko: '봉인하라: 감정보다 믿음을', ar: 'اختمها: الإيمان فوق المشاعر', fa: 'مهرش کن: ایمان برتر از احساسات', hi: 'इसे मुहरबंद करें: भावनाओं से ऊपर विश्वास', id: 'Meteraikan: iman di atas perasaan', sw: 'Itie muhuri: imani juu ya hisia', tl: 'Tatakan ito: pananampalataya higit sa damdamin', am: 'አትም፦ እምነት ከስሜት በላይ' }, ref: '2 Timothy 4:7' },
    ],
  },
  {
    id: 'others30',
    emoji: '🤝',
    count: 30,
    titleKey: 'plan30Title',
    subKey: 'plan30Sub',
    days: [
      { theme: { en: 'Your spouse or closest person', fr: 'Ton conjoint ou la personne la plus proche', es: 'Tu cónyuge o la persona más cercana', pt: 'Seu cônjuge ou a pessoa mais próxima', de: 'Dein Ehepartner oder der nächste Mensch', ru: 'Твой супруг или самый близкий человек', zh: '你的配偶或最亲近的人', ja: 'あなたの配偶者、または最も近しい人', ko: '당신의 배우자나 가장 가까운 사람', ar: 'زوجك أو أقرب الناس إليك', fa: 'همسرت یا نزدیک‌ترین فرد', hi: 'आपका जीवनसाथी या सबसे करीबी व्यक्ति', id: 'Pasanganmu atau orang terdekat', sw: 'Mwenzi wako au mtu wa karibu zaidi', tl: 'Ang iyong asawa o pinakamalapit na tao', am: 'የትዳር አጋርህ ወይም በጣም ቅርብ የሆነው ሰው' }, ref: 'Philippians 1:9-11' },
      { theme: { en: 'Your children or the next generation', fr: 'Tes enfants ou la génération suivante', es: 'Tus hijos o la próxima generación', pt: 'Seus filhos ou a próxima geração', de: 'Deine Kinder oder die nächste Generation', ru: 'Твои дети или следующее поколение', zh: '你的儿女或下一代', ja: 'あなたの子ども、または次の世代', ko: '당신의 자녀나 다음 세대', ar: 'أولادك أو الجيل القادم', fa: 'فرزندانت یا نسل بعد', hi: 'आपके बच्चे या अगली पीढ़ी', id: 'Anak-anakmu atau generasi berikutnya', sw: 'Watoto wako au kizazi kijacho', tl: 'Ang iyong mga anak o susunod na henerasyon', am: 'ልጆችህ ወይም ቀጣዩ ትውልድ' }, ref: 'Isaiah 54:13' },
      { theme: { en: 'Your parents', fr: 'Tes parents', es: 'Tus padres', pt: 'Seus pais', de: 'Deine Eltern', ru: 'Твои родители', zh: '你的父母', ja: 'あなたの両親', ko: '당신의 부모님', ar: 'والداك', fa: 'والدینت', hi: 'आपके माता-पिता', id: 'Orang tuamu', sw: 'Wazazi wako', tl: 'Ang iyong mga magulang', am: 'ወላጆችህ' }, ref: 'Exodus 20:12' },
      { theme: { en: 'Your siblings', fr: 'Tes frères et sœurs', es: 'Tus hermanos', pt: 'Seus irmãos', de: 'Deine Geschwister', ru: 'Твои братья и сёстры', zh: '你的兄弟姐妹', ja: 'あなたの兄弟姉妹', ko: '당신의 형제자매', ar: 'إخوتك', fa: 'خواهران و برادرانت', hi: 'आपके भाई-बहन', id: 'Saudara-saudaramu', sw: 'Ndugu zako', tl: 'Ang iyong mga kapatid', am: 'ወንድሞችህና እህቶችህ' }, ref: 'Psalm 133:1' },
      { theme: { en: 'A friend in need', fr: 'Un ami dans le besoin', es: 'Un amigo en necesidad', pt: 'Um amigo em necessidade', de: 'Ein Freund in Not', ru: 'Друг в нужде', zh: '有需要的朋友', ja: '困っている友', ko: '어려움에 처한 친구', ar: 'صديق في ضيق', fa: 'دوستی که در نیاز است', hi: 'ज़रूरत में पड़ा एक मित्र', id: 'Seorang teman yang membutuhkan', sw: 'Rafiki aliye na shida', tl: 'Isang kaibigang nangangailangan', am: 'በችግር ውስጥ ያለ ወዳጅ' }, ref: 'Job 42:10' },
      { theme: { en: 'Someone who is sick', fr: 'Une personne malade', es: 'Alguien que está enfermo', pt: 'Alguém que está doente', de: 'Jemand, der krank ist', ru: 'Кто-то, кто болен', zh: '一位患病的人', ja: '病んでいる人', ko: '병든 누군가', ar: 'شخص مريض', fa: 'کسی که بیمار است', hi: 'कोई जो बीमार है', id: 'Seseorang yang sakit', sw: 'Mtu aliye mgonjwa', tl: 'Isang taong may sakit', am: 'የታመመ ሰው' }, ref: 'James 5:14-15' },
      { theme: { en: 'Someone grieving', fr: 'Une personne en deuil', es: 'Alguien que está de duelo', pt: 'Alguém que está de luto', de: 'Jemand, der trauert', ru: 'Кто-то скорбящий', zh: '一位正在哀伤的人', ja: '悲しみの中にある人', ko: '슬픔에 잠긴 누군가', ar: 'شخص يحزن', fa: 'کسی که سوگوار است', hi: 'कोई जो शोक में है', id: 'Seseorang yang berdukacita', sw: 'Mtu aliye na huzuni', tl: 'Isang taong nagdadalamhati', am: 'የሚያዝን ሰው' }, ref: 'Psalm 34:18' },
      { theme: { en: 'Someone far from God', fr: 'Une personne loin de Dieu', es: 'Alguien lejos de Dios', pt: 'Alguém longe de Deus', de: 'Jemand, der fern von Gott ist', ru: 'Кто-то далёкий от Бога', zh: '一位远离神的人', ja: '神様から遠く離れている人', ko: '하나님에게서 멀리 있는 누군가', ar: 'شخص بعيد عن الله', fa: 'کسی که از خدا دور است', hi: 'कोई जो परमेश्वर से दूर है', id: 'Seseorang yang jauh dari Allah', sw: 'Mtu aliye mbali na Mungu', tl: 'Isang taong malayo sa Diyos', am: 'ከእግዚአብሔር የራቀ ሰው' }, ref: '2 Peter 3:9' },
      { theme: { en: 'Your pastor and church leaders', fr: 'Ton pasteur et les responsables d\'église', es: 'Tu pastor y los líderes de la iglesia', pt: 'Seu pastor e os líderes da igreja', de: 'Dein Pastor und die Gemeindeleiter', ru: 'Твой пастор и церковные служители', zh: '你的牧师和教会领袖', ja: 'あなたの牧師と教会の指導者', ko: '당신의 목사님과 교회 지도자들', ar: 'راعيك وقادة الكنيسة', fa: 'شبان و رهبران کلیسایت', hi: 'आपके पास्टर और कलीसिया के अगुवे', id: 'Gembala dan para pemimpin gerejamu', sw: 'Mchungaji wako na viongozi wa kanisa', tl: 'Ang iyong pastor at mga pinuno ng iglesia', am: 'እረኛህና የቤተ ክርስቲያን መሪዎች' }, ref: '1 Thessalonians 5:12-13' },
      { theme: { en: 'Your church family', fr: 'Ta famille d\'église', es: 'Tu familia de la iglesia', pt: 'Sua família da igreja', de: 'Deine Gemeindefamilie', ru: 'Твоя церковная семья', zh: '你的教会大家庭', ja: 'あなたの教会家族', ko: '당신의 교회 가족', ar: 'عائلتك الكنسية', fa: 'خانوادهٔ کلیسایت', hi: 'आपका कलीसिया परिवार', id: 'Keluarga gerejamu', sw: 'Familia yako ya kanisa', tl: 'Ang iyong pamilya sa iglesia', am: 'የቤተ ክርስቲያን ቤተሰብህ' }, ref: 'John 17:20-21' },
      { theme: { en: 'A neighbour', fr: 'Un voisin', es: 'Un vecino', pt: 'Um vizinho', de: 'Ein Nachbar', ru: 'Сосед', zh: '一位邻舍', ja: '隣人', ko: '이웃 한 사람', ar: 'جار', fa: 'یک همسایه', hi: 'एक पड़ोसी', id: 'Seorang tetangga', sw: 'Jirani', tl: 'Isang kapitbahay', am: 'ጎረቤት' }, ref: 'Luke 10:27' },
      { theme: { en: 'Your colleagues or classmates', fr: 'Tes collègues ou camarades', es: 'Tus colegas o compañeros de clase', pt: 'Seus colegas de trabalho ou de classe', de: 'Deine Kollegen oder Mitschüler', ru: 'Твои коллеги или одноклассники', zh: '你的同事或同学', ja: 'あなたの同僚や同級生', ko: '당신의 동료나 급우들', ar: 'زملاؤك في العمل أو الدراسة', fa: 'همکاران یا هم‌کلاسی‌هایت', hi: 'आपके सहकर्मी या सहपाठी', id: 'Rekan kerja atau teman sekelasmu', sw: 'Wenzako kazini au shuleni', tl: 'Ang iyong mga katrabaho o kaklase', am: 'የስራ ባልደረቦችህ ወይም የክፍል ጓደኞችህ' }, ref: 'Matthew 5:16' },
      { theme: { en: 'Someone who hurt you', fr: 'Une personne qui t\'a blessé', es: 'Alguien que te hirió', pt: 'Alguém que o feriu', de: 'Jemand, der dich verletzt hat', ru: 'Тот, кто причинил тебе боль', zh: '一位曾伤害你的人', ja: 'あなたを傷つけた人', ko: '당신에게 상처 준 누군가', ar: 'شخص جرحك', fa: 'کسی که به تو آسیب زده', hi: 'कोई जिसने आपको चोट पहुंचाई', id: 'Seseorang yang menyakitimu', sw: 'Mtu aliyekuumiza', tl: 'Isang taong nanakit sa iyo', am: 'ያሳመመህ ሰው' }, ref: 'Matthew 5:44' },
      { theme: { en: 'The poor and the hungry', fr: 'Les pauvres et ceux qui ont faim', es: 'Los pobres y los hambrientos', pt: 'Os pobres e os famintos', de: 'Die Armen und die Hungernden', ru: 'Бедные и голодные', zh: '贫穷人和饥饿的人', ja: '貧しい人と飢えている人', ko: '가난한 자들과 굶주린 자들', ar: 'الفقراء والجياع', fa: 'فقیران و گرسنگان', hi: 'गरीब और भूखे लोग', id: 'Orang miskin dan yang lapar', sw: 'Maskini na wenye njaa', tl: 'Ang mga mahihirap at nagugutom', am: 'ድሆችና የተራቡ' }, ref: 'Proverbs 19:17' },
      { theme: { en: 'Refugees and displaced people', fr: 'Les réfugiés et les déplacés', es: 'Los refugiados y desplazados', pt: 'Os refugiados e deslocados', de: 'Flüchtlinge und Vertriebene', ru: 'Беженцы и переселенцы', zh: '难民和流离失所的人', ja: '難民と避難を強いられた人々', ko: '난민과 실향민들', ar: 'اللاجئون والنازحون', fa: 'پناهندگان و آوارگان', hi: 'शरणार्थी और विस्थापित लोग', id: 'Para pengungsi dan orang terlantar', sw: 'Wakimbizi na waliohamishwa makazi', tl: 'Ang mga refugee at napalayas na tao', am: 'ስደተኞችና ተፈናቃዮች' }, ref: 'Deuteronomy 10:18-19' },
      { theme: { en: 'Orphans and widows', fr: 'Les orphelins et les veuves', es: 'Los huérfanos y las viudas', pt: 'Os órfãos e as viúvas', de: 'Waisen und Witwen', ru: 'Сироты и вдовы', zh: '孤儿和寡妇', ja: '孤児とやもめ', ko: '고아와 과부들', ar: 'الأيتام والأرامل', fa: 'یتیمان و بیوه‌زنان', hi: 'अनाथ और विधवाएं', id: 'Anak yatim dan para janda', sw: 'Yatima na wajane', tl: 'Ang mga ulila at balo', am: 'ወላጅ አልባዎችና መበለቶች' }, ref: 'James 1:27' },
      { theme: { en: 'The persecuted church', fr: 'L\'Église persécutée', es: 'La iglesia perseguida', pt: 'A igreja perseguida', de: 'Die verfolgte Gemeinde', ru: 'Гонимая церковь', zh: '受逼迫的教会', ja: '迫害されている教会', ko: '핍박받는 교회', ar: 'الكنيسة المضطهَدة', fa: 'کلیسای جفادیده', hi: 'सताई गई कलीसिया', id: 'Gereja yang teraniaya', sw: 'Kanisa linaloteswa', tl: 'Ang iglesiang inuusig', am: 'የተሰደደችው ቤተ ክርስቲያን' }, ref: 'Hebrews 13:3' },
      { theme: { en: 'Missionaries and evangelists', fr: 'Les missionnaires et évangélistes', es: 'Los misioneros y evangelistas', pt: 'Os missionários e evangelistas', de: 'Missionare und Evangelisten', ru: 'Миссионеры и благовестники', zh: '宣教士和传福音的人', ja: '宣教師と伝道者', ko: '선교사들과 전도자들', ar: 'المرسلون والمبشرون', fa: 'مبشران و بشارت‌دهندگان', hi: 'मिशनरी और सुसमाचार प्रचारक', id: 'Para misionaris dan penginjil', sw: 'Wamisionari na wainjilisti', tl: 'Ang mga misyonero at ebanghelista', am: 'ሚስዮናውያንና ወንጌላውያን' }, ref: 'Matthew 9:37-38' },
      { theme: { en: 'Your city', fr: 'Ta ville', es: 'Tu ciudad', pt: 'Sua cidade', de: 'Deine Stadt', ru: 'Твой город', zh: '你的城市', ja: 'あなたの町', ko: '당신의 도시', ar: 'مدينتك', fa: 'شهرت', hi: 'आपका शहर', id: 'Kotamu', sw: 'Jiji lako', tl: 'Ang iyong lungsod', am: 'ከተማህ' }, ref: 'Jeremiah 29:7' },
      { theme: { en: 'Your nation and its leaders', fr: 'Ta nation et ses dirigeants', es: 'Tu nación y sus líderes', pt: 'Sua nação e seus líderes', de: 'Deine Nation und ihre Führung', ru: 'Твой народ и его руководители', zh: '你的国家和领袖', ja: 'あなたの国とその指導者', ko: '당신의 나라와 지도자들', ar: 'أمّتك وقادتها', fa: 'ملت تو و رهبرانش', hi: 'आपका राष्ट्र और उसके नेता', id: 'Bangsamu dan para pemimpinnya', sw: 'Taifa lako na viongozi wake', tl: 'Ang iyong bansa at mga pinuno nito', am: 'ሀገርህና መሪዎቿ' }, ref: '1 Timothy 2:1-2' },
      { theme: { en: 'Teachers and schools', fr: 'Les enseignants et les écoles', es: 'Los maestros y las escuelas', pt: 'Os professores e as escolas', de: 'Lehrer und Schulen', ru: 'Учителя и школы', zh: '教师和学校', ja: '教師と学校', ko: '교사들과 학교들', ar: 'المعلمون والمدارس', fa: 'معلمان و مدارس', hi: 'शिक्षक और स्कूल', id: 'Para guru dan sekolah', sw: 'Walimu na shule', tl: 'Ang mga guro at paaralan', am: 'መምህራንና ትምህርት ቤቶች' }, ref: 'Proverbs 22:6' },
      { theme: { en: 'Doctors and caregivers', fr: 'Les médecins et soignants', es: 'Los médicos y cuidadores', pt: 'Os médicos e cuidadores', de: 'Ärzte und Pflegende', ru: 'Врачи и те, кто ухаживает за больными', zh: '医生和照护者', ja: '医師と介護者', ko: '의사들과 돌보는 이들', ar: 'الأطباء ومقدّمو الرعاية', fa: 'پزشکان و پرستاران', hi: 'डॉक्टर और देखभाल करने वाले', id: 'Para dokter dan perawat', sw: 'Madaktari na watunzaji', tl: 'Ang mga doktor at tagapag-alaga', am: 'ዶክተሮችና ተንከባካቢዎች' }, ref: 'Colossians 3:23' },
      { theme: { en: 'The lonely and the elderly', fr: 'Les personnes seules et âgées', es: 'Los solitarios y los ancianos', pt: 'Os solitários e os idosos', de: 'Die Einsamen und die Alten', ru: 'Одинокие и пожилые', zh: '孤单的人和年长的人', ja: '孤独な人と高齢の人', ko: '외로운 이들과 노인들', ar: 'الوحيدون وكبار السن', fa: 'تنهایان و سالمندان', hi: 'अकेले और बुज़ुर्ग लोग', id: 'Orang yang kesepian dan lanjut usia', sw: 'Wapweke na wazee', tl: 'Ang mga nag-iisa at matatanda', am: 'ብቸኞችና አረጋውያን' }, ref: 'Psalm 68:5-6' },
      { theme: { en: 'Prodigals — those who walked away', fr: 'Les prodigues — ceux qui se sont éloignés', es: 'Los pródigos: los que se alejaron', pt: 'Os pródigos — os que se afastaram', de: 'Die verlorenen Söhne — die sich abgewandt haben', ru: 'Блудные — те, кто отошёл', zh: '浪子——那些离开的人', ja: '放蕩の者——離れ去った人々', ko: '탕자들 — 떠나간 이들', ar: 'الضالّون — الذين ابتعدوا', fa: 'گمشدگان — کسانی که دور شده‌اند', hi: 'उड़ाऊ लोग — जो दूर चले गए', id: 'Mereka yang hilang — yang telah menjauh', sw: 'Wapotevu — wale walioondoka', tl: 'Ang mga alibughang anak — silang lumayo', am: 'አባካኞች — የራቁት' }, ref: 'Luke 15:20' },
      { theme: { en: 'Marriages under strain', fr: 'Les couples en difficulté', es: 'Los matrimonios en dificultad', pt: 'Os casamentos em dificuldade', de: 'Ehen unter Belastung', ru: 'Браки в трудностях', zh: '陷入困境的婚姻', ja: '緊張の中にある夫婦', ko: '어려움 가운데 있는 부부들', ar: 'الزيجات المتعثّرة', fa: 'ازدواج‌های زیر فشار', hi: 'तनाव में पड़े वैवाहिक जीवन', id: 'Pernikahan yang sedang goyah', sw: 'Ndoa zilizo katika shida', tl: 'Ang mga pagsasamang nasa gitna ng pagsubok', am: 'በችግር ውስጥ ያሉ ትዳሮች' }, ref: 'Ecclesiastes 4:12' },
      { theme: { en: 'The unemployed and discouraged', fr: 'Les sans-emploi et découragés', es: 'Los desempleados y desanimados', pt: 'Os desempregados e desanimados', de: 'Die Arbeitslosen und Entmutigten', ru: 'Безработные и унывающие', zh: '失业和灰心的人', ja: '職を失い落胆している人', ko: '실직하고 낙심한 이들', ar: 'العاطلون والمحبَطون', fa: 'بیکاران و دلسردشدگان', hi: 'बेरोज़गार और निराश लोग', id: 'Para penganggur dan yang putus asa', sw: 'Wasio na ajira na waliokata tamaa', tl: 'Ang mga walang trabaho at nanghihina ng loob', am: 'ስራ አጦችና ተስፋ የቆረጡ' }, ref: 'Isaiah 41:10' },
      { theme: { en: 'Those battling addiction', fr: 'Ceux qui luttent contre une dépendance', es: 'Los que luchan contra una adicción', pt: 'Os que lutam contra o vício', de: 'Die gegen Sucht kämpfen', ru: 'Те, кто борется с зависимостью', zh: '与瘾癖争战的人', ja: '依存症と闘っている人', ko: '중독과 싸우는 이들', ar: 'المكافحون للإدمان', fa: 'کسانی که با اعتیاد مبارزه می‌کنند', hi: 'व्यसन से जूझ रहे लोग', id: 'Mereka yang berjuang melawan kecanduan', sw: 'Wale wanaopambana na uraibu', tl: 'Ang mga nakikipaglaban sa adiksyon', am: 'ከሱስ ጋር የሚታገሉ' }, ref: 'John 8:36' },
      { theme: { en: 'New believers', fr: 'Les nouveaux croyants', es: 'Los nuevos creyentes', pt: 'Os novos convertidos', de: 'Neue Gläubige', ru: 'Новообращённые', zh: '初信的人', ja: '新しい信者', ko: '새신자들', ar: 'المؤمنون الجدد', fa: 'ایمانداران تازه', hi: 'नए विश्वासी', id: 'Orang-orang percaya yang baru', sw: 'Waamini wapya', tl: 'Ang mga bagong mananampalataya', am: 'አዲስ አማኞች' }, ref: 'Colossians 2:6-7' },
      { theme: { en: 'Peace where there is conflict', fr: 'La paix là où il y a conflit', es: 'Paz donde hay conflicto', pt: 'Paz onde há conflito', de: 'Frieden, wo Konflikt herrscht', ru: 'Мир там, где конфликт', zh: '在冲突之处求平安', ja: '争いのあるところに平和を', ko: '갈등이 있는 곳에 평화를', ar: 'سلام حيث يوجد نزاع', fa: 'صلح در جایی که درگیری هست', hi: 'जहां संघर्ष है वहां शांति', id: 'Damai di tempat yang penuh konflik', sw: 'Amani mahali penye migogoro', tl: 'Kapayapaan kung saan may alitan', am: 'ግጭት ባለበት ሰላም' }, ref: 'Matthew 5:9' },
      { theme: { en: 'One more: whoever God brings to mind', fr: 'Encore un : celui que Dieu met sur ton cœur', es: 'Uno más: aquel que Dios traiga a tu mente', pt: 'Mais um: aquele que Deus trouxer à mente', de: 'Noch einer: wen Gott dir ins Herz legt', ru: 'Ещё один: тот, кого напомнит Бог', zh: '再多一个：神让你想起的那个人', ja: 'もう一人——神様が心に思い起こさせる人', ko: '한 사람 더: 하나님이 마음에 떠올려 주시는 이', ar: 'واحد آخر: من يضعه الله في قلبك', fa: 'یکی دیگر: هر که خدا به یادت می‌آورد', hi: 'एक और: जिसे परमेश्वर आपके मन में लाए', id: 'Satu lagi: siapa pun yang Allah ingatkan', sw: 'Mmoja zaidi: yeyote Mungu akuletaye moyoni', tl: 'Isa pa: sinumang ipaalala ng Diyos sa iyo', am: 'አንድ ተጨማሪ፦ እግዚአብሔር ወደ ልብህ የሚያመጣው ማንኛውም ሰው' }, ref: 'Romans 10:1' },
    ],
  },
];

export function getPlan(id) {
  return PLANS.find((p) => p.id === id) || null;
}

// Day content (1-based) for a plan, or null past the end.
export function planDayContent(planId, dayNumber) {
  const plan = getPlan(planId);
  if (!plan || !dayNumber || dayNumber < 1 || dayNumber > plan.days.length) return null;
  return plan.days[dayNumber - 1];
}
