// The gospel journey: a gentle, Scripture-first reading for someone new to
// prayer or exploring the Christian faith. It is NOT an advertisement, an
// interruption, or a separate app — it is a natural continuation of the prayer
// experience, offered clearly, kept completely optional, and always respectful.
//
// Prayer is available to everyone. Gospel exploration is clearly offered,
// completely optional, and always respectful. This file holds only authored
// content: warm prose anchored in explicit Scripture references the reader can
// open and weigh for themselves. No Bible text is stored here or generated by AI
// — every claim points to a passage rendered through the shared Scripture reader.
//
// Shape (localized fields are { en, fr }; other languages fold in on demand as
// JSON overlays under translations/gospel/<lang>.json — see translations.js):
//   {
//     id, type, emoji, theme,
//     title, summary,
//     sections: [{ id, heading, body, refs: [] }],   // exactly six, stable ids
//     respondHeading, respondBody, guidedPrayer, formulaDisclaimer,
//     starterPrompt,                                  // seeds a private prayer
//     relatedArticleIds: [],                          // stable Learn article ids
//     questions: [{ id, heading, refs: [], articleId? }],
//   }

const gospelJourney = {
  id: 'hope-behind-prayer',
  type: 'gospel-journey',
  emoji: '🌅',
  theme: 'seeker',
  title: { en: 'The hope behind prayer', fr: 'L\'espérance derrière la prière' },
  summary: {
    en: 'Prayer is more than sending requests into the unknown. Discover the God Christians pray to and the hope He offers through Jesus.',
    fr: 'La prière est plus que d\'envoyer des demandes dans l\'inconnu. Découvre le Dieu à qui les chrétiens prient et l\'espérance qu\'il offre par Jésus.',
  },

  sections: [
    {
      id: 'come-honestly',
      heading: { en: 'You can come honestly', fr: 'Tu peux venir honnêtement' },
      body: {
        en: 'You do not need perfect words, impressive prayers, or a religious background to speak honestly to God. Christians believe God already sees our fears, our questions, our suffering, our guilt, and our deepest needs — and still invites us to come to Him just as we are. Prayer is not a reward for those who have it all together; it is a door opened to the weary. (This does not mean every request will be answered the way we hope — but it does mean we are truly heard.)',
        fr: 'Tu n\'as pas besoin de mots parfaits, de prières impressionnantes ou d\'un passé religieux pour parler honnêtement à Dieu. Les chrétiens croient que Dieu voit déjà nos peurs, nos questions, notre souffrance, notre culpabilité et nos besoins les plus profonds — et qu\'il nous invite pourtant à venir à lui tels que nous sommes. La prière n\'est pas une récompense pour ceux qui ont tout réglé ; c\'est une porte ouverte à ceux qui sont fatigués. (Cela ne veut pas dire que chaque demande recevra la réponse espérée — mais que nous sommes vraiment entendus.)',
      },
      refs: ['Psalm 34:18', 'Matthew 11:28', 'Hebrews 4:14-16'],
    },
    {
      id: 'made-to-know-god',
      heading: { en: 'We were made to know God', fr: 'Nous sommes faits pour connaître Dieu' },
      body: {
        en: 'Prayer is relational, not merely a way to request help. The Bible teaches that God made us — on purpose, in His own image — to know Him, to love Him, and to live in relationship with Him. He is not a distant force to be managed but a Person near to each of us. When we pray, we are responding to the God who made us and loved us first.',
        fr: 'La prière est relationnelle, non pas seulement un moyen de demander de l\'aide. La Bible enseigne que Dieu nous a faits — volontairement, à son image — pour le connaître, l\'aimer et vivre en relation avec lui. Il n\'est pas une force lointaine à gérer, mais une Personne proche de chacun de nous. Quand nous prions, nous répondons au Dieu qui nous a faits et qui nous a aimés le premier.',
      },
      refs: ['Genesis 1:26-27', 'Acts 17:24-28', 'John 17:3'],
    },
    {
      id: 'relationship-broken',
      heading: { en: 'Our relationship with God is broken', fr: 'Notre relation avec Dieu est brisée' },
      body: {
        en: 'If God is so near, why does He often feel far? The Bible answers honestly: all of us have turned from God\'s rightful place in our lives — in our thoughts, our desires, our words, and our actions. This is what the Bible calls sin. It is not only the harm we do to one another; it is a real break in our relationship with God. Sin separates us from Him, wounds us and others, and is something we cannot repair by simply trying harder or being good enough.',
        fr: 'Si Dieu est si proche, pourquoi semble-t-il souvent si loin ? La Bible répond avec honnêteté : nous nous sommes tous détournés de la place qui revient à Dieu dans nos vies — dans nos pensées, nos désirs, nos paroles et nos actes. C\'est ce que la Bible appelle le péché. Ce n\'est pas seulement le mal que nous nous faisons les uns aux autres ; c\'est une véritable rupture dans notre relation avec Dieu. Le péché nous sépare de lui, nous blesse et blesse les autres, et nous ne pouvons pas le réparer en faisant simplement plus d\'efforts ou en étant assez bons.',
      },
      refs: ['Isaiah 53:6', 'Romans 3:23', 'Romans 6:23'],
    },
    {
      id: 'god-came-near',
      heading: { en: 'God came near in Jesus', fr: 'Dieu s\'est approché en Jésus' },
      body: {
        en: 'God did not stay distant from our brokenness. In Jesus Christ, God Himself entered the world: He made the Father known, lived a life without sin, welcomed the very people others pushed away, and stepped into real human suffering. Jesus is not simply a wise teacher or a good example among many — He is God with us, come to seek and to save the lost. To see Jesus is to see what God is truly like.',
        fr: 'Dieu n\'est pas resté loin de notre brisure. En Jésus-Christ, Dieu lui-même est entré dans le monde : il a fait connaître le Père, a vécu une vie sans péché, a accueilli ceux-là mêmes que les autres rejetaient, et est entré dans la vraie souffrance humaine. Jésus n\'est pas seulement un sage parmi d\'autres ou un bon exemple — il est Dieu avec nous, venu chercher et sauver ce qui était perdu. Voir Jésus, c\'est voir qui est vraiment Dieu.',
      },
      refs: ['John 1:1-14', 'Colossians 1:15-20', 'Luke 19:10', 'Hebrews 4:15'],
    },
    {
      id: 'died-and-rose',
      heading: { en: 'Jesus died and rose again', fr: 'Jésus est mort et ressuscité' },
      body: {
        en: 'Here is the heart of it. Jesus willingly died for sinners — He took upon Himself the judgment our sin deserved, dying in our place. He was buried, and on the third day He physically rose from the dead. His resurrection is not a symbol or a legend; it is the foundation of Christian hope, God\'s promise that death and sin do not have the last word. Because Jesus lives, forgiveness and reconciliation with God are truly possible through Him.',
        fr: 'Voici le cœur de tout. Jésus a volontairement donné sa vie pour les pécheurs — il a pris sur lui le jugement que notre péché méritait, mourant à notre place. Il a été enseveli, et le troisième jour il est ressuscité physiquement d\'entre les morts. Sa résurrection n\'est ni un symbole ni une légende ; elle est le fondement de l\'espérance chrétienne, la promesse de Dieu que la mort et le péché n\'ont pas le dernier mot. Parce que Jésus est vivant, le pardon et la réconciliation avec Dieu sont vraiment possibles par lui.',
      },
      refs: ['Isaiah 53:4-6', 'Romans 5:6-8', '1 Corinthians 15:3-4', '1 Peter 3:18'],
    },
    {
      id: 'invited-to-respond',
      heading: { en: 'God invites you to respond', fr: 'Dieu t\'invite à répondre' },
      body: {
        en: 'God invites each of us to turn from sin and to place our trust in Jesus — this is what the Bible means by repentance and faith. Forgiveness is not something we earn through good works, religious effort, or perfect prayers. It is God\'s gift, freely given, received simply by trusting in Christ. To believe is not merely to agree that Jesus existed, but to entrust your whole self to Him as Lord — the One who died and rose for you.',
        fr: 'Dieu invite chacun de nous à se détourner du péché et à mettre sa confiance en Jésus — c\'est ce que la Bible appelle la repentance et la foi. Le pardon n\'est pas quelque chose que nous méritons par de bonnes œuvres, par un effort religieux ou par des prières parfaites. C\'est le don de Dieu, offert gratuitement, reçu simplement en se confiant en Christ. Croire, ce n\'est pas seulement reconnaître que Jésus a existé, mais te remettre tout entier à lui comme Seigneur — celui qui est mort et ressuscité pour toi.',
      },
      refs: ['Mark 1:14-15', 'John 3:16-18', 'Ephesians 2:8-10', 'Romans 10:9-13'],
    },
  ],

  // The optional response section, shown gently after the six sections. This is
  // authored gospel content (translated via overlay), never a saving formula.
  respondHeading: { en: 'Would you like to respond to God?', fr: 'Voudrais-tu répondre à Dieu ?' },
  respondBody: {
    en: 'Becoming a Christian is not about saying perfect words or pressing a button. It means honestly turning to God and trusting in Jesus. You can speak to Him in your own words, or use this prayer as a guide.',
    fr: 'Devenir chrétien ne consiste pas à dire des mots parfaits ni à appuyer sur un bouton. Cela signifie se tourner honnêtement vers Dieu et se confier en Jésus. Tu peux lui parler avec tes propres mots, ou t\'aider de cette prière comme d\'un guide.',
  },
  guidedPrayer: {
    en: 'God, I know that I need You. I have sinned and cannot restore myself to You. Thank You that Jesus died for my sins and rose again. I turn from my old way of life and place my trust in Jesus. Please forgive me, make me new, and teach me to follow You. Amen.',
    fr: 'Dieu, je sais que j\'ai besoin de toi. J\'ai péché et je ne peux pas me rétablir moi-même auprès de toi. Merci que Jésus soit mort pour mes péchés et ressuscité. Je me détourne de mon ancienne manière de vivre et je place ma confiance en Jésus. Pardonne-moi, renouvelle-moi et apprends-moi à te suivre. Amen.',
  },
  formulaDisclaimer: {
    en: 'This prayer is not a formula, and saying these words does not earn salvation. What matters is sincere repentance and faith in Jesus Christ.',
    fr: 'Cette prière n\'est pas une formule, et prononcer ces mots ne mérite pas le salut. Ce qui compte, c\'est une repentance sincère et la foi en Jésus-Christ.',
  },

  // Seeds the "Create a private prayer" next step. Fully editable by the user.
  starterPrompt: {
    en: 'God, help me understand who Jesus is and respond to You honestly.',
    fr: 'Dieu, aide-moi à comprendre qui est Jésus et à te répondre honnêtement.',
  },

  // "Continue exploring" — related Learn articles by STABLE id (never by title).
  relatedArticleIds: ['why-pray', 'grace', 'faith', 'repentance'],

  // "I still have questions" — each points to Scripture (and, where one fits, an
  // existing Learn article by stable id). Never to AI-generated answers.
  questions: [
    { id: 'who-is-jesus', heading: { en: 'Who is Jesus?', fr: 'Qui est Jésus ?' }, refs: ['John 1:1-14', 'Colossians 1:15-20'] },
    { id: 'why-jesus-died', heading: { en: 'Why did Jesus have to die?', fr: 'Pourquoi Jésus devait-il mourir ?' }, refs: ['Isaiah 53:4-6', 'Romans 5:6-8'], articleId: 'grace' },
    { id: 'can-god-forgive', heading: { en: 'Can God forgive me?', fr: 'Dieu peut-il me pardonner ?' }, refs: ['1 John 1:8-9', 'Psalm 103:8-12'], articleId: 'confession' },
    { id: 'still-have-doubts', heading: { en: 'What if I still have doubts?', fr: 'Et si j\'ai encore des doutes ?' }, refs: ['Mark 9:24', 'John 20:24-29'], articleId: 'faith' },
    { id: 'begin-reading-bible', heading: { en: 'How do I begin reading the Bible?', fr: 'Comment commencer à lire la Bible ?' }, refs: ['Psalm 119:105', 'Luke 24:27'] },
    { id: 'follow-jesus', heading: { en: 'What does it mean to follow Jesus?', fr: 'Que signifie suivre Jésus ?' }, refs: ['Luke 9:23', 'John 10:27-28'], articleId: 'sanctification' },
  ],
};

export default gospelJourney;
