import { describe, expect, it } from 'vitest';
import { LANG_CODES } from '../src/i18n';
import AI_GLOSSARY from './_aiGlossary.js';

const GLOSSARIES = Object.fromEntries(
  Object.entries(import.meta.glob('../src/content-quality/glossary/*.json', { eager: true, import: 'default' }))
    .map(([path, glossary]) => [path.match(/(\w+)\.json$/)[1], glossary]),
);

// The AI proxy runs outside the app bundle, so it carries a compact copy of the
// Christian terminology glossaries for its prompts. After editing a glossary:
//
//   npx vitest run api/aiGlossary.test.js -u
function expectedData() {
  const concepts = Object.keys(GLOSSARIES.en.terms);
  return Object.fromEntries(LANG_CODES.map((lang) => [lang, concepts.map((concept) => {
    const { preferred, avoid } = GLOSSARIES[lang].terms[concept];
    const term = lang === 'en' ? preferred : `${GLOSSARIES.en.terms[concept].preferred} = ${preferred}`;
    return avoid.length ? `${term} (not ${avoid.join(', ')})` : term;
  }).join('; ')]));
}

describe('AI prompt glossary', () => {
  it('matches the content-quality glossaries', async () => {
    const source = [
      '// Generated by api/aiGlossary.test.js from src/content-quality/glossary.',
      '// Do not edit. Regenerate with: npx vitest run api/aiGlossary.test.js -u',
      `export default ${JSON.stringify(expectedData(), null, 2)};`,
      '',
    ].join('\n');
    await expect(source).toMatchFileSnapshot('./_aiGlossary.js');
  });

  it('covers every app language', () => {
    expect(Object.keys(AI_GLOSSARY).sort()).toEqual([...LANG_CODES].sort());
  });
});
