import { describe, expect, it } from 'vitest';
import { PLANS } from '../src/content/prayerPlans';
import { isPlanReviewed } from '../src/lib/planReview';
import { LANG_CODES } from '../src/i18n';
import PLAN_PREVIEW from './_planPreviewData.js';
import handler, { planPreviewPage } from './plan-preview.js';

const LOCALES = Object.fromEntries(
  Object.entries(import.meta.glob('../src/i18n/locales/*.js', { eager: true, import: 'default' }))
    .map(([path, strings]) => [path.match(/(\w+)\.js$/)[1], strings]),
);

const TOKEN = 'AbCdEfGhIjKlMnOpQrStUv';
const esc = (value) => value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');

// The preview function runs outside the app bundle, so it carries its own copy
// of what it may say about each plan. This builds that copy from the catalogue
// and the locale bundles; the file snapshot below keeps the committed module in
// step. After changing a plan's name, subtitle or length, or its review status:
//
//   npx vitest run api/planPreview.test.js -u
function expectedData() {
  const text = (lang, key) => LOCALES[lang]?.[key] ?? LOCALES.fr[key];
  const plans = {};
  for (const plan of PLANS.filter(isPlanReviewed)) {
    plans[plan.id] = { count: plan.count, title: {}, sub: {}, days: {} };
    for (const lang of LANG_CODES) {
      plans[plan.id].title[lang] = text(lang, plan.titleKey);
      plans[plan.id].sub[lang] = text(lang, plan.subKey);
      plans[plan.id].days[lang] = text(lang, 'planDays').replace('{n}', String(plan.count));
    }
  }
  return { langs: LANG_CODES, plans };
}

describe('plan preview data', () => {
  it('matches the catalogue and the locale bundles', async () => {
    const source = [
      '// Generated by api/planPreview.test.js from the plan catalogue and locale bundles.',
      '// Do not edit. Regenerate with: npx vitest run api/planPreview.test.js -u',
      `export default ${JSON.stringify(expectedData(), null, 2)};`,
      '',
    ].join('\n');
    await expect(source).toMatchFileSnapshot('./_planPreviewData.js');
  });

  it('holds every shareable plan and nothing that is not', () => {
    expect(Object.keys(PLAN_PREVIEW.plans).sort()).toEqual(PLANS.filter(isPlanReviewed).map((p) => p.id).sort());
  });
});

describe('planPreviewPage', () => {
  it('names the plan in the sharer’s language', () => {
    const html = planPreviewPage({ planId: 'altar7', token: TOKEN, lang: 'fr' });
    const plan = PLAN_PREVIEW.plans.altar7;
    expect(html).toContain(`<meta property="og:title" content="${esc(plan.title.fr)} · Praystead" />`);
    expect(html).toContain(`content="${esc(`${plan.sub.fr} · ${plan.days.fr}`)}"`);
    expect(html).toContain('<meta property="og:image" content="https://praystead.com/og/plans/altar7.png" />');
    expect(html).toContain(`<meta property="og:url" content="https://praystead.com/plans/altar7/${TOKEN}" />`);
    expect(html).toContain('<html lang="fr">');
  });

  it('falls back to English for an unknown language', () => {
    const html = planPreviewPage({ planId: 'altar7', lang: 'xx' });
    expect(html).toContain(`${esc(PLAN_PREVIEW.plans.altar7.title.en)} · Praystead`);
  });

  it('shows the generic preview for an unknown or malformed plan', () => {
    for (const planId of ['nope', '"><script>', undefined]) {
      const html = planPreviewPage({ planId, token: TOKEN, lang: 'en' });
      expect(html).toContain('content="https://praystead.com/og.png"');
      expect(html).toContain('<meta property="og:url" content="https://praystead.com/" />');
      expect(html).not.toContain('<script>');
    }
  });

  it('drops a malformed token instead of echoing it', () => {
    const html = planPreviewPage({ planId: 'altar7', token: '"><img src=x>', lang: 'en' });
    expect(html).toContain('<meta property="og:url" content="https://praystead.com/plans/altar7" />');
    expect(html).not.toContain('<img');
  });

  it('never carries a sharer’s name', () => {
    const html = planPreviewPage({ planId: 'altar7', token: TOKEN, lang: 'en' });
    expect(html).not.toMatch(/invites you/i);
  });

  it('gives a mistaken person a way through that the rewrite never catches', () => {
    expect(planPreviewPage({ planId: 'altar7', token: TOKEN, lang: 'en' })).toContain(`href="/plans/altar7/${TOKEN}?app=1"`);
  });
});

describe('handler', () => {
  it('answers with cacheable HTML', () => {
    const headers = {};
    const res = {
      setHeader: (key, value) => { headers[key] = value; },
      status(code) { this.statusCode = code; return this; },
      send(body) { this.body = body; return this; },
    };
    handler({ query: { planId: 'fast3', token: TOKEN, lang: ['de'] } }, res);
    expect(res.statusCode).toBe(200);
    expect(headers['Content-Type']).toMatch(/text\/html/);
    expect(headers['Cache-Control']).toMatch(/s-maxage/);
    expect(res.body).toContain(esc(PLAN_PREVIEW.plans.fast3.title.de));
  });
});
