// Paul's approval in the project conversation on 2026-09-30: "approved not yet
// recommended resources and plans", confirmed the same day by choosing, in
// answer to an explicit scope question, "13 new plans", "254 new-plan
// resources" and "Older pending drafts too", and "Apply them" for the curator
// proposals in docs/NEW_PLANS_2026-09-23.md.
//
// Scope: the thirteen curricula drafted from 2026-09-23 (contentVersion 1) and
// the 254 resource candidates in src/content/resources/newPlans/, sensitive
// ones included, as presented that day with the reviewer notes in
// docs/NEW_PLANS_2026-09-23.md. Locale approval covers the current
// presentation, including AI-drafted titles and English prose fallbacks; it is
// not a native-speaker review. It is not an independent audit of each
// resource, and it does not cover a plan version, locale or candidate added
// later. Link and edition checks are separate (`lastVerifiedAt`).

// Registered in src/content/prayerPlans.js and held to the shared contract in
// src/content/plans/testing/newPlanContract.js.
export const NEW_PLAN_IDS = [
  'fruit10', 'identity21', 'kingdomCome14', 'holySpirit21',
  'children21', 'prodigal30', 'unbelievers30', 'work21', 'psalms42',
  'manOfGod21', 'womanOfGod21', 'unborn21', 'churchHurt21',
];

// Plans whose subject needs a safeguarding sign-off as well as a theological
// one (pregnancy and loss, abuse, guidance claims, disputed gender roles,
// estranged family). Paul signed both.
export const SENSITIVE_PLAN_IDS = [
  'unborn21', 'churchHurt21', 'holySpirit21', 'prodigal30', 'manOfGod21', 'womanOfGod21',
];

export const NEW_PLAN_REVIEWED_LOCALES = [
  'en', 'fr', 'de', 'es', 'pt', 'ru', 'zh', 'ja', 'ko', 'ar', 'fa', 'hi', 'id', 'sw', 'tl', 'am',
];

export const NEW_PLAN_SIGNOFF = { status: 'approved', reviewer: 'Paul', reviewedAt: '2026-09-30' };

export const NEW_PLAN_APPROVALS = Object.fromEntries(NEW_PLAN_IDS.map((id) => [id, {
  status: 'approved',
  contentVersion: 1,
  draftedAt: '2026-09-23',
  draftedWith: 'ai-assisted',
  sensitive: SENSITIVE_PLAN_IDS.includes(id),
  theology: { ...NEW_PLAN_SIGNOFF },
  safety: { ...NEW_PLAN_SIGNOFF },
  locales: Object.fromEntries(NEW_PLAN_REVIEWED_LOCALES.map((lang) => [lang, {
    ...NEW_PLAN_SIGNOFF,
    scope: 'current-presentation-including-authored-fallbacks',
  }])),
}]));

export const NEW_PLAN_RESOURCE_SIGNOFF = {
  status: 'approved', reviewedBy: 'Paul', reviewedAt: '2026-09-30',
  approvalId: 'new-plan-resources-2026-09-30',
};

// Closed list, grouped by the plan whose research found the entry. An id not
// on it stays `needs_review`, so a candidate added later is never approved by
// default.
export const NEW_PLAN_RESOURCE_APPROVED_IDS = [
  // children21 (23)
  'crouch-tech-wise-family',
  'ortiz-consejos-culto-familiar',
  'berndt-praying-scriptures-children',
  'bloom-seven-things-pray-children',
  'powell-sticky-faith',
  'nielson-parents-we-get-to-pray',
  'guthrie-praying-through-bible-kids',
  'beeke-ore-pela-salvacao-filhos',
  'shin-hyungseob-faith-planting-parent-coaching',
  'cheng-depeng-raising-godly-next-generation-grace',
  'reju-on-guard',
  'jones-how-and-when-tell-kids-about-sex',
  'obuchi-jozu-ni-okoru-hito-ni-naru',
  'macarthur-kak-blagovestvovat-detyam',
  'pardoe-pray-big-things-little-ones',
  'shenouda-family-religious-education',
  'steer-doaye-madar-baraye-farzand',
  'parfan-usapang-pamilya-mga-anak',
  'varak-transmettre-la-foi-enfants',
  'erf-voss-wie-kinder-glauben-lernen',
  'gotquestions-let-go-adult-children',
  'mahibere-kidusan-technology-child-rearing',
  'gotquestions-parents-leaving-inheritance',
  // churchHurt21 (21)
  'mcknight-church-called-tov',
  'gangloff-identifier-systeme-religieux-abusif',
  'thirtyoneeight-spiritual-abuse-training-matters',
  'langberg-redeeming-power',
  'degroat-when-narcissism-comes-to-church',
  'oakley-escaping-maze-spiritual-abuse',
  'mullen-somethings-not-right',
  'grace-for-survivors-advocates',
  'langberg-when-the-church-harms',
  'tempelmann-religioeser-missbrauch',
  'ead-leitfaden-religioeser-machtmissbrauch',
  'cesar-feridos-em-nome-de-deus',
  'protestantedigital-abuso-espiritual-visibilidad',
  'cemk-tov-church-review',
  'denhollander-more-to-gospel-than-forgiveness',
  'hill-church-hurt-source',
  'kruger-what-is-spiritual-abuse',
  'zivi-shinko-gyakutai-kaiho',
  'gotquestions-what-is-spiritual-abuse',
  'gotquestions-pastor-authority',
  'hill-sighing-on-sunday',
  // fruit10 (16)
  'wright-cultivating-the-fruit-of-the-spirit',
  'bridges-practice-of-godliness',
  'bibleproject-galatians-overview',
  'bibleproject-shalom-peace',
  'stott-message-of-galatians',
  'ligonier-what-is-the-fruit-of-the-spirit',
  'rossi-obra-del-espiritu-santo-segun-galatas',
  'charriere-le-fruit-de-l-esprit',
  'vollkommer-frucht-die-nach-gott-schmeckt',
  'lopes-galatas-carta-da-liberdade-crista',
  'lohmann-der-heilige-geist-und-seine-frucht',
  'gee-fruit-of-the-spirit',
  'sproul-fruit-of-the-holy-spirit',
  'ag-credibility-fruit-of-the-spirit-in-witness',
  'keller-galatians-for-you',
  'gotquestions-fruit-of-the-holy-spirit',
  // holySpirit21 (21)
  'packer-keep-in-step-with-the-spirit',
  'ferguson-the-holy-spirit',
  'chan-forgotten-god',
  'fee-paul-the-spirit-and-the-people-of-god',
  'keener-gift-and-giver',
  'stronstad-charismatic-theology-of-st-luke',
  'ag-modern-day-prophecy',
  'willard-hearing-god',
  'gotquestions-who-is-the-holy-spirit',
  'storms-beginners-guide-to-spiritual-gifts',
  'stott-message-of-acts',
  'fee-first-epistle-to-the-corinthians',
  'fee-saint-esprit-presence-renouvelee-de-dieu',
  'blocher-plenitude-du-saint-esprit',
  'bfp-grundlegende-wirkungen-des-heiligen-geistes',
  'rust-geist-gottes-quelle-des-lebens',
  'salcedo-como-andar-por-el-espiritu',
  'he-chunxun-ruhe-jiechu-shengling-de-guozi',
  'sgc-holy-life-fullness-of-the-spirit',
  'bibleproject-spirit-of-god-podcast',
  'hayford-sorting-out-spiritual-language',
  // identity21 (17)
  'wilbourne-union-with-christ',
  'ferguson-children-of-the-living-god',
  'keller-freedom-of-self-forgetfulness',
  'bibleproject-ephesians-overview',
  'bibleproject-romans-5-16-overview',
  'bibleproject-colossians-overview',
  'bridges-who-am-i',
  'billings-union-with-christ',
  'keener-mind-of-the-spirit',
  'gotquestions-identity-in-christ',
  'morey-introduccion-union-con-cristo',
  'lotz-identitaet-wiederhergestellt-in-christus',
  'kruger-identity-theft',
  'lawrence-biblical-theology-and-identity',
  'tennison-what-we-believe-about-sanctification',
  'mbewe-unity',
  'gaffin-union-with-christ',
  // kingdomCome14 (20)
  'wright-lord-and-his-prayer',
  'keller-prayer',
  'packer-praying-the-lords-prayer',
  'greig-how-to-pray',
  '24-7-prayer-the-prayer-course',
  'bibleproject-lords-prayer',
  'bibleproject-gospel-of-the-kingdom',
  'bibleproject-heaven-and-earth',
  'bibleproject-justice',
  'bibleproject-sermon-on-the-mount-podcast',
  'coalicion-padre-nuestro-curso',
  'ladd-gospel-of-the-kingdom',
  'mcknight-kingdom-conspiracy',
  'stott-message-of-the-sermon-on-the-mount',
  'evangile21-seigneur-apprends-nous-a-prier',
  'leparcours-le-notre-pere',
  'erf-dein-reich-komme',
  'evangelium21-vergebung-im-vaterunser',
  'sproul-prayer-of-the-lord',
  'oshima-asayu-ni-inoru-shu-no-inori',
  // manOfGod21 (20)
  'hughes-disciplines-of-a-godly-man',
  'scazzero-emotionally-healthy-spirituality',
  'chester-closing-the-window',
  'covenant-eyes-life-change-workbook',
  'piper-husbands-who-love-like-christ',
  'cbe-pershey-ephesians-5',
  'hunter-why-is-friendship-hard-for-men',
  'hunter-made-for-friendship',
  'pyle-man-enough',
  'bloom-strong-legacy-of-a-weak-father',
  'packer-finishing-our-course-with-joy',
  'erf-raus-aus-der-porno-falle',
  'burgarth-echte-maenner-singen-nicht',
  'lambert-finally-free',
  'orange-etre-un-homme-selon-dieu',
  'servir-ensemble-masculinite-de-jesus',
  'atkinson-amistad-masculina',
  'mccormick-se-un-hombre-como-jesus',
  'segal-more-than-sexual-purity',
  'fiel-machismo-vs-masculinidade-biblica',
  // prodigal30 (20)
  'graham-prodigals-and-those-who-love-them',
  'keller-prodigal-god',
  'piper-seven-encouragements-parents-prodigals',
  'kohlmeyer-six-ways-love-wayward-child',
  'childers-barnett-loved-one-deconstructing',
  'vandewerken-praying-for-prodigal-children',
  'harvey-lift-heavy-burden-of-shame',
  'banks-prayers-for-prodigals',
  'banks-hope-lies-ahead',
  'herrera-hijo-indiferente-al-evangelio',
  'richards-los-hijos-prodigos',
  'moore-ama-a-tu-hijo-prodigo',
  'ortis-when-prodigal-children-dont-return',
  'gandolfo-a-mae-do-filho-prodigo',
  'nouwen-return-of-the-prodigal-son',
  'foma-deti-uhodyat-iz-tserkvi',
  'mofei-wei-langzixing-ernu-daogao',
  'hawksley-masal-gomshodeha',
  'bing-grace-lessons-prodigal-son',
  'guzik-luke-15-commentary',
  // psalms42 (24)
  'bibleproject-psalms-overview',
  'bibleproject-how-to-read-psalms',
  'bibleproject-psalms-study-podcast',
  'bibleproject-psalms-1-2-podcast',
  'keller-songs-of-jesus',
  'bonhoeffer-psalms-prayer-book',
  'vroegop-dark-clouds-deep-mercy',
  'peterson-answering-god',
  'wright-case-for-the-psalms',
  'longman-how-to-read-the-psalms',
  'longman-psalms-totc',
  'kidner-psalms',
  'wax-cs-lewis-cursing-psalms',
  'coalicion-oracion-imprecatoria',
  'wax-psalms-in-30-days',
  'cavin-prier-jugement-ennemis',
  'excelsis-redecouvrir-les-psaumes',
  'nicole-livre-des-psaumes',
  'brueggemann-message-of-the-psalms',
  'ellison-christ-shape-psalms',
  'fox-hope-darkest-psalm',
  'everingham-learning-to-lament',
  'godfrey-learning-to-love-the-psalms',
  'thornton-tears-in-heaven-psalm-56',
  // unbelievers30 (17)
  'operation-world-pray-today',
  'joshua-project-unreached-of-the-day',
  'open-doors-world-watch-list',
  'thy-kingdom-come-pray-for-five',
  'lawrence-how-can-i-pray-for-non-christians',
  'pippert-out-of-the-saltshaker',
  'chan-evangelism-skeptical-world-course',
  'koukl-tactics',
  'lausanne-cape-town-commitment',
  'sgc-biblical-evangelism-and-discipleship',
  'kapitaniuk-prier-pour-le-salut-de-non-chretiens',
  'thirty-days-prayer-muslim-world',
  'kalameh-basharat-ya-feshar',
  'gotquestions-evangelize-friends-family',
  'challies-18-prayers-for-unbelievers',
  'perez-relacionarme-con-un-no-creyente',
  'ando-inorarete-shu-no-waza-wo-miru',
  // unborn21 (23)
  'hutto-inheritance-of-tears',
  'booker-grace-like-scarlett',
  'furman-labor-with-hope',
  'swanson-pregnancy-can-be-scary',
  'polimino-praying-through-your-pregnancy',
  'butler-postpartum-depression-christian',
  'brisley-medication-postpartum-depression',
  'brisley-verses-dont-enjoy-motherhood',
  'wunnenberg-grieving-child-never-knew',
  'mcclure-consuelo-perdida-embarazo',
  'sabatier-consolar-casal-aborto-espontaneo',
  'lessa-consolo-gestante',
  'knodel-bin-kaum-da-muss-schon-fort',
  'gibson-gods-comfort-loss-of-child',
  'singh-miscarriage-pregnancy-loss-love-of-god',
  'carlson-sharing-painful-loss-miscarriage',
  'allen-psalms-lamenting-miscarriage',
  'gotquestions-miscarriage-bible',
  'kraus-beremennost-i-poterya-rebenka',
  'howard-pregnant-in-a-pandemic',
  'mame-meditations-au-fil-de-ma-grossesse',
  'tombrella-dads-paternity-leave',
  'topchretien-ne-me-volez-pas-mon-deuil',
  // womanOfGod21 (16)
  'wilkin-women-of-the-word',
  'custis-james-gospel-of-ruth',
  'custis-james-half-the-church',
  'peppiatt-rediscovering-scriptures-vision-for-women',
  'smith-gods-good-design',
  'cbe-women-in-scripture-and-mission',
  'wilkin-in-his-image',
  'guthrie-even-better-than-eden',
  'bibleproject-image-of-god',
  'bibleproject-ruth-overview',
  'bibleproject-esther-overview',
  'ag-role-of-women-in-ministry',
  'strickland-is-it-abuse',
  'garn-image-bearers-what-women-need-to-know',
  'coalicion-la-mujer-y-la-biblia',
  'rourke-seven-womens-ministries',
  // work21 (16)
  'keller-every-good-endeavor',
  'theologyofwork-rest-and-work',
  'theologyofwork-calling-and-vocation',
  'theologyofwork-finding-god-in-unemployment',
  'theologyofwork-godliness-with-contentment',
  'guinness-the-call',
  'greene-fruitfulness-on-the-frontline',
  'comer-ruthless-elimination-of-hurry',
  'dawn-keeping-the-sabbath-wholly',
  'bibleproject-sabbath',
  'keller-generous-justice',
  'alcorn-treasure-principle',
  'martin-you-are-never-without-work',
  'michelen-la-teologia-del-trabajo',
  'theologyofwork-10-key-points-work',
  'graber-beruf-und-berufung',
];
