// Explicit user instruction in the project conversation on 2026-09-23: "add
// all books left out because there are new plans coming, and approve those you
// added to make them visible to users", confirmed as "Approve all 154 author
// books under the name Paul".
// Scope: the 154 entries in src/content/resources/authors/ as presented that
// day, sensitive ones included, listed by id below. It is not an independent
// audit of each book, and it does not cover an entry added to those files
// later. Link and edition checks are separate (`lastVerifiedAt` on each edition).
export const AUTHOR_BOOKS_SIGNOFF = {
  status: 'approved', reviewedBy: 'Paul', reviewedAt: '2026-09-23',
  approvalId: 'author-books-2026-09-23',
};

export const AUTHOR_BOOKS_APPROVED_IDS = [
  // Myles Munroe (34)
  'munroe-purpose-and-power-of-prayer',
  'munroe-purpose-and-power-of-the-holy-spirit',
  'munroe-waiting-and-dating',
  'munroe-single-married-separated',
  'munroe-purpose-and-power-of-love-and-marriage',
  'munroe-purpose-and-power-of-men',
  'munroe-purpose-and-power-of-women',
  'munroe-fatherhood-principle',
  'munroe-prayer-with-purpose-and-power',
  'munroe-experiencing-the-holy-spirit',
  'munroe-man-of-purpose-and-power',
  'munroe-woman-of-purpose-and-power',
  'munroe-principles-and-power-of-vision',
  'munroe-vision-with-purpose-and-power',
  'munroe-principles-and-power-of-success',
  'munroe-success-with-purpose-and-power',
  'munroe-purpose-and-power-of-change',
  'munroe-principles-and-benefits-of-change',
  'munroe-understanding-your-potential',
  'munroe-un-potentiel-formidable',
  'munroe-releasing-your-potential',
  'munroe-unleash-your-purpose',
  'munroe-become-who-you-were-meant-to-be',
  'munroe-reclaiming-gods-original-purpose',
  'munroe-spirit-of-leadership',
  'munroe-becoming-a-leader',
  'munroe-leader-of-purpose-and-power',
  'munroe-power-of-character-in-leadership',
  'munroe-purpose-and-power-of-authority',
  'munroe-kingdom-principles',
  'munroe-rediscovering-the-kingdom',
  'munroe-kingdom-citizenship',
  'munroe-you-are-a-king',
  'munroe-rediscovering-kingdom-worship',
  // Nicky & Sila Lee (7)
  'lee-parenting-book',
  'lee-marriage-book',
  'alpha-marriage-course',
  'lee-the-marriage-course',
  'lee-the-pre-marriage-course',
  'lee-parenting-children-course',
  'lee-parenting-teenagers-course',
  // Mohammed & Lilliane Sanogo (58)
  'sanogo-apprends-moi-a-prier',
  'sanogo-grandir-dans-l-intimite-avec-dieu',
  'sanogo-cheminer-vers-plus-de-profondeur',
  'sanogo-j-ai-donne-ma-vie-a-jesus',
  'sanogo-marcher-au-son-de-sa-voix',
  'sanogo-vin-nouveau-pour-mon-mariage',
  'lilliane-sanogo-sept-secrets-couple',
  'lilliane-sanogo-4-m-femme-de-dieu',
  'sanogo-vaincre-les-attaques-du-malin',
  'sanogo-renverser-les-autels-d-appauvrissement',
  'sanogo-neutraliser-la-malediction-de-pauvrete',
  'sanogo-la-3e-presence-de-dieu-l-onction',
  'sanogo-activer-l-onction-fraiche',
  'sanogo-attirer-les-differentes-onctions',
  'sanogo-comment-se-consacrer-a-dieu',
  'sanogo-oint-et-consacre',
  'sanogo-marcher-devant-la-face-de-dieu',
  'sanogo-le-pouvoir-de-marcher-dans-la-saintete',
  'sanogo-devenir-un-intime-de-dieu',
  'sanogo-les-fruits-d-une-vie-ordonnee-la-paix',
  'sanogo-les-fruits-d-une-vie-ordonnee-la-joie',
  'sanogo-le-mystere-de-la-joie-divine',
  'sanogo-reflete-la-paix-divine',
  'sanogo-la-patience-divine',
  'sanogo-manifeste-la-bonte-comme-dieu',
  'sanogo-la-benignite',
  'sanogo-la-fidelite',
  'sanogo-aimer-comme-christ',
  'sanogo-posseder-son-territoire-de-faveur',
  'sanogo-benediction-de-la-fecondite-divine',
  'sanogo-la-benediction-de-la-provision-divine',
  'sanogo-commencer-et-achever-avec-grace',
  'sanogo-quand-la-benediction-te-poursuit',
  'sanogo-vaincre-les-5-types-d-avatars-ennemis',
  'sanogo-la-benediction-de-la-faveur-des-hommes',
  'sanogo-la-benediction-de-la-vie-abondante',
  'sanogo-la-benediction-du-ciel-ouvert',
  'sanogo-la-benediction-de-l-influence',
  'sanogo-la-benediction-de-l-elevation',
  'sanogo-sagesses-pour-multiplier-ses-graces',
  'sanogo-quand-ta-vie-amene-la-faveur',
  'sanogo-mene-une-vie-fructueuse',
  'sanogo-source-de-benediction',
  'sanogo-provoquer-la-pluie-d-en-haut',
  'sanogo-recevoir-la-pluie-d-en-haut',
  'sanogo-insatisfait',
  'sanogo-developper-la-mentalite-de-conquete',
  'sanogo-a-l-assaut',
  'sanogo-12-portes-d-influence',
  'sanogo-comment-devenir-plus-productif',
  'sanogo-la-lumiere-pour-mieux-gerer-tes-priorites',
  'sanogo-controle-les-petits-chiens',
  'sanogo-comment-bien-organiser-ta-vie',
  'sanogo-decouvrir-et-comprendre-la-sagesse-divine',
  'sanogo-marcher-dans-les-sept-colonnes-de-la-sagesse',
  'sanogo-reussir-sa-vie-par-la-sagesse-divine',
  'lilliane-sanogo-bouillon-de-graces',
  'lilliane-sanogo-lumiere-de-sagesse-pour-une-femme',
  // Zac, Annie & Santosh Poonen (44)
  'poonen-god-centred-praying',
  'poonen-finding-gods-will',
  'poonen-hear-o-my-sons',
  'poonen-one-body-in-christ',
  'poonen-the-purpose-of-failure',
  'poonen-secrets-of-victory',
  'poonen-practical-discipleship',
  'poonen-living-as-jesus-lived',
  'poonen-a-heavenly-home',
  'poonen-a-godly-family-life',
  'poonen-sex-love-marriage',
  'poonen-know-your-enemy',
  'poonen-the-way-of-wisdom',
  'annie-poonen-woman-why-are-you-weeping',
  'annie-poonen-mother-in-law-bond',
  'annie-poonen-encouragement-for-mothers',
  'annie-poonen-god-made-mothers',
  'annie-poonen-a-girls-viewpoint',
  'poonen-through-the-bible',
  'poonen-the-final-triumph',
  'poonen-the-lord-and-his-church',
  'poonen-the-real-truth',
  'poonen-amazing-facts',
  'poonen-the-full-gospel',
  'poonen-fundamental-biblical-truths',
  'poonen-basic-christian-teachings',
  'poonen-a-good-foundation',
  'poonen-all-that-jesus-taught',
  'poonen-being-ready-for-christs-return',
  'poonen-beauty-for-ashes',
  'poonen-knowing-gods-ways',
  'poonen-the-supreme-priorities',
  'poonen-gaining-gods-approval',
  'poonen-fifty-marks-of-pharisees',
  'poonen-fifty-marks-of-godly-men',
  'poonen-needed-men-of-god',
  'poonen-a-spiritual-leader',
  'poonen-principles-of-serving-god',
  'poonen-the-new-covenant-servant',
  'poonen-gods-work-done-in-gods-way',
  'poonen-the-day-of-small-beginnings',
  'poonen-new-wine-in-new-wineskins',
  'santosh-poonen-congregation-club-church',
  'annie-poonen-what-the-lord-has-done-for-me',
  // Reinhold Ruthe (11)
  'ruthe-check-up-fuer-die-liebe',
  'ruthe-taegliche-audienz-bei-gott',
  'ruthe-sehen-was-gott-tut',
  'ruthe-was-meine-seele-stark-macht',
  'ruthe-charlotte-geht',
  'ruthe-typen-und-temperamente',
  'ruthe-glueck',
  'ruthe-hochsensibilitaet-und-depression',
  'ruthe-heilsame-gespraeche',
  'ruthe-handbuch-der-therapeutischen-seelsorge',
  'ruthe-gespraechsfuehrung-in-der-seelsorge',
];
